version: "3"

services:
  nodaacd:
    image: aacio/aac:latest
    command: /opt/aacio/bin/nodaacd.sh --data-dir /opt/aacio/bin/data-dir -e --http-alias=nodaacd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: nodaacd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodaac-data-volume:/opt/aacio/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  kaacd:
    image: aacio/aac:latest
    command: /opt/aacio/bin/kaacd --wallet-dir /opt/aacio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=kaacd:8900 --http-alias=localhost:8900
    hostname: kaacd
    links:
      - nodaacd
    volumes:
      - kaacd-data-volume:/opt/aacio/bin/data-dir
    stop_grace_period: 10m

volumes:
 nodaac-data-volume:
   external: true
 kaacd-data-volume:
   external: true
