version: "3"

services:
  builder:
    build:
      context: builder
    image: aacio/builder

  nodaacd:
    build:
      context: .
    image: aacio/aac
    command: /opt/aacio/bin/nodaacd.sh
    hostname: nodaacd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodaac-data-volume:/opt/aacio/bin/data-dir

  kaacd:
    image: aacio/aac
    command: /opt/aacio/bin/kaacd
    hostname: kaacd
    links:
      - nodaacd
    volumes:
      - kaacd-data-volume:/opt/aacio/bin/data-dir

volumes:
  nodaac-data-volume:
    external: true
  kaacd-data-volume:
    external: true
