.TH "__dir_stream" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__dir_stream
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__dir_stream\fP & \fBoperator=\fP (const \fB__dir_stream\fP &)=delete"
.br
.ti -1c
.RI "\fB__dir_stream\fP (\fB__dir_stream\fP &&\fBother\fP) noexcept"
.br
.ti -1c
.RI "\fB__dir_stream\fP (const path &root, directory_options opts, error_code &ec)"
.br
.ti -1c
.RI "bool \fBgood\fP () const noexcept"
.br
.ti -1c
.RI "bool \fBadvance\fP (error_code &ec)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "path \fB__root_\fP"
.br
.ti -1c
.RI "directory_entry \fB__entry_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
