.TH "__libc" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__libc
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcan_do_threads\fP"
.br
.ti -1c
.RI "int \fBthreaded\fP"
.br
.ti -1c
.RI "int \fBsecure\fP"
.br
.ti -1c
.RI "volatile int \fBthreads_minus_1\fP"
.br
.ti -1c
.RI "size_t * \fBauxv\fP"
.br
.ti -1c
.RI "struct \fBtls_module\fP * \fBtls_head\fP"
.br
.ti -1c
.RI "size_t \fBtls_size\fP"
.br
.ti -1c
.RI "size_t \fBtls_align\fP"
.br
.ti -1c
.RI "size_t \fBtls_cnt\fP"
.br
.ti -1c
.RI "size_t \fBpage_size\fP"
.br
.ti -1c
.RI "struct \fB__locale_struct\fP \fBglobal_locale\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
