.TH "__libcpp_debug_exception::__libcpp_debug_exception_imp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__libcpp_debug_exception::__libcpp_debug_exception_imp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "__libcpp_debug_info \fB__info_\fP"
.br
.ti -1c
.RI "std::string \fB__what_str_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
