.TH "__locale_map" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__locale_map
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const void * \fBmap\fP"
.br
.ti -1c
.RI "size_t \fBmap_size\fP"
.br
.ti -1c
.RI "char \fBname\fP [LOCALE_NAME_MAX+1]"
.br
.ti -1c
.RI "const struct \fB__locale_map\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
