.TH "__time_get_temp< CharT >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__time_get_temp< CharT >
.SH SYNOPSIS
.br
.PP
.PP
Inherits ctype_byname< CharT >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__time_get_temp\fP (const char *nm)"
.br
.ti -1c
.RI "\fB__time_get_temp\fP (const string &nm)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
