.TH "_IO_FILE" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_IO_FILE
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBflags\fP"
.br
.ti -1c
.RI "unsigned char * \fBrpos\fP"
.br
.ti -1c
.RI "unsigned char * \fBrend\fP"
.br
.ti -1c
.RI "int(* \fBclose\fP )(\fBFILE\fP *)"
.br
.ti -1c
.RI "unsigned char * \fBwend\fP"
.br
.ti -1c
.RI "unsigned char * \fBwpos\fP"
.br
.ti -1c
.RI "unsigned char * \fBmustbezero_1\fP"
.br
.ti -1c
.RI "unsigned char * \fBwbase\fP"
.br
.ti -1c
.RI "size_t(* \fBread\fP )(\fBFILE\fP *, unsigned char *, size_t)"
.br
.ti -1c
.RI "size_t(* \fBwrite\fP )(\fBFILE\fP *, const unsigned char *, size_t)"
.br
.ti -1c
.RI "off_t(* \fBseek\fP )(\fBFILE\fP *, off_t, int)"
.br
.ti -1c
.RI "unsigned char * \fBbuf\fP"
.br
.ti -1c
.RI "size_t \fBbuf_size\fP"
.br
.ti -1c
.RI "\fBFILE\fP * \fBprev\fP"
.br
.ti -1c
.RI "\fBFILE\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "int \fBpipe_pid\fP"
.br
.ti -1c
.RI "long \fBlockcount\fP"
.br
.ti -1c
.RI "short \fBdummy3\fP"
.br
.ti -1c
.RI "signed char \fBmode\fP"
.br
.ti -1c
.RI "signed char \fBlbf\fP"
.br
.ti -1c
.RI "volatile int \fBlock\fP"
.br
.ti -1c
.RI "volatile int \fBwaiters\fP"
.br
.ti -1c
.RI "void * \fBcookie\fP"
.br
.ti -1c
.RI "off_t \fBoff\fP"
.br
.ti -1c
.RI "char * \fBgetln_buf\fP"
.br
.ti -1c
.RI "void * \fBmustbezero_2\fP"
.br
.ti -1c
.RI "unsigned char * \fBshend\fP"
.br
.ti -1c
.RI "off_t \fBshlim\fP"
.br
.ti -1c
.RI "off_t \fBshcnt\fP"
.br
.ti -1c
.RI "\fBFILE\fP * \fBprev_locked\fP"
.br
.ti -1c
.RI "\fBFILE\fP * \fBnext_locked\fP"
.br
.ti -1c
.RI "struct \fB__locale_struct\fP * \fBlocale\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
