.TH "A_int_2" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
A_int_2
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr int \fBoperator()\fP (int x, int y) const"
.br
.ti -1c
.RI "\fBA_int_2\fP (int)"
.br
.ti -1c
.RI "int \fBmem1\fP (int x, int y)"
.br
.ti -1c
.RI "int \fBmem2\fP (int x, int y) const"
.br
.ti -1c
.RI "int \fBoperator()\fP (int x, int y)"
.br
.ti -1c
.RI "int \fBoperator()\fP (int x, int y) const"
.br
.ti -1c
.RI "int \fBoperator()\fP (int i, int j)"
.br
.ti -1c
.RI "int \fBmem1\fP (int i)"
.br
.ti -1c
.RI "int \fBmem2\fP (int i) const"
.br
.ti -1c
.RI "int \fBoperator()\fP (int i, int j)"
.br
.ti -1c
.RI "int \fBmem1\fP (int i)"
.br
.ti -1c
.RI "int \fBmem2\fP (int i) const"
.br
.ti -1c
.RI "\fBA_int_2\fP (int)"
.br
.ti -1c
.RI "int \fBmem1\fP (int x, int y)"
.br
.ti -1c
.RI "int \fBmem2\fP (int x, int y) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
