.TH "A_wrap< A >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
A_wrap< A >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBA_wrap\fP (int x)"
.br
.ti -1c
.RI "\fBA\fP & \fBoperator*\fP ()"
.br
.ti -1c
.RI "\fBA\fP const  & \fBoperator*\fP () const"
.br
.ti -1c
.RI "\fBA_wrap\fP (int x)"
.br
.ti -1c
.RI "\fBA\fP & \fBoperator*\fP ()"
.br
.ti -1c
.RI "\fBA\fP const  & \fBoperator*\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBA\fP \fBm_a\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
