.TH "libraries/chain/include/aacio/chain/contracts/aac_contract.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/include/aacio/chain/contracts/aac_contract.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/apply_context\&.hpp>\fP
.br
\fC#include <aacio/chain/types\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBaacio::chain::contracts::apply_aacio_newaccount\fP (apply_context &context)"
.br
.ti -1c
.RI "void \fBaacio::chain::contracts::apply_aacio_updateauth\fP (apply_context &context)"
.br
.ti -1c
.RI "void \fBaacio::chain::contracts::apply_aacio_deleteauth\fP (apply_context &context)"
.br
.ti -1c
.RI "void \fBaacio::chain::contracts::apply_aacio_linkauth\fP (apply_context &context)"
.br
.ti -1c
.RI "void \fBaacio::chain::contracts::apply_aacio_unlinkauth\fP (apply_context &context)"
.br
.ti -1c
.RI "void \fBaacio::chain::contracts::apply_aacio_postrecovery\fP (apply_context &context)"
.br
.ti -1c
.RI "void \fBaacio::chain::contracts::apply_aacio_passrecovery\fP (apply_context &context)"
.br
.ti -1c
.RI "void \fBaacio::chain::contracts::apply_aacio_vetorecovery\fP (apply_context &context)"
.br
.ti -1c
.RI "void \fBaacio::chain::contracts::apply_aacio_setcode\fP (apply_context &context)"
.br
.ti -1c
.RI "void \fBaacio::chain::contracts::apply_aacio_setabi\fP (apply_context &context)"
.br
.ti -1c
.RI "void \fBaacio::chain::contracts::apply_aacio_onerror\fP (apply_context &context)"
.br
.ti -1c
.RI "void \fBaacio::chain::contracts::apply_aacio_canceldelay\fP (apply_context &context)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
