.TH "aacclienttool" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacclienttool \- Tool for sending transactions and querying state from \fBnodaac\fP\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Tool for sending transactions and querying state from \fBnodaac\fP\&. 


.SH "Introduction to claac"
.PP
\fCclaac\fP is a command line tool that interfaces with the REST api exposed by \fBnodaac\fP\&. In order to use \fCclaac\fP you will need to have a local copy of \fCnodaac\fP running and configured to load the '\fBaacio::chain_api_plugin\fP'\&.
.PP
claac contains documentation for all of its commands\&. For a list of all commands known to claac, simply run it with no arguments: 
.PP
.nf
$ \&./claac
Command Line Interface to AACIO Client
Usage: programs/clAcute-Angle-Chain/claac [OPTIONS] SUBCOMMAND

Options:
  -h,--help                   Print this help message and exit
  -H,--host TEXT=localhost    the host where nodaac is running
  -p,--port UINT=8888         the port where nodaac is running
  --wallet-host TEXT=localhost
                              the host where kaacd is running
  --wallet-port UINT=8888     the port where kaacd is running
  -v,--verbose                output verbose actions on error

Subcommands:
  version                     Retrieve version information
  create                      Create various items, on and off the blockchain
  get                         Retrieve various items and information from the blockchain
  set                         Set or update blockchain state
  transfer                    Transfer AAC from account to account
  net                         Interact with local p2p network connections
  wallet                      Interact with local wallet
  sign                        Sign a transaction
  push                        Push arbitrary transactions to the blockchain

.fi
.PP
 To get help with any particular subcommand, run it with no arguments as well: 
.PP
.nf
$ \&./claac create
Create various items, on and off the blockchain
Usage: \&./claac create SUBCOMMAND

Subcommands:
  key                         Create a new keypair and print the public and private keys
  account                     Create a new account on the blockchain

$ \&./claac create account
Create a new account on the blockchain
Usage: \&./claac create account [OPTIONS] creator name OwnerKey ActiveKey

Positionals:
  creator TEXT                The name of the account creating the new account
  name TEXT                   The name of the new account
  OwnerKey TEXT               The owner public key for the new account
  ActiveKey TEXT              The active public key for the new account

Options:
  -x,--expiration             set the time in seconds before a transaction expires, defaults to 30s
  -f,--force-unique           force the transaction to be unique\&. this will consume extra bandwidth and remove any protections against accidently issuing the same transaction multiple times
  -s,--skip-sign              Specify if unlocked wallet keys should be used to sign transaction
  -d,--dont-broadcast         don't broadcast transaction to the network (just print to stdout)
  -p,--permission TEXT \&.\&.\&.    An account and permission level to authorize, as in 'account@permission' (defaults to 'creator@active')

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
