.TH "aacd_def" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacd_def
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_host\fP (\fBhost_def\fP *h, bool is_bios)"
.br
.ti -1c
.RI "void \fBmk_dot_label\fP ()"
.br
.ti -1c
.RI "const string & \fBdot_label\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBconfig_dir_name\fP"
.br
.ti -1c
.RI "string \fBdata_dir_name\fP"
.br
.ti -1c
.RI "uint16_t \fBp2p_port\fP"
.br
.ti -1c
.RI "uint16_t \fBhttp_port\fP"
.br
.ti -1c
.RI "uint16_t \fBfile_size\fP"
.br
.ti -1c
.RI "bool \fBhas_db\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "\fBtn_node_def\fP * \fBnode\fP"
.br
.ti -1c
.RI "string \fBhost\fP"
.br
.ti -1c
.RI "string \fBp2p_endpoint\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
