.TH "aacio::extended_asset" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::extended_asset
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::asset\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBextended_symbol\fP \fBget_extended_symbol\fP () const"
.br
.ti -1c
.RI "\fBextended_asset\fP (int64_t v, \fBextended_symbol\fP s)"
.br
.ti -1c
.RI "\fBextended_asset\fP (\fBasset\fP a, \fBaccount_name\fP c)"
.br
.ti -1c
.RI "void \fBprint\fP () const"
.br
.ti -1c
.RI "\fBextended_asset\fP \fBoperator\-\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccount_name\fP \fBcontract\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBextended_asset\fP \fBoperator\-\fP (const \fBextended_asset\fP &a, const \fBextended_asset\fP &b)"
.br
.ti -1c
.RI "\fBextended_asset\fP \fBoperator+\fP (const \fBextended_asset\fP &a, const \fBextended_asset\fP &b)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
