.TH "aacio::chain::producer_api" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::producer_api
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::chain::context_aware_api\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBget_active_producers\fP (\fBarray_ptr\fP< \fBchain::account_name\fP > \fBproducers\fP, size_t datalen)"
.br
.ti -1c
.RI "\fBcontext_aware_api\fP (\fBapply_context\fP &ctx, bool context_free=false)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
