.TH "aacio::mongo_db_plugin_impl" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::mongo_db_plugin_impl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBapplied_block\fP (const \fBblock_trace\fP &)"
.br
.ti -1c
.RI "void \fBapplied_irreversible_block\fP (const \fBsigned_block\fP &)"
.br
.ti -1c
.RI "void \fBprocess_block\fP (const \fBblock_trace\fP &, const \fBsigned_block\fP &)"
.br
.ti -1c
.RI "void \fB_process_block\fP (const \fBblock_trace\fP &, const \fBsigned_block\fP &)"
.br
.ti -1c
.RI "void \fBprocess_irreversible_block\fP (const \fBsigned_block\fP &)"
.br
.ti -1c
.RI "void \fB_process_irreversible_block\fP (const \fBsigned_block\fP &)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBwipe_database\fP ()"
.br
.ti -1c
.RI "void \fBconsume_blocks\fP ()"
.br
.ti -1c
.RI "void \fBupdate_account\fP (const \fBchain::action\fP &msg)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBconfigured\fP {false}"
.br
.ti -1c
.RI "bool \fBwipe_database_on_startup\fP {false}"
.br
.ti -1c
.RI "std::string \fBdb_name\fP"
.br
.ti -1c
.RI "mongocxx::instance \fBmongo_inst\fP"
.br
.ti -1c
.RI "mongocxx::client \fBmongo_conn\fP"
.br
.ti -1c
.RI "mongocxx::collection \fBaccounts\fP"
.br
.ti -1c
.RI "size_t \fBqueue_size\fP = 0"
.br
.ti -1c
.RI "size_t \fBprocessed\fP = 0"
.br
.ti -1c
.RI "\fBstd::deque\fP< \fBsigned_block\fP > \fBsigned_block_queue\fP"
.br
.ti -1c
.RI "\fBstd::deque\fP< \fBsigned_block\fP > \fBsigned_block_process_queue\fP"
.br
.ti -1c
.RI "\fBstd::deque\fP< std::pair< \fBblock_trace\fP, \fBsigned_block\fP > > \fBblock_trace_queue\fP"
.br
.ti -1c
.RI "\fBstd::deque\fP< std::pair< \fBblock_trace\fP, \fBsigned_block\fP > > \fBblock_trace_process_queue\fP"
.br
.ti -1c
.RI "\fBstd::map\fP< std::string, \fBstd::vector\fP< \fBchain::action\fP > > \fBreversible_actions\fP"
.br
.ti -1c
.RI "boost::mutex \fBmtx\fP"
.br
.ti -1c
.RI "boost::condition_variable \fBcondtion\fP"
.br
.ti -1c
.RI "boost::thread \fBconsume_thread\fP"
.br
.ti -1c
.RI "boost::atomic< bool > \fBdone\fP {false}"
.br
.ti -1c
.RI "boost::atomic< bool > \fBstartup\fP {true}"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBabi_def\fP \fBaac_abi\fP"
.br
.ti -1c
.RI "static const \fBaccount_name\fP \fBnewaccount\fP = 'newaccount'"
.br
.ti -1c
.RI "static const \fBaccount_name\fP \fBtransfer\fP = 'transfer'"
.br
.ti -1c
.RI "static const \fBaccount_name\fP \fBsetabi\fP = 'setabi'"
.br
.ti -1c
.RI "static const std::string \fBblocks_col\fP = 'Blocks'"
.br
.ti -1c
.RI "static const std::string \fBtrans_col\fP = 'Transactions'"
.br
.ti -1c
.RI "static const std::string \fBactions_col\fP = 'Actions'"
.br
.ti -1c
.RI "static const std::string \fBaction_traces_col\fP = 'ActionTraces'"
.br
.ti -1c
.RI "static const std::string \fBaccounts_col\fP = 'Accounts'"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
