.TH "aacio::generate_abi_action" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::generate_abi_action
.SH SYNOPSIS
.br
.PP
.PP
Inherits ASTFrontendAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgenerate_abi_action\fP (bool verbose, bool opt_sfs, string abi_context, \fBabi_def\fP &output, const string &\fBcontract\fP, const \fBvector\fP< string > &actions)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< ASTConsumer > \fBCreateASTConsumer\fP (CompilerInstance &compiler_instance, llvm::StringRef) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
