.TH "aacio::chain::contracts::secondary_index< SecondaryKey, ObjectTypeId, SecondaryKeyLess >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::secondary_index< SecondaryKey, ObjectTypeId, SecondaryKeyLess >
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBindex_object\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef chainbase::shared_multi_index_container< \fBindex_object\fP, \fBindexed_by\fP< ordered_unique< tag< by_id >, member< \fBindex_object\fP, typename \fBindex_object::id_type\fP, &index_object::id > >, ordered_unique< tag< by_primary >, composite_key< \fBindex_object\fP, member< \fBindex_object\fP, \fBtable_id\fP, &index_object::t_id >, member< \fBindex_object\fP, uint64_t, &index_object::primary_key > >, composite_key_compare< std::less< \fBtable_id\fP >, std::less< uint64_t > > >, ordered_unique< tag< by_secondary >, composite_key< \fBindex_object\fP, member< \fBindex_object\fP, \fBtable_id\fP, &index_object::t_id >, member< \fBindex_object\fP, SecondaryKey, &index_object::secondary_key >, member< \fBindex_object\fP, uint64_t, &index_object::primary_key > >, composite_key_compare< std::less< \fBtable_id\fP >, SecondaryKeyLess, std::less< uint64_t > > > > > \fBindex_index\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
