.TH "aacio::chain::wasm_ops::field_specific_params< Field >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::wasm_ops::field_specific_params< Field >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static auto \fBunpack\fP (char *opcode, Field &f)"
.br
.ti -1c
.RI "static auto \fBpack\fP (Field &f)"
.br
.ti -1c
.RI "static auto \fBto_string\fP (Field &f)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBskip_ahead\fP = sizeof(uint16_t) + sizeof(Field)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
