.TH "aacio::chain::config::billable_size< contracts::table_id_object >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::config::billable_size< contracts::table_id_object >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const uint64_t \fBoverhead\fP = overhead_per_row_per_index_ram_bytes * 2"
.br
.RI "overhead for 2x indices internal-key and code,scope,table "
.ti -1c
.RI "static const uint64_t \fBvalue\fP = 44 + \fBoverhead\fP"
.br
.RI "36 bytes for constant size fields + overhead "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
