.TH "aacio::chain::webassembly::wavm::intrinsic_invoker_impl< Ret, std::tuple< const fc::time_point_sec &, Inputs... >, std::tuple< Translated... > >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::wavm::intrinsic_invoker_impl< Ret, std::tuple< const fc::time_point_sec &, Inputs... >, std::tuple< Translated... > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wavm\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBnext_step\fP = \fBintrinsic_invoker_impl\fP< Ret, std::tuple< Inputs\&.\&.\&. >, std::tuple< Translated\&.\&.\&., native_to_wasm_t< const \fBfc::time_point_sec\fP & > > >"
.br
.ti -1c
.RI "using \fBthen_type\fP = Ret(*)(\fBrunning_instance_context\fP &, const \fBfc::time_point_sec\fP &, Inputs\&.\&.\&., Translated\&.\&.\&.)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<then_type Then> static Ret \fBtranslate_one\fP (\fBrunning_instance_context\fP &ctx, Inputs\&.\&.\&. rest, Translated\&.\&.\&. translated, native_to_wasm_t< const \fBfc::time_point_sec\fP &> wasm_value)"
.br
.ti -1c
.RI "template<then_type Then> static const auto \fBfn\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Ret, typename\&.\&.\&. Inputs, typename \&.\&.\&. Translated>
.br
struct aacio::chain::webassembly::wavm::intrinsic_invoker_impl< Ret, std::tuple< const fc::time_point_sec &, Inputs\&.\&.\&. >, std::tuple< Translated\&.\&.\&. > >"
Specialization for transcribing a reference to a \fBfc::time_point_sec\fP which can be passed as a native value This type transcribes into a native type which is loaded by value into a variable on the stack and then passed by reference to the intrinsic\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIRet\fP - the return type of the native method 
.br
\fIInputs\fP - the remaining native parameters to transcribe 
.br
\fITranslated\fP - the list of transcribed wasm parameters 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
