.TH "aacio::chain::block_log" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::block_log
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBblock_log\fP (const \fBfc::path\fP &data_dir)"
.br
.ti -1c
.RI "\fBblock_log\fP (\fBblock_log\fP &&\fBother\fP)"
.br
.ti -1c
.RI "uint64_t \fBappend\fP (const \fBsigned_block\fP &b)"
.br
.ti -1c
.RI "void \fBflush\fP ()"
.br
.ti -1c
.RI "std::pair< \fBsigned_block\fP, uint64_t > \fBread_block\fP (uint64_t file_pos) const"
.br
.ti -1c
.RI "\fBoptional\fP< \fBsigned_block\fP > \fBread_block_by_num\fP (uint32_t block_num) const"
.br
.ti -1c
.RI "\fBoptional\fP< \fBsigned_block\fP > \fBread_block_by_id\fP (const \fBblock_id_type\fP &id) const"
.br
.ti -1c
.RI "uint64_t \fBget_block_pos\fP (uint32_t block_num) const"
.br
.ti -1c
.RI "\fBoptional\fP< \fBsigned_block\fP > \fBread_head\fP () const"
.br
.ti -1c
.RI "const \fBoptional\fP< \fBsigned_block\fP > & \fBhead\fP () const"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const uint64_t \fBnpos\fP = std::numeric_limits<uint64_t>::max()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "uint64_t aacio::chain::block_log::get_block_pos (uint32_t block_num) const"
Return offset of block in file, or block_log::npos if it does not exist\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
