.TH "aacio::detail::asio_with_stub_log::transport_config" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::detail::asio_with_stub_log::transport_config
.SH SYNOPSIS
.br
.PP
.PP
Inherits transport_config\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBtype::concurrency_type\fP \fBconcurrency_type\fP"
.br
.ti -1c
.RI "typedef \fBtype::alog_type\fP \fBalog_type\fP"
.br
.ti -1c
.RI "typedef \fBtype::elog_type\fP \fBelog_type\fP"
.br
.ti -1c
.RI "typedef \fBtype::request_type\fP \fBrequest_type\fP"
.br
.ti -1c
.RI "typedef \fBtype::response_type\fP \fBresponse_type\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::transport::asio::basic_socket::endpoint\fP \fBsocket_type\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
