.TH "aacio::contract" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::contract
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBaacio::bios\fP, \fBaacio::multisig\fP, \fBaacio::testinline\fP, \fBaacio::token< Code, Symbol, NumberType >\fP, \fBdice\fP, and \fBsimpletoken\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcontract\fP (\fBaccount_name\fP n)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccount_name\fP \fB_self\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
