.TH "aacio::chain::incremental_merkle_impl< DigestType, Container, Args >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::incremental_merkle_impl< DigestType, Container, Args > \- detail  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <incremental_merkle\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Allocator > \fBincremental_merkle_impl\fP (Allocator &&alloc)"
.br
.ti -1c
.RI "const DigestType & \fBappend\fP (const DigestType &digest)"
.br
.ti -1c
.RI "DigestType \fBget_root\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename DigestType, template< typename \&.\&.\&. > class Container = vector, typename \&.\&.\&. Args>
.br
class aacio::chain::incremental_merkle_impl< DigestType, Container, Args >"
detail 

\fBA\fP balanced merkle tree built in such that the set of leaf nodes can be appended to without triggering the reconstruction of inner nodes that represent a complete subset of previous nodes\&.
.PP
to achieve this new nodes can either imply an set of future nodes that achieve a balanced tree OR realize one of these future nodes\&.
.PP
Once a sub-tree contains only realized nodes its sub-root will never change\&. This allows proofs based on this merkle to be very stable after some time has past only needing to update or add a single value to maintain validity\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename DigestType, template< typename \&.\&.\&. > class Container = vector, typename \&.\&.\&. Args> const DigestType& \fBaacio::chain::incremental_merkle_impl\fP< DigestType, Container, Args >::append (const DigestType & digest)\fC [inline]\fP"
Add a node to the incremental tree and recalculate the _active_nodes so they are prepared for the next append\&.
.PP
The algorithm for this is to start at the new node and retreat through the tree for any node that is the concatenation of a fully-realized node and a partially realized node we must record the value of the fully-realized node in the new _active_nodes so that the next append can fetch it\&. Fully realized nodes and Fully implied nodes do not have an effect on the _active_nodes\&.
.PP
For convention \fIAND\fP to allow appends when the _node_count is a power-of-2, the current root of the incremental tree is always appended to the end of the new _active_nodes\&.
.PP
In practice, this can be done iteratively by recording any 'left' value that is to be combined with an implied node\&.
.PP
If the appended node is a 'left' node in its pair, it will immediately push itself into the new active nodes list\&.
.PP
If the new node is a 'right' node it will begin collapsing upward in the tree, reading and discarding the 'left' node data from the old active nodes list, until it becomes a 'left' node\&. It must then push the 'top' of its current collapsed sub-tree into the new active nodes list\&.
.PP
Once any value has been added to the new active nodes, all remaining 'left' nodes should be present in the order they are needed in the previous active nodes as an artifact of the previous append\&. As they are read from the old active nodes, they will need to be copied in to the new active nodes list as they are still needed for future appends\&.
.PP
As a result, if an append collapses the entire tree while always being the 'right' node, the new list of active nodes will be empty and by definition the tree contains a power-of-2 number of nodes\&.
.PP
Regardless of the contents of the new active nodes list, the top 'collapsed' value is appended\&. If this tree is \fInot\fP a power-of-2 number of nodes, this node will not be used in the next append but still serves as a conventional place to access the root of the current tree\&. If this \fIis\fP a power-of-2 number of nodes, this node will be needed during then collapse phase of the next append so, it serves double duty as a legitimate active node and the conventional storage location of the root\&.
.PP
\fBParameters:\fP
.RS 4
\fIdigest\fP - the node to add 
.RE
.PP
\fBReturns:\fP
.RS 4
- the new root 
.RE
.PP

.SS "template<typename DigestType, template< typename \&.\&.\&. > class Container = vector, typename \&.\&.\&. Args> DigestType \fBaacio::chain::incremental_merkle_impl\fP< DigestType, Container, Args >::get_root () const\fC [inline]\fP"
l return the current root of the incremental merkle
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
