.TH "aacio::chain::class_from_wasm< apply_context >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::class_from_wasm< apply_context >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static auto & \fBvalue\fP (\fBapply_context\fP &ctx)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static auto& \fBaacio::chain::class_from_wasm\fP< \fBapply_context\fP >::value (\fBapply_context\fP & ctx)\fC [inline]\fP, \fC [static]\fP"
Don't construct a new \fBapply_context\fP, just return a reference to the existing ont 
.PP
\fBParameters:\fP
.RS 4
\fIwasm\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
