.TH "aaciosystem::voting< SystemAccount >::producer_info" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aaciosystem::voting< SystemAccount >::producer_info
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBprimary_key\fP () const"
.br
.ti -1c
.RI "uint128_t \fBby_votes\fP () const"
.br
.ti -1c
.RI "bool \fBactive\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "account_name \fBowner\fP"
.br
.ti -1c
.RI "uint128_t \fBtotal_votes\fP = 0"
.br
.ti -1c
.RI "aacio_parameters \fBprefs\fP"
.br
.ti -1c
.RI "\fBaacio::bytes\fP \fBpacked_key\fP"
.br
.ti -1c
.RI "system_token_type \fBper_block_payments\fP"
.br
.RI "a packed public key object "
.ti -1c
.RI "time \fBlast_rewards_claim\fP = 0"
.br
.ti -1c
.RI "time \fBtime_became_active\fP = 0"
.br
.ti -1c
.RI "time \fBlast_produced_block_time\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
