.TH "aacio::update_request_time" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::update_request_time
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (struct \fBtransaction_state\fP &ts)"
.br
.ti -1c
.RI "void \fBoperator()\fP (struct \fBblock_state\fP &bs)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
