.TH "aacio::chain::webassembly::wavm::intrinsic_invoker_impl< Ret, std::tuple< null_terminated_ptr, Inputs... >, std::tuple< Translated... > >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::wavm::intrinsic_invoker_impl< Ret, std::tuple< null_terminated_ptr, Inputs... >, std::tuple< Translated... > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wavm\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBnext_step\fP = \fBintrinsic_invoker_impl\fP< Ret, std::tuple< Inputs\&.\&.\&. >, std::tuple< Translated\&.\&.\&., I32 > >"
.br
.ti -1c
.RI "using \fBthen_type\fP = Ret(*)(\fBrunning_instance_context\fP &, \fBnull_terminated_ptr\fP, Inputs\&.\&.\&., Translated\&.\&.\&.)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<then_type Then> static Ret \fBtranslate_one\fP (\fBrunning_instance_context\fP &ctx, Inputs\&.\&.\&. rest, Translated\&.\&.\&. translated, I32 ptr)"
.br
.ti -1c
.RI "template<then_type Then> static const auto \fBfn\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Ret, typename\&.\&.\&. Inputs, typename \&.\&.\&. Translated>
.br
struct aacio::chain::webassembly::wavm::intrinsic_invoker_impl< Ret, std::tuple< null_terminated_ptr, Inputs\&.\&.\&. >, std::tuple< Translated\&.\&.\&. > >"
Specialization for transcribing a \fBnull_terminated_ptr\fP type in the native method signature This type transcribes 1 wasm parameters: a char pointer which is validated to contain a null value before the end of the allocated memory\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIRet\fP - the return type of the native method 
.br
\fIInputs\fP - the remaining native parameters to transcribe 
.br
\fITranslated\fP - the list of transcribed wasm parameters 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
