.TH "aacio::sync_state" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::sync_state
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsync_state\fP (uint32_t start=0, uint32_t end=0, uint32_t last_acted=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBstart_block\fP"
.br
.ti -1c
.RI "uint32_t \fBend_block\fP"
.br
.ti -1c
.RI "uint32_t \fBlast\fP"
.br
.RI "last sent or received "
.ti -1c
.RI "\fBtime_point\fP \fBstart_time\fP"
.br
.RI "time request made or received "
.in -1c
.SH "Detailed Description"
.PP 
Index by start_block_num 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
