.TH "contracts/aacio.system/aacio.system.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/aacio.system/aacio.system.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'delegate_bandwidth\&.hpp'\fP
.br
\fC#include 'native\&.hpp'\fP
.br
\fC#include <aaciolib/optional\&.hpp>\fP
.br
\fC#include <aaciolib/generic_currency\&.hpp>\fP
.br
\fC#include <aaciolib/currency\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaaciosystem::block_header\fP"
.br
.ti -1c
.RI "class \fBaaciosystem::contract< SystemAccount >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
