.TH "aacio::real" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::real
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBreal\fP (const uint64_t &_val)"
.br
.RI "Constructor to double object from uint64 value\&. "
.ti -1c
.RI "uint64_t \fBvalue\fP () const"
.br
.ti -1c
.RI "\fBreal\fP \fBoperator+\fP (const \fBreal\fP &rhs) const"
.br
.RI "Add two real variables\&. "
.ti -1c
.RI "\fBreal\fP \fBoperator*\fP (const \fBreal\fP &rhs) const"
.br
.RI "Multiply two real variables\&. "
.ti -1c
.RI "\fBreal\fP \fBoperator/\fP (const \fBreal\fP &rhs) const"
.br
.RI "Division between two real variables\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBreal\fP &c1, const \fBreal\fP &c2)"
.br
.RI "Compares two double variables c1 and c2\&. "
.ti -1c
.RI "bool \fBoperator>\fP (const \fBreal\fP &c1, const \fBreal\fP &c2)"
.br
.RI "Compares two double variables c1 and c2\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBreal\fP &c1, const \fBreal\fP &c2)"
.br
.RI "Compares two double variables c1 and c2\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "aacio::real::real (const uint64_t & _val)\fC [inline]\fP"

.PP
Constructor to double object from uint64 value\&. Constructor to double object from uint64 value 
.PP
\fBParameters:\fP
.RS 4
\fI_val\fP data 
.RE
.PP

.SH "Friends And Related Function Documentation"
.PP 
.SS "bool operator< (const \fBreal\fP & c1, const \fBreal\fP & c2)\fC [friend]\fP"

.PP
Compares two double variables c1 and c2\&. Compares two double variables c1 and c2 
.PP
\fBReturns:\fP
.RS 4
if c1 < c2, return true, otherwise false 
.RE
.PP

.SS "bool operator== (const \fBreal\fP & c1, const \fBreal\fP & c2)\fC [friend]\fP"

.PP
Compares two double variables c1 and c2\&. Compares two double variables c1 and c2 
.PP
\fBReturns:\fP
.RS 4
if c1 == c2, return true, otherwise false 
.RE
.PP

.SS "bool operator> (const \fBreal\fP & c1, const \fBreal\fP & c2)\fC [friend]\fP"

.PP
Compares two double variables c1 and c2\&. Compares two double variables c1 and c2 
.PP
\fBReturns:\fP
.RS 4
if c1 > c2, return true, otherwise false 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
