.TH "aacio::abi_generator_astconsumer" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::abi_generator_astconsumer
.SH SYNOPSIS
.br
.PP
.PP
Inherits ASTConsumer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBabi_generator_astconsumer\fP (CompilerInstance &compiler_instance, \fBabi_generator\fP &abi_gen)"
.br
.ti -1c
.RI "void \fBHandleTagDeclDefinition\fP (TagDecl *tag_decl) override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBabi_generator\fP & \fBabi_gen\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
