.TH "aacio::chain::webassembly::wavm::native_to_wasm< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::wavm::native_to_wasm< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wavm\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = void"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct aacio::chain::webassembly::wavm::native_to_wasm< T >"
template that maps native types to WASM VM types 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fI\fBT\fP\fP the native type 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
