.TH "aacio::chain::config::billable_size< generated_transaction_object >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::config::billable_size< generated_transaction_object >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const uint64_t \fBoverhead\fP = overhead_per_row_per_index_ram_bytes * 5"
.br
.RI "overhead for 5x indices internal-key, txid, expiration, delay, sender_id "
.ti -1c
.RI "static const uint64_t \fBvalue\fP = 96 + 4 + \fBoverhead\fP"
.br
.RI "96 bytes for our constant size fields, 4 bytes for a varint for packed_trx size and 96 bytes of implementation overhead "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
