.TH "aacio::chain::wasm_ops::instr" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::wasm_ops::instr
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBaacio::chain::wasm_ops::instr_base< Mutators >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBto_string\fP ()"
.br
.ti -1c
.RI "virtual uint16_t \fBget_code\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBvisit\fP (\fBvisitor_arg\fP &&\fBarg\fP)=0"
.br
.ti -1c
.RI "virtual int \fBskip_ahead\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBunpack\fP (char *opcode)=0"
.br
.ti -1c
.RI "virtual \fBstd::vector\fP< U8 > \fBpack\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
