.TH "aacio::chain::transaction_api" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::transaction_api
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::chain::context_aware_api\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsend_inline\fP (\fBarray_ptr\fP< char > data, size_t data_len)"
.br
.ti -1c
.RI "void \fBsend_context_free_inline\fP (\fBarray_ptr\fP< char > data, size_t data_len)"
.br
.ti -1c
.RI "void \fBsend_deferred\fP (const uint128_t &sender_id, \fBaccount_name\fP payer, \fBarray_ptr\fP< char > data, size_t data_len)"
.br
.ti -1c
.RI "void \fBcancel_deferred\fP (const unsigned __int128 &val)"
.br
.ti -1c
.RI "\fBcontext_aware_api\fP (\fBapply_context\fP &ctx, bool context_free=false)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
