.TH "aacio::chain::wasm_ops::AACIO_OperatorDecoderStream< Op_Types >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::wasm_ops::AACIO_OperatorDecoderStream< Op_Types >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAACIO_OperatorDecoderStream\fP (const \fBstd::vector\fP< U8 > &codeBytes)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "\fBinstr\fP * \fBdecodeOp\fP ()"
.br
.ti -1c
.RI "\fBinstr\fP * \fBdecodeOpWithoutConsume\fP ()"
.br
.ti -1c
.RI "uint32_t \fBindex\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
