.TH "aacio::connection_status" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::connection_status
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBpeer\fP"
.br
.ti -1c
.RI "bool \fBconnecting\fP = false"
.br
.ti -1c
.RI "bool \fBsyncing\fP = false"
.br
.ti -1c
.RI "\fBhandshake_message\fP \fBlast_handshake\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
