.TH "aacio::generic_currency< Token >::transfer_memo" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::generic_currency< Token >::transfer_memo
.SH SYNOPSIS
.br
.PP
.PP
Inherits transfer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtransfer_memo\fP (\fBaccount_name\fP f, \fBaccount_name\fP t, token_type q, string m)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBmemo\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
