.TH "aacio::action" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::action
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <action\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Action > \fBaction\fP (\fBvector\fP< \fBpermission_level\fP > &&auth, const Action &value)"
.br
.ti -1c
.RI "template<typename Action > \fBaction\fP (const \fBpermission_level\fP &auth, const Action &value)"
.br
.ti -1c
.RI "template<typename Action > \fBaction\fP (const Action &value)"
.br
.ti -1c
.RI "template<typename Action > \fBaction\fP (const \fBpermission_level\fP &auth, \fBaccount_name\fP a, action_name n, const Action &value)"
.br
.ti -1c
.RI "\fBAACLIB_SERIALIZE\fP (\fBaction\fP,(\fBaccount\fP)(\fBname\fP)(authorization)(data)) void send() const"
.br
.ti -1c
.RI "void \fBsend_context_free\fP () const"
.br
.ti -1c
.RI "template<typename T > \fBT\fP \fBdata_as\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccount_name\fP \fBaccount\fP"
.br
.ti -1c
.RI "action_name \fBname\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBpermission_level\fP > \fBauthorization\fP"
.br
.ti -1c
.RI "\fBbytes\fP \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the packed representation of an action along with meta-data about the authorization levels\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Action > aacio::action::action (\fBvector\fP< \fBpermission_level\fP > && auth, const Action & value)\fC [inline]\fP"

.PP
\fBTemplate Parameters:\fP
.RS 4
\fIAction\fP - a type derived from action_meta<Scope,Name> 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP - will be serialized via pack into data 
.RE
.PP

.SS "template<typename Action > aacio::action::action (const \fBpermission_level\fP & auth, const Action & value)\fC [inline]\fP"

.PP
\fBTemplate Parameters:\fP
.RS 4
\fIAction\fP - a type derived from action_meta<Scope,Name> 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP - will be serialized via pack into data 
.RE
.PP

.SS "template<typename Action > aacio::action::action (const Action & value)\fC [inline]\fP"

.PP
\fBTemplate Parameters:\fP
.RS 4
\fIAction\fP - a type derived from action_meta<Scope,Name> 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP - will be serialized via pack into data 
.RE
.PP

.SS "template<typename Action > aacio::action::action (const \fBpermission_level\fP & auth, \fBaccount_name\fP a, action_name n, const Action & value)\fC [inline]\fP"

.PP
\fBTemplate Parameters:\fP
.RS 4
\fIAction\fP - a type derived from action_meta<Scope,Name> 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP - will be serialized via pack into data 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > \fBT\fP aacio::action::data_as ()\fC [inline]\fP"
Retrieve the unpacked data as \fBT\fP 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fI\fBT\fP\fP expected type of data 
.RE
.PP
\fBReturns:\fP
.RS 4
the action data 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
