.TH "aacio::chain::contracts::key_value_object" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::key_value_object
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBchainbase::object< key_value_object_type, key_value_object >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef uint64_t \fBkey_type\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBid_type\fP \fBid\fP"
.br
.ti -1c
.RI "\fBtable_id\fP \fBt_id\fP"
.br
.ti -1c
.RI "uint64_t \fBprimary_key\fP"
.br
.ti -1c
.RI "\fBaccount_name\fP \fBpayer\fP = 0"
.br
.ti -1c
.RI "shared_vector< char > \fBvalue\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBnumber_of_keys\fP = 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
