.TH "aacio::transaction_state" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::transaction_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtransaction_id_type\fP \fBid\fP"
.br
.ti -1c
.RI "bool \fBis_known_by_peer\fP = false"
.br
.RI "true if we sent or received this trx to this peer or received notice from peer "
.ti -1c
.RI "bool \fBis_noticed_to_peer\fP = false"
.br
.RI "have we sent peer notice we know it (true if we receive from this peer) "
.ti -1c
.RI "uint32_t \fBblock_num\fP = 0"
.br
.RI "the block number the transaction was included in "
.ti -1c
.RI "\fBtime_point\fP \fBrequested_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Index by id Index by is_known, block_num, validated_time, this is the order we will broadcast to peer\&. Index by is_noticed, validated_time 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
