.TH "aacio::update_entry" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::update_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBupdate_entry\fP (const \fBpacked_transaction\fP &msg)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBnode_transaction_state\fP &nts)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBpacked_transaction\fP & \fBtxn\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
