.TH "aacio::utilities::padding_ostream< BlockSize, PaddingChar >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::utilities::padding_ostream< BlockSize, PaddingChar >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::buffered_ostream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpadding_ostream\fP (fc::ostream_ptr o, size_t bufsize=4096)"
.br
.ti -1c
.RI "virtual size_t \fBwritesome\fP (const char *buffer, size_t len)"
.br
.ti -1c
.RI "virtual size_t \fBwritesome\fP (const std::shared_ptr< const char > &buf, size_t len, size_t offset)"
.br
.ti -1c
.RI "virtual void \fBflush\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
