.TH "aacio::abi_generator" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::abi_generator \- Generates aacio::abi_def struct handling events from ASTConsumer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <abi_generator\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBoptimization\fP { \fBOPT_SINGLE_FIELD_STRUCT\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBenable_optimizaton\fP (optimization o)"
.br
.RI "Enable optimization when generating ABI\&. "
.ti -1c
.RI "bool \fBis_opt_enabled\fP (optimization o)"
.br
.RI "Check if an optimization is enabled\&. "
.ti -1c
.RI "void \fBset_output\fP (\fBabi_def\fP &output)"
.br
.RI "Set the destination ABI struct to write\&. "
.ti -1c
.RI "void \fBset_verbose\fP (bool verbose)"
.br
.RI "Enable/Disable verbose status messages\&. "
.ti -1c
.RI "void \fBset_abi_context\fP (const string &abi_context)"
.br
.RI "Set the root folder that limits where types will be imported\&. Types declared in header files located in child sub-folders will also be exported\&. "
.ti -1c
.RI "void \fBset_compiler_instance\fP (CompilerInstance &compiler_instance)"
.br
.RI "Set the single instance of the Clang compiler\&. "
.ti -1c
.RI "void \fBhandle_tagdecl_definition\fP (TagDecl *tag_decl)"
.br
.RI "Handle declaration of struct/union/enum\&. "
.ti -1c
.RI "void \fBset_target_contract\fP (const string &\fBcontract\fP, const \fBvector\fP< string > &actions)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generates aacio::abi_def struct handling events from ASTConsumer\&. 
.SH "Member Function Documentation"
.PP 
.SS "void aacio::abi_generator::enable_optimizaton (abi_generator::optimization o)"

.PP
Enable optimization when generating ABI\&. 
.PP
\fBParameters:\fP
.RS 4
\fIo\fP optimization to enable 
.RE
.PP

.SS "void aacio::abi_generator::handle_tagdecl_definition (TagDecl * tag_decl)"

.PP
Handle declaration of struct/union/enum\&. 
.PP
\fBParameters:\fP
.RS 4
\fItag_decl\fP declaration to handle 
.RE
.PP

.SS "bool aacio::abi_generator::is_opt_enabled (abi_generator::optimization o)"

.PP
Check if an optimization is enabled\&. 
.PP
\fBParameters:\fP
.RS 4
\fIo\fP optimization to check 
.RE
.PP

.SS "void aacio::abi_generator::set_abi_context (const string & abi_context)"

.PP
Set the root folder that limits where types will be imported\&. Types declared in header files located in child sub-folders will also be exported\&. 
.PP
\fBParameters:\fP
.RS 4
\fIabi_context\fP folder 
.RE
.PP

.SS "void aacio::abi_generator::set_compiler_instance (CompilerInstance & compiler_instance)"

.PP
Set the single instance of the Clang compiler\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcompiler_instance\fP compiler instance 
.RE
.PP

.SS "void aacio::abi_generator::set_output (\fBabi_def\fP & output)"

.PP
Set the destination ABI struct to write\&. 
.PP
\fBParameters:\fP
.RS 4
\fIoutput\fP ABI destination 
.RE
.PP

.SS "void aacio::abi_generator::set_verbose (bool verbose)"

.PP
Enable/Disable verbose status messages\&. 
.PP
\fBParameters:\fP
.RS 4
\fIverbose\fP enable/disable flag 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
