.TH "aacio::chain::resource_limits::resource_usage_object" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::resource_limits::resource_usage_object
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBchainbase::object< resource_usage_object_type, resource_usage_object >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBis_dirty\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBid_type\fP \fBid\fP"
.br
.ti -1c
.RI "\fBaccount_name\fP \fBowner\fP"
.br
.ti -1c
.RI "\fBusage_accumulator\fP \fBnet_usage\fP"
.br
.ti -1c
.RI "\fBusage_accumulator\fP \fBcpu_usage\fP"
.br
.ti -1c
.RI "uint64_t \fBram_usage\fP = 0"
.br
.ti -1c
.RI "uint64_t \fBpending_ram_usage\fP = 0"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
