.TH "aacio::chain::webassembly::binaryen::binaryen_instantiated_module" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::binaryen::binaryen_instantiated_module
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::chain::wasm_instantiated_module_interface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbinaryen_instantiated_module\fP (\fBlinear_memory_type\fP &shared_linear_memory, \fBstd::vector\fP< uint8_t > initial_memory, \fBcall_indirect_table_type\fP table, \fBimport_lut_type\fP import_lut, \fBunique_ptr\fP< \fBModule\fP > &&module)"
.br
.ti -1c
.RI "void \fBapply\fP (\fBapply_context\fP &context) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
