.TH "aaciosystem::delegate_bandwidth< SystemAccount >::total_resources" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aaciosystem::delegate_bandwidth< SystemAccount >::total_resources
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBprimary_key\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "account_name \fBowner\fP"
.br
.ti -1c
.RI "currency::token_type \fBnet_weight\fP"
.br
.ti -1c
.RI "currency::token_type \fBcpu_weight\fP"
.br
.ti -1c
.RI "currency::token_type \fBstorage_stake\fP"
.br
.ti -1c
.RI "uint64_t \fBstorage_bytes\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
