.TH "aacio::chain::wasm_ops::cached_ops< Op_Types >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::wasm_ops::cached_ops< Op_Types >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wasm_aacio_binary_ops\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBstd::vector\fP< \fBinstr\fP * > * \fBget_cached_ops\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Op_Types>
.br
class aacio::chain::wasm_ops::cached_ops< Op_Types >"
Section for cached ops 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
