.TH "aacio::exchange::upmargin" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::exchange::upmargin
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccount_name\fP \fBborrower\fP"
.br
.ti -1c
.RI "\fBsymbol_type\fP \fBmarket\fP"
.br
.ti -1c
.RI "\fBextended_asset\fP \fBdelta_borrow\fP"
.br
.ti -1c
.RI "\fBextended_asset\fP \fBdelta_collateral\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
