.TH "aacio::chain::webassembly::wavm::wasm_function_type_provider< typename >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::wavm::wasm_function_type_provider< typename >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wavm\&.hpp>\fP
.SH "Detailed Description"
.PP 

.SS "template<typename>
.br
struct aacio::chain::webassembly::wavm::wasm_function_type_provider< typename >"
Forward declaration of provider for FunctionType given a desired \fBC\fP ABI signature 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
