.TH "aacio::chain::action_trace" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::action_trace
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccount_name\fP \fBreceiver\fP"
.br
.ti -1c
.RI "bool \fBcontext_free\fP"
.br
.ti -1c
.RI "uint64_t \fBcpu_usage\fP"
.br
.ti -1c
.RI "\fBaction\fP \fBact\fP"
.br
.ti -1c
.RI "string \fBconsole\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBdata_access_info\fP > \fBdata_access\fP"
.br
.ti -1c
.RI "uint32_t \fBauths_used\fP"
.br
.ti -1c
.RI "\fBfc::microseconds\fP \fB_profiling_us\fP = \fBfc::microseconds\fP(0)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
