.TH "aacio::chain::webassembly::wavm::wavm_instantiated_module" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::wavm::wavm_instantiated_module
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::chain::wasm_instantiated_module_interface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwavm_instantiated_module\fP (\fBModuleInstance\fP *instance, \fBModule\fP *module, \fBstd::vector\fP< uint8_t > initial_mem)"
.br
.ti -1c
.RI "void \fBapply\fP (\fBapply_context\fP &context) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
