.TH "aacio::chain::shard_summary" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::shard_summary
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.RI "new or generated transactions "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvector\fP< \fBshard_lock\fP > \fBread_locks\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBshard_lock\fP > \fBwrite_locks\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBtransaction_receipt\fP > \fBtransactions\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
