.TH "aacio::chain::wasm_interface" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::wasm_interface
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBvm_type\fP { \fBwavm\fP, \fBbinaryen\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwasm_interface\fP (vm_type vm)"
.br
.ti -1c
.RI "void \fBapply\fP (const \fBdigest_type\fP &code_id, const shared_vector< char > &code, \fBapply_context\fP &context)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBvalidate\fP (const \fBbytes\fP &code)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBaacio::chain::webassembly::common::intrinsics_accessor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
