.TH "aacio::chain::permission_visitor" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::permission_visitor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpermission_visitor\fP (const \fBchain_controller\fP &controller)"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBpermission_level\fP &perm_level)"
.br
.ti -1c
.RI "void \fBpush_undo\fP ()"
.br
.ti -1c
.RI "void \fBpop_undo\fP ()"
.br
.ti -1c
.RI "void \fBsquash_undo\fP ()"
.br
.ti -1c
.RI "\fBfc::microseconds\fP \fBget_max_delay\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
