.TH "aacio::chain::webassembly::wavm::wasm_function_type_provider< Ret(Args...)>" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::wavm::wasm_function_type_provider< Ret(Args...)>
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wavm\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const \fBFunctionType\fP * \fBtype\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Ret, typename \&.\&.\&. Args>
.br
struct aacio::chain::webassembly::wavm::wasm_function_type_provider< Ret(Args\&.\&.\&.)>"
specialization to destructure return and arguments 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
