.TH "aacio::test::expector< Pred, Eval, T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::test::expector< Pred, Eval, T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexpector\fP (Eval _eval, const \fBT\fP &_expected, const char *const _msg)"
.br
.ti -1c
.RI "template<typename Input > void \fBoperator()\fP (const Input &input)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP \fBexpected\fP"
.br
.ti -1c
.RI "Eval \fBeval\fP"
.br
.ti -1c
.RI "char const  *const \fBmsg\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
