.TH "aacio::testing::tester" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::testing::tester \- provides utility function to simplify the creation of unit tests  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tester\&.hpp>\fP
.PP
Inherits \fBaacio::testing::base_tester\fP\&.
.PP
Inherited by \fBaacio_msig_tester\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtester\fP (bool push_genesis, \fBchain_controller::runtime_limits\fP limits=\fBchain_controller::runtime_limits\fP())"
.br
.ti -1c
.RI "\fBtester\fP (\fBchain_controller::runtime_limits\fP limits=\fBchain_controller::runtime_limits\fP())"
.br
.ti -1c
.RI "\fBtester\fP (\fBchain_controller::controller_config\fP \fBconfig\fP)"
.br
.ti -1c
.RI "\fBsigned_block\fP \fBproduce_block\fP (\fBfc::microseconds\fP skip_time=fc::milliseconds(config::block_interval_ms), uint32_t skip_flag=skip_missed_block_penalty) override"
.br
.ti -1c
.RI "bool \fBvalidate\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
provides utility function to simplify the creation of unit tests 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
