.TH "aacio::currency::create" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::currency::create
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccount_name\fP \fBissuer\fP"
.br
.ti -1c
.RI "\fBasset\fP \fBmaximum_supply\fP"
.br
.ti -1c
.RI "uint8_t \fBissuer_can_freeze\fP = true"
.br
.ti -1c
.RI "uint8_t \fBissuer_can_recall\fP = true"
.br
.ti -1c
.RI "uint8_t \fBissuer_can_whitelist\fP = true"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
