.TH "aacio::chain::shared_producer_schedule_type" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::shared_producer_schedule_type
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshared_producer_schedule_type\fP (chainbase::allocator< char > alloc)"
.br
.ti -1c
.RI "\fBshared_producer_schedule_type\fP & \fBoperator=\fP (const \fBproducer_schedule_type\fP &a)"
.br
.ti -1c
.RI "\fBoperator producer_schedule_type\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBversion\fP = 0"
.br
.RI "sequentially incrementing version number "
.ti -1c
.RI "shared_vector< \fBproducer_key\fP > \fBproducers\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
