.TH "aacio::wallet::plain_keys" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::wallet::plain_keys
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfc::sha512\fP \fBchecksum\fP"
.br
.ti -1c
.RI "\fBmap\fP< \fBpublic_key_type\fP, \fBprivate_key_type\fP > \fBkeys\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
