.TH "aacio::currency::currency_stats" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::currency::currency_stats
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBprimary_key\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBasset\fP \fBsupply\fP"
.br
.ti -1c
.RI "\fBasset\fP \fBmax_supply\fP"
.br
.ti -1c
.RI "\fBaccount_name\fP \fBissuer\fP"
.br
.ti -1c
.RI "bool \fBcan_freeze\fP = true"
.br
.ti -1c
.RI "bool \fBcan_recall\fP = true"
.br
.ti -1c
.RI "bool \fBcan_whitelist\fP = true"
.br
.ti -1c
.RI "bool \fBis_frozen\fP = false"
.br
.ti -1c
.RI "bool \fBenforce_whitelist\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
