.TH "aacio::multi_index< TableName, T, Indices >::index< IndexName, Extractor, Number, IsConst >::const_iterator" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::multi_index< TableName, T, Indices >::index< IndexName, Extractor, Number, IsConst >::const_iterator
.SH SYNOPSIS
.br
.PP
.PP
Inherits iterator< std::bidirectional_iterator_tag, const T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const \fBT\fP & \fBoperator*\fP () const"
.br
.ti -1c
.RI "const \fBT\fP * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBoperator++\fP (int) const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBoperator\-\-\fP (int) const"
.br
.ti -1c
.RI "\fBconst_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBconst_iterator\fP & \fBoperator\-\-\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "struct \fBindex\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBconst_iterator\fP &a, const \fBconst_iterator\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBconst_iterator\fP &a, const \fBconst_iterator\fP &b)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
