.TH "aaciosystem::authority" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aaciosystem::authority
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBthreshold\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBkey_weight\fP > \fBkeys\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBpermission_level_weight\fP > \fBaccounts\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
