.TH "aacio::chain::webassembly::wavm::intrinsic_invoker_impl< Ret, std::tuple< array_ptr< char >, int, size_t >, std::tuple<> >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::wavm::intrinsic_invoker_impl< Ret, std::tuple< array_ptr< char >, int, size_t >, std::tuple<> >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wavm\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBnext_step\fP = \fBintrinsic_invoker_impl\fP< Ret, std::tuple<>, std::tuple< I32, I32, I32 > >"
.br
.ti -1c
.RI "using \fBthen_type\fP = Ret(*)(\fBrunning_instance_context\fP &, \fBarray_ptr\fP< char >, int, size_t)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<then_type Then> static Ret \fBtranslate_one\fP (\fBrunning_instance_context\fP &ctx, I32 ptr, I32 value, I32 size)"
.br
.ti -1c
.RI "template<then_type Then> static const auto \fBfn\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Ret>
.br
struct aacio::chain::webassembly::wavm::intrinsic_invoker_impl< Ret, std::tuple< array_ptr< char >, int, size_t >, std::tuple<> >"
Specialization for transcribing memset parameters
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIRet\fP - the return type of the native method 
.br
\fIInputs\fP - the remaining native parameters to transcribe 
.br
\fITranslated\fP - the list of transcribed wasm parameters 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
