.TH "aacio::chain::block_summary_object" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::block_summary_object \- tracks minimal information about past blocks to implement TaPOS
.PP
When attempting to calculate the validity of a transaction we need to lookup a past block and check its block hash and the time it occurred so we can calculate whether the current transaction is valid and at what time it should expire\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <block_summary_object\&.hpp>\fP
.PP
Inherits \fBchainbase::object< block_summary_object_type, block_summary_object >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
tracks minimal information about past blocks to implement TaPOS
.PP
When attempting to calculate the validity of a transaction we need to lookup a past block and check its block hash and the time it occurred so we can calculate whether the current transaction is valid and at what time it should expire\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
