.TH "aacio::chain::authority_checker< PermissionToAuthorityFunc, PermissionVisitorFunc >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::authority_checker< PermissionToAuthorityFunc, PermissionVisitorFunc > \- namespace detail  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <authority_checker\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBauthority_checker\fP (PermissionToAuthorityFunc permission_to_authority, PermissionVisitorFunc \fBpermission_visitor\fP, uint16_t recursion_depth_limit, const flat_set< \fBpublic_key_type\fP > &signing_keys, const flat_set< \fBaccount_name\fP > &provided_auths=flat_set< \fBaccount_name\fP >(), const flat_set< \fBpermission_level\fP > &provided_levels=flat_set< \fBpermission_level\fP >())"
.br
.ti -1c
.RI "bool \fBsatisfied\fP (const \fBpermission_level\fP &permission, uint16_t depth=0)"
.br
.ti -1c
.RI "template<typename AuthorityType > bool \fBsatisfied\fP (const AuthorityType &\fBauthority\fP, uint16_t depth=0)"
.br
.ti -1c
.RI "bool \fBall_keys_used\fP () const"
.br
.ti -1c
.RI "flat_set< \fBpublic_key_type\fP > \fBused_keys\fP () const"
.br
.ti -1c
.RI "flat_set< \fBpublic_key_type\fP > \fBunused_keys\fP () const"
.br
.ti -1c
.RI "const PermissionVisitorFunc & \fBget_permission_visitor\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename PermissionToAuthorityFunc, typename PermissionVisitorFunc>
.br
class aacio::chain::authority_checker< PermissionToAuthorityFunc, PermissionVisitorFunc >"
namespace detail 

This class determines whether a set of signing keys are sufficient to satisfy an authority or not
.PP
To determine whether an authority is satisfied or not, we first determine which keys have approved of a message, and then determine whether that list of keys is sufficient to satisfy the authority\&. This class takes a list of keys and provides the \fBsatisfied\fP method to determine whether that list of keys satisfies a provided authority\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fI\fBF\fP\fP \fBA\fP callable which takes a single argument of type \fBAccountPermission\fP and returns the corresponding authority 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
