.TH "aacio::chain::wasm_instantiated_module_interface" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::wasm_instantiated_module_interface
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBaacio::chain::webassembly::binaryen::binaryen_instantiated_module\fP, and \fBaacio::chain::webassembly::wavm::wavm_instantiated_module\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBapply\fP (\fBapply_context\fP &context)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
