.TH "aacio::chain::symbol" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::symbol
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsymbol\fP (uint8_t p, const char *s)"
.br
.ti -1c
.RI "\fBsymbol\fP (uint64_t v=SY(4, AAC))"
.br
.ti -1c
.RI "uint64_t \fBvalue\fP () const"
.br
.ti -1c
.RI "bool \fBvalid\fP () const"
.br
.ti -1c
.RI "uint8_t \fBdecimals\fP () const"
.br
.ti -1c
.RI "uint64_t \fBprecision\fP () const"
.br
.ti -1c
.RI "string \fBname\fP () const"
.br
.ti -1c
.RI "\fBsymbol_code\fP \fBto_symbol_code\fP () const"
.br
.ti -1c
.RI "\fBoperator string\fP () const"
.br
.ti -1c
.RI "string \fBto_string\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBsymbol\fP \fBfrom_string\fP (const string &from)"
.br
.ti -1c
.RI "static bool \fBvalid_name\fP (const string &\fBname\fP)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "struct \fBfc::reflector< symbol >\fP"
.br
.ti -1c
.RI "template<typename DataStream > DataStream & \fBoperator<<\fP (DataStream &ds, const \fBsymbol\fP &s)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
