.TH "aacio::generic_currency< Token >::account" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::generic_currency< Token >::account
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBprimary_key\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "token_type \fBbalance\fP"
.br
.ti -1c
.RI "uint64_t \fBsymbol\fP = token_type::symbol"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
