.TH "aacio::request_message" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::request_message
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBordered_txn_ids\fP \fBreq_trx\fP"
.br
.ti -1c
.RI "\fBordered_blk_ids\fP \fBreq_blocks\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
