.TH "aacio::detail::faucet_testnet_create_account_params" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::detail::faucet_testnet_create_account_params
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBaccount\fP"
.br
.ti -1c
.RI "\fBfaucet_testnet_keys\fP \fBkeys\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
