.TH "aacio::chain::authority" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::authority
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBauthority\fP (\fBpublic_key_type\fP k)"
.br
.ti -1c
.RI "\fBauthority\fP (uint32_t t, \fBvector\fP< \fBkey_weight\fP > k, \fBvector\fP< \fBpermission_level_weight\fP > p={})"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBthreshold\fP = 0"
.br
.ti -1c
.RI "\fBvector\fP< \fBkey_weight\fP > \fBkeys\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBpermission_level_weight\fP > \fBaccounts\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
