.TH "aacio::indexed_by< IndexName, Extractor >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::indexed_by< IndexName, Extractor >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBconstants\fP { \fBindex_name\fP = IndexName }"
.br
.ti -1c
.RI "typedef Extractor \fBsecondary_extractor_type\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
