.TH "aacio::chain::aac_extension_unpack_visitor< Stream, T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::aac_extension_unpack_visitor< Stream, T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaac_extension_unpack_visitor\fP (Stream &s, \fBT\fP &v)"
.br
.ti -1c
.RI "void \fBmaybe_read_next_which\fP () const"
.br
.ti -1c
.RI "template<typename Member , class Class , Member Class::* member> void \fBoperator()\fP (const char *\fBname\fP) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBwhich\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBnext_which\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBcount_left\fP = 0"
.br
.ti -1c
.RI "Stream & \fBstream\fP"
.br
.ti -1c
.RI "\fBT\fP & \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
