.TH "aacio::chain::contracts::onerror" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::onerror
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstd::vector< T, Alloc >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBaccount_name\fP \fBget_account\fP ()"
.br
.ti -1c
.RI "static action_name \fBget_name\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
