.TH "aaciosystem::native< SystemAccount >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aaciosystem::native< SystemAccount >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBaaciosystem::contract< SystemAccount >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBonerror\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBACTION\fP (SystemAccount, newaccount)"
.br
.ti -1c
.RI "\fBACTION\fP (SystemAccount, updateauth)"
.br
.ti -1c
.RI "\fBACTION\fP (SystemAccount, deleteauth)"
.br
.ti -1c
.RI "\fBACTION\fP (SystemAccount, linkauth)"
.br
.ti -1c
.RI "\fBACTION\fP (SystemAccount, unlinkauth)"
.br
.ti -1c
.RI "\fBACTION\fP (SystemAccount, postrecovery)"
.br
.ti -1c
.RI "\fBACTION\fP (SystemAccount, passrecovery)"
.br
.ti -1c
.RI "\fBACTION\fP (SystemAccount, vetorecovery)"
.br
.ti -1c
.RI "\fBACTION\fP (SystemAccount, canceldelay)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBon\fP (const newaccount &)"
.br
.ti -1c
.RI "static void \fBon\fP (const updateauth &)"
.br
.ti -1c
.RI "static void \fBon\fP (const deleteauth &)"
.br
.ti -1c
.RI "static void \fBon\fP (const linkauth &)"
.br
.ti -1c
.RI "static void \fBon\fP (const unlinkauth &)"
.br
.ti -1c
.RI "static void \fBon\fP (const postrecovery &)"
.br
.ti -1c
.RI "static void \fBon\fP (const passrecovery &)"
.br
.ti -1c
.RI "static void \fBon\fP (const vetorecovery &)"
.br
.ti -1c
.RI "static void \fBon\fP (const \fBonerror\fP &)"
.br
.ti -1c
.RI "static void \fBon\fP (const canceldelay &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
