.TH "aacio::account_history_plugin_impl" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::account_history_plugin_impl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpacked_transaction\fP \fBget_transaction\fP (const \fBchain::transaction_id_type\fP &transaction_id) const"
.br
.ti -1c
.RI "\fBget_transactions_results\fP \fBget_transactions\fP (const \fBaccount_name\fP &\fBaccount_name\fP, const \fBoptional\fP< uint32_t > &skip_seq, const \fBoptional\fP< uint32_t > &num_seq) const"
.br
.ti -1c
.RI "\fBvector\fP< \fBaccount_name\fP > \fBget_key_accounts\fP (const \fBpublic_key_type\fP &\fBpublic_key\fP) const"
.br
.ti -1c
.RI "\fBvector\fP< \fBaccount_name\fP > \fBget_controlled_accounts\fP (const \fBaccount_name\fP &controlling_account) const"
.br
.ti -1c
.RI "void \fBapplied_block\fP (const \fBchain::block_trace\fP &)"
.br
.ti -1c
.RI "\fBfc::variant\fP \fBtransaction_to_variant\fP (const \fBpacked_transaction\fP &pretty_input) const"
.br
.ti -1c
.RI "void \fBcheck_init_db\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchain_plugin\fP * \fBchain_plug\fP"
.br
.ti -1c
.RI "int64_t \fBtransactions_time_limit\fP = DEFAULT_TRANSACTION_TIME_LIMIT"
.br
.ti -1c
.RI "\fBstd::set\fP< \fBaccount_name\fP > \fBfilter_on\fP"
.br
.ti -1c
.RI "bool \fBinit_db\fP = false"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int64_t \fBDEFAULT_TRANSACTION_TIME_LIMIT\fP = 3"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
