.TH "aacio::chain::action_api" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::action_api
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::chain::context_aware_api\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaction_api\fP (\fBapply_context\fP &ctx)"
.br
.ti -1c
.RI "int \fBread_action_data\fP (\fBarray_ptr\fP< char > memory, size_t size)"
.br
.ti -1c
.RI "int \fBaction_data_size\fP ()"
.br
.ti -1c
.RI "\fBfc::time_point_sec\fP \fBpublication_time\fP ()"
.br
.ti -1c
.RI "\fBname\fP \fBcurrent_sender\fP ()"
.br
.ti -1c
.RI "\fBname\fP \fBcurrent_receiver\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
