.TH "aacio::wallet_plugin" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::wallet_plugin
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBappbase::plugin< wallet_plugin >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwallet_plugin\fP (const \fBwallet_plugin\fP &)=delete"
.br
.ti -1c
.RI "\fBwallet_plugin\fP (\fBwallet_plugin\fP &&)=delete"
.br
.ti -1c
.RI "\fBwallet_plugin\fP & \fBoperator=\fP (const \fBwallet_plugin\fP &)=delete"
.br
.ti -1c
.RI "\fBwallet_plugin\fP & \fBoperator=\fP (\fBwallet_plugin\fP &&)=delete"
.br
.ti -1c
.RI "virtual void \fBset_program_options\fP (options_description &cli, options_description &cfg) override"
.br
.ti -1c
.RI "void \fBplugin_initialize\fP (const variables_map &options)"
.br
.ti -1c
.RI "void \fBplugin_startup\fP ()"
.br
.ti -1c
.RI "void \fBplugin_shutdown\fP ()"
.br
.ti -1c
.RI "\fBwallet_manager\fP & \fBget_wallet_manager\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
