.TH "aacio::exaccount" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::exaccount
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exchange_accounts\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBprimary_key\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccount_name\fP \fBowner\fP"
.br
.ti -1c
.RI "flat_map< \fBextended_symbol\fP, int64_t > \fBbalances\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Each user has their own account with the exchange contract that keeps track of how much a user has on deposit for each extended asset type\&. The assumption is that storing a single flat map of all balances for a particular user will be more practical than breaking this down into a multi-index table sorted by the \fBextended_symbol\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
