.TH "aacio::faucet_testnet_plugin" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::faucet_testnet_plugin
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBappbase::plugin< faucet_testnet_plugin >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBset_program_options\fP (options_description &, options_description &cfg) override"
.br
.ti -1c
.RI "void \fBplugin_initialize\fP (const variables_map &options)"
.br
.ti -1c
.RI "void \fBplugin_startup\fP ()"
.br
.ti -1c
.RI "void \fBplugin_shutdown\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
