.TH "aacio::multisig" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::multisig
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::contract\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmultisig\fP (\fBaccount_name\fP self)"
.br
.ti -1c
.RI "void \fBpropose\fP ()"
.br
.ti -1c
.RI "void \fBapprove\fP (\fBaccount_name\fP proposer, \fBname\fP proposal_name, \fBpermission_level\fP level)"
.br
.ti -1c
.RI "void \fBunapprove\fP (\fBaccount_name\fP proposer, \fBname\fP proposal_name, \fBpermission_level\fP level)"
.br
.ti -1c
.RI "void \fBcancel\fP (\fBaccount_name\fP proposer, \fBname\fP proposal_name, \fBaccount_name\fP canceler)"
.br
.ti -1c
.RI "void \fBexec\fP (\fBaccount_name\fP proposer, \fBname\fP proposal_name, \fBaccount_name\fP executer)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
