.TH "aacio::chain::scope_sequence_object" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::scope_sequence_object
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBchainbase::object< scope_sequence_object_type, scope_sequence_object >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
