.TH "aaciosystem::voting< SystemAccount >::voter_info" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aaciosystem::voting< SystemAccount >::voter_info
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBprimary_key\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "account_name \fBowner\fP = 0"
.br
.ti -1c
.RI "account_name \fBproxy\fP = 0"
.br
.ti -1c
.RI "time \fBlast_update\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBis_proxy\fP = 0"
.br
.ti -1c
.RI "system_token_type \fBstaked\fP"
.br
.ti -1c
.RI "system_token_type \fBunstaking\fP"
.br
.ti -1c
.RI "system_token_type \fBunstake_per_week\fP"
.br
.ti -1c
.RI "uint128_t \fBproxied_votes\fP = 0"
.br
.ti -1c
.RI "\fBstd::vector\fP< account_name > \fBproducers\fP"
.br
.ti -1c
.RI "uint32_t \fBdeferred_trx_id\fP = 0"
.br
.ti -1c
.RI "time \fBlast_unstake_time\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
