.TH "aacio::public_key_history_object" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::public_key_history_object
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBchainbase::object< chain::public_key_history_object_type, public_key_history_object >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
