.TH "aacio::action_meta< Account, Name >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::action_meta< Account, Name >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBidentity_test::contract::get_identity_for_account\fP, and \fBidentity_test::contract::get_owner_for_identity\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static uint64_t \fBget_account\fP ()"
.br
.ti -1c
.RI "static uint64_t \fBget_name\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
