.TH "aacio::testing::validating_tester" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::testing::validating_tester
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::testing::base_tester\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvalidating_tester\fP (\fBchain_controller::runtime_limits\fP limits=\fBchain_controller::runtime_limits\fP())"
.br
.ti -1c
.RI "\fBvalidating_tester\fP (\fBchain_controller::controller_config\fP \fBconfig\fP)"
.br
.ti -1c
.RI "\fBsigned_block\fP \fBproduce_block\fP (\fBfc::microseconds\fP skip_time=fc::milliseconds(config::block_interval_ms), uint32_t skip_flag=skip_missed_block_penalty) override"
.br
.ti -1c
.RI "bool \fBvalidate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBunique_ptr\fP< \fBchain_controller\fP > \fBvalidating_node\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
