.TH "aacio::chain::string_api" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::string_api
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::chain::context_aware_api\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBassert_is_utf8\fP (\fBarray_ptr\fP< const char > str, size_t datalen, \fBnull_terminated_ptr\fP msg)"
.br
.ti -1c
.RI "\fBcontext_aware_api\fP (\fBapply_context\fP &ctx, bool context_free=false)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
