.TH "aacio::find_aacio_abi_macro_action::callback_handler" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::find_aacio_abi_macro_action::callback_handler
.SH SYNOPSIS
.br
.PP
.PP
Inherits PPCallbacks\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcallback_handler\fP (CompilerInstance &compiler_instance, \fBfind_aacio_abi_macro_action\fP &act)"
.br
.ti -1c
.RI "void \fBMacroExpands\fP (const Token &\fBtoken\fP, const MacroDefinition &md, SourceRange range, const MacroArgs *args) override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CompilerInstance & \fBcompiler_instance\fP"
.br
.ti -1c
.RI "\fBfind_aacio_abi_macro_action\fP & \fBact\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
