.TH "aacio::chain::webassembly::wavm::native_to_wasm< T * >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::wavm::native_to_wasm< T * >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wavm\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = I32"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct aacio::chain::webassembly::wavm::native_to_wasm< T * >"
specialization for mapping pointers to int32's 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
