.TH "aacio::chain::contracts::type_def" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::type_def
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtype_def\fP (const type_name &new_type_name, const type_name &type)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "type_name \fBnew_type_name\fP"
.br
.ti -1c
.RI "type_name \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
