.TH "aacio::currency" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::currency
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <currency\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaccount\fP"
.br
.ti -1c
.RI "struct \fBcreate\fP"
.br
.ti -1c
.RI "struct \fBcurrency_stats\fP"
.br
.ti -1c
.RI "struct \fBfee_schedule\fP"
.br
.ti -1c
.RI "struct \fBissue\fP"
.br
.ti -1c
.RI "struct \fBtransfer\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBaacio::multi_index\fP< \fBN\fP(\fBaccounts\fP), \fBaccount\fP > \fBaccounts\fP"
.br
.ti -1c
.RI "typedef \fBaacio::multi_index\fP< \fBN\fP(stat), \fBcurrency_stats\fP > \fBstats\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcurrency\fP (\fBaccount_name\fP \fBcontract\fP)"
.br
.ti -1c
.RI "\fBasset\fP \fBget_balance\fP (\fBaccount_name\fP owner, symbol_name \fBsymbol\fP) const"
.br
.ti -1c
.RI "\fBasset\fP \fBget_supply\fP (symbol_name \fBsymbol\fP) const"
.br
.ti -1c
.RI "void \fBinline_transfer\fP (\fBaccount_name\fP from, \fBaccount_name\fP to, \fBasset\fP amount, string memo=string(), \fBpermission_name\fP perm=\fBN\fP(active))"
.br
.ti -1c
.RI "bool \fBapply\fP (\fBaccount_name\fP \fBcontract\fP, action_name act)"
.br
.ti -1c
.RI "void \fBcreate_currency\fP (const \fBcreate\fP &c)"
.br
.ti -1c
.RI "void \fBissue_currency\fP (const \fBissue\fP &i)"
.br
.ti -1c
.RI "void \fBon\fP (const \fBcreate\fP &c)"
.br
.ti -1c
.RI "void \fBon\fP (const \fBissue\fP &i)"
.br
.ti -1c
.RI "void \fBon\fP (const \fBtransfer\fP &t)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinline_transfer\fP (\fBaccount_name\fP from, \fBaccount_name\fP to, \fBextended_asset\fP amount, string memo=string(), \fBpermission_name\fP perm=\fBN\fP(active))"
.br
.in -1c
.SH "Detailed Description"
.PP 
This contract enables the creation, issuance, and transfering of many different tokens\&. 
.SH "Member Function Documentation"
.PP 
.SS "void aacio::currency::create_currency (const \fBcreate\fP & c)\fC [inline]\fP"
This is factored out so it can be used as a building block 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
