.TH "aacio::chain::webassembly::binaryen::intrinsic_function_invoker< void, MethodSig, Cls, Params... >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::binaryen::intrinsic_function_invoker< void, MethodSig, Cls, Params... >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBimpl\fP = \fBintrinsic_invoker_impl\fP< \fBvoid_type\fP, std::tuple< Params\&.\&.\&. > >"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<MethodSig Method> static \fBvoid_type\fP \fBwrapper\fP (\fBinterpreter_interface\fP *interface, Params\&.\&.\&. params, \fBLiteralList\fP &args, int offset)"
.br
.ti -1c
.RI "template<MethodSig Method> static const intrinsic_registrator::intrinsic_fn \fBfn\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
