.TH "aacio::chain::webassembly::wavm::intrinsic_invoker_impl< Ret, std::tuple< Input, Inputs... >, std::tuple< Translated... > >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::wavm::intrinsic_invoker_impl< Ret, std::tuple< Input, Inputs... >, std::tuple< Translated... > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wavm\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtranslated_type\fP = native_to_wasm_t< Input >"
.br
.ti -1c
.RI "using \fBnext_step\fP = \fBintrinsic_invoker_impl\fP< Ret, std::tuple< Inputs\&.\&.\&. >, std::tuple< Translated\&.\&.\&., translated_type > >"
.br
.ti -1c
.RI "using \fBthen_type\fP = Ret(*)(\fBrunning_instance_context\fP &, Input, Inputs\&.\&.\&., Translated\&.\&.\&.)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<then_type Then> static Ret \fBtranslate_one\fP (\fBrunning_instance_context\fP &ctx, Inputs\&.\&.\&. rest, Translated\&.\&.\&. translated, translated_type last)"
.br
.ti -1c
.RI "template<then_type Then> static const auto \fBfn\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Ret, typename Input, typename\&.\&.\&. Inputs, typename\&.\&.\&. Translated>
.br
struct aacio::chain::webassembly::wavm::intrinsic_invoker_impl< Ret, std::tuple< Input, Inputs\&.\&.\&. >, std::tuple< Translated\&.\&.\&. > >"
Sepcialization for transcribing a simple type in the native method signature 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIRet\fP - the return type of the native method 
.br
\fIInput\fP - the type of the native parameter to transcribe 
.br
\fIInputs\fP - the remaining native parameters to transcribe 
.br
\fITranslated\fP - the list of transcribed wasm parameters 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
