.TH "aacio::chain::contracts::updateauth" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::updateauth
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBaccount_name\fP \fBget_account\fP ()"
.br
.ti -1c
.RI "static action_name \fBget_name\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccount_name\fP \fBaccount\fP"
.br
.ti -1c
.RI "\fBpermission_name\fP \fBpermission\fP"
.br
.ti -1c
.RI "\fBpermission_name\fP \fBparent\fP"
.br
.ti -1c
.RI "\fBauthority\fP \fBdata\fP"
.br
.ti -1c
.RI "uint32_t \fBdelay\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
