.TH "aacio::chain::contracts::secondary_index< SecondaryKey, ObjectTypeId, SecondaryKeyLess >::index_object" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::secondary_index< SecondaryKey, ObjectTypeId, SecondaryKeyLess >::index_object
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBchainbase::object< ObjectTypeId, index_object >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef SecondaryKey \fBsecondary_key_type\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchainbase::object\fP< ObjectTypeId, \fBindex_object\fP >::\fBid_type\fP \fBid\fP"
.br
.ti -1c
.RI "\fBtable_id\fP \fBt_id\fP"
.br
.ti -1c
.RI "uint64_t \fBprimary_key\fP"
.br
.ti -1c
.RI "\fBaccount_name\fP \fBpayer\fP = 0"
.br
.ti -1c
.RI "SecondaryKey \fBsecondary_key\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
