.TH "aacio::exchange_state" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::exchange_state
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exchange_state\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBconnector\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBprimary_key\fP () const"
.br
.ti -1c
.RI "\fBextended_asset\fP \fBconvert_to_exchange\fP (\fBconnector\fP &c, \fBextended_asset\fP in)"
.br
.ti -1c
.RI "\fBextended_asset\fP \fBconvert_from_exchange\fP (\fBconnector\fP &c, \fBextended_asset\fP in)"
.br
.ti -1c
.RI "\fBextended_asset\fP \fBconvert\fP (\fBextended_asset\fP from, \fBextended_symbol\fP to)"
.br
.ti -1c
.RI "bool \fBrequires_margin_call\fP (const \fBexchange_state::connector\fP &con) const"
.br
.ti -1c
.RI "bool \fBrequires_margin_call\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccount_name\fP \fBmanager\fP"
.br
.ti -1c
.RI "\fBextended_asset\fP \fBsupply\fP"
.br
.ti -1c
.RI "uint32_t \fBfee\fP = 0"
.br
.ti -1c
.RI "\fBconnector\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBconnector\fP \fBquote\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Uses Bancor math to create a 50/50 relay between two asset types\&. The state of the bancor exchange is entirely contained within this struct\&. There are no external side effects associated with using this API\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
