.TH "aacio::chain::webassembly::binaryen::binaryen_runtime" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::binaryen::binaryen_runtime
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::chain::wasm_runtime_interface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBwasm_instantiated_module_interface\fP > \fBinstantiate_module\fP (const char *code_bytes, size_t code_size, \fBstd::vector\fP< uint8_t > initial_memory) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
