.TH "aaciosystem::delegate_bandwidth< SystemAccount >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aaciosystem::delegate_bandwidth< SystemAccount >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaaciosystem::voting< SystemAccount >\fP\&.
.PP
Inherited by \fBaaciosystem::contract< SystemAccount >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdelegated_bandwidth\fP"
.br
.ti -1c
.RI "struct \fBrefund_request\fP"
.br
.ti -1c
.RI "struct \fBtotal_resources\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBcurrency\fP = typename \fBcommon\fP< SystemAccount >::currency"
.br
.ti -1c
.RI "using \fBsystem_token_type\fP = typename \fBcommon\fP< SystemAccount >::system_token_type"
.br
.ti -1c
.RI "using \fBaacio_parameters\fP = typename \fBcommon\fP< SystemAccount >::aacio_parameters"
.br
.ti -1c
.RI "using \fBglobal_state_singleton\fP = typename \fBcommon\fP< SystemAccount >::global_state_singleton"
.br
.ti -1c
.RI "typedef \fBaacio::multi_index\fP< \fBN\fP(totalband), \fBtotal_resources\fP > \fBtotal_resources_table\fP"
.br
.ti -1c
.RI "typedef \fBaacio::multi_index\fP< \fBN\fP(delband), \fBdelegated_bandwidth\fP > \fBdel_bandwidth_table\fP"
.br
.ti -1c
.RI "typedef \fBaacio::multi_index\fP< \fBN\fP(refunds), \fBrefund_request\fP > \fBrefunds_table\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBACTION\fP (SystemAccount, delegatebw)"
.br
.ti -1c
.RI "\fBACTION\fP (SystemAccount, undelegatebw)"
.br
.ti -1c
.RI "\fBACTION\fP (SystemAccount, refund)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBon\fP (const delegatebw &del)"
.br
.ti -1c
.RI "static void \fBon\fP (account_name receiver, const undelegatebw &del)"
.br
.ti -1c
.RI "static void \fBon\fP (const refund &r)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr account_name \fBsystem_account\fP = SystemAccount"
.br
.ti -1c
.RI "static constexpr time \fBrefund_delay\fP = 3*24*3600"
.br
.ti -1c
.RI "static constexpr time \fBrefund_expiration_time\fP = 3600"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
