.TH "aacio::chain::producer_key" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::producer_key
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <producer_schedule\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccount_name\fP \fBproducer_name\fP"
.br
.ti -1c
.RI "\fBpublic_key_type\fP \fBblock_signing_key\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBproducer_key\fP &a, const \fBproducer_key\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBproducer_key\fP &a, const \fBproducer_key\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used as part of the \fBproducer_schedule_type\fP, mapps the producer name to their key\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
