.TH "aacio::msgHandler" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::msgHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::visitor< void >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmsgHandler\fP (\fBnet_plugin_impl\fP &imp, connection_ptr conn)"
.br
.ti -1c
.RI "template<typename T > void \fBoperator()\fP (const \fBT\fP &msg) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnet_plugin_impl\fP & \fBimpl\fP"
.br
.ti -1c
.RI "connection_ptr \fBc\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
