.TH "aacio::chain::webassembly::wavm::intrinsic_function_invoker< WasmSig, Ret, MethodSig, Cls, Params >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::wavm::intrinsic_function_invoker< WasmSig, Ret, MethodSig, Cls, Params >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wavm\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBimpl\fP = \fBintrinsic_invoker_impl\fP< Ret, std::tuple< Params\&.\&.\&. >, std::tuple<> >"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<MethodSig Method> static Ret \fBwrapper\fP (\fBrunning_instance_context\fP &ctx, Params\&.\&.\&. params)"
.br
.ti -1c
.RI "template<MethodSig Method> static const WasmSig * \fBfn\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename WasmSig, typename Ret, typename MethodSig, typename Cls, typename\&.\&.\&. Params>
.br
struct aacio::chain::webassembly::wavm::intrinsic_function_invoker< WasmSig, Ret, MethodSig, Cls, Params >"
forward declaration of a wrapper class to call methods of the class 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
