.TH "aacio::chain::webassembly::binaryen::intrinsic_registrator" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::binaryen::intrinsic_registrator
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBintrinsic_fn\fP = \fBLiteral\fP(*)(\fBinterpreter_interface\fP *, \fBLiteralList\fP &)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBintrinsic_registrator\fP (const char *\fBname\fP, intrinsic_fn fn)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static auto & \fBget_map\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
