.TH "aacio::chain::context_aware_api" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::context_aware_api
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBaacio::chain::action_api\fP, \fBaacio::chain::checktime_api\fP, \fBaacio::chain::compiler_builtins\fP, \fBaacio::chain::console_api\fP, \fBaacio::chain::context_free_api\fP, \fBaacio::chain::context_free_transaction_api\fP, \fBaacio::chain::crypto_api\fP, \fBaacio::chain::database_api\fP, \fBaacio::chain::math_api\fP, \fBaacio::chain::memory_api\fP, \fBaacio::chain::permission_api\fP, \fBaacio::chain::privileged_api\fP, \fBaacio::chain::producer_api\fP, \fBaacio::chain::softfloat_api\fP, \fBaacio::chain::string_api\fP, \fBaacio::chain::system_api\fP, and \fBaacio::chain::transaction_api\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcontext_aware_api\fP (\fBapply_context\fP &ctx, bool context_free=false)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBapply_context\fP & \fBcontext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
