.TH "aacio_msig_tester" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio_msig_tester
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::testing::tester\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "action_result \fBpush_action\fP (const account_name &signer, const action_name &\fBname\fP, const \fBvariant_object\fP &data, bool auth=true)"
.br
.ti -1c
.RI "\fBtransaction\fP \fBreqauth\fP (account_name from, const \fBvector\fP< \fBpermission_level\fP > &auths)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBabi_serializer\fP \fBabi_ser\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
