.TH "aacio::chain::global_property_object" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::global_property_object \- Maintains global state information (committee_member list, current fees)
.PP
This is an implementation detail\&. The values here are set by committee_members to tune the blockchain parameters\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <global_property_object\&.hpp>\fP
.PP
Inherits \fBchainbase::object< global_property_object_type, global_property_object >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Maintains global state information (committee_member list, current fees)
.PP
This is an implementation detail\&. The values here are set by committee_members to tune the blockchain parameters\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
