.TH "aacio::chain::block_header" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::block_header
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBaacio::chain::signed_block_header\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdigest_type\fP \fBdigest\fP () const"
.br
.ti -1c
.RI "uint32_t \fBblock_num\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static uint32_t \fBnum_from_id\fP (const \fBblock_id_type\fP &id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBblock_id_type\fP \fBprevious\fP"
.br
.ti -1c
.RI "\fBblock_timestamp_type\fP \fBtimestamp\fP"
.br
.ti -1c
.RI "\fBchecksum256_type\fP \fBtransaction_mroot\fP"
.br
.ti -1c
.RI "\fBchecksum256_type\fP \fBaction_mroot\fP"
.br
.RI "mroot of cycles_summary "
.ti -1c
.RI "\fBchecksum256_type\fP \fBblock_mroot\fP"
.br
.ti -1c
.RI "\fBaccount_name\fP \fBproducer\fP"
.br
.ti -1c
.RI "uint32_t \fBschedule_version\fP = 0"
.br
.ti -1c
.RI "\fBoptional\fP< \fBproducer_schedule_type\fP > \fBnew_producers\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint32_t aacio::chain::block_header::schedule_version = 0"
The producer schedule version that should validate this block, this is used to indicate that the prior block which included new_producers->version has been marked irreversible and that it the new producer schedule takes effect this block\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
