.TH "aacio::utilities::rand::random" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::utilities::rand::random
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rand\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrandom\fP (uint64_t seed)"
.br
.ti -1c
.RI "uint64_t \fBnext\fP ()"
.br
.ti -1c
.RI "template<typename Range > void \fBshuffle\fP (Range &&range)"
.br
.in -1c
.SH "Detailed Description"
.PP 
High performance random generator http://xorshift.di.unimi.it/ 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
