.TH "aacio::chain::database_api" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::database_api
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::chain::context_aware_api\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBdb_store_i64\fP (uint64_t scope, uint64_t table, uint64_t payer, uint64_t id, \fBarray_ptr\fP< const char > buffer, size_t buffer_size)"
.br
.ti -1c
.RI "void \fBdb_update_i64\fP (int itr, uint64_t payer, \fBarray_ptr\fP< const char > buffer, size_t buffer_size)"
.br
.ti -1c
.RI "void \fBdb_remove_i64\fP (int itr)"
.br
.ti -1c
.RI "int \fBdb_get_i64\fP (int itr, \fBarray_ptr\fP< char > buffer, size_t buffer_size)"
.br
.ti -1c
.RI "int \fBdb_next_i64\fP (int itr, uint64_t &primary)"
.br
.ti -1c
.RI "int \fBdb_previous_i64\fP (int itr, uint64_t &primary)"
.br
.ti -1c
.RI "int \fBdb_find_i64\fP (uint64_t code, uint64_t scope, uint64_t table, uint64_t id)"
.br
.ti -1c
.RI "int \fBdb_lowerbound_i64\fP (uint64_t code, uint64_t scope, uint64_t table, uint64_t id)"
.br
.ti -1c
.RI "int \fBdb_upperbound_i64\fP (uint64_t code, uint64_t scope, uint64_t table, uint64_t id)"
.br
.ti -1c
.RI "int \fBdb_end_i64\fP (uint64_t code, uint64_t scope, uint64_t table)"
.br
.ti -1c
.RI "\fBcontext_aware_api\fP (\fBapply_context\fP &ctx, bool context_free=false)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
