.TH "aacio::chain::resource_limits::elastic_limit_parameters" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::resource_limits::elastic_limit_parameters
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBtarget\fP"
.br
.ti -1c
.RI "uint64_t \fBmax\fP"
.br
.ti -1c
.RI "uint32_t \fBperiods\fP"
.br
.ti -1c
.RI "uint32_t \fBmax_multiplier\fP"
.br
.ti -1c
.RI "\fBratio\fP \fBcontract_rate\fP"
.br
.ti -1c
.RI "\fBratio\fP \fBexpand_rate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
