.TH "aacio::chain::contracts::field_def" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::field_def
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfield_def\fP (const field_name &\fBname\fP, const type_name &type)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBfield_def\fP &\fBother\fP) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "field_name \fBname\fP"
.br
.ti -1c
.RI "type_name \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
