.TH "aacio::chain::contracts::table_def" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::table_def
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtable_def\fP (const \fBtable_name\fP &\fBname\fP, const type_name &index_type, const \fBvector\fP< field_name > &key_names, const \fBvector\fP< type_name > &key_types, const type_name &type)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtable_name\fP \fBname\fP"
.br
.ti -1c
.RI "type_name \fBindex_type\fP"
.br
.ti -1c
.RI "\fBvector\fP< field_name > \fBkey_names\fP"
.br
.ti -1c
.RI "\fBvector\fP< type_name > \fBkey_types\fP"
.br
.ti -1c
.RI "type_name \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
