.TH "aacio::extended_symbol" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::extended_symbol
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::symbol_type\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBextended_symbol\fP (symbol_name s=0, \fBaccount_name\fP c=0)"
.br
.ti -1c
.RI "void \fBprint\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccount_name\fP \fBcontract\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBextended_symbol\fP &a, const \fBextended_symbol\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBextended_symbol\fP &a, const \fBextended_symbol\fP &b)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
