.TH "aacio::chain::blocknum_producer_schedule" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::blocknum_producer_schedule
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBblocknum_producer_schedule\fP (allocator< char > a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "block_num_type \fBfirst\fP"
.br
.ti -1c
.RI "\fBshared_producer_schedule_type\fP \fBsecond\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
