.TH "aaciosystem::block_header" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aaciosystem::block_header
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchecksum256\fP \fBprevious\fP"
.br
.ti -1c
.RI "time \fBtimestamp\fP"
.br
.ti -1c
.RI "\fBchecksum256\fP \fBtransaction_mroot\fP"
.br
.ti -1c
.RI "\fBchecksum256\fP \fBaction_mroot\fP"
.br
.ti -1c
.RI "\fBchecksum256\fP \fBblock_mroot\fP"
.br
.ti -1c
.RI "account_name \fBproducer\fP"
.br
.ti -1c
.RI "uint32_t \fBschedule_version\fP"
.br
.ti -1c
.RI "\fBaacio::optional\fP< \fBaacio::producer_schedule\fP > \fBnew_producers\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
