.TH "aacio::exchange" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::exchange
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exchange\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcovermargin\fP"
.br
.ti -1c
.RI "struct \fBtrade\fP"
.br
.ti -1c
.RI "struct \fBupmargin\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexchange\fP (\fBaccount_name\fP self)"
.br
.ti -1c
.RI "void \fBcreatex\fP (\fBaccount_name\fP creator, \fBasset\fP initial_supply, uint32_t fee, \fBextended_asset\fP base_deposit, \fBextended_asset\fP quote_deposit)"
.br
.ti -1c
.RI "void \fBdeposit\fP (\fBaccount_name\fP from, \fBextended_asset\fP quantity)"
.br
.ti -1c
.RI "void \fBwithdraw\fP (\fBaccount_name\fP from, \fBextended_asset\fP quantity)"
.br
.ti -1c
.RI "void \fBlend\fP (\fBaccount_name\fP lender, \fBsymbol_type\fP market, \fBextended_asset\fP quantity)"
.br
.ti -1c
.RI "void \fBunlend\fP (\fBaccount_name\fP lender, \fBsymbol_type\fP market, double interest_shares, \fBextended_symbol\fP interest_symbol)"
.br
.ti -1c
.RI "void \fBon\fP (const \fBtrade\fP &t)"
.br
.ti -1c
.RI "void \fBon\fP (const \fBupmargin\fP &b)"
.br
.ti -1c
.RI "void \fBon\fP (const \fBcovermargin\fP &b)"
.br
.ti -1c
.RI "void \fBon\fP (const \fBcurrency::transfer\fP &t, \fBaccount_name\fP code)"
.br
.ti -1c
.RI "void \fBapply\fP (\fBaccount_name\fP \fBcontract\fP, \fBaccount_name\fP act)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This contract enables users to create an exchange between any pair of standard currency types\&. \fBA\fP new exchange is created by funding it with an equal value of both sides of the order book and giving the issuer the initial shares in that orderbook\&.
.PP
To prevent exessive rounding errors, the initial deposit should include a sizeable quantity of both the base and quote currencies and the exchange shares should have a quantity 100x the quantity of the largest initial deposit\&.
.PP
Users must deposit funds into the exchange before they can trade on the exchange\&.
.PP
Each time an exchange is created a new currency for that exchanges market maker is also created\&. This currencies supply and symbol must be unique and it uses the currency contract's tables to manage it\&. 
.SH "Member Function Documentation"
.PP 
.SS "void aacio::exchange::on (const \fBtrade\fP & t)"
TODO: if pending order start deferred trx to fill it 
.SS "void aacio::exchange::on (const \fBupmargin\fP & b)"
This action shall fail if it would result in a margin call if this succeeds then the borrower will see their balances adjusted accordingly, if they don't have sufficient balance to either fund the collateral or pay off the debt then this will fail before we go further\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
