.TH "aacio::chain::shared_authority" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::shared_authority
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshared_authority\fP (chainbase::allocator< char > alloc)"
.br
.ti -1c
.RI "\fBshared_authority\fP & \fBoperator=\fP (const \fBauthority\fP &a)"
.br
.ti -1c
.RI "\fBoperator authority\fP () const"
.br
.ti -1c
.RI "\fBauthority\fP \fBto_authority\fP () const"
.br
.ti -1c
.RI "size_t \fBget_billable_size\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBthreshold\fP = 0"
.br
.ti -1c
.RI "shared_vector< \fBkey_weight\fP > \fBkeys\fP"
.br
.ti -1c
.RI "shared_vector< \fBpermission_level_weight\fP > \fBaccounts\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "size_t aacio::chain::shared_authority::get_billable_size () const\fC [inline]\fP"
< serialized size of the key 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
