.TH "aacio::select_ids< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::select_ids< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "id_list_modes \fBmode\fP"
.br
.ti -1c
.RI "uint32_t \fBpending\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBT\fP > \fBids\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
