.TH "aaciosystem::common< SystemAccount >::aacio_global_state" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aaciosystem::common< SystemAccount >::aacio_global_state
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaaciosystem::common< SystemAccount >::aacio_parameters\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBtotal_storage_bytes_reserved\fP = 0"
.br
.ti -1c
.RI "system_token_type \fBtotal_storage_stake\fP"
.br
.ti -1c
.RI "system_token_type \fBpayment_per_block\fP = system_token_type()"
.br
.ti -1c
.RI "system_token_type \fBpayment_to_aac_bucket\fP = system_token_type()"
.br
.ti -1c
.RI "time \fBfirst_block_time_in_cycle\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBblocks_per_cycle\fP = 0"
.br
.ti -1c
.RI "time \fBlast_bucket_fill_time\fP = 0"
.br
.ti -1c
.RI "system_token_type \fBaac_bucket\fP = system_token_type()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
