.TH "aacio::chain::contracts::table_id_object" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::table_id_object \- The \fBtable_id_object\fP class tracks the mapping of (scope, code, table) to an opaque identifier\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <contract_table_objects\&.hpp>\fP
.PP
Inherits \fBchainbase::object< table_id_object_type, table_id_object >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBtable_id_object\fP class tracks the mapping of (scope, code, table) to an opaque identifier\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
