.TH "aacio::chain::memory_api" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::memory_api
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::chain::context_aware_api\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmemory_api\fP (\fBapply_context\fP &ctx)"
.br
.ti -1c
.RI "char * \fBmemcpy\fP (\fBarray_ptr\fP< char > dest, \fBarray_ptr\fP< const char > src, size_t length)"
.br
.ti -1c
.RI "char * \fBmemmove\fP (\fBarray_ptr\fP< char > dest, \fBarray_ptr\fP< const char > src, size_t length)"
.br
.ti -1c
.RI "int \fBmemcmp\fP (\fBarray_ptr\fP< const char > dest, \fBarray_ptr\fP< const char > src, size_t length)"
.br
.ti -1c
.RI "char * \fBmemset\fP (\fBarray_ptr\fP< char > dest, int value, size_t length)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
