.TH "aacio::find_aacio_abi_macro_action" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::find_aacio_abi_macro_action
.SH SYNOPSIS
.br
.PP
.PP
Inherits PreprocessOnlyAction\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcallback_handler\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfind_aacio_abi_macro_action\fP (string &\fBcontract\fP, \fBvector\fP< string > &actions, const string &abi_context)"
.br
.ti -1c
.RI "void \fBExecuteAction\fP () override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string & \fBcontract\fP"
.br
.ti -1c
.RI "\fBvector\fP< string > & \fBactions\fP"
.br
.ti -1c
.RI "const string & \fBabi_context\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
