.TH "aacio::chain::webassembly::wavm::intrinsic_invoker_impl< void_type, std::tuple<>, std::tuple< Translated... > >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::wavm::intrinsic_invoker_impl< void_type, std::tuple<>, std::tuple< Translated... > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wavm\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBnext_method_type\fP = \fBvoid_type\fP(*)(\fBrunning_instance_context\fP &, Translated\&.\&.\&.)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<next_method_type Method> static void \fBinvoke\fP (Translated\&.\&.\&. translated)"
.br
.ti -1c
.RI "template<next_method_type Method> static const auto \fBfn\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename \&.\&.\&. Translated>
.br
struct aacio::chain::webassembly::wavm::intrinsic_invoker_impl< void_type, std::tuple<>, std::tuple< Translated\&.\&.\&. > >"
specialization of the fully transcribed signature for void return values 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fITranslated\fP - the arguments to the wasm function 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
