.TH "aacio::chain::console_api" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::console_api
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::chain::context_aware_api\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconsole_api\fP (\fBapply_context\fP &ctx)"
.br
.ti -1c
.RI "void \fBprints\fP (\fBnull_terminated_ptr\fP str)"
.br
.ti -1c
.RI "void \fBprints_l\fP (\fBarray_ptr\fP< const char > str, size_t str_len)"
.br
.ti -1c
.RI "void \fBprintui\fP (uint64_t val)"
.br
.ti -1c
.RI "void \fBprinti\fP (int64_t val)"
.br
.ti -1c
.RI "void \fBprinti128\fP (const unsigned __int128 &val)"
.br
.ti -1c
.RI "void \fBprintdf\fP (double val)"
.br
.ti -1c
.RI "void \fBprintff\fP (float val)"
.br
.ti -1c
.RI "void \fBprintn\fP (const \fBname\fP &value)"
.br
.ti -1c
.RI "void \fBprinthex\fP (\fBarray_ptr\fP< const char > data, size_t data_len)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
