.TH "aacio::chain::contracts::impl::type_requires_abi< T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::impl::type_requires_abi< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <abi_serializer\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static constexpr bool \fBvalue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct aacio::chain::contracts::impl::type_requires_abi< T >"
Basic constexpr for a type, aliases the basic check directly 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fI\fBT\fP\fP - the type to check 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
