.TH "aacio::chain::properties_median_calculator_visitor< T, Range >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::properties_median_calculator_visitor< T, Range >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBproperties_median_calculator_visitor\fP (\fBT\fP &medians, Range votes)"
.br
.ti -1c
.RI "template<typename Member , class Class , Member Class::* member> void \fBoperator()\fP (const char *) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP & \fBmedians\fP"
.br
.ti -1c
.RI "Range \fBvotes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
