.TH "aacio::deferred_transaction" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::deferred_transaction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::transaction\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBdeferred_transaction\fP \fBfrom_current_action\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint128_t \fBsender_id\fP"
.br
.ti -1c
.RI "\fBaccount_name\fP \fBsender\fP"
.br
.ti -1c
.RI "\fBaccount_name\fP \fBpayer\fP"
.br
.ti -1c
.RI "time \fBexecute_after\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
