.TH "aacio::chain::config::billable_size< permission_link_object >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::config::billable_size< permission_link_object >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const uint64_t \fBoverhead\fP = overhead_per_row_per_index_ram_bytes * 3"
.br
.RI "3x indices id, action, permission "
.ti -1c
.RI "static const uint64_t \fBvalue\fP = 40 + \fBoverhead\fP"
.br
.RI "fixed field + overhead "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
