.TH "aacio::chain::shard_lock" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::shard_lock
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccount_name\fP \fBaccount\fP"
.br
.ti -1c
.RI "\fBscope_name\fP \fBscope\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBshard_lock\fP &a, const \fBshard_lock\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBshard_lock\fP &a, const \fBshard_lock\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBshard_lock\fP &a, const \fBshard_lock\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBshard_lock\fP &a, const \fBshard_lock\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBshard_lock\fP &a, const \fBshard_lock\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBshard_lock\fP &a, const \fBshard_lock\fP &b)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
