.TH "aacio::bios" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::bios
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::contract\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbios\fP (action_name self)"
.br
.ti -1c
.RI "void \fBsetpriv\fP (\fBaccount_name\fP \fBaccount\fP, uint8_t ispriv)"
.br
.ti -1c
.RI "void \fBsetalimits\fP (\fBaccount_name\fP \fBaccount\fP, uint64_t ram_bytes, uint64_t net_weight, uint64_t cpu_weight)"
.br
.ti -1c
.RI "void \fBsetglimits\fP (uint64_t ram, uint64_t net, uint64_t cpu)"
.br
.ti -1c
.RI "void \fBsetprods\fP (\fBproducer_schedule\fP sch)"
.br
.ti -1c
.RI "void \fBreqauth\fP (action_name from)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
