.TH "aaciosystem::common< SystemAccount >::aacio_parameters" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aaciosystem::common< SystemAccount >::aacio_parameters
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::blockchain_parameters\fP\&.
.PP
Inherited by \fBaaciosystem::common< SystemAccount >::aacio_global_state\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBmax_storage_size\fP = 10 * 1024 * 1024"
.br
.ti -1c
.RI "uint32_t \fBpercent_of_max_inflation_rate\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBstorage_reserve_ratio\fP = 1000"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
