.TH "aacio::exchange_state::connector" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::exchange_state::connector
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBextended_asset\fP \fBbalance\fP"
.br
.ti -1c
.RI "uint32_t \fBweight\fP = 500"
.br
.ti -1c
.RI "\fBmargin_state\fP \fBpeer_margin\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
