.TH "aacio::testing::assert_message_is" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::testing::assert_message_is
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tester\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBassert_message_is\fP (string \fBexpected\fP)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBfc::exception\fP &ex)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBexpected\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utility predicate to check whether an FC_ASSERT message ends with a given string 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
