.TH "aacio::transaction_header" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::transaction_header
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBaacio::transaction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtransaction_header\fP (time exp=\fBnow\fP()+60, region_id r=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "time \fBexpiration\fP"
.br
.ti -1c
.RI "region_id \fBregion\fP"
.br
.ti -1c
.RI "uint16_t \fBref_block_num\fP"
.br
.ti -1c
.RI "uint32_t \fBref_block_prefix\fP"
.br
.ti -1c
.RI "\fBunsigned_int\fP \fBnet_usage_words\fP = 0UL"
.br
.ti -1c
.RI "\fBunsigned_int\fP \fBkcpu_usage\fP = 0UL"
.br
.RI "number of 8 byte words this transaction can serialize into after compressions "
.ti -1c
.RI "\fBunsigned_int\fP \fBdelay_sec\fP = 0UL"
.br
.RI "number of CPU usage units to bill transaction for "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
