.TH "aacio::chain::contracts::chain_initializer" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::chain_initializer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBchain_initializer\fP (const \fBgenesis_state_type\fP &genesis)"
.br
.ti -1c
.RI "\fBtime_point\fP \fBget_chain_start_time\fP ()"
.br
.ti -1c
.RI "\fBchain::chain_config\fP \fBget_chain_start_configuration\fP ()"
.br
.ti -1c
.RI "\fBproducer_schedule_type\fP \fBget_chain_start_producers\fP ()"
.br
.ti -1c
.RI "void \fBregister_types\fP (\fBchain::chain_controller\fP &chain, \fBchainbase::database\fP &db)"
.br
.ti -1c
.RI "void \fBprepare_database\fP (\fBchain::chain_controller\fP &chain, \fBchainbase::database\fP &db)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBabi_def\fP \fBaac_contract_abi\fP (const \fBabi_def\fP &aacio_system_abi)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void aacio::chain::contracts::chain_initializer::prepare_database (\fBchain::chain_controller\fP & chain, \fBchainbase::database\fP & db)"
Reserve id of 0 in permission_index by creating dummy \fBpermission_object\fP as the very first object in the index:
.PP
Create the native contract accounts manually; sadly, we can't run their contracts to make them create themselves 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
