.TH "aacio::chain::detail::block_log_impl" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::detail::block_log_impl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcheck_block_read\fP ()"
.br
.ti -1c
.RI "void \fBcheck_block_write\fP ()"
.br
.ti -1c
.RI "void \fBcheck_index_read\fP ()"
.br
.ti -1c
.RI "void \fBcheck_index_write\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBoptional\fP< \fBsigned_block\fP > \fBhead\fP"
.br
.ti -1c
.RI "\fBblock_id_type\fP \fBhead_id\fP"
.br
.ti -1c
.RI "std::fstream \fBblock_stream\fP"
.br
.ti -1c
.RI "std::fstream \fBindex_stream\fP"
.br
.ti -1c
.RI "\fBfc::path\fP \fBblock_file\fP"
.br
.ti -1c
.RI "\fBfc::path\fP \fBindex_file\fP"
.br
.ti -1c
.RI "bool \fBblock_write\fP"
.br
.ti -1c
.RI "bool \fBindex_write\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
