.TH "aacio::chain::webassembly::wavm::intrinsic_function_invoker_wrapper< WasmSig, Ret(Cls::*)(Params...)>" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::webassembly::wavm::intrinsic_function_invoker_wrapper< WasmSig, Ret(Cls::*)(Params...)>
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = \fBintrinsic_function_invoker\fP< WasmSig, Ret, Ret(Cls::*)(Params\&.\&.\&.), Cls, Params\&.\&.\&. >"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
