.TH "aacio::chain::contracts::newaccount" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::newaccount
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBaccount_name\fP \fBget_account\fP ()"
.br
.ti -1c
.RI "static action_name \fBget_name\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccount_name\fP \fBcreator\fP"
.br
.ti -1c
.RI "\fBaccount_name\fP \fBname\fP"
.br
.ti -1c
.RI "\fBauthority\fP \fBowner\fP"
.br
.ti -1c
.RI "\fBauthority\fP \fBactive\fP"
.br
.ti -1c
.RI "\fBauthority\fP \fBrecovery\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
