.TH "aacio::uint128" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::uint128 \- \fBA\fP struct that wraps \fBuint128\fP integer and defines common operator overloads\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <math\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuint128\fP (uint128_t i=0)"
.br
.ti -1c
.RI "\fBuint128\fP (uint64_t i)"
.br
.ti -1c
.RI "\fBuint128\fP (uint32_t i)"
.br
.ti -1c
.RI "\fBuint128\fP & \fBoperator*=\fP (const uint128_t &\fBother\fP)"
.br
.ti -1c
.RI "\fBuint128\fP & \fBoperator*=\fP (const \fBuint128\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBuint128\fP & \fBoperator/=\fP (const uint128_t &\fBother\fP)"
.br
.ti -1c
.RI "\fBuint128\fP & \fBoperator/=\fP (const \fBuint128\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBoperator uint64_t\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBuint128\fP \fBoperator*\fP (\fBuint128\fP a, const \fBuint128\fP &b)"
.br
.ti -1c
.RI "\fBuint128\fP \fBoperator/\fP (\fBuint128\fP a, const \fBuint128\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBuint128\fP &a, const \fBuint128\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBuint128\fP &a, const \fBuint128\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP struct that wraps \fBuint128\fP integer and defines common operator overloads\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
