.TH "aacio::chain::contracts::action_def" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::action_def
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaction_def\fP (const action_name &\fBname\fP, const type_name &type, const string &ricardian_contract)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "action_name \fBname\fP"
.br
.ti -1c
.RI "type_name \fBtype\fP"
.br
.ti -1c
.RI "string \fBricardian_contract\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
