.TH "aacio::symbol_type" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::symbol_type
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBaacio::extended_symbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.ti -1c
.RI "uint64_t \fBprecision\fP () const"
.br
.ti -1c
.RI "uint64_t \fBname\fP () const"
.br
.ti -1c
.RI "uint32_t \fBname_length\fP () const"
.br
.ti -1c
.RI "\fBoperator symbol_name\fP () const"
.br
.ti -1c
.RI "void \fBprint\fP (bool show_precision=true) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "symbol_name \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
