.TH "aacio::chain::transaction" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::transaction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transaction\&.hpp>\fP
.PP
Inherits \fBaacio::chain::transaction_header\fP\&.
.PP
Inherited by \fBaacio::chain::deferred_transaction\fP, and \fBaacio::chain::signed_transaction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtransaction_id_type\fP \fBid\fP () const"
.br
.ti -1c
.RI "\fBdigest_type\fP \fBsig_digest\fP (const \fBchain_id_type\fP &chain_id, const \fBvector\fP< \fBbytes\fP > &cfd=\fBvector\fP< \fBbytes\fP >()) const"
.br
.ti -1c
.RI "flat_set< \fBpublic_key_type\fP > \fBget_signature_keys\fP (const \fBvector\fP< \fBsignature_type\fP > &signatures, const \fBchain_id_type\fP &chain_id, const \fBvector\fP< \fBbytes\fP > &cfd=\fBvector\fP< \fBbytes\fP >(), bool allow_duplicate_keys=false) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvector\fP< \fBaction\fP > \fBcontext_free_actions\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBaction\fP > \fBactions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP transaction consits of a set of messages which must all be applied or all are rejected\&. These messages have access to data within the given read and write scopes\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
