.TH "aacio::chain::producer_object" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::producer_object
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBchainbase::object< producer_object_type, producer_object >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
