.TH "aacio::blockchain_parameters" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::blockchain_parameters
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBaaciosystem::common< SystemAccount >::aacio_parameters\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBbase_per_transaction_net_usage\fP"
.br
.ti -1c
.RI "uint32_t \fBbase_per_transaction_cpu_usage\fP"
.br
.ti -1c
.RI "uint32_t \fBbase_per_action_cpu_usage\fP"
.br
.ti -1c
.RI "uint32_t \fBbase_setcode_cpu_usage\fP"
.br
.ti -1c
.RI "uint32_t \fBper_signature_cpu_usage\fP"
.br
.ti -1c
.RI "uint32_t \fBper_lock_net_usage\fP"
.br
.ti -1c
.RI "uint64_t \fBcontext_free_discount_cpu_usage_num\fP"
.br
.ti -1c
.RI "uint64_t \fBcontext_free_discount_cpu_usage_den\fP"
.br
.ti -1c
.RI "uint32_t \fBmax_transaction_cpu_usage\fP"
.br
.ti -1c
.RI "uint32_t \fBmax_transaction_net_usage\fP"
.br
.ti -1c
.RI "uint64_t \fBmax_block_cpu_usage\fP"
.br
.ti -1c
.RI "uint32_t \fBtarget_block_cpu_usage_pct\fP"
.br
.ti -1c
.RI "uint64_t \fBmax_block_net_usage\fP"
.br
.ti -1c
.RI "uint32_t \fBtarget_block_net_usage_pct\fP"
.br
.ti -1c
.RI "uint32_t \fBmax_transaction_lifetime\fP"
.br
.ti -1c
.RI "uint32_t \fBmax_transaction_exec_time\fP"
.br
.ti -1c
.RI "uint16_t \fBmax_authority_depth\fP"
.br
.ti -1c
.RI "uint16_t \fBmax_inline_depth\fP"
.br
.ti -1c
.RI "uint32_t \fBmax_inline_action_size\fP"
.br
.ti -1c
.RI "uint32_t \fBmax_generated_transaction_count\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
