.TH "aacio::chain::signed_block_summary" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::signed_block_summary
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <block\&.hpp>\fP
.PP
Inherits \fBaacio::chain::signed_block_header\fP\&.
.PP
Inherited by \fBaacio::chain::signed_block\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvector\fP< \fBregion_summary\fP > \fBregions\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The block_summary defines the set of transactions that were successfully applied as they are organized into cycles and shards\&. \fBA\fP shard contains the set of transactions IDs which are either user generated transactions or code-generated transactions\&.
.PP
The primary purpose of a block is to define the order in which messages are processed\&.
.PP
The secodnary purpose of a block is certify that the messages are valid according to a group of 3rd party validators (producers)\&.
.PP
The next purpose of a block is to enable light-weight proofs that a transaction occured and was considered valid\&.
.PP
The next purpose is to enable code to generate messages that are certified by the producers to be authorized\&.
.PP
\fBA\fP block is therefore defined by the ordered set of executed and generated transactions, and the merkle proof is over set of messages delivered as a result of executing the transactions\&.
.PP
\fBA\fP message is defined by { receiver, code, function, permission, data }, the merkle tree of a block should be generated over a set of message IDs rather than a set of transaction ids\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
