.TH "aacio::chain::contracts::genesis_state_type" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::contracts::genesis_state_type
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBchain_id_type\fP \fBcompute_chain_id\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchain_config\fP \fBinitial_configuration\fP"
.br
.ti -1c
.RI "\fBtime_point\fP \fBinitial_timestamp\fP = fc::time_point::from_iso_string( '2018\-03\-01T12:00:00' )"
.br
.ti -1c
.RI "\fBpublic_key_type\fP \fBinitial_key\fP = \fBfc::variant\fP('AAC84snobCGtpQvTTfVaxvMuxGDd4p2LhtQhbWX1yWAU5yt4tiB55')\&.as<\fBpublic_key_type\fP>()"
.br
.ti -1c
.RI "\fBchain_id_type\fP \fBinitial_chain_id\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBchain::chain_id_type\fP aacio::chain::contracts::genesis_state_type::compute_chain_id () const"
Get the chain_id corresponding to this genesis state\&.
.PP
This is the SHA256 serialization of the genesis_state\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBchain_id_type\fP aacio::chain::contracts::genesis_state_type::initial_chain_id"
Temporary, will be moved elsewhere\&. 
.SS "\fBchain_config\fP aacio::chain::contracts::genesis_state_type::initial_configuration"
\fBInitial value:\fP
.PP
.nf
= {
      \&.base_per_transaction_net_usage = config::default_base_per_transaction_net_usage,
      \&.base_per_transaction_cpu_usage = config::default_base_per_transaction_cpu_usage,
      \&.base_per_action_cpu_usage      = config::default_base_per_action_cpu_usage,
      \&.base_setcode_cpu_usage         = config::default_base_setcode_cpu_usage,
      \&.per_signature_cpu_usage        = config::default_per_signature_cpu_usage,
      \&.per_lock_net_usage             = config::default_per_lock_net_usage,
      \&.context_free_discount_cpu_usage_num      = config::default_context_free_discount_cpu_usage_num,
      \&.context_free_discount_cpu_usage_den      = config::default_context_free_discount_cpu_usage_den,
      \&.max_transaction_cpu_usage      = config::default_max_transaction_cpu_usage,
      \&.max_transaction_net_usage      = config::default_max_transaction_net_usage,
      \&.max_block_cpu_usage            = config::default_max_block_cpu_usage,
      \&.target_block_cpu_usage_pct     = config::default_target_block_cpu_usage_pct,
      \&.max_block_net_usage            = config::default_max_block_net_usage,
      \&.target_block_net_usage_pct     = config::default_target_block_net_usage_pct,
      \&.max_transaction_lifetime       = config::default_max_trx_lifetime,
      \&.max_transaction_exec_time      = 0, 
      \&.max_authority_depth            = config::default_max_auth_depth,
      \&.max_inline_depth               = config::default_max_inline_depth,
      \&.max_inline_action_size         = config::default_max_inline_action_size,
      \&.max_generated_transaction_count = config::default_max_gen_trx_count
   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
