.TH "aacio::account_history_api_plugin" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::account_history_api_plugin
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBappbase::plugin< account_history_api_plugin >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAPPBASE_PLUGIN_REQUIRES\fP ((\fBaccount_history_plugin\fP)(\fBchain_plugin\fP)(\fBhttp_plugin\fP)) \fBaccount_history_api_plugin\fP()"
.br
.ti -1c
.RI "virtual void \fBset_program_options\fP (options_description &, options_description &) override"
.br
.ti -1c
.RI "void \fBplugin_initialize\fP (const variables_map &)"
.br
.ti -1c
.RI "void \fBplugin_startup\fP ()"
.br
.ti -1c
.RI "void \fBplugin_shutdown\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
