.TH "aacio::chain::wasm_ops::branchtabletype" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aacio::chain::wasm_ops::branchtabletype
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBtarget_depth\fP"
.br
.ti -1c
.RI "uint64_t \fBtable_index\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
