.TH "accountapi" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
accountapi \- Define API for querying account data\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBAccount C API\fP"
.br
.RI "\fBC\fP API for querying account data\&. "
.ti -1c
.RI "\fBAccount C++ API\fP"
.br
.RI "C++ API for querying account data, e\&.g\&. account balance\&. "
.in -1c
.SH "Detailed Description"
.PP 
Define API for querying account data\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
