.TH "contracts/aaciolib/account.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/aaciolib/account.hpp \- Defines types and ABI for account API interactions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <aaciolib/account\&.h>\fP
.br
\fC#include <aaciolib/print\&.hpp>\fP
.br
\fC#include <aaciolib/asset\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBaacio::account::get\fP (account_balance &acnt)"
.br
.RI "Retrieve a populated balance structure\&. "
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "struct \fBaacio::account::PACKED\fP (account_balance)"
.br
.RI "The binary structure expected and populated by native balance function\&. "
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Defines types and ABI for account API interactions\&. 


.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
