.TH "plugins/account_history_plugin/include/aacio/account_history_plugin/account_history_plugin.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/account_history_plugin/include/aacio/account_history_plugin/account_history_plugin.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <appbase/application\&.hpp>\fP
.br
\fC#include <aacio/chain_plugin/chain_plugin\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaacio::account_history_apis::empty\fP"
.br
.ti -1c
.RI "class \fBaacio::account_history_apis::read_only\fP"
.br
.ti -1c
.RI "struct \fBaacio::account_history_apis::read_only::get_transaction_params\fP"
.br
.ti -1c
.RI "struct \fBaacio::account_history_apis::read_only::get_transaction_results\fP"
.br
.ti -1c
.RI "struct \fBaacio::account_history_apis::read_only::get_transactions_params\fP"
.br
.ti -1c
.RI "struct \fBaacio::account_history_apis::read_only::ordered_transaction_results\fP"
.br
.ti -1c
.RI "struct \fBaacio::account_history_apis::read_only::get_transactions_results\fP"
.br
.ti -1c
.RI "struct \fBaacio::account_history_apis::read_only::get_key_accounts_params\fP"
.br
.ti -1c
.RI "struct \fBaacio::account_history_apis::read_only::get_key_accounts_results\fP"
.br
.ti -1c
.RI "struct \fBaacio::account_history_apis::read_only::get_controlled_accounts_params\fP"
.br
.ti -1c
.RI "struct \fBaacio::account_history_apis::read_only::get_controlled_accounts_results\fP"
.br
.ti -1c
.RI "class \fBaacio::account_history_apis::read_write\fP"
.br
.ti -1c
.RI "class \fBaacio::account_history_plugin\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBfc\fP"
.br
.RI "aacio::chain "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef shared_ptr< class account_history_plugin_impl > \fBaacio::account_history_ptr\fP"
.br
.ti -1c
.RI "typedef shared_ptr< const class account_history_plugin_impl > \fBaacio::account_history_const_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
