.TH "plugins/account_history_api_plugin/include/aacio/account_history_api_plugin/account_history_api_plugin.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/account_history_api_plugin/include/aacio/account_history_api_plugin/account_history_api_plugin.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/account_history_plugin/account_history_plugin\&.hpp>\fP
.br
\fC#include <aacio/chain_plugin/chain_plugin\&.hpp>\fP
.br
\fC#include <aacio/http_plugin/http_plugin\&.hpp>\fP
.br
\fC#include <appbase/application\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::account_history_api_plugin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
