.TH "libraries/chain/include/aacio/chain/account_object.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/include/aacio/chain/account_object.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/types\&.hpp>\fP
.br
\fC#include <aacio/chain/authority\&.hpp>\fP
.br
\fC#include <aacio/chain/block_timestamp\&.hpp>\fP
.br
\fC#include <aacio/chain/contracts/types\&.hpp>\fP
.br
\fC#include 'multi_index_includes\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::chain::account_object\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBaacio::chain::account_id_type\fP = account_object::id_type"
.br
.ti -1c
.RI "using \fBaacio::chain::account_index\fP = chainbase::shared_multi_index_container< account_object, indexed_by< ordered_unique< tag< by_id >, member< account_object, account_object::id_type, &account_object::id > >, ordered_unique< tag< by_name >, member< account_object, account_name, &account_object::name > > > >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
