.TH "plugins/account_history_plugin/include/aacio/account_history_plugin/account_transaction_history_object.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/account_history_plugin/include/aacio/account_history_plugin/account_transaction_history_object.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <chainbase/chainbase\&.hpp>\fP
.br
\fC#include <aacio/chain/types\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstd::hash< aacio::chain::account_name >\fP"
.br
.ti -1c
.RI "class \fBaacio::account_transaction_history_object\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBaacio::account_transaction_history_multi_index\fP = chainbase::shared_multi_index_container< account_transaction_history_object, indexed_by< ordered_unique< tag< by_id >, BOOST_MULTI_INDEX_MEMBER(account_transaction_history_object, account_transaction_history_object::id_type, id)>, ordered_unique< tag< by_account_name >, composite_key< account_transaction_history_object, member< account_transaction_history_object, account_name, &account_transaction_history_object::name >, member< account_transaction_history_object, \fBtransaction_id_type\fP, &account_transaction_history_object::transaction_id > > > > >"
.br
.ti -1c
.RI "typedef \fBchainbase::generic_index\fP< account_transaction_history_multi_index > \fBaacio::account_transaction_history_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
