.TH "contracts/aaciolib/account.h" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/aaciolib/account.h
.SH SYNOPSIS
.br
.PP
\fC#include <aaciolib/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBaccount_balance_get\fP (void *balance, uint32_t len)"
.br
.RI "Retrieve the balance for the provided account\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
