.TH "actionapi" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
actionapi \- Define API for querying action properties\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBAction C API\fP"
.br
.RI "Define API for querying action properties\&. "
.ti -1c
.RI "\fBAction C++ API\fP"
.br
.RI "Type-safe C++ wrapers for Action \fBC\fP API\&. "
.in -1c
.SH "Detailed Description"
.PP 
Define API for querying action properties\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
