.TH "action_proof_data" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
action_proof_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "account_name \fBreceiver\fP"
.br
.ti -1c
.RI "scope_name \fBscope\fP"
.br
.ti -1c
.RI "action_name \fBname\fP"
.br
.ti -1c
.RI "\fBbytes\fP \fBdata\fP"
.br
.ti -1c
.RI "uint64_t \fBregion_id\fP"
.br
.ti -1c
.RI "uint64_t \fBcycle_index\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBdata_access_info\fP > \fBdata_access\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
