.TH "contracts/aaciolib/action.h" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/aaciolib/action.h
.SH SYNOPSIS
.br
.PP
\fC#include <aaciolib/system\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBread_action_data\fP (void *msg, uint32_t len)"
.br
.RI "Copy current action data to the specified location\&. "
.ti -1c
.RI "uint32_t \fBaction_data_size\fP ()"
.br
.RI "Get the length of current action's data field\&. "
.ti -1c
.RI "void \fBrequire_recipient\fP (account_name name)"
.br
.RI "Add the specified account to set of accounts to be notified\&. "
.ti -1c
.RI "void \fBrequire_auth\fP (account_name name)"
.br
.RI "Verify specified account exists in the set of provided auths\&. "
.ti -1c
.RI "bool \fBhas_auth\fP (account_name name)"
.br
.ti -1c
.RI "void \fBrequire_auth2\fP (account_name name, permission_name permission)"
.br
.RI "Verify specified account exists in the set of provided auths\&. "
.ti -1c
.RI "void \fBsend_inline\fP (char *serialized_action, size_t size)"
.br
.ti -1c
.RI "void \fBsend_context_free_inline\fP (char *serialized_action, size_t size)"
.br
.ti -1c
.RI "void \fBrequire_write_lock\fP (account_name name)"
.br
.RI "Verifies that \fBname\fP exists in the set of write locks held\&. "
.ti -1c
.RI "void \fBrequire_read_lock\fP (account_name name)"
.br
.RI "Verifies that \fBname\fP exists in the set of read locks held\&. "
.ti -1c
.RI "time \fBpublication_time\fP ()"
.br
.RI "Get the publication time\&. "
.ti -1c
.RI "account_name \fBcurrent_sender\fP ()"
.br
.RI "Get the sender of the action\&. "
.ti -1c
.RI "account_name \fBcurrent_receiver\fP ()"
.br
.RI "Get the current receiver of the action\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
