.TH "action_proof_info" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
action_proof_info \- transfer_test  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaction_trace\fP \fBtrace\fP"
.br
.ti -1c
.RI "size_t \fBaction_leaf\fP"
.br
.ti -1c
.RI "size_t \fBblock_leaf\fP"
.br
.ti -1c
.RI "uint32_t \fBcycle_index\fP"
.br
.ti -1c
.RI "uint32_t \fBregion_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
transfer_test 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
