.TH "action" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
action
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaction\fP (action_type t, connection_hdl h)"
.br
.ti -1c
.RI "\fBaction\fP (action_type t, connection_hdl h, \fBserver::message_ptr\fP m)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "action_type \fBtype\fP"
.br
.ti -1c
.RI "\fBwebsocketpp::connection_hdl\fP \fBhdl\fP"
.br
.ti -1c
.RI "\fBserver::message_ptr\fP \fBmsg\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
