.TH "AllCtors" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AllCtors
.SH SYNOPSIS
.br
.PP
.PP
Inherits DEFINE_BASEAllCtors\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBBase\fP = DEFINE_BASE(\fBAllCtors\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "DEFINE_EXPLICIT DEFINE_CONSTEXPR \fBAllCtors\fP (\fBAllCtors\fP const &) DEFINE_CTOR"
.br
.ti -1c
.RI "DEFINE_EXPLICIT DEFINE_CONSTEXPR \fBAllCtors\fP (\fBAllCtors\fP &&) DEFINE_CTOR"
.br
.ti -1c
.RI "DEFINE_ASSIGN_CONSTEXPR \fBAllCtors\fP & \fBoperator=\fP (\fBAllCtors\fP const &) DEFINE_ASSIGN"
.br
.ti -1c
.RI "DEFINE_ASSIGN_CONSTEXPR \fBAllCtors\fP & \fBoperator=\fP (\fBAllCtors\fP &&) DEFINE_ASSIGN"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
