.TH "alloc_last" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alloc_last
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBA1\fP< int > \fBallocator_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBalloc_last\fP (int d)"
.br
.ti -1c
.RI "\fBalloc_last\fP (const \fBA1\fP< int > &a)"
.br
.ti -1c
.RI "\fBalloc_last\fP (int d, const \fBA1\fP< int > &a)"
.br
.ti -1c
.RI "\fBalloc_last\fP (const \fBalloc_last\fP &d, const \fBA1\fP< int > &a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdata_\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBallocator_constructed\fP = false"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBalloc_last\fP &x, const \fBalloc_last\fP &y)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBalloc_last\fP &x, const \fBalloc_last\fP &y)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
