.TH "AllocController" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AllocController
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcountAlloc\fP (void *p, size_t s, size_t a)"
.br
.ti -1c
.RI "void \fBcountDealloc\fP (void *p, size_t s, size_t a)"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args, class Alloc , class Tp > void \fBcountConstruct\fP (Alloc const &, Tp *p)"
.br
.ti -1c
.RI "template<class Alloc , class Tp > void \fBcountDestroy\fP (Alloc const &, Tp *p)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBresetConstructDestroy\fP ()"
.br
.ti -1c
.RI "bool \fBcheckAlloc\fP (void *p, size_t s, size_t a) const"
.br
.ti -1c
.RI "bool \fBcheckAlloc\fP (void *p, size_t s) const"
.br
.ti -1c
.RI "bool \fBcheckAllocAtLeast\fP (void *p, size_t s, size_t a) const"
.br
.ti -1c
.RI "bool \fBcheckAllocAtLeast\fP (void *p, size_t s) const"
.br
.ti -1c
.RI "bool \fBcheckDealloc\fP (void *p, size_t s, size_t a) const"
.br
.ti -1c
.RI "bool \fBcheckDealloc\fP (void *p, size_t s) const"
.br
.ti -1c
.RI "bool \fBcheckDeallocMatchesAlloc\fP () const"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args, class Alloc , class Tp > bool \fBcheckConstruct\fP (Alloc const &, Tp *p) const"
.br
.ti -1c
.RI "template<class Alloc , class Tp > bool \fBcheckDestroy\fP (Alloc const &, Tp *p) const"
.br
.ti -1c
.RI "bool \fBcheckDestroyMatchesConstruct\fP () const"
.br
.ti -1c
.RI "void \fBcountIsEqual\fP ()"
.br
.ti -1c
.RI "bool \fBcheckIsEqualCalledEq\fP (int n) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcopy_constructed\fP = 0"
.br
.ti -1c
.RI "int \fBmove_constructed\fP = 0"
.br
.ti -1c
.RI "int \fBalive\fP = 0"
.br
.ti -1c
.RI "int \fBalloc_count\fP = 0"
.br
.ti -1c
.RI "int \fBdealloc_count\fP = 0"
.br
.ti -1c
.RI "int \fBis_equal_count\fP = 0"
.br
.ti -1c
.RI "std::size_t \fBalive_size\fP"
.br
.ti -1c
.RI "std::size_t \fBallocated_size\fP"
.br
.ti -1c
.RI "std::size_t \fBdeallocated_size\fP"
.br
.ti -1c
.RI "std::size_t \fBlast_size\fP = 0"
.br
.ti -1c
.RI "std::size_t \fBlast_align\fP = 0"
.br
.ti -1c
.RI "void * \fBlast_pointer\fP = 0"
.br
.ti -1c
.RI "std::size_t \fBlast_alloc_size\fP = 0"
.br
.ti -1c
.RI "std::size_t \fBlast_alloc_align\fP = 0"
.br
.ti -1c
.RI "void * \fBlast_alloc_pointer\fP = nullptr"
.br
.ti -1c
.RI "std::size_t \fBlast_dealloc_size\fP = 0"
.br
.ti -1c
.RI "std::size_t \fBlast_dealloc_align\fP = 0"
.br
.ti -1c
.RI "void * \fBlast_dealloc_pointer\fP = nullptr"
.br
.ti -1c
.RI "bool \fBthrow_on_alloc\fP = false"
.br
.ti -1c
.RI "int \fBconstruct_called\fP = 0"
.br
.ti -1c
.RI "void * \fBlast_construct_pointer\fP = nullptr"
.br
.ti -1c
.RI "\fBTypeID\fP const  * \fBlast_construct_alloc\fP = nullptr"
.br
.ti -1c
.RI "\fBTypeID\fP const  * \fBlast_construct_type\fP = nullptr"
.br
.ti -1c
.RI "\fBTypeID\fP const  * \fBlast_construct_args\fP = nullptr"
.br
.ti -1c
.RI "int \fBdestroy_called\fP = 0"
.br
.ti -1c
.RI "void * \fBlast_destroy_pointer\fP = nullptr"
.br
.ti -1c
.RI "\fBTypeID\fP const  * \fBlast_destroy_alloc\fP = nullptr"
.br
.ti -1c
.RI "\fBTypeID\fP const  * \fBlast_destroy_type\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
