.TH "Ambiguous" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ambiguous
.SH SYNOPSIS
.br
.PP
.PP
Inherits true_type, and true_type\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoperator float\fP ()"
.br
.ti -1c
.RI "\fBoperator double\fP ()"
.br
.ti -1c
.RI "\fBoperator float\fP ()"
.br
.ti -1c
.RI "\fBoperator double\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
