.TH "appbase::application_impl" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
appbase::application_impl
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const variables_map * \fB_options\fP = nullptr"
.br
.ti -1c
.RI "options_description \fB_app_options\fP"
.br
.ti -1c
.RI "options_description \fB_cfg_options\fP"
.br
.ti -1c
.RI "bfs::path \fB_data_dir\fP {'data\-dir'}"
.br
.ti -1c
.RI "bfs::path \fB_config_dir\fP {'config\-dir'}"
.br
.ti -1c
.RI "bfs::path \fB_logging_conf\fP {'logging\&.json'}"
.br
.ti -1c
.RI "uint64_t \fB_version\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
