.TH "AppendOperatorTestcase" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppendOperatorTestcase
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMultiStringType\fP \fBlhs\fP"
.br
.ti -1c
.RI "\fBMultiStringType\fP \fBrhs\fP"
.br
.ti -1c
.RI "\fBMultiStringType\fP \fBexpect\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
