.TH "libraries/chain/include/aacio/chain/apply_context.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/include/aacio/chain/apply_context.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/block_trace\&.hpp>\fP
.br
\fC#include <aacio/chain/transaction\&.hpp>\fP
.br
\fC#include <aacio/chain/transaction_metadata\&.hpp>\fP
.br
\fC#include <aacio/chain/contracts/contract_table_objects\&.hpp>\fP
.br
\fC#include <fc/utility\&.hpp>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <set>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::chain::apply_context\fP"
.br
.ti -1c
.RI "class \fBaacio::chain::apply_context::generic_index< ObjectType, SecondaryKeyProxy, SecondaryKeyProxyConst >\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::apply_context::apply_results\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBaacio::chain::apply_handler\fP = std::function< void(apply_context &)>"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
