.TH "Archive::Child" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Archive::Child
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChild\fP (const \fBArchive\fP *parent, const uint8_t *data, bool *\fBerror\fP)"
.br
.ti -1c
.RI "uint32_t \fBgetSize\fP () const"
.br
.ti -1c
.RI "\fBSubBuffer\fP \fBgetBuffer\fP () const"
.br
.ti -1c
.RI "std::string \fBgetRawName\fP () const"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBChild\fP &\fBother\fP) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBArchive\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
