.TH "Archive::child_iterator" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Archive::child_iterator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBchild_iterator\fP (bool \fBerror\fP)"
.br
.ti -1c
.RI "\fBchild_iterator\fP (const \fBChild\fP &c)"
.br
.ti -1c
.RI "const \fBChild\fP * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "const \fBChild\fP & \fBoperator*\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBchild_iterator\fP &\fBother\fP) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBchild_iterator\fP &\fBother\fP) const"
.br
.ti -1c
.RI "\fBchild_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "bool \fBhasError\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBArchive\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
