.TH "Archive" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Archive
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChild\fP"
.br
.ti -1c
.RI "class \fBchild_iterator\fP"
.br
.ti -1c
.RI "struct \fBSubBuffer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArchive\fP (\fBBuffer\fP &buffer, bool &\fBerror\fP)"
.br
.ti -1c
.RI "\fBchild_iterator\fP \fBchild_begin\fP (bool SkipInternal=true) const"
.br
.ti -1c
.RI "\fBchild_iterator\fP \fBchild_end\fP () const"
.br
.ti -1c
.RI "void \fBdump\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
