.TH "ArenaVector< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArenaVector< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBArenaVectorBase< ArenaVector< T >, T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArenaVector\fP (\fBMixedArena\fP &allocator)"
.br
.ti -1c
.RI "\fBArenaVector\fP (\fBArenaVector\fP< \fBT\fP > &&\fBother\fP)"
.br
.ti -1c
.RI "void \fBallocate\fP (size_t size)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
