.TH "ArenaVectorBase< SubType, T >::Iterator" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArenaVectorBase< SubType, T >::Iterator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP (const SubType *parent, size_t index)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBIterator\fP &\fBother\fP) const"
.br
.ti -1c
.RI "void \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBT\fP & \fBoperator*\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const SubType * \fBparent\fP"
.br
.ti -1c
.RI "size_t \fBindex\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
