.TH "AsmData" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AsmData
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLocal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBstd::unordered_map\fP< \fBcashew::IString\fP, \fBLocal\fP > \fBLocals\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "AsmType \fBgetType\fP (const \fBcashew::IString\fP &name)"
.br
.ti -1c
.RI "void \fBsetType\fP (const \fBcashew::IString\fP &name, AsmType type)"
.br
.ti -1c
.RI "bool \fBisLocal\fP (const \fBcashew::IString\fP &name)"
.br
.ti -1c
.RI "bool \fBisParam\fP (const \fBcashew::IString\fP &name)"
.br
.ti -1c
.RI "bool \fBisVar\fP (const \fBcashew::IString\fP &name)"
.br
.ti -1c
.RI "\fBAsmData\fP (\fBcashew::Ref\fP f)"
.br
.ti -1c
.RI "void \fBdenormalize\fP ()"
.br
.ti -1c
.RI "void \fBaddParam\fP (\fBcashew::IString\fP name, AsmType type)"
.br
.ti -1c
.RI "void \fBaddVar\fP (\fBcashew::IString\fP name, AsmType type)"
.br
.ti -1c
.RI "void \fBdeleteVar\fP (\fBcashew::IString\fP name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLocals\fP \fBlocals\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBcashew::IString\fP > \fBparams\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBcashew::IString\fP > \fBvars\fP"
.br
.ti -1c
.RI "AsmType \fBret\fP"
.br
.ti -1c
.RI "\fBcashew::Ref\fP \fBfunc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
