.TH "contracts/asserter/asserter.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/asserter/asserter.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aaciolib/aacio\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBasserter::PACKED\fP (\fBassertdef\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
