.TH "libraries/chain/include/aacio/chain/asset.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/include/aacio/chain/asset.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <fc/exception/exception\&.hpp>\fP
.br
\fC#include <aacio/chain/types\&.hpp>\fP
.br
\fC#include <aacio/chain/symbol\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAAC_SYMBOL_VALUE\fP   (int64_t(4) | (uint64_t('\fBA\fP') << 8) | (uint64_t('\fBA\fP') << 16) | (uint64_t('\fBC\fP') << 24))"
.br
.RI "aac with 8 digits of precision "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
