.TH "libraries/chain/include/aacio/chain/authority.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/include/aacio/chain/authority.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <chainbase/chainbase\&.hpp>\fP
.br
\fC#include <aacio/chain/transaction\&.hpp>\fP
.br
\fC#include <aacio/chain/config\&.hpp>\fP
.br
\fC#include <type_traits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaacio::chain::permission_level_weight\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::key_weight\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::config::billable_size< permission_level_weight >\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::config::billable_size< key_weight >\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::authority\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::shared_authority\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBaacio::chain::operator<\fP (const permission_level &a, const permission_level &b)"
.br
.ti -1c
.RI "template<typename Authority > bool \fBaacio::chain::validate\fP (const Authority &auth)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "template<typename Authority > bool aacio::chain::validate (const Authority & auth)\fC [inline]\fP"
Makes sure all keys are unique and sorted and all account permissions are unique and sorted and that authority can be satisfied 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
