.TH "B< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
B< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits nested_exception, and nested_exception\&.
.PP
Inherited by \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBA< T >\fP, \fBB1< T >\fP, \fBB2\fP, \fBD< T >\fP, \fBD< T >\fP, \fBD< T >\fP, \fBD< T >\fP, \fBD< T >\fP, \fBD< T >\fP, \fBD< T >\fP, \fBD< T >\fP, and \fBD< T >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrebind\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBA1\fP< \fBB\fP > \fBallocator_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef int \fBallocator_type\fP"
.br
.ti -1c
.RI "typedef short \fBelement_type\fP"
.br
.ti -1c
.RI "typedef char \fBelement_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBB\fP * \fBoperator &\fP () const"
.br
.ti -1c
.RI "\fBB\fP (int id)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &a)"
.br
.ti -1c
.RI "bool \fBawait_ready\fP ()"
.br
.ti -1c
.RI "\fBB\fP \fBawait_resume\fP ()"
.br
.ti -1c
.RI "template<typename F > void \fBawait_suspend\fP (\fBF\fP)"
.br
.ti -1c
.RI "\fBB\fP (int d=1)"
.br
.ti -1c
.RI "int \fBget\fP () const"
.br
.ti -1c
.RI "const \fBB\fP * \fBoperator &\fP () const"
.br
.ti -1c
.RI "\fBB\fP * \fBoperator &\fP ()"
.br
.ti -1c
.RI "\fBB\fP (int data)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &b)"
.br
.ti -1c
.RI "\fBB\fP (int data)"
.br
.ti -1c
.RI "\fBB\fP (std::allocator_arg_t, const \fBallocator_type\fP &a, int i)"
.br
.ti -1c
.RI "\fBvalue_type\fP * \fBallocate\fP (std::size_t n)"
.br
.ti -1c
.RI "\fBvalue_type\fP * \fBallocate\fP (std::size_t n, const void *p)"
.br
.ti -1c
.RI "template<class U > void \fBdestroy\fP (\fBU\fP *p)"
.br
.ti -1c
.RI "size_t \fBmax_size\fP () const"
.br
.ti -1c
.RI "\fBB\fP (int i=0)"
.br
.ti -1c
.RI "\fBB\fP \fBselect_on_container_copy_construction\fP () const"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &b)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &b)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &b)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &b)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBA\fP)"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBA\fP)"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBA\fP)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.ti -1c
.RI "\fBB\fP (int i=0)"
.br
.ti -1c
.RI "\fBB\fP (int i=0)"
.br
.ti -1c
.RI "\fBB\fP (int i=0)"
.br
.ti -1c
.RI "\fBB\fP (int i)"
.br
.ti -1c
.RI "\fBB\fP (int i)"
.br
.ti -1c
.RI "\fBB\fP (int i)"
.br
.ti -1c
.RI "\fBB\fP (int i)"
.br
.ti -1c
.RI "\fBB\fP (int i)"
.br
.ti -1c
.RI "\fBB\fP (double d, unsigned u1, unsigned u2)"
.br
.ti -1c
.RI "double \fBget_d\fP () const"
.br
.ti -1c
.RI "unsigned \fBget_u1\fP () const"
.br
.ti -1c
.RI "unsigned \fBget_u2\fP () const"
.br
.ti -1c
.RI "\fBB\fP (const \fBB\fP &)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::max_align_t \fBmember\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBi_\fP"
.br
.ti -1c
.RI "int \fBid_\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBcount\fP = 0"
.br
.ti -1c
.RI "static bool \fBconstructed\fP = false"
.br
.ti -1c
.RI "static int \fBcount_\fP = 0"
.br
.ti -1c
.RI "static int \fBpopulation_\fP = 0"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBB\fP &x, const \fBB\fP &y)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBB\fP &x, const \fBB\fP &y)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
