.TH "B1< T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
B1< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBB< T >\fP\&.
.PP
Inherited by \fBD< T >\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
