.TH "BadComparator< ValueType >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BadComparator< ValueType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCompareBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (ValueType const &, ValueType const &) const"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
