.TH "contracts/bancor/bancor.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/bancor/bancor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <bancor/bancor\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbancor::apply\fP (uint64_t r, uint64_t c, uint64_t a)"
.br
.RI "The apply method implements the dispatch of events to this contract\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
