.TH "bancor::converter_contract< ConverterCurrency, FirstCurrency, SecondCurrency >::connector< CurrencyType, Weight, Base >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bancor::converter_contract< ConverterCurrency, FirstCurrency, SecondCurrency >::connector< CurrencyType, Weight, Base >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef CurrencyType \fBcurrency_type\fP"
.br
.ti -1c
.RI "typedef converter_currency::token_type \fBconverter_token_type\fP"
.br
.ti -1c
.RI "typedef currency_type::token_type \fBin_token_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "converter_token_type \fBconvert_to_converter\fP (in_token_type in, \fBconverter_state\fP &state)"
.br
.ti -1c
.RI "in_token_type \fBconvert_from_converter\fP (converter_token_type converter_in, \fBconverter_state\fP &state)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename ConverterCurrency , typename FirstCurrency , typename SecondCurrency > template<typename CurrencyType , uint32_t Weight = 500000, uint32_t Base = 1000000> converter_token_type \fBbancor::converter_contract\fP< ConverterCurrency, FirstCurrency, SecondCurrency >::\fBconnector\fP< CurrencyType, Weight, \fBBase\fP >::convert_to_converter (in_token_type in, \fBconverter_state\fP & state)\fC [inline]\fP"
balance already changed when transfer executed, get pre-transfer balance 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
