.TH "contracts/bancor/bancor.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/bancor/bancor.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aaciolib/aac\&.hpp>\fP
.br
\fC#include <aaciolib/token\&.hpp>\fP
.br
\fC#include <aaciolib/reflect\&.hpp>\fP
.br
\fC#include <aaciolib/generic_currency\&.hpp>\fP
.br
\fC#include <bancor/converter\&.hpp>\fP
.br
\fC#include <currency/currency\&.hpp>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBaacio::generic_currency\fP< \fBaacio::token\fP< \fBN\fP(\fBother\fP), \fBS\fP(4, OTHER)> > \fBbancor::other_currency\fP"
.br
.ti -1c
.RI "typedef \fBaacio::generic_currency\fP< \fBaacio::token\fP< \fBN\fP(bancor), \fBS\fP(4, RELAY)> > \fBbancor::relay_currency\fP"
.br
.ti -1c
.RI "typedef \fBaacio::generic_currency\fP< \fBaacio::token\fP< \fBN\fP(currency), \fBS\fP(4, CUR)> > \fBbancor::cur_currency\fP"
.br
.ti -1c
.RI "typedef converter< relay_currency, other_currency, cur_currency > \fBbancor::example_converter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
