.TH "Base" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Base
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcheck_is_representable< FileTimeT, TimeT, TimeSpec, Base, TK_FloatingPoint >\fP, \fBcheck_is_representable< FileTimeT, TimeT, TimeSpecT, Base, TK_32Bit >\fP, \fBcheck_is_representable< FileTimeT, TimeT, TimeSpecT, Base, TK_64Bit >\fP, \fBDerived< T >\fP, \fBDerived< T >\fP, \fBDerived< T >\fP, \fBDerived< T >\fP, \fBDerived< T >\fP, \fBDerived< T >\fP, \fBDerived< T >\fP, and \fBDerivedFromType< Base >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
