.TH "base_properties" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
base_properties
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdefault_properties\fP, and \fBsmall_block_properties\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBglobal_property_object\fP \fBproperties\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
