.TH "BCinfo" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BCinfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdp0\fP"
.br
.ti -1c
.RI "int \fBdp1\fP"
.br
.ti -1c
.RI "int \fBdplen\fP"
.br
.ti -1c
.RI "int \fBdsign\fP"
.br
.ti -1c
.RI "int \fBe0\fP"
.br
.ti -1c
.RI "int \fBinexact\fP"
.br
.ti -1c
.RI "int \fBnd\fP"
.br
.ti -1c
.RI "int \fBnd0\fP"
.br
.ti -1c
.RI "int \fBrounding\fP"
.br
.ti -1c
.RI "int \fBscale\fP"
.br
.ti -1c
.RI "int \fBuflchk\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
