.TH "bf" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bf
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBi1\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBi2\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBi3\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBi4\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBi5\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBi6\fP: 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
