.TH "BF_ctx" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BF_ctx
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   BF_key \fBP\fP"
.br
.ti -1c
.RI "   BF_word \fBS\fP [4][0x100]"
.br
.ti -1c
.RI "} \fBs\fP"
.br
.ti -1c
.RI "BF_word \fBPS\fP [BF_N+2+4 *0x100]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
