.TH "Bigint" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bigint
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBBigint\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBk\fP"
.br
.ti -1c
.RI "int \fBmaxwds\fP"
.br
.ti -1c
.RI "int \fBsign\fP"
.br
.ti -1c
.RI "int \fBwds\fP"
.br
.ti -1c
.RI "ULong \fBx\fP [1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
