.TH "bignum_error" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bignum_error
.SH SYNOPSIS
.br
.PP
.PP
Inherits runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbignum_error\fP (const std::string &str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Errors thrown by the bignum class 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
