.TH "Binary< inType >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Binary< inType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinary\fP (\fBNode\fP *inFirstChild, \fBNode\fP *inSecondChild)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNode\fP * \fBfirstChild\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBsecondChild\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
