.TH "binding" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binding
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBbinding\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBdirlen\fP"
.br
.ti -1c
.RI "volatile int \fBactive\fP"
.br
.ti -1c
.RI "char * \fBdomainname\fP"
.br
.ti -1c
.RI "char * \fBdirname\fP"
.br
.ti -1c
.RI "char \fBbuf\fP []"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
