.TH "libraries/chain/include/aacio/chain/block_summary_object.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/include/aacio/chain/block_summary_object.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/types\&.hpp>\fP
.br
\fC#include 'multi_index_includes\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::chain::block_summary_object\fP"
.br
.RI "tracks minimal information about past blocks to implement TaPOS
.PP
When attempting to calculate the validity of a transaction we need to lookup a past block and check its block hash and the time it occurred so we can calculate whether the current transaction is valid and at what time it should expire\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBaacio::chain::block_summary_multi_index\fP = chainbase::shared_multi_index_container< block_summary_object, indexed_by< ordered_unique< tag< by_id >, BOOST_MULTI_INDEX_MEMBER(block_summary_object, block_summary_object::id_type, id)> > >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
