.TH "libraries/chain/include/aacio/chain/block.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/include/aacio/chain/block.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/block_timestamp\&.hpp>\fP
.br
\fC#include <aacio/chain/transaction\&.hpp>\fP
.br
\fC#include <aacio/chain/producer_schedule\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaacio::chain::block_header\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::signed_block_header\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::shard_lock\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::shard_summary\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::region_summary\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::signed_block_summary\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::signed_block\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef vector< shard_summary > \fBaacio::chain::cycle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
