.TH "tests/tests/block_schedule_tests.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/tests/block_schedule_tests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <boost/test/unit_test\&.hpp>\fP
.br
\fC#include <AcuteAngleChain/chain/block_schedule\&.hpp>\fP
.br
\fC#include '\&.\&./common/expect\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBshuffled_functor< NEXT >\fP"
.br
.ti -1c
.RI "struct \fBlossy_functor< NUM, DEN, NEXT >\fP"
.br
.ti -1c
.RI "class \fBcommon_fixture\fP"
.br
.ti -1c
.RI "struct \fBcommon_fixture::test_transaction\fP"
.br
.ti -1c
.RI "class \fBcompose_fixture< PROPERTIES_POLICY >\fP"
.br
.ti -1c
.RI "struct \fBbase_properties\fP"
.br
.ti -1c
.RI "struct \fBdefault_properties\fP"
.br
.ti -1c
.RI "struct \fBsmall_block_properties\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBcompose_fixture\fP< \fBdefault_properties\fP > \fBdefault_fixture\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (no_conflicts, \fBdefault_fixture\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (some_conflicts, \fBdefault_fixture\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (basic_cycle, \fBdefault_fixture\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (small_block, \fBcompose_fixture\fP< \fBsmall_block_properties\fP >)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (no_conflicts_shuffled, \fBdefault_fixture\fP)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (some_conflicts_shuffled, \fBdefault_fixture\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
