.TH "book" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
book
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBchainbase::object< 0, book >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Constructor , typename Allocator > \fBbook\fP (Constructor &&c, Allocator &&a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBid_type\fP \fBid\fP"
.br
.ti -1c
.RI "int \fBa\fP = 0"
.br
.ti -1c
.RI "int \fBb\fP = 1"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
