.TH "boost::fibers::asio::round_robin" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::fibers::asio::round_robin
.SH SYNOPSIS
.br
.PP
.PP
Inherits algorithm\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBservice\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBround_robin\fP (boost::asio::io_service &io_svc)"
.br
.ti -1c
.RI "void \fBawakened\fP (context *ctx) noexcept"
.br
.ti -1c
.RI "context * \fBpick_next\fP () noexcept"
.br
.ti -1c
.RI "bool \fBhas_ready_fibers\fP () const noexcept"
.br
.ti -1c
.RI "void \fBsuspend_until\fP (std::chrono::steady_clock::time_point const &abs_time) noexcept"
.br
.ti -1c
.RI "void \fBnotify\fP () noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
