.TH "boost::pfr::detail::offset_based_getter< U, S >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::pfr::detail::offset_based_getter< U, S >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<std::size_t idx> \fBindex_t\fP< idx > & \fBget\fP (\fBU\fP &u, size_t_< idx >) const noexcept"
.br
.ti -1c
.RI "template<std::size_t idx> \fBindex_t\fP< idx > const  & \fBget\fP (\fBU\fP const &u, size_t_< idx >) const noexcept"
.br
.ti -1c
.RI "template<std::size_t idx> \fBindex_t\fP< idx > volatile & \fBget\fP (\fBU\fP volatile &u, size_t_< idx >) const noexcept"
.br
.ti -1c
.RI "template<std::size_t idx> \fBindex_t\fP< idx > const volatile & \fBget\fP (\fBU\fP const volatile &u, size_t_< idx >) const noexcept"
.br
.ti -1c
.RI "template<std::size_t idx> \fBindex_t\fP< idx > && \fBget\fP (\fBrvalue_t\fP< \fBU\fP > u, size_t_< idx >) const =delete"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
