.TH "boost::fibers::asio::detail::yield_handler_base" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::fibers::asio::detail::yield_handler_base
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBboost::fibers::asio::detail::yield_handler< T >\fP, and \fBboost::fibers::asio::detail::yield_handler< void >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fByield_handler_base\fP (\fByield_t\fP const &y)"
.br
.ti -1c
.RI "void \fBoperator()\fP (boost::system::error_code const &ec)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::fibers::context * \fBctx_\fP"
.br
.ti -1c
.RI "\fByield_t\fP \fByt_\fP"
.br
.ti -1c
.RI "\fByield_completion\fP * \fBycomp_\fP { nullptr }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
