.TH "boost::pfr::detail::is_aggregate_initializable_n< T, N >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::pfr::detail::is_aggregate_initializable_n< T, N >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<std::size_t \&.\&.\&. I> static constexpr bool \fBis_not_constructible_n\fP (std::index_sequence< I\&.\&.\&. >) noexcept"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr bool \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<class T , std::size_t N> constexpr bool \fBboost::pfr::detail::is_aggregate_initializable_n\fP< \fBT\fP, \fBN\fP >::value\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
           std::is_empty<T>::value
        || std::is_fundamental<T>::value
        || is_not_constructible_n(std::make_index_sequence<N>{})
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
