.TH "boost::fibers::asio::detail::yield_handler< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::fibers::asio::detail::yield_handler< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBboost::fibers::asio::detail::yield_handler_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fByield_handler\fP (\fByield_t\fP const &y)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBT\fP t)"
.br
.ti -1c
.RI "void \fBoperator()\fP (boost::system::error_code const &ec, \fBT\fP t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP * \fBvalue_\fP { nullptr }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
