.TH "boost::pfr::detail::is_single_field_and_aggregate_initializable< 1, T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::pfr::detail::is_single_field_and_aggregate_initializable< 1, T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, !std::is_constructible< T, ubiq_constructor_except< T > >::value >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
