.TH "boost::pfr::not_equal< T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::pfr::not_equal< T > \- std::not_equal like comparator  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functors\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBT\fP &x, const \fBT\fP &y) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T = void>
.br
struct boost::pfr::not_equal< T >"
std::not_equal like comparator 
.SH "Member Function Documentation"
.PP 
.SS "template<class T  = void> bool \fBboost::pfr::not_equal\fP< \fBT\fP >::operator() (const \fBT\fP & x, const \fBT\fP & y) const\fC [inline]\fP"

.PP
\fBReturns:\fP
.RS 4
\fBtrue\fP if at least one field \fBx\fP not equals the field with same index of \fBy\fP\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
