.TH "boost::pfr::flat_greater< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::pfr::flat_greater< T > \- std::greater like flattening comparator  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functors\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBT\fP &x, const \fBT\fP &y) const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T = void>
.br
struct boost::pfr::flat_greater< T >"
std::greater like flattening comparator 
.SH "Member Function Documentation"
.PP 
.SS "template<class T  = void> bool \fBboost::pfr::flat_greater\fP< \fBT\fP >::operator() (const \fBT\fP & x, const \fBT\fP & y) const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
\fBReturns:\fP
.RS 4
\fBtrue\fP if field of \fBx\fP greater than the field with same index of \fBy\fP and all previous fields of \fBx\fP equal to the same fields of \fBy\fP\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
