.TH "boost::pfr::detail::size_array< N >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::pfr::detail::size_array< N >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::size_t \fBtype\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr std::size_t \fBcount_nonzeros\fP () const noexcept"
.br
.ti -1c
.RI "constexpr std::size_t \fBcount_from_opening_till_matching_parenthis_seq\fP (std::size_t from, std::size_t opening_parenthis, std::size_t closing_parenthis) const noexcept"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static constexpr std::size_t \fBsize\fP () noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::size_t \fBdata\fP [\fBN\fP]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
