.TH "boost::pfr::detail::is_single_field_and_aggregate_initializable< N, T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::pfr::detail::is_single_field_and_aggregate_initializable< N, T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits false_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
