.TH "bootseq_tester" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bootseq_tester
.SH SYNOPSIS
.br
.PP
.PP
Inherits TESTER\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "action_result \fBpush_action\fP (const account_name &\fBaccount\fP, const account_name &signer, const action_name &\fBname\fP, const \fBvariant_object\fP &data, bool auth=true)"
.br
.ti -1c
.RI "void \fBcreate_currency\fP (\fBname\fP \fBcontract\fP, \fBname\fP manager, \fBasset\fP maxsupply)"
.br
.ti -1c
.RI "void \fBissue\fP (\fBname\fP \fBcontract\fP, \fBname\fP manager, \fBname\fP to, \fBasset\fP amount)"
.br
.ti -1c
.RI "action_result \fBstake\fP (const account_name &from, const account_name &to, const string &net, const string &cpu, const string &storage)"
.br
.ti -1c
.RI "action_result \fBstake\fP (const account_name &acnt, const string &net, const string &cpu, const string &storage)"
.br
.ti -1c
.RI "\fBasset\fP \fBget_balance\fP (const account_name &act)"
.br
.ti -1c
.RI "action_result \fBregproducer\fP (const account_name &acnt, int params_fixture=1)"
.br
.ti -1c
.RI "void \fBset_code_abi\fP (const account_name &\fBaccount\fP, const char *wast, const char *abi)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBfc::variant_object\fP \fBproducer_parameters_example\fP (int n)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBabi_serializer\fP \fBabi_ser\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
