.TH "BufferProvider< Size >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BufferProvider< Size >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void * \fBallocate\fP (size_t s, size_t a)"
.br
.ti -1c
.RI "void \fBdeallocate\fP (void *, size_t, size_t)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBbuffer\fP [Size]"
.br
.ti -1c
.RI "void * \fBnext\fP = &buffer"
.br
.ti -1c
.RI "size_t \fBspace\fP = Size"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
