.TH "C< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtest_compare< C >\fP\fC [private]\fP, and \fBtest_hash< C >\fP\fC [private]\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBconst_pointer\fP"
.br
.ti -1c
.RI "struct \fBconst_void_pointer\fP"
.br
.ti -1c
.RI "struct \fBpointer\fP"
.br
.ti -1c
.RI "struct \fBvoid_pointer\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef int \fBargument_type\fP"
.br
.ti -1c
.RI "typedef int \fBresult_type\fP"
.br
.ti -1c
.RI "typedef int \fBargument_type\fP"
.br
.ti -1c
.RI "typedef int \fBresult_type\fP"
.br
.ti -1c
.RI "typedef int \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef int & \fBreference\fP"
.br
.ti -1c
.RI "typedef const int & \fBconst_reference\fP"
.br
.ti -1c
.RI "typedef int \fBsize_type\fP"
.br
.ti -1c
.RI "typedef int \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef int & \fBreference\fP"
.br
.ti -1c
.RI "typedef const int & \fBconst_reference\fP"
.br
.ti -1c
.RI "typedef int \fBsize_type\fP"
.br
.ti -1c
.RI "typedef int \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef int & \fBreference\fP"
.br
.ti -1c
.RI "typedef const int & \fBconst_reference\fP"
.br
.ti -1c
.RI "typedef int \fBsize_type\fP"
.br
.ti -1c
.RI "typedef std::scoped_allocator_adaptor< \fBA2\fP< \fBC\fP > > \fBallocator_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBCPtr\fP< \fBT\fP > \fBpointer\fP"
.br
.ti -1c
.RI "typedef \fBCPtr\fP< const \fBT\fP > \fBconst_pointer\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBCPtr\fP< const void > \fBconst_void_pointer\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBCPtr\fP< void > \fBvoid_pointer\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class U > \fBD\fP \fBoperator,\fP (\fBU\fP &&)"
.br
.ti -1c
.RI "TEST_CONSTEXPR int \fBget\fP () const"
.br
.ti -1c
.RI "\fBC\fP * \fBoperator &\fP () const"
.br
.ti -1c
.RI "\fBC\fP (std::allocator_arg_t, const allocator_type &a, int i)"
.br
.ti -1c
.RI "\fBC\fP (const \fBC\fP &)"
.br
.ti -1c
.RI "\fBC\fP (const \fBC\fP &)"
.br
.ti -1c
.RI "\fBC\fP (const \fBC\fP &)"
.br
.ti -1c
.RI "\fBC\fP (const \fBC\fP &)"
.br
.ti -1c
.RI "\fBC\fP (const \fBC\fP &)"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBC\fP &)"
.br
.ti -1c
.RI "\fBC\fP (\fBC\fP &)"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBC\fP &)"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBC\fP &)"
.br
.ti -1c
.RI "\fBC\fP (\fBC\fP &)"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBC\fP &)"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBC\fP &)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnot_empty_\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBconstructed\fP = false"
.br
.ti -1c
.RI "static int \fBallocator_type\fP"
.br
.ti -1c
.RI "static int \fBcount\fP = 0"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "TEST_CONSTEXPR bool \fBoperator==\fP (const \fBC\fP &x, const \fBC\fP &y)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
