.TH "cashew::OperatorClass" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cashew::OperatorClass
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBBinary\fP = 0, \fBPrefix\fP = 1, \fBPostfix\fP = 2, \fBTertiary\fP = 3 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOperatorClass\fP (const char *o, bool r, \fBType\fP t)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBgetPrecedence\fP (\fBType\fP type, \fBIString\fP op)"
.br
.ti -1c
.RI "static bool \fBgetRtl\fP (int prec)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIStringSet\fP \fBops\fP"
.br
.ti -1c
.RI "bool \fBrtl\fP"
.br
.ti -1c
.RI "\fBType\fP \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
