.TH "cashew::Ref" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cashew::Ref
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRef\fP (\fBValue\fP *v=nullptr)"
.br
.ti -1c
.RI "\fBValue\fP * \fBget\fP ()"
.br
.ti -1c
.RI "\fBValue\fP & \fBoperator*\fP ()"
.br
.ti -1c
.RI "\fBValue\fP * \fBoperator\->\fP ()"
.br
.ti -1c
.RI "\fBRef\fP & \fBoperator[]\fP (unsigned x)"
.br
.ti -1c
.RI "\fBRef\fP & \fBoperator[]\fP (\fBIString\fP x)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const char *str)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const char *str)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBIString\fP &str)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBIString\fP &str)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (double d)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBRef\fP \fBother\fP)"
.br
.ti -1c
.RI "bool \fBoperator!\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBValue\fP * \fBinst\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
