.TH "cashew::StackedStack< T, init >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cashew::StackedStack< T, init >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "void \fBpush_back\fP (const \fBT\fP &t)"
.br
.ti -1c
.RI "\fBT\fP & \fBback\fP ()"
.br
.ti -1c
.RI "void \fBpop_back\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP \fBstackStorage\fP [init]"
.br
.ti -1c
.RI "\fBT\fP * \fBstorage\fP"
.br
.ti -1c
.RI "int \fBused\fP"
.br
.ti -1c
.RI "int \fBavailable\fP"
.br
.ti -1c
.RI "bool \fBalloced\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
