.TH "cashew::IString::CStringEqual" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cashew::IString::CStringEqual
.SH SYNOPSIS
.br
.PP
.PP
Inherits equal_to< const char *>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const char *x, const char *y) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
