.TH "cashew::AssignName" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cashew::AssignName
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcashew::Value\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssignName\fP (\fBIString\fP targetInit, \fBRef\fP valueInit)"
.br
.ti -1c
.RI "\fBIString\fP & \fBtarget\fP ()"
.br
.ti -1c
.RI "\fBRef\fP & \fBvalue\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIString\fP \fBtarget_\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
