.TH "cashew::ArrayStorage" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cashew::ArrayStorage
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBArenaVectorBase< ArrayStorage, Ref >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBallocate\fP (size_t size)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
