.TH "CAutoBN_CTX" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAutoBN_CTX
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoperator BN_CTX *\fP ()"
.br
.ti -1c
.RI "BN_CTX & \fBoperator*\fP ()"
.br
.ti -1c
.RI "BN_CTX ** \fBoperator &\fP ()"
.br
.ti -1c
.RI "bool \fBoperator!\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "BN_CTX * \fBoperator=\fP (BN_CTX *pnew)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "BN_CTX * \fBpctx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RAII encapsulated BN_CTX (OpenSSL bignum context) 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
