.TH "cf_action" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cf_action
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static uint64_t \fBget_name\fP ()"
.br
.ti -1c
.RI "static uint64_t \fBget_account\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBpayload\fP = 100"
.br
.ti -1c
.RI "uint32_t \fBcfd_idx\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
