.TH "CFG::SimpleShape" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFG::SimpleShape
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCFG::Shape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwasm::Expression\fP * \fBRender\fP (\fBRelooperBuilder\fP &Builder, bool InLoop) override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBlock\fP * \fBInner\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
