.TH "CFG::InsertOrderedSet< T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFG::InsertOrderedSet< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBstd::list\fP< \fBT\fP >::iterator \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "iterator \fBbegin\fP ()"
.br
.ti -1c
.RI "iterator \fBend\fP ()"
.br
.ti -1c
.RI "void \fBerase\fP (const \fBT\fP &val)"
.br
.ti -1c
.RI "void \fBerase\fP (iterator position)"
.br
.ti -1c
.RI "void \fBinsert\fP (const \fBT\fP &val)"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "size_t \fBcount\fP (const \fBT\fP &val) const"
.br
.ti -1c
.RI "\fBInsertOrderedSet\fP (const \fBInsertOrderedSet\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBInsertOrderedSet\fP & \fBoperator=\fP (const \fBInsertOrderedSet\fP &\fBother\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::map\fP< \fBT\fP, typename \fBstd::list\fP< \fBT\fP >::iterator > \fBMap\fP"
.br
.ti -1c
.RI "\fBstd::list\fP< \fBT\fP > \fBList\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
