.TH "CFG::Branch" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFG::Branch
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFlowType\fP { \fBDirect\fP = 0, \fBBreak\fP = 1, \fBContinue\fP = 2 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBranch\fP (\fBwasm::Expression\fP *ConditionInit, \fBwasm::Expression\fP *CodeInit=nullptr)"
.br
.ti -1c
.RI "\fBBranch\fP (\fBstd::vector\fP< wasm::Index > &&ValuesInit, \fBwasm::Expression\fP *CodeInit=nullptr)"
.br
.ti -1c
.RI "\fBwasm::Expression\fP * \fBRender\fP (\fBRelooperBuilder\fP &Builder, \fBBlock\fP *Target, bool SetLabel)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBShape\fP * \fBAncestor\fP"
.br
.ti -1c
.RI "Branch::FlowType \fBType\fP"
.br
.ti -1c
.RI "\fBwasm::Expression\fP * \fBCondition\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBstd::vector\fP< wasm::Index > > \fBSwitchValues\fP"
.br
.ti -1c
.RI "\fBwasm::Expression\fP * \fBCode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
