.TH "CFG::InsertOrderedMap< Key, T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFG::InsertOrderedMap< Key, T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBstd::list\fP< std::pair< \fBKey\fP, \fBT\fP > >::iterator \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBT\fP & \fBoperator[]\fP (const \fBKey\fP &k)"
.br
.ti -1c
.RI "iterator \fBbegin\fP ()"
.br
.ti -1c
.RI "iterator \fBend\fP ()"
.br
.ti -1c
.RI "void \fBerase\fP (const \fBKey\fP &k)"
.br
.ti -1c
.RI "void \fBerase\fP (iterator position)"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "size_t \fBcount\fP (const \fBKey\fP &k) const"
.br
.ti -1c
.RI "\fBInsertOrderedMap\fP (\fBInsertOrderedMap\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBInsertOrderedMap\fP & \fBoperator=\fP (const \fBInsertOrderedMap\fP &\fBother\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::map\fP< \fBKey\fP, typename \fBstd::list\fP< std::pair< \fBKey\fP, \fBT\fP > >::iterator > \fBMap\fP"
.br
.ti -1c
.RI "\fBstd::list\fP< std::pair< \fBKey\fP, \fBT\fP > > \fBList\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
