.TH "libraries/chain/include/aacio/chain/chain_config.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/include/aacio/chain/chain_config.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/types\&.hpp>\fP
.br
\fC#include <aacio/chain/config\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaacio::chain::chain_config\fP"
.br
.RI "Producer-voted blockchain configuration parameters\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBaacio::chain::operator==\fP (const chain_config &a, const chain_config &b)"
.br
.ti -1c
.RI "bool \fBaacio::chain::operator!=\fP (const chain_config &a, const chain_config &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
