.TH "chaincapi" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chaincapi \- \fBC\fP API for querying internal chain state\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBget_active_producers\fP (account_name *\fBproducers\fP, uint32_t datalen)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBC\fP API for querying internal chain state\&. 


.SH "Function Documentation"
.PP 
.SS "uint32_t get_active_producers (account_name * producers, uint32_t datalen)"
Return the set of active producers 
.PP
\fBParameters:\fP
.RS 4
\fIproducers\fP - a pointer to an buffer of account_names 
.br
\fIdatalen\fP - byte length of buffer 
.RE
.PP
\fBReturns:\fP
.RS 4
the number of bytes actually populated
.RE
.PP
Example: 
.PP
.nf
account_name producers[21];
uint32_t bytes_populated = get_active_producers(producers, sizeof(account_name)*21);

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
