.TH "chainbase::database::session" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chainbase::database::session
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsession\fP (\fBsession\fP &&s)"
.br
.ti -1c
.RI "\fBsession\fP (\fBvector\fP< std::unique_ptr< \fBabstract_session\fP >> &&s)"
.br
.ti -1c
.RI "void \fBpush\fP ()"
.br
.ti -1c
.RI "void \fBsquash\fP ()"
.br
.ti -1c
.RI "void \fBundo\fP ()"
.br
.ti -1c
.RI "int64_t \fBrevision\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBdatabase\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
