.TH "plugins/chain_plugin/chain_plugin.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/chain_plugin/chain_plugin.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain_plugin/chain_plugin\&.hpp>\fP
.br
\fC#include <aacio/chain/fork_database\&.hpp>\fP
.br
\fC#include <aacio/chain/block_log\&.hpp>\fP
.br
\fC#include <aacio/chain/exceptions\&.hpp>\fP
.br
\fC#include <aacio/chain/permission_object\&.hpp>\fP
.br
\fC#include <aacio/chain/producer_object\&.hpp>\fP
.br
\fC#include <aacio/chain/config\&.hpp>\fP
.br
\fC#include <aacio/chain/types\&.hpp>\fP
.br
\fC#include <aacio/chain/wasm_interface\&.hpp>\fP
.br
\fC#include <aacio/chain/contracts/chain_initializer\&.hpp>\fP
.br
\fC#include <aacio/chain/contracts/genesis_state\&.hpp>\fP
.br
\fC#include <aacio/chain/contracts/aac_contract\&.hpp>\fP
.br
\fC#include <aacio/utilities/key_conversion\&.hpp>\fP
.br
\fC#include <aacio/chain/wast_to_wasm\&.hpp>\fP
.br
\fC#include <fc/io/json\&.hpp>\fP
.br
\fC#include <fc/variant\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::chain_plugin_impl\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain_apis::resolver_factory< Api >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBaacio::vm_type\fP = wasm_interface::vm_type"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "abi_def \fBaacio::chain_apis::get_abi\fP (const \fBchain_controller\fP &db, const \fBname\fP &\fBaccount\fP)"
.br
.ti -1c
.RI "string \fBaacio::chain_apis::get_table_type\fP (const abi_def &abi, const \fBname\fP &table_name)"
.br
.ti -1c
.RI "template<typename Api > auto \fBaacio::chain_apis::make_resolver\fP (const Api *api)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
