.TH "chainbase::session_impl< SessionType >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chainbase::session_impl< SessionType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBchainbase::abstract_session\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsession_impl\fP (SessionType &&s)"
.br
.ti -1c
.RI "virtual void \fBpush\fP () override"
.br
.ti -1c
.RI "virtual void \fBsquash\fP () override"
.br
.ti -1c
.RI "virtual void \fBundo\fP () override"
.br
.ti -1c
.RI "virtual int64_t \fBrevision\fP () const override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
