.TH "libraries/chain/chain_config.cpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/chain_config.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/chain_config\&.hpp>\fP
.br
\fC#include <boost/range/algorithm/nth_element\&.hpp>\fP
.br
\fC#include <fc/io/json\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaacio::chain::properties_median_calculator_visitor< T, Range >\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::comparison_visitor< T >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename Range > properties_median_calculator_visitor< \fBT\fP, Range > \fBaacio::chain::get_median_properties_calculator\fP (\fBT\fP &medians, Range &&votes)"
.br
.ti -1c
.RI "bool \fBaacio::chain::operator==\fP (const chain_config &a, const chain_config &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
