.TH "chainbase::environment_check" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chainbase::environment_check
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::array< char, 256 > \fBcompiler_version\fP"
.br
.ti -1c
.RI "bool \fBdebug\fP = false"
.br
.ti -1c
.RI "bool \fBapple\fP = false"
.br
.ti -1c
.RI "bool \fBwindows\fP = false"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBenvironment_check\fP &a, const \fBenvironment_check\fP &b)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
