.TH "libraries/chain/contracts/chain_initializer.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/contracts/chain_initializer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/contracts/chain_initializer\&.hpp>\fP
.br
\fC#include <aacio/chain/contracts/aac_contract\&.hpp>\fP
.br
\fC#include <aacio/chain/contracts/types\&.hpp>\fP
.br
\fC#include <aacio/chain/producer_object\&.hpp>\fP
.br
\fC#include <aacio/chain/permission_object\&.hpp>\fP
.br
\fC#include <fc/io/json\&.hpp>\fP
.br
\fC#include <boost/range/adaptor/transformed\&.hpp>\fP
.br
\fC#include <boost/range/algorithm/copy\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSET_APP_HANDLER\fP(contract,  scope,  \fBaction\fP,  nspace)   chain\&._set_apply_handler( #contract, #scope, #\fBaction\fP, &BOOST_PP_CAT(contracts::apply_, BOOST_PP_CAT(contract, BOOST_PP_CAT(_,\fBaction\fP) ) ) )"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
