.TH "chainbase::strcmp_less" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chainbase::strcmp_less
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const shared_string &a, const shared_string &b) const"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const shared_string &a, const std::string &b) const"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const std::string &a, const shared_string &b) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
