.TH "chainbase::oid< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chainbase::oid< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chainbase\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoid\fP (int64_t i=0)"
.br
.ti -1c
.RI "\fBoid\fP & \fBoperator++\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fB_id\fP = 0"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBoid\fP &a, const \fBoid\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBoid\fP &a, const \fBoid\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBoid\fP &a, const \fBoid\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBoid\fP &a, const \fBoid\fP &b)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &s, const \fBoid\fP &id)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class chainbase::oid< T >"
Object ID type that includes the type of the object it references 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
