.TH "chainbase::get_index_type< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chainbase::get_index_type< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chainbase\&.hpp>\fP
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct chainbase::get_index_type< T >"
this class is ment to be specified to enable lookup of index type by object type using the SET_INDEX_TYPE macro\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
