.TH "chainbase::read_write_mutex_manager" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chainbase::read_write_mutex_manager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBnext_lock\fP ()"
.br
.ti -1c
.RI "read_write_mutex & \fBcurrent_lock\fP ()"
.br
.ti -1c
.RI "uint32_t \fBcurrent_lock_num\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
