.TH "chainbase::abstract_index" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chainbase::abstract_index
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBchainbase::index_impl< BaseIndex >\fP, and \fBchainbase::index_impl< IndexType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBabstract_index\fP (void *i)"
.br
.ti -1c
.RI "virtual void \fBset_revision\fP (uint64_t revision)=0"
.br
.ti -1c
.RI "virtual unique_ptr< \fBabstract_session\fP > \fBstart_undo_session\fP (bool enabled)=0"
.br
.ti -1c
.RI "virtual int64_t \fBrevision\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBundo\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBsquash\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBcommit\fP (int64_t revision) const =0"
.br
.ti -1c
.RI "virtual void \fBundo_all\fP () const =0"
.br
.ti -1c
.RI "virtual uint32_t \fBtype_id\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBremove_object\fP (int64_t id)=0"
.br
.ti -1c
.RI "void * \fBget\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
