.TH "libraries/chain/chain_controller.cpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/chain_controller.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/chain_controller\&.hpp>\fP
.br
\fC#include <aacio/chain/block_summary_object\&.hpp>\fP
.br
\fC#include <aacio/chain/global_property_object\&.hpp>\fP
.br
\fC#include <aacio/chain/contracts/contract_table_objects\&.hpp>\fP
.br
\fC#include <aacio/chain/action_objects\&.hpp>\fP
.br
\fC#include <aacio/chain/generated_transaction_object\&.hpp>\fP
.br
\fC#include <aacio/chain/transaction_object\&.hpp>\fP
.br
\fC#include <aacio/chain/producer_object\&.hpp>\fP
.br
\fC#include <aacio/chain/permission_link_object\&.hpp>\fP
.br
\fC#include <aacio/chain/authority_checker\&.hpp>\fP
.br
\fC#include <aacio/chain/contracts/chain_initializer\&.hpp>\fP
.br
\fC#include <aacio/chain/scope_sequence_object\&.hpp>\fP
.br
\fC#include <aacio/chain/merkle\&.hpp>\fP
.br
\fC#include <aacio/chain/exceptions\&.hpp>\fP
.br
\fC#include <aacio/chain/wasm_interface\&.hpp>\fP
.br
\fC#include <aacio/utilities/rand\&.hpp>\fP
.br
\fC#include <fc/smart_ref_impl\&.hpp>\fP
.br
\fC#include <fc/uint128\&.hpp>\fP
.br
\fC#include <fc/crypto/digest\&.hpp>\fP
.br
\fC#include <boost/range/algorithm/copy\&.hpp>\fP
.br
\fC#include <boost/range/algorithm_ext/erase\&.hpp>\fP
.br
\fC#include <boost/range/algorithm_ext/is_sorted\&.hpp>\fP
.br
\fC#include <boost/range/adaptor/transformed\&.hpp>\fP
.br
\fC#include <boost/range/adaptor/map\&.hpp>\fP
.br
\fC#include <boost/range/algorithm/sort\&.hpp>\fP
.br
\fC#include <boost/range/algorithm/find\&.hpp>\fP
.br
\fC#include <boost/range/algorithm/remove_if\&.hpp>\fP
.br
\fC#include <boost/range/algorithm/equal\&.hpp>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <chrono>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::chain::permission_visitor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
