.TH "chainbase::generic_index< MultiIndexType >::session" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chainbase::generic_index< MultiIndexType >::session
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsession\fP (\fBsession\fP &&mv)"
.br
.ti -1c
.RI "void \fBpush\fP ()"
.br
.ti -1c
.RI "void \fBsquash\fP ()"
.br
.ti -1c
.RI "void \fBundo\fP ()"
.br
.ti -1c
.RI "\fBsession\fP & \fBoperator=\fP (\fBsession\fP &&mv)"
.br
.ti -1c
.RI "int64_t \fBrevision\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBgeneric_index\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename MultiIndexType > void \fBchainbase::generic_index\fP< MultiIndexType >::session::push ()\fC [inline]\fP"
leaves the UNDO state on the stack when session goes out of scope 
.SS "template<typename MultiIndexType > void \fBchainbase::generic_index\fP< MultiIndexType >::session::squash ()\fC [inline]\fP"
combines this session with the prior session 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
