.TH "channel" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
channel
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpush_awaiter\fP \fBpush\fP (\fBT\fP const &value)"
.br
.ti -1c
.RI "\fBpull_awaiter\fP \fBpull\fP ()"
.br
.ti -1c
.RI "void \fBsync_push\fP (\fBT\fP const &value)"
.br
.ti -1c
.RI "auto \fBsync_pull\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "struct \fBpush_awaiter\fP"
.br
.ti -1c
.RI "struct \fBpull_awaiter\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
