.TH "check_bitmask_type< EnumType, Val1, Val2, UT, UVal1, UVal2, UZero, Zero >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
check_bitmask_type< EnumType, Val1, Val2, UT, UVal1, UVal2, UZero, Zero >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static constexpr UT \fBdcast\fP (\fBEnumType\fP e)"
.br
.ti -1c
.RI "static constexpr UT \fBunpromote\fP (decltype((~UZero)) promoted)"
.br
.ti -1c
.RI "static bool \fBcheck\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
