.TH "Checkpoint" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Checkpoint
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCheckpoint\fP (const char *xfile, const char *xfunc, int xline, const char *xmsg)"
.br
.ti -1c
.RI "template<class Stream > void \fBprint\fP (Stream &s) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBfile\fP"
.br
.ti -1c
.RI "const char * \fBfunc\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "const char * \fBmsg\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
