.TH "CLI::BadNameString" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLI::BadNameString \- Thrown on construction of a bad name\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CLI11\&.hpp>\fP
.PP
Inherits \fBCLI::ConstructionError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBadNameString\fP (std::string name)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Thrown on construction of a bad name\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
