.TH "CLI::ParseError" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLI::ParseError \- Anything that can error in Parse\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CLI11\&.hpp>\fP
.PP
Inherits \fBCLI::Error\fP\&.
.PP
Inherited by \fBCLI::CallForHelp\fP, \fBCLI::ConversionError\fP, \fBCLI::ExcludesError\fP, \fBCLI::ExtrasError\fP, \fBCLI::ExtrasINIError\fP, \fBCLI::FileError\fP, \fBCLI::HorribleError\fP, \fBCLI::InvalidError\fP, \fBCLI::RequiredError\fP, \fBCLI::RequiresError\fP, \fBCLI::Success\fP, and \fBCLI::ValidationError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseError\fP (std::string parent, std::string name, ExitCodes exit_code=ExitCodes::BaseClass, bool print_help=true)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Anything that can error in Parse\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
