.TH "CLI::HorribleError" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLI::HorribleError \- This is just a safety check to verify selection and parsing match\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CLI11\&.hpp>\fP
.PP
Inherits \fBCLI::ParseError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHorribleError\fP (std::string name)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is just a safety check to verify selection and parsing match\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
