.TH "CLI::IncorrectConstruction" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLI::IncorrectConstruction \- Thrown when an option is set to conflicting values (non-vector and multi args, for example)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CLI11\&.hpp>\fP
.PP
Inherits \fBCLI::ConstructionError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIncorrectConstruction\fP (std::string name)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Thrown when an option is set to conflicting values (non-vector and multi args, for example) 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
