.TH "CLI::ExtrasINIError" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLI::ExtrasINIError \- Thrown when extra values are found in an INI file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CLI11\&.hpp>\fP
.PP
Inherits \fBCLI::ParseError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExtrasINIError\fP (std::string name)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Thrown when extra values are found in an INI file\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
