.TH "CLI::ConstructionError" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLI::ConstructionError \- Construction errors (not in parsing)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CLI11\&.hpp>\fP
.PP
Inherits \fBCLI::Error\fP\&.
.PP
Inherited by \fBCLI::BadNameString\fP, \fBCLI::IncorrectConstruction\fP, and \fBCLI::OptionAlreadyAdded\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstructionError\fP (std::string parent, std::string name, ExitCodes exit_code=ExitCodes::BaseClass, bool print_help=true)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Construction errors (not in parsing) 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
