.TH "cmsghdr" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmsghdr
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "socklen_t \fBcmsg_len\fP"
.br
.ti -1c
.RI "int \fBcmsg_level\fP"
.br
.ti -1c
.RI "int \fBcmsg_type\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
