.TH "commonNaN" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
commonNaN
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBsign\fP"
.br
.ti -1c
.RI "uint64_t \fBv64\fP"
.br
.ti -1c
.RI "uint64_t \fBv0\fP"
.br
.ti -1c
.RI "char \fB_unused\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
