.TH "common_fixture" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common_fixture
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcompose_fixture< PROPERTIES_POLICY >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtest_transaction\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "auto \fBcreate_transactions\fP (const std::initializer_list< \fBtest_transaction\fP > &transactions)"
.br
.ti -1c
.RI "auto \fBcreate_pending\fP (const \fBstd::vector\fP< \fBsigned_transaction\fP > &transactions)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
