.TH "compare_bench" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
compare_bench
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcheck_inputs\fP (in1, in2, flags)"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
compare_bench.py - Compare two benchmarks or their results and report the
           difference.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def compare_bench\&.check_inputs ( in1,  in2,  flags)"

.PP
.nf
Perform checking on the user provided inputs and diagnose any abnormalities

.fi
.PP
 
.SS "def compare_bench\&.main (void)"

.PP
.nf
Invoked when the script is run directly by the python interpreter

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
