.TH "compose_fixture< PROPERTIES_POLICY >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
compose_fixture< PROPERTIES_POLICY >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcommon_fixture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename SCHED_FN , typename \&.\&.\&. VALIDATORS> void \fBschedule_and_validate\fP (SCHED_FN sched_fn, const std::initializer_list< \fBtest_transaction\fP > &transactions, VALIDATORS \&.\&.\&.validators)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
