.TH "comparable_struct" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
comparable_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "short \fBs\fP"
.br
.ti -1c
.RI "bool \fBbl\fP"
.br
.ti -1c
.RI "int \fBa\fP"
.br
.ti -1c
.RI "int \fBb\fP"
.br
.ti -1c
.RI "int \fBc\fP"
.br
.ti -1c
.RI "int \fBd\fP"
.br
.ti -1c
.RI "int \fBe\fP"
.br
.ti -1c
.RI "int \fBf\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
