.TH "tests/tests/config.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/tests/config.hpp
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr char \fBaacio::tests::config::aaciolib_path\fP [] = '/Users/caokun_8341/AcuteAngleChain/tests/\&.\&./contracts'"
.br
.ti -1c
.RI "constexpr char \fBaacio::tests::config::pfr_include_path\fP [] = '/Users/caokun_8341/AcuteAngleChain/tests/\&.\&./externals/magic_get/include'"
.br
.ti -1c
.RI "constexpr char \fBaacio::tests::config::boost_include_path\fP [] = '/usr/local/include'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
