.TH "config_tls" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_tls
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwebsocketpp::config::asio_tls_client\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtransport_config\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBconfig\fP \fBtype\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::config::asio\fP \fBbase\fP"
.br
.ti -1c
.RI "typedef \fBbase::concurrency_type\fP \fBconcurrency_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::request_type\fP \fBrequest_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::response_type\fP \fBresponse_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::message_type\fP \fBmessage_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::con_msg_manager_type\fP \fBcon_msg_manager_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::endpoint_msg_manager_type\fP \fBendpoint_msg_manager_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::alog_type\fP \fBalog_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::elog_type\fP \fBelog_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::rng_type\fP \fBrng_type\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::transport::asio::endpoint\fP< \fBtransport_config\fP > \fBtransport_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const long \fBtimeout_open_handshake\fP = 500"
.br
.RI "Length of time before an opening handshake is aborted\&. "
.ti -1c
.RI "static const long \fBtimeout_close_handshake\fP = 500"
.br
.RI "Length of time before a closing handshake is aborted\&. "
.ti -1c
.RI "static const long \fBtimeout_pong\fP = 500"
.br
.RI "Length of time to wait for a pong after a ping\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
