.TH "connection_setup" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
connection_setup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnection_setup\fP (bool p_is_server)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "websocketpp::lib::error_code \fBec\fP"
.br
.ti -1c
.RI "stub_config::alog_type \fBalog\fP"
.br
.ti -1c
.RI "stub_config::elog_type \fBelog\fP"
.br
.ti -1c
.RI "stub_config::rng_type \fBrng\fP"
.br
.ti -1c
.RI "\fBwebsocketpp::connection\fP< \fBstub_config\fP > \fBc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
