.TH "connection_metadata" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
connection_metadata
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef websocketpp::lib::shared_ptr< \fBconnection_metadata\fP > \fBptr\fP"
.br
.ti -1c
.RI "typedef websocketpp::lib::shared_ptr< \fBconnection_metadata\fP > \fBptr\fP"
.br
.ti -1c
.RI "typedef websocketpp::lib::shared_ptr< \fBconnection_metadata\fP > \fBptr\fP"
.br
.ti -1c
.RI "typedef websocketpp::lib::shared_ptr< \fBconnection_metadata\fP > \fBptr\fP"
.br
.ti -1c
.RI "typedef websocketpp::lib::shared_ptr< \fBconnection_metadata\fP > \fBptr\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnection_metadata\fP (int id, \fBwebsocketpp::connection_hdl\fP hdl, std::string uri)"
.br
.ti -1c
.RI "void \fBon_open\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "void \fBon_fail\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "void \fBon_close\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "\fBwebsocketpp::connection_hdl\fP \fBget_hdl\fP () const"
.br
.ti -1c
.RI "int \fBget_id\fP () const"
.br
.ti -1c
.RI "std::string \fBget_status\fP () const"
.br
.ti -1c
.RI "\fBconnection_metadata\fP (int id, \fBwebsocketpp::connection_hdl\fP hdl, std::string uri)"
.br
.ti -1c
.RI "void \fBon_open\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "void \fBon_fail\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "void \fBon_close\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "void \fBon_message\fP (\fBwebsocketpp::connection_hdl\fP, \fBclient::message_ptr\fP msg)"
.br
.ti -1c
.RI "\fBwebsocketpp::connection_hdl\fP \fBget_hdl\fP () const"
.br
.ti -1c
.RI "int \fBget_id\fP () const"
.br
.ti -1c
.RI "std::string \fBget_status\fP () const"
.br
.ti -1c
.RI "void \fBrecord_sent_message\fP (std::string message)"
.br
.ti -1c
.RI "\fBconnection_metadata\fP (int id, \fBwebsocketpp::connection_hdl\fP hdl, std::string uri)"
.br
.ti -1c
.RI "void \fBon_open\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "void \fBon_fail\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "\fBconnection_metadata\fP (int id, \fBwebsocketpp::connection_hdl\fP hdl, std::string uri)"
.br
.ti -1c
.RI "void \fBon_open\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "void \fBon_fail\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "void \fBon_close\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "\fBwebsocketpp::connection_hdl\fP \fBget_hdl\fP () const"
.br
.ti -1c
.RI "int \fBget_id\fP () const"
.br
.ti -1c
.RI "std::string \fBget_status\fP () const"
.br
.ti -1c
.RI "\fBconnection_metadata\fP (int id, \fBwebsocketpp::connection_hdl\fP hdl, std::string uri)"
.br
.ti -1c
.RI "void \fBon_open\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "void \fBon_fail\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "void \fBon_close\fP (\fBclient\fP *c, \fBwebsocketpp::connection_hdl\fP hdl)"
.br
.ti -1c
.RI "void \fBon_message\fP (\fBwebsocketpp::connection_hdl\fP, \fBclient::message_ptr\fP msg)"
.br
.ti -1c
.RI "\fBwebsocketpp::connection_hdl\fP \fBget_hdl\fP () const"
.br
.ti -1c
.RI "int \fBget_id\fP () const"
.br
.ti -1c
.RI "std::string \fBget_status\fP () const"
.br
.ti -1c
.RI "void \fBrecord_sent_message\fP (std::string message)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, \fBconnection_metadata\fP const &data)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, \fBconnection_metadata\fP const &data)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, \fBconnection_metadata\fP const &data)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, \fBconnection_metadata\fP const &data)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, \fBconnection_metadata\fP const &data)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
