.TH "consoleapi" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
consoleapi \- Enables applications to log/print text messages\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBConsole C API\fP"
.br
.RI "\fBC\fP API to log/print text messages\&. "
.ti -1c
.RI "\fBConsole C++ API\fP"
.br
.RI "C++ wrapper for Console \fBC\fP API\&. "
.in -1c
.SH "Detailed Description"
.PP 
Enables applications to log/print text messages\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
