.TH "ConstTrackingDeleter< ID >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstTrackingDeleter< ID >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstTrackingDeleter\fP (\fBConstTrackingDeleter\fP const &)"
.br
.ti -1c
.RI "\fBConstTrackingDeleter\fP (\fBConstTrackingDeleter\fP &&)"
.br
.ti -1c
.RI "template<class T , class  = EnableIfSpecialization<ConstTrackingDeleter, T>> \fBConstTrackingDeleter\fP (\fBT\fP &&)"
.br
.ti -1c
.RI "const \fBConstTrackingDeleter\fP & \fBoperator=\fP (\fBConstTrackingDeleter\fP const &) const"
.br
.ti -1c
.RI "const \fBConstTrackingDeleter\fP & \fBoperator=\fP (\fBConstTrackingDeleter\fP &&) const"
.br
.ti -1c
.RI "template<class T , class  = EnableIfSpecialization<ConstTrackingDeleter, T>> const \fBConstTrackingDeleter\fP & \fBoperator=\fP (\fBT\fP &&) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (void *) const"
.br
.ti -1c
.RI "\fBTypeID\fP const  * \fBreset\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTypeID\fP const  * \fBarg_type\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
