.TH "ConstructibleFromInt" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstructibleFromInt
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBState\fP { \fBFromInt\fP, \fBCopied\fP, \fBMoved\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstructibleFromInt\fP (\fBConstructibleFromInt\fP const &)"
.br
.ti -1c
.RI "\fBConstructibleFromInt\fP (\fBConstructibleFromInt\fP &&)"
.br
.ti -1c
.RI "\fBConstructibleFromInt\fP (int)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "State \fBstate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
