.TH "ConstCallable< Ret >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstCallable< Ret >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstCallable\fP (\fBConstCallable\fP const &\fBother\fP)"
.br
.ti -1c
.RI "\fBConstCallable\fP (\fBConstCallable\fP &&\fBother\fP)"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args> Ret \fBoperator()\fP (Args &&\&.\&.\&.) const"
.br
.ti -1c
.RI "\fBConstCallable\fP (bool x)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Ret \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
