.TH "ConvertingType" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConvertingType
.SH SYNOPSIS
.br
.PP
.PP
Inherits DEFINE_BASEConvertingType\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBBase\fP = DEFINE_BASE(\fBConvertingType\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "DEFINE_EXPLICIT DEFINE_CONSTEXPR \fBConvertingType\fP (\fBConvertingType\fP const &) DEFINE_CTOR"
.br
.ti -1c
.RI "DEFINE_EXPLICIT DEFINE_CONSTEXPR \fBConvertingType\fP (\fBConvertingType\fP &&) DEFINE_CTOR"
.br
.ti -1c
.RI "\fBConvertingType\fP & \fBoperator=\fP (\fBConvertingType\fP const &) DEFINE_ASSIGN"
.br
.ti -1c
.RI "\fBConvertingType\fP & \fBoperator=\fP (\fBConvertingType\fP &&) DEFINE_ASSIGN"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args> DEFINE_EXPLICIT DEFINE_CONSTEXPR \fBConvertingType\fP (Args &&\&.\&.\&.)"
.br
.ti -1c
.RI "template<class Arg > \fBConvertingType\fP & \fBoperator=\fP (Arg &&)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
