.TH "cookie_FILE" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cookie_FILE
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFILE\fP \fBf\fP"
.br
.ti -1c
.RI "struct \fBfcookie\fP \fBfc\fP"
.br
.ti -1c
.RI "unsigned char \fBbuf\fP [UNGET+BUFSIZ]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
