.TH "cookie" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cookie
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBpos\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "unsigned char * \fBbuf\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "char ** \fBbufp\fP"
.br
.ti -1c
.RI "size_t * \fBsizep\fP"
.br
.ti -1c
.RI "char * \fBbuf\fP"
.br
.ti -1c
.RI "size_t \fBspace\fP"
.br
.ti -1c
.RI "wchar_t ** \fBbufp\fP"
.br
.ti -1c
.RI "wchar_t * \fBbuf\fP"
.br
.ti -1c
.RI "\fBmbstate_t\fP \fBmbs\fP"
.br
.ti -1c
.RI "char * \fBs\fP"
.br
.ti -1c
.RI "size_t \fBn\fP"
.br
.ti -1c
.RI "wchar_t * \fBws\fP"
.br
.ti -1c
.RI "size_t \fBl\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
