.TH "CopyAssignable" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CopyAssignable
.SH SYNOPSIS
.br
.PP
.PP
Inherits DEFINE_BASECopyAssignable\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBBase\fP = DEFINE_BASE(\fBCopyAssignable\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCopyAssignable\fP & \fBoperator=\fP (\fBCopyAssignable\fP const &)=default"
.br
.ti -1c
.RI "\fBCopyAssignable\fP & \fBoperator=\fP (\fBCopyAssignable\fP &&)=delete"
.br
.ti -1c
.RI "\fBCopyAssignable\fP & \fBoperator=\fP (\fBCopyAssignable\fP const &)=default"
.br
.ti -1c
.RI "\fBCopyAssignable\fP & \fBoperator=\fP (\fBCopyAssignable\fP &&)=delete"
.br
.ti -1c
.RI "\fBCopyAssignable\fP (\fBCopyAssignable\fP const &)=default"
.br
.ti -1c
.RI "\fBCopyAssignable\fP & \fBoperator=\fP (\fBCopyAssignable\fP const &)=default"
.br
.ti -1c
.RI "\fBCopyAssignable\fP & \fBoperator=\fP (\fBCopyAssignable\fP &&)=delete"
.br
.ti -1c
.RI "\fBCopyAssignable\fP & \fBoperator=\fP (\fBCopyAssignable\fP const &)=default"
.br
.ti -1c
.RI "\fBCopyAssignable\fP & \fBoperator=\fP (\fBCopyAssignable\fP &&)=delete"
.br
.ti -1c
.RI "\fBCopyAssignable\fP & \fBoperator=\fP (\fBCopyAssignable\fP const &) DEFINE_ASSIGN"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
