.TH "CopyCallable< Ret >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CopyCallable< Ret >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCopyCallable\fP (\fBCopyCallable\fP const &\fBother\fP)"
.br
.ti -1c
.RI "\fBCopyCallable\fP (\fBCopyCallable\fP &&\fBother\fP)"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args> Ret \fBoperator()\fP (Args &&\&.\&.\&.)"
.br
.ti -1c
.RI "\fBCopyCallable\fP (bool x)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Ret \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
