.TH "CopyCannotThrow" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CopyCannotThrow
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCopyCannotThrow\fP (const \fBCopyCannotThrow\fP &) noexcept"
.br
.ti -1c
.RI "\fBCopyCannotThrow\fP (\fBCopyCannotThrow\fP &&) noexcept"
.br
.ti -1c
.RI "\fBCopyCannotThrow\fP & \fBoperator=\fP (const \fBCopyCannotThrow\fP &) noexcept=default"
.br
.ti -1c
.RI "\fBCopyCannotThrow\fP & \fBoperator=\fP (\fBCopyCannotThrow\fP &&) noexcept"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBalive\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
