.TH "CopyInsertable< Dummy >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CopyInsertable< Dummy >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCopyInsertable\fP (int val)"
.br
.ti -1c
.RI "\fBCopyInsertable\fP (\fBCopyInsertable\fP const &\fBother\fP)"
.br
.ti -1c
.RI "\fBCopyInsertable\fP (\fBCopyInsertable\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBCopyInsertable\fP (\fBCopyInsertable\fP &&\fBother\fP)"
.br
.ti -1c
.RI "\fBCopyInsertable\fP (\fBCopyInsertable\fP const &&\fBother\fP)"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args> \fBCopyInsertable\fP (Args &&\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBreset\fP (int value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdata\fP"
.br
.ti -1c
.RI "bool \fBcopied_once\fP"
.br
.ti -1c
.RI "bool \fBconstructed_under_allocator\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
