.TH "CopyAssignableWrapper" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CopyAssignableWrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCopyAssignableWrapper\fP (\fBCopyAssignableWrapper\fP const &)=default"
.br
.ti -1c
.RI "\fBCopyAssignableWrapper\fP (\fBCopyAssignableWrapper\fP &&)=default"
.br
.ti -1c
.RI "\fBCopyAssignableWrapper\fP & \fBoperator=\fP (\fBCopyAssignableWrapper\fP const &)=default"
.br
.ti -1c
.RI "\fBCopyAssignableWrapper\fP & \fBoperator=\fP (\fBCopyAssignableWrapper\fP &&)=default"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args> bool \fBoperator()\fP (Args &&\&.\&.\&.)"
.br
.ti -1c
.RI "\fBCopyAssignableWrapper\fP (bool x)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
