.TH "CopyMaybeThrows" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CopyMaybeThrows
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCopyMaybeThrows\fP (const \fBCopyMaybeThrows\fP &)"
.br
.ti -1c
.RI "\fBCopyMaybeThrows\fP & \fBoperator=\fP (const \fBCopyMaybeThrows\fP &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
