.TH "CopyOnly" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CopyOnly
.SH SYNOPSIS
.br
.PP
.PP
Inherits DEFINE_BASECopyOnly\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBBase\fP = DEFINE_BASE(\fBCopyOnly\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCopyOnly\fP (const \fBCopyOnly\fP &)=default"
.br
.ti -1c
.RI "\fBCopyOnly\fP (\fBCopyOnly\fP &&)=delete"
.br
.ti -1c
.RI "\fBCopyOnly\fP & \fBoperator=\fP (const \fBCopyOnly\fP &)=default"
.br
.ti -1c
.RI "\fBCopyOnly\fP & \fBoperator=\fP (\fBCopyOnly\fP &&)=delete"
.br
.ti -1c
.RI "\fBCopyOnly\fP (const \fBCopyOnly\fP &)=default"
.br
.ti -1c
.RI "\fBCopyOnly\fP (\fBCopyOnly\fP &&)=delete"
.br
.ti -1c
.RI "\fBCopyOnly\fP & \fBoperator=\fP (const \fBCopyOnly\fP &)=default"
.br
.ti -1c
.RI "\fBCopyOnly\fP & \fBoperator=\fP (\fBCopyOnly\fP &&)=delete"
.br
.ti -1c
.RI "DEFINE_EXPLICIT DEFINE_CONSTEXPR \fBCopyOnly\fP (\fBCopyOnly\fP const &) DEFINE_CTOR"
.br
.ti -1c
.RI "DEFINE_EXPLICIT DEFINE_CONSTEXPR \fBCopyOnly\fP (\fBCopyOnly\fP &&)=delete"
.br
.ti -1c
.RI "\fBCopyOnly\fP & \fBoperator=\fP (\fBCopyOnly\fP const &) DEFINE_ASSIGN"
.br
.ti -1c
.RI "\fBCopyOnly\fP & \fBoperator=\fP (\fBCopyOnly\fP &&)=delete"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
