.TH "Copyable" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Copyable
.SH SYNOPSIS
.br
.PP
.PP
Inherits DEFINE_BASECopyable\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBBase\fP = DEFINE_BASE(\fBCopyable\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "DEFINE_EXPLICIT DEFINE_CONSTEXPR \fBCopyable\fP (\fBCopyable\fP const &) DEFINE_CTOR"
.br
.ti -1c
.RI "\fBCopyable\fP & \fBoperator=\fP (\fBCopyable\fP const &) DEFINE_ASSIGN"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCopyable\fP &x, const \fBCopyable\fP &y)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCopyable\fP &x, const \fBCopyable\fP &y)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
