.TH "coro2::promise_type" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coro2::promise_type
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "suspend_never \fBinitial_suspend\fP ()"
.br
.ti -1c
.RI "suspend_never \fBfinal_suspend\fP ()"
.br
.ti -1c
.RI "\fBcoro2\fP \fBget_return_object\fP ()"
.br
.ti -1c
.RI "void \fBreturn_void\fP ()"
.br
.ti -1c
.RI "\fBBug\fP \fByield_value\fP (int)"
.br
.ti -1c
.RI "void \fBunhandled_exception\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
