.TH "coro_t" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coro_t
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpromise_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcoro_t\fP (coroutine_handle< \fBpromise_type\fP > hh)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "coroutine_handle< \fBpromise_type\fP > \fBh\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
