.TH "Counted" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Counted
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCounted\fP (\fBCounted\fP const &)"
.br
.ti -1c
.RI "\fBCounted\fP (\fBCounted\fP const &)"
.br
.ti -1c
.RI "\fBCounted\fP (\fBCounted\fP const &)"
.br
.ti -1c
.RI "\fBCounted\fP (\fBCounted\fP const &)"
.br
.ti -1c
.RI "\fBCounted\fP (\fBCounted\fP const &)"
.br
.ti -1c
.RI "\fBCounted\fP (\fBCounted\fP const &)"
.br
.ti -1c
.RI "\fBCounted\fP (\fBCounted\fP const &)"
.br
.ti -1c
.RI "\fBCounted\fP (int &&x)"
.br
.ti -1c
.RI "\fBCounted\fP (\fBCounted\fP const &)"
.br
.ti -1c
.RI "\fBCounted\fP (int &&x)"
.br
.ti -1c
.RI "\fBCounted\fP (\fBCounted\fP const &)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBcount\fP = 0"
.br
.ti -1c
.RI "static int \fBconstructed\fP = 0"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "void \fBoperator &\fP (\fBCounted\fP)=delete"
.br
.ti -1c
.RI "void \fBoperator &\fP (\fBCounted\fP)=delete"
.br
.ti -1c
.RI "void \fBoperator &\fP (\fBCounted\fP)=delete"
.br
.ti -1c
.RI "void \fBoperator &\fP (\fBCounted\fP)=delete"
.br
.ti -1c
.RI "void \fBoperator &\fP (\fBCounted\fP)=delete"
.br
.ti -1c
.RI "void \fBoperator &\fP (\fBCounted\fP)=delete"
.br
.ti -1c
.RI "void \fBoperator &\fP (\fBCounted\fP)=delete"
.br
.ti -1c
.RI "void \fBoperator &\fP (\fBCounted\fP)=delete"
.br
.ti -1c
.RI "void \fBoperator &\fP (\fBCounted\fP)=delete"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
