.TH "CountCopiesAllocV2" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CountCopiesAllocV2
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ex::memory_resource * \fBallocator_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCountCopiesAllocV2\fP (\fBCountCopiesAllocV2\fP const &o, allocator_type const &a)"
.br
.ti -1c
.RI "\fBCountCopiesAllocV2\fP (\fBCountCopiesAllocV2\fP const &o)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "allocator_type \fBalloc\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
