.TH "count_server" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
count_server
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBon_open\fP (connection_hdl hdl)"
.br
.ti -1c
.RI "void \fBon_close\fP (connection_hdl hdl)"
.br
.ti -1c
.RI "void \fBcount\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP (uint16_t port)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
