.TH "currency_tester" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
currency_tester
.SH SYNOPSIS
.br
.PP
.PP
Inherits TESTER\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBpush_action\fP (const account_name &signer, const action_name &\fBname\fP, const \fBvariant_object\fP &data)"
.br
.ti -1c
.RI "\fBasset\fP \fBget_balance\fP (const account_name &\fBaccount\fP) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBabi_serializer\fP \fBabi_ser\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
