.TH "D< T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBB< T >\fP, \fBB< T >\fP, \fBB< T >\fP, \fBB< T >\fP, \fBB< T >\fP, \fBB< T >\fP, \fBB< T >\fP, \fBB< T >\fP, \fBB< T >\fP, \fBB1< T >\fP, \fBB2\fP, and nested_exception\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrebind\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::scoped_allocator_adaptor< \fBA2\fP< \fBD\fP > > \fBallocator_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef short \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef char \fBdifference_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBD\fP (int i, int j, const \fBallocator_type\fP &a)"
.br
.ti -1c
.RI "\fBD\fP (int i=0)"
.br
.ti -1c
.RI "\fBD\fP (int i)"
.br
.ti -1c
.RI "\fBD\fP (int i)"
.br
.ti -1c
.RI "\fBD\fP (int i)"
.br
.ti -1c
.RI "\fBD\fP (int i)"
.br
.ti -1c
.RI "\fBD\fP (int i)"
.br
.ti -1c
.RI "\fBD\fP (int i)"
.br
.ti -1c
.RI "\fBD\fP (int i)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBallocator_type\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBconstructed\fP = false"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
