.TH "DCounted" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DCounted
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVCounted\fP\&.
.SS "Friends"

.in +1c
.ti -1c
.RI "void \fBoperator &\fP (\fBDCounted\fP)=delete"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
