.TH "debug_custom" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
debug_custom
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwebsocketpp::config::debug_asio\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtransport_config\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBdebug_custom\fP \fBtype\fP"
.br
.ti -1c
.RI "typedef debug_asio \fBbase\fP"
.br
.ti -1c
.RI "typedef base::concurrency_type \fBconcurrency_type\fP"
.br
.ti -1c
.RI "typedef base::request_type \fBrequest_type\fP"
.br
.ti -1c
.RI "typedef base::response_type \fBresponse_type\fP"
.br
.ti -1c
.RI "typedef base::message_type \fBmessage_type\fP"
.br
.ti -1c
.RI "typedef base::con_msg_manager_type \fBcon_msg_manager_type\fP"
.br
.ti -1c
.RI "typedef base::endpoint_msg_manager_type \fBendpoint_msg_manager_type\fP"
.br
.ti -1c
.RI "typedef base::alog_type \fBalog_type\fP"
.br
.RI "Custom Logging policies\&. "
.ti -1c
.RI "typedef base::elog_type \fBelog_type\fP"
.br
.ti -1c
.RI "typedef base::rng_type \fBrng_type\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::transport::asio::endpoint\fP< \fBtransport_config\fP > \fBtransport_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const long \fBtimeout_open_handshake\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
====== WARNING ======== This example is presently used as a scratch space\&. It may or may not be broken at any given time\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
