.TH "debug_config_client" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
debug_config_client
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwebsocketpp::config::core\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtransport_config\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBdebug_config_client\fP \fBtype\fP"
.br
.ti -1c
.RI "typedef core::concurrency_type \fBconcurrency_type\fP"
.br
.ti -1c
.RI "typedef core::request_type \fBrequest_type\fP"
.br
.ti -1c
.RI "typedef core::response_type \fBresponse_type\fP"
.br
.ti -1c
.RI "typedef core::message_type \fBmessage_type\fP"
.br
.ti -1c
.RI "typedef core::con_msg_manager_type \fBcon_msg_manager_type\fP"
.br
.ti -1c
.RI "typedef core::endpoint_msg_manager_type \fBendpoint_msg_manager_type\fP"
.br
.ti -1c
.RI "typedef core::alog_type \fBalog_type\fP"
.br
.ti -1c
.RI "typedef core::elog_type \fBelog_type\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::random::none::int_generator\fP< uint32_t > \fBrng_type\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::transport::debug::endpoint\fP< \fBtransport_config\fP > \fBtransport_type\fP"
.br
.RI "Transport Endpoint Component\&. "
.ti -1c
.RI "typedef core::endpoint_base \fBendpoint_base\fP"
.br
.ti -1c
.RI "typedef \fBconnection_extension\fP \fBconnection_base\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const websocketpp::log::level \fBelog_level\fP = \fBwebsocketpp::log::elevel::none\fP"
.br
.ti -1c
.RI "static const websocketpp::log::level \fBalog_level\fP = \fBwebsocketpp::log::alevel::none\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
