.TH "contracts/aacio.system/delegate_bandwidth.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/aacio.system/delegate_bandwidth.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.hpp'\fP
.br
\fC#include 'voting\&.hpp'\fP
.br
\fC#include <aaciolib/aacio\&.hpp>\fP
.br
\fC#include <aaciolib/token\&.hpp>\fP
.br
\fC#include <aaciolib/print\&.hpp>\fP
.br
\fC#include <aaciolib/generic_currency\&.hpp>\fP
.br
\fC#include <aaciolib/datastream\&.hpp>\fP
.br
\fC#include <aaciolib/serialize\&.hpp>\fP
.br
\fC#include <aaciolib/multi_index\&.hpp>\fP
.br
\fC#include <aaciolib/privileged\&.h>\fP
.br
\fC#include <aaciolib/transaction\&.hpp>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaaciosystem::delegate_bandwidth< SystemAccount >\fP"
.br
.ti -1c
.RI "struct \fBaaciosystem::delegate_bandwidth< SystemAccount >::total_resources\fP"
.br
.ti -1c
.RI "struct \fBaaciosystem::delegate_bandwidth< SystemAccount >::delegated_bandwidth\fP"
.br
.ti -1c
.RI "struct \fBaaciosystem::delegate_bandwidth< SystemAccount >::refund_request\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
