.TH "Deleter< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Deleter< T >
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpointer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class Tp > void \fBoperator()\fP (Tp) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (void *)"
.br
.ti -1c
.RI "void \fBoperator()\fP (int *p) const"
.br
.ti -1c
.RI "int \fBstate\fP () const"
.br
.ti -1c
.RI "void \fBoperator()\fP (void *)"
.br
.ti -1c
.RI "void \fBoperator()\fP (void *) const"
.br
.ti -1c
.RI "int \fBtest\fP ()"
.br
.ti -1c
.RI "int \fBtest\fP () const"
.br
.ti -1c
.RI "\fBDeleter\fP (int s)"
.br
.ti -1c
.RI "\fBDeleter\fP (\fBDeleter\fP const &\fBother\fP)"
.br
.ti -1c
.RI "\fBDeleter\fP & \fBoperator=\fP (\fBDeleter\fP const &\fBother\fP)"
.br
.ti -1c
.RI "template<class U > \fBDeleter\fP (\fBDeleter\fP< \fBU\fP > d, typename std::enable_if<!std::is_same< \fBU\fP, \fBT\fP >::value >::type *=0)"
.br
.ti -1c
.RI "int \fBstate\fP () const"
.br
.ti -1c
.RI "void \fBset_state\fP (int i)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBT\fP *p)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
