.TH "DenseStaticIntSet< Index, maxIndexPlusOne >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DenseStaticIntSet< Index, maxIndexPlusOne >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDenseStaticIntSet\fP (Index index)"
.br
.ti -1c
.RI "bool \fBcontains\fP (Index index) const"
.br
.ti -1c
.RI "bool \fBisEmpty\fP () const"
.br
.ti -1c
.RI "Index \fBgetSmallestMember\fP () const"
.br
.ti -1c
.RI "void \fBadd\fP (Index index)"
.br
.ti -1c
.RI "void \fBaddRange\fP (Index rangeMin, Index rangeMax)"
.br
.ti -1c
.RI "bool \fBremove\fP (Index index)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBDenseStaticIntSet\fP \fBoperator~\fP (const \fBDenseStaticIntSet\fP &set)"
.br
.ti -1c
.RI "\fBDenseStaticIntSet\fP \fBoperator|\fP (const \fBDenseStaticIntSet\fP &left, const \fBDenseStaticIntSet\fP &right)"
.br
.ti -1c
.RI "\fBDenseStaticIntSet\fP \fBoperator &\fP (const \fBDenseStaticIntSet\fP &left, const \fBDenseStaticIntSet\fP &right)"
.br
.ti -1c
.RI "\fBDenseStaticIntSet\fP \fBoperator^\fP (const \fBDenseStaticIntSet\fP &left, const \fBDenseStaticIntSet\fP &right)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBDenseStaticIntSet\fP &left, const \fBDenseStaticIntSet\fP &right)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBDenseStaticIntSet\fP &left, const \fBDenseStaticIntSet\fP &right)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBDenseStaticIntSet\fP &left, const \fBDenseStaticIntSet\fP &right)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
