.TH "deprecated" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBMember \fBwebsocketpp::connection< config >::buffered_amount\fP () const\fP" 1c
use \fCget_buffered_amount\fP instead  
.IP "\fBMember \fBwebsocketpp::transport::asio::connection< config >::set_tcp_init_handler\fP (tcp_init_handler h)\fP" 1c
Use set_tcp_pre_init_handler instead 
.IP "\fBMember \fBwebsocketpp::transport::asio::endpoint< config >::set_tcp_init_handler\fP (tcp_init_handler h)\fP" 1c
Use set_tcp_pre_init_handler instead 
.IP "\fBMember \fBwebsocketpp::transport::iostream::connection< config >::readsome\fP (char const *buf, size_t len)\fP" 1c
DEPRECATED in favor of \fBread_some()\fP 
.PP

