.TH "DerefPropType< To >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DerefPropType< To >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class Up > \fBDerefPropType\fP (Up const &val)"
.br
.ti -1c
.RI "To & \fBoperator*\fP ()"
.br
.ti -1c
.RI "To const  & \fBoperator*\fP () const"
.br
.ti -1c
.RI "To volatile & \fBoperator*\fP () volatile"
.br
.ti -1c
.RI "To const volatile & \fBoperator*\fP () const volatile"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "To \fBobject\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
