.TH "DerivedFromType< Base >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DerivedFromType< Base >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class Tp > \fBDerivedFromType\fP (Tp const &t)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
