.TH "Derived< T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Derived< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBase\fP, \fBBase\fP, tuple< T >, \fBBase\fP, \fBBase\fP, \fBBase\fP, \fBBase\fP, and \fBBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class U > \fBoperator std::tuple< U >\fP () &&"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
