.TH "detail::TakeNArgs< N, Args >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::TakeNArgs< N, Args >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdetail::TakeNImp< N==0, N, ArgumentListID<>, Args\&.\&.\&. >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
