.TH "detail::TypeID" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::TypeID
.SH SYNOPSIS
.br
.PP
.SS "Friends"

.in +1c
.ti -1c
.RI "template<class T > class \fBTypeInfo\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBTypeID\fP const &LHS, \fBTypeID\fP const &RHS)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBTypeID\fP const &LHS, \fBTypeID\fP const &RHS)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
