.TH "detail::TakeNImp< false, N, ArgumentListID< A1... >, F, R... >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::TakeNImp< false, N, ArgumentListID< A1... >, F, R... >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdetail::TakeNImp< N\-1==0, N \- 1, ArgumentListID< A1\&.\&.\&., F >, R\&.\&.\&. >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
