.TH "dice" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dice
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::contract\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdice\fP (account_name self)"
.br
.ti -1c
.RI "void \fBofferbet\fP (const \fBasset\fP &bet, const account_name player, const \fBchecksum256\fP &commitment)"
.br
.ti -1c
.RI "void \fBcanceloffer\fP (const \fBchecksum256\fP &commitment)"
.br
.ti -1c
.RI "void \fBreveal\fP (const \fBchecksum256\fP &commitment, const \fBchecksum256\fP &\fBsource\fP)"
.br
.ti -1c
.RI "void \fBclaimexpired\fP (const uint64_t gameid)"
.br
.ti -1c
.RI "void \fBdeposit\fP (const account_name from, const \fBasset\fP &a)"
.br
.ti -1c
.RI "void \fBwithdraw\fP (const account_name to, const \fBasset\fP &a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const uint32_t \fBFIVE_MINUTES\fP = 5*60"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
