.TH "dice_tester" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dice_tester
.SH SYNOPSIS
.br
.PP
.PP
Inherits TESTER\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const \fBcontracts::table_id_object\fP * \fBfind_table\fP (\fBname\fP code, \fBname\fP scope, \fBname\fP table)"
.br
.ti -1c
.RI "template<typename IndexType , typename Scope > const auto & \fBget_index\fP ()"
.br
.ti -1c
.RI "void \fBoffer_bet\fP (account_name \fBaccount\fP, \fBasset\fP amount, const \fBchecksum_type\fP &commitment)"
.br
.ti -1c
.RI "void \fBcancel_offer\fP (account_name \fBaccount\fP, const \fBchecksum_type\fP &commitment)"
.br
.ti -1c
.RI "void \fBdeposit\fP (account_name \fBaccount\fP, \fBasset\fP amount)"
.br
.ti -1c
.RI "void \fBwithdraw\fP (account_name \fBaccount\fP, \fBasset\fP amount)"
.br
.ti -1c
.RI "void \fBreveal\fP (account_name \fBaccount\fP, const \fBchecksum_type\fP &commitment, const \fBchecksum_type\fP &\fBsource\fP)"
.br
.ti -1c
.RI "bool \fBdice_account\fP (account_name \fBaccount\fP, account_t &acnt)"
.br
.ti -1c
.RI "bool \fBdice_game\fP (uint64_t game_id, game_t &game)"
.br
.ti -1c
.RI "uint32_t \fBopen_games\fP (account_name \fBaccount\fP)"
.br
.ti -1c
.RI "\fBasset\fP \fBgame_bet\fP (uint64_t game_id)"
.br
.ti -1c
.RI "uint32_t \fBopen_offers\fP (account_name \fBaccount\fP)"
.br
.ti -1c
.RI "\fBasset\fP \fBbalance_of\fP (account_name \fBaccount\fP)"
.br
.ti -1c
.RI "\fBchecksum_type\fP \fBcommitment_for\fP (const char *secret)"
.br
.ti -1c
.RI "\fBchecksum_type\fP \fBcommitment_for\fP (const \fBchecksum_type\fP &secret)"
.br
.ti -1c
.RI "void \fBadd_dice_authority\fP (account_name \fBaccount\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
