.TH "contracts/dice/dice.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/dice/dice.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <utility>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <aaciolib/crypto\&.h>\fP
.br
\fC#include <aaciolib/types\&.hpp>\fP
.br
\fC#include <aaciolib/token\&.hpp>\fP
.br
\fC#include <aaciolib/print\&.hpp>\fP
.br
\fC#include <aaciolib/action\&.hpp>\fP
.br
\fC#include <aaciolib/multi_index\&.hpp>\fP
.br
\fC#include <aaciolib/contract\&.hpp>\fP
.br
\fC#include <aacio\&.system/aacio\&.system\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdice\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBaac_currency\fP = \fBaaciosystem::contract\fP< \fBN\fP(aacio)>::currency"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
