.TH "DPair< T, U >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DPair< T, U >
.SH SYNOPSIS
.br
.PP
.PP
Inherits pair< T, U >, and pair< T, U >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBBase\fP = std::pair< \fBT\fP, \fBU\fP >"
.br
.ti -1c
.RI "using \fBBase\fP = std::pair< \fBT\fP, \fBU\fP >"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
