.TH "dummy_char_traits" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dummy_char_traits
.SH SYNOPSIS
.br
.PP
.PP
Inherits char_traits< char >, char_traits< char >, char_traits< char >, char_traits< char >, char_traits< char >, and char_traits< char >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
