.TH "dummy_action" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dummy_action
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static uint64_t \fBget_name\fP ()"
.br
.ti -1c
.RI "static uint64_t \fBget_account\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBa\fP"
.br
.ti -1c
.RI "uint64_t \fBb\fP"
.br
.ti -1c
.RI "int32_t \fBc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
