.TH "DummyIt< ValueType, Reference >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DummyIt< ValueType, Reference >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::forward_iterator_tag \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef ValueType \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef std::ptrdiff_t \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef ValueType * \fBpointer\fP"
.br
.ti -1c
.RI "typedef Reference \fBreference\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
