.TH "E< T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBE1\fP, and \fBE2\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrebind\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::scoped_allocator_adaptor< \fBA1\fP< \fBE\fP > > \fBallocator_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBC\fP \fBoperator &\fP () const"
.br
.ti -1c
.RI "\fBE\fP (int i, int j, const allocator_type &a)"
.br
.ti -1c
.RI "template<class > void \fBrebind\fP ()"
.br
.ti -1c
.RI "\fBE\fP & \fBoperator=\fP (int)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBconstructed\fP = false"
.br
.ti -1c
.RI "static int \fBdifference_type\fP"
.br
.ti -1c
.RI "static int \fBelement_type\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
