.TH "EvallingModuleInstance" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EvallingModuleInstance
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::ModuleInstanceBase< EvallingGlobalManager, EvallingModuleInstance >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBSTACK_START\fP = 0x40000000, \fBSTACK_SIZE\fP = 32 * 1024 * 1024 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEvallingModuleInstance\fP (\fBModule\fP &wasm, ExternalInterface *externalInterface)"
.br
.ti -1c
.RI "void \fBsetupEnvironment\fP ()"
.br
.ti -1c
.RI "void \fBflattenMemory\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::vector\fP< char > \fBstack\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
