.TH "EvallingGlobalManager" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EvallingGlobalManager
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBIterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddDangerous\fP (\fBName\fP name)"
.br
.ti -1c
.RI "void \fBseal\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBEvallingGlobalManager\fP &\fBother\fP)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBEvallingGlobalManager\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBLiteral\fP & \fBoperator[]\fP (\fBName\fP name)"
.br
.ti -1c
.RI "\fBIterator\fP \fBfind\fP (\fBName\fP name)"
.br
.ti -1c
.RI "\fBIterator\fP \fBend\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
