.TH "EvallingGlobalManager::Iterator" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EvallingGlobalManager::Iterator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP (\fBName\fP name, \fBLiteral\fP value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBIterator\fP &\fBother\fP)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBIterator\fP &\fBother\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBName\fP \fBfirst\fP"
.br
.ti -1c
.RI "\fBLiteral\fP \fBsecond\fP"
.br
.ti -1c
.RI "bool \fBfound\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
