.TH "exchange_state" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exchange_state
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtransfer\fP (account_name user, \fBasset\fP q)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "token_type \fBsupply\fP"
.br
.ti -1c
.RI "symbol_type \fBsymbol\fP = exchange_symbol"
.br
.ti -1c
.RI "\fBconnector\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBconnector\fP \fBquote\fP"
.br
.ti -1c
.RI "\fBmap\fP< \fBbalance_key\fP, token_type > \fBoutput\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBmargin\fP > \fBmargins\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
