.TH "exchange_tester" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exchange_tester
.SH SYNOPSIS
.br
.PP
.PP
Inherits TESTER\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBpush_action\fP (account_name \fBcontract\fP, const account_name &signer, const action_name &\fBname\fP, const \fBvariant_object\fP &data)"
.br
.ti -1c
.RI "\fBasset\fP \fBget_balance\fP (const account_name &\fBaccount\fP) const"
.br
.ti -1c
.RI "\fBexchange_state\fP \fBget_market_state\fP (account_name \fBexchange\fP, \fBsymbol\fP sym)"
.br
.ti -1c
.RI "\fBextended_asset\fP \fBget_exchange_balance\fP (account_name \fBexchange\fP, account_name \fBcurrency\fP, \fBsymbol\fP sym, account_name owner)"
.br
.ti -1c
.RI "double \fBget_lent_shares\fP (account_name \fBexchange\fP, \fBsymbol\fP market, account_name owner, bool \fBbase\fP)"
.br
.ti -1c
.RI "void \fBdeploy_currency\fP (account_name ac)"
.br
.ti -1c
.RI "void \fBdeploy_exchange\fP (account_name ac)"
.br
.ti -1c
.RI "void \fBcreate_currency\fP (\fBname\fP \fBcontract\fP, \fBname\fP signer, \fBasset\fP maxsupply)"
.br
.ti -1c
.RI "void \fBissue\fP (\fBname\fP \fBcontract\fP, \fBname\fP signer, \fBname\fP to, \fBasset\fP amount)"
.br
.ti -1c
.RI "auto \fBtrade\fP (\fBname\fP ex_contract, \fBname\fP signer, \fBsymbol\fP market, \fBextended_asset\fP sell, \fBextended_asset\fP min_receive)"
.br
.ti -1c
.RI "auto \fBdeposit\fP (\fBname\fP exchangecontract, \fBname\fP signer, \fBextended_asset\fP amount)"
.br
.ti -1c
.RI "auto \fBlend\fP (\fBname\fP \fBcontract\fP, \fBname\fP signer, \fBextended_asset\fP quantity, \fBsymbol\fP market)"
.br
.ti -1c
.RI "auto \fBunlend\fP (\fBname\fP \fBcontract\fP, \fBname\fP signer, double interest_shares, \fBextended_symbol\fP interest_symbol, \fBsymbol\fP market)"
.br
.ti -1c
.RI "auto \fBcreate_exchange\fP (\fBname\fP \fBcontract\fP, \fBname\fP signer, \fBextended_asset\fP base_deposit, \fBextended_asset\fP quote_deposit, \fBasset\fP exchange_supply)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBabi_serializer\fP \fBabi_ser\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
