.TH "expected< T, Error >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
expected< T, Error >
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBData\fP"
.br
.ti -1c
.RI "struct \fBDataPtr\fP"
.br
.ti -1c
.RI "struct \fBpromise_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexpected\fP (\fBT\fP val)"
.br
.ti -1c
.RI "\fBexpected\fP (struct \fBerror\fP, Error \fBerror\fP)"
.br
.ti -1c
.RI "\fBexpected\fP (\fBDataPtr\fP &p)"
.br
.ti -1c
.RI "bool \fBawait_ready\fP ()"
.br
.ti -1c
.RI "\fBT\fP \fBawait_resume\fP ()"
.br
.ti -1c
.RI "void \fBawait_suspend\fP (coroutine_handle< \fBpromise_type\fP > h)"
.br
.ti -1c
.RI "\fBT\fP const  & \fBvalue\fP ()"
.br
.ti -1c
.RI "Error const  & \fBerror\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBData\fP \fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
