.TH "tests/common/expect.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/common/expect.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaacio::test::expector< Pred, Eval, T >\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_NUM_ARGS\fP(\fBA\fP,  \fBB\fP,  \fBC\fP,  \fBN\fP, \&.\&.\&.)   \fBN\fP"
.br
.ti -1c
.RI "#define \fBNUM_ARGS\fP(\&.\&.\&.)   _NUM_ARGS(__VA_ARGS__, 3, 2, 1)"
.br
.ti -1c
.RI "#define \fBEXPECT\fP(\&.\&.\&.)   EXPECT_(NUM_ARGS(__VA_ARGS__),__VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBEXPECT_\fP(\fBN\fP, \&.\&.\&.)   EXPECT__(\fBN\fP, __VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBEXPECT__\fP(\fBN\fP, \&.\&.\&.)   EXPECT_##\fBN\fP(__VA_ARGS__)"
.br
.ti -1c
.RI "#define \fBEXPECT_3\fP(\fBP\fP,  \fBE\fP,  \fBT\fP)   aacio::test::expect<\fBP\fP>(\fBE\fP,\fBT\fP,'EXPECT<' #P '>(' #\fBE\fP ',' #\fBT\fP ')')"
.br
.ti -1c
.RI "#define \fBEXPECT_2\fP(\fBE\fP,  \fBT\fP)   aacio::test::expect(\fBE\fP,\fBT\fP,'EXPECT(' #E ',' #\fBT\fP ')')"
.br
.ti -1c
.RI "#define \fBEXPECT_1\fP(\fBE\fP)   aacio::test::expect(\fBE\fP,'EXPECT(' #E ')')"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Pred , typename Eval , typename T > auto \fBaacio::test::expect\fP (Eval &&eval, \fBT\fP \fBexpected\fP, char const *const msg)"
.br
.ti -1c
.RI "template<typename Eval , typename T > auto \fBaacio::test::expect\fP (Eval &&eval, \fBT\fP \fBexpected\fP, char const *const msg)"
.br
.ti -1c
.RI "template<typename Eval > auto \fBaacio::test::expect\fP (Eval &&eval, char const *const msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
