.TH "ExplicitBool" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExplicitBool
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExplicitBool\fP (\fBExplicitBool\fP const &)=default"
.br
.ti -1c
.RI "\fBExplicitBool\fP (\fBExplicitBool\fP &&)=default"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "struct \fBMoveOnlyCallable< ExplicitBool >\fP"
.br
.ti -1c
.RI "struct \fBCopyCallable< ExplicitBool >\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
