.TH "ExplicitDerived< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExplicitDerived< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits tuple< T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class U > \fBoperator std::tuple< U >\fP () &&"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
