.TH "fc::actor< Interface >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::actor< Interface >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <actor\&.hpp>\fP
.PP
Inherits \fBfc::api< Interface, detail::actor_member >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename InterfaceType > \fBactor\fP (InterfaceType *p, fc::thread *t=&fc::thread::current())"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename Interface>
.br
class fc::actor< Interface >"
Posts all method calls to another thread and returns a future\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
