.TH "fc::aligned< S, T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::aligned< S, T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoperator char *\fP ()"
.br
.ti -1c
.RI "\fBoperator const char *\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBT\fP \fB_align\fP"
.br
.ti -1c
.RI "   char \fB_data\fP [\fBS\fP]"
.br
.ti -1c
.RI "} \fB_store\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
