.TH "fc::appender_factory" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::appender_factory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::retainable\fP\&.
.PP
Inherited by \fBfc::detail::appender_factory_impl< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBfc::shared_ptr\fP< \fBappender_factory\fP > \fBptr\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBfc::shared_ptr\fP< \fBappender\fP > \fBcreate\fP (const \fBvariant\fP &args)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
