.TH "fc::aes_decoder" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::aes_decoder
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBimpl\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (const \fBfc::sha256\fP &key, const \fBfc::uint128\fP &init_value)"
.br
.ti -1c
.RI "uint32_t \fBdecode\fP (const char *ciphertxt, uint32_t len, char *plaintext)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
