.TH "fc::api_connection" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::api_connection
.SH SYNOPSIS
.br
.PP
.PP
Inherits enable_shared_from_this< fc::api_connection >\&.
.PP
Inherited by \fBfc::local_api_connection\fP, \fBfc::rpc::cli\fP, \fBfc::rpc::http_api_connection\fP, and \fBfc::rpc::websocket_api_connection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBapi\fP< \fBT\fP > \fBget_remote_api\fP (api_id_type api_id=0)"
.br
.ti -1c
.RI "virtual \fBvariant\fP \fBsend_call\fP (api_id_type api_id, string method_name, \fBvariants\fP args=\fBvariants\fP())=0"
.br
.ti -1c
.RI "virtual \fBvariant\fP \fBsend_callback\fP (uint64_t callback_id, \fBvariants\fP args=\fBvariants\fP())=0"
.br
.ti -1c
.RI "virtual void \fBsend_notice\fP (uint64_t callback_id, \fBvariants\fP args=\fBvariants\fP())=0"
.br
.ti -1c
.RI "\fBvariant\fP \fBreceive_call\fP (api_id_type api_id, const string &method_name, const \fBvariants\fP &args=\fBvariants\fP()) const"
.br
.ti -1c
.RI "\fBvariant\fP \fBreceive_callback\fP (uint64_t callback_id, const \fBvariants\fP &args=\fBvariants\fP()) const"
.br
.ti -1c
.RI "void \fBreceive_notice\fP (uint64_t callback_id, const \fBvariants\fP &args=\fBvariants\fP()) const"
.br
.ti -1c
.RI "template<typename Interface > api_id_type \fBregister_api\fP (const Interface &a)"
.br
.ti -1c
.RI "template<typename Signature > uint64_t \fBregister_callback\fP (const std::function< Signature > &cb)"
.br
.ti -1c
.RI "\fBstd::vector\fP< std::string > \fBget_method_names\fP (api_id_type local_api_id=0) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "fc::signal< void()> \fBclosed\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBvariant\fP fc::api_connection::send_call (api_id_type api_id, string method_name, \fBvariants\fP args = \fC\fBvariants\fP()\fP)\fC [pure virtual]\fP"
makes calls to the remote server 
.PP
Implemented in \fBfc::local_api_connection\fP, \fBfc::rpc::cli\fP, \fBfc::rpc::http_api_connection\fP, and \fBfc::rpc::websocket_api_connection\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
