.TH "fc::appender_config" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::appender_config
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBappender_config\fP (const string &name='', const string &type='', \fBvariant\fP args=\fBvariant\fP())"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "\fBvariant\fP \fBargs\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
