.TH "fc::aac_extension_from_variant_visitor< T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::aac_extension_from_variant_visitor< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaac_extension_from_variant_visitor\fP (const \fBvariant_object\fP &v, \fBT\fP &val)"
.br
.ti -1c
.RI "template<typename Member , class Class , Member Class::* member> void \fBoperator()\fP (const char *name) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBvariant_object\fP & \fBvo\fP"
.br
.ti -1c
.RI "\fBT\fP & \fBvalue\fP"
.br
.ti -1c
.RI "uint32_t \fBcount_left\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
