.TH "fc::array< unsigned char, N >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::array< unsigned char, N >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <array\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBT\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBT\fP * \fBbegin\fP ()"
.br
.ti -1c
.RI "const \fBT\fP * \fBbegin\fP () const"
.br
.ti -1c
.RI "const \fBT\fP * \fBend\fP () const"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBT\fP & \fBat\fP (size_t pos)"
.br
.ti -1c
.RI "const \fBT\fP & \fBat\fP (size_t pos) const"
.br
.in -1c
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP \fBdata\fP [\fBN\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<size_t N>
.br
class fc::array< unsigned char, N >"
provided for default 0 init 
.SH "Member Function Documentation"
.PP 
.SS "template<size_t N> \fBT\fP& \fBfc::array\fP< unsigned char, \fBN\fP >::at (size_t pos)\fC [inline]\fP"
Checked indexing (when in debug build) that also simplifies dereferencing when you have an array<T,N>*\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
