.TH "fc::buffered_istream" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::buffered_istream \- Reads data from an unbuffered stream and enables peek functionality\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <buffered_iostream\&.hpp>\fP
.PP
Inherits istream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbuffered_istream\fP (istream_ptr is)"
.br
.ti -1c
.RI "\fBbuffered_istream\fP (\fBbuffered_istream\fP &&o)"
.br
.ti -1c
.RI "\fBbuffered_istream\fP & \fBoperator=\fP (\fBbuffered_istream\fP &&i)"
.br
.ti -1c
.RI "virtual std::size_t \fBreadsome\fP (char *buf, std::size_t len)"
.br
.ti -1c
.RI "virtual size_t \fBreadsome\fP (const std::shared_ptr< char > &buf, size_t len, size_t offset)"
.br
.ti -1c
.RI "virtual char \fBpeek\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reads data from an unbuffered stream and enables peek functionality\&. 
.SH "Member Function Documentation"
.PP 
.SS "char fc::buffered_istream::peek () const\fC [virtual]\fP"
This method may block until at least 1 character is available\&. 
.SS "virtual std::size_t fc::buffered_istream::readsome (char * buf, std::size_t len)\fC [virtual]\fP"
read at least 1 byte or throw, if no data is available this method should block cooperatively until data is available or fc::eof_exception is thrown\&.
.PP
\fBPrecondition:\fP
.RS 4
len > 0 
.PP
buf != nullptr 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIfc::eof\fP if at least 1 byte cannot be read 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
