.TH "fc::bloom_parameters" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::bloom_parameters
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBoptimal_parameters_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator!\fP ()"
.br
.ti -1c
.RI "virtual bool \fBcompute_optimal_parameters\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long long int \fBminimum_size\fP"
.br
.ti -1c
.RI "unsigned long long int \fBmaximum_size\fP"
.br
.ti -1c
.RI "unsigned int \fBminimum_number_of_hashes\fP"
.br
.ti -1c
.RI "unsigned int \fBmaximum_number_of_hashes\fP"
.br
.ti -1c
.RI "unsigned long long int \fBprojected_element_count\fP"
.br
.ti -1c
.RI "double \fBfalse_positive_probability\fP"
.br
.ti -1c
.RI "unsigned long long int \fBrandom_seed\fP"
.br
.ti -1c
.RI "\fBoptimal_parameters_t\fP \fBoptimal_parameters\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
