.TH "fc::binary_api_connection" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::binary_api_connection
.SH SYNOPSIS
.br
.PP
.PP
Inherits enable_shared_from_this< fc::binary_api_connection >\&.
.PP
Inherited by \fBfc::local_binary_api_connection\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBstd::vector\fP< char > \fBparams_type\fP"
.br
.ti -1c
.RI "typedef \fBstd::vector\fP< char > \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBapi\fP< \fBT\fP > \fBget_remote_api\fP (api_id_type api_id=0)"
.br
.ti -1c
.RI "virtual \fBresult_type\fP \fBsend_call\fP (api_id_type api_id, string method_name, \fBparams_type\fP args=\fBparams_type\fP())=0"
.br
.ti -1c
.RI "virtual \fBresult_type\fP \fBsend_callback\fP (uint64_t callback_id, \fBparams_type\fP args=\fBparams_type\fP())=0"
.br
.ti -1c
.RI "virtual void \fBsend_notice\fP (uint64_t callback_id, \fBparams_type\fP args=\fBparams_type\fP())=0"
.br
.ti -1c
.RI "\fBresult_type\fP \fBreceive_call\fP (api_id_type api_id, const string &method_name, const \fBparams_type\fP &args=\fBparams_type\fP()) const"
.br
.ti -1c
.RI "\fBresult_type\fP \fBreceive_callback\fP (uint64_t callback_id, const \fBparams_type\fP &args=\fBparams_type\fP()) const"
.br
.ti -1c
.RI "void \fBreceive_notice\fP (uint64_t callback_id, const \fBparams_type\fP &args=\fBparams_type\fP()) const"
.br
.ti -1c
.RI "template<typename Interface > api_id_type \fBregister_api\fP (const Interface &a)"
.br
.ti -1c
.RI "template<typename Signature > uint64_t \fBregister_callback\fP (const std::function< Signature > &cb)"
.br
.ti -1c
.RI "\fBstd::vector\fP< std::string > \fBget_method_names\fP (api_id_type local_api_id=0) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "fc::signal< void()> \fBclosed\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBresult_type\fP fc::binary_api_connection::send_call (api_id_type api_id, string method_name, \fBparams_type\fP args = \fC\fBparams_type\fP()\fP)\fC [pure virtual]\fP"
makes calls to the remote server 
.PP
Implemented in \fBfc::local_binary_api_connection\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
