.TH "fc::bloom_parameters::optimal_parameters_t" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::bloom_parameters::optimal_parameters_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBnumber_of_hashes\fP"
.br
.ti -1c
.RI "unsigned long long int \fBtable_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
