.TH "fc::buffered_ostream" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::buffered_ostream
.SH SYNOPSIS
.br
.PP
.PP
Inherits ostream\&.
.PP
Inherited by \fBaacio::utilities::padding_ostream< BlockSize, PaddingChar >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbuffered_ostream\fP (ostream_ptr o, size_t bufsize=4096)"
.br
.ti -1c
.RI "\fBbuffered_ostream\fP (\fBbuffered_ostream\fP &&m)"
.br
.ti -1c
.RI "\fBbuffered_ostream\fP & \fBoperator=\fP (\fBbuffered_ostream\fP &&m)"
.br
.ti -1c
.RI "virtual size_t \fBwritesome\fP (const char *buf, size_t len)"
.br
.ti -1c
.RI "virtual size_t \fBwritesome\fP (const std::shared_ptr< const char > &buf, size_t len, size_t offset)"
.br
.ti -1c
.RI "virtual void \fBclose\fP ()"
.br
.ti -1c
.RI "virtual void \fBflush\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "size_t fc::buffered_ostream::writesome (const char * buf, size_t len)\fC [virtual]\fP"
This method will return immediately unless the buffer is full, in which case it will flush which may block\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
