.TH "fc::console_appender::level_color" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::console_appender::level_color
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlevel_color\fP (\fBlog_level\fP l=log_level::all, color::type c=color::console_default)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlog_level\fP \fBlevel\fP"
.br
.ti -1c
.RI "console_appender::color::type \fBcolor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
