.TH "fc::crypto::recovery_visitor" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::crypto::recovery_visitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::visitor< public_key::storage_type >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrecovery_visitor\fP (const \fBsha256\fP &digest, bool check_canonical)"
.br
.ti -1c
.RI "template<typename SignatureType > \fBpublic_key::storage_type\fP \fBoperator()\fP (const SignatureType &s) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBsha256\fP & \fB_digest\fP"
.br
.ti -1c
.RI "bool \fB_check_canonical\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
