.TH "fc::console_appender::config" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::console_appender::config
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "fc::string \fBformat\fP"
.br
.ti -1c
.RI "console_appender::stream::type \fBstream\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBlevel_color\fP > \fBlevel_colors\fP"
.br
.ti -1c
.RI "bool \fBflush\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
