.TH "fc::crypto::base58_str_parser< fc::static_variant< Ts... >, Prefixes >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::crypto::base58_str_parser< fc::static_variant< Ts... >, Prefixes >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBfc::static_variant\fP< Ts\&.\&.\&. > \fBapply\fP (const std::string &base58str)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<const char *const * Prefixes, typename \&.\&.\&. Ts>
.br
struct fc::crypto::base58_str_parser< fc::static_variant< Ts\&.\&.\&. >, Prefixes >"
Destructure a variant and call the parse_base58str on it 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fITs\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbase58str\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
