.TH "fc::crypto::shim< Data >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::crypto::shim< Data >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBdata_type\fP = Data"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshim\fP (data_type &&data)"
.br
.ti -1c
.RI "\fBshim\fP (const data_type &data)"
.br
.ti -1c
.RI "const data_type & \fBserialize\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "data_type \fB_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
