.TH "fc::crypto::private_key" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::crypto::private_key
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBstorage_type\fP = \fBstatic_variant\fP< \fBecc::private_key_shim\fP, \fBr1::private_key_shim\fP >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprivate_key\fP (\fBprivate_key\fP &&)=default"
.br
.ti -1c
.RI "\fBprivate_key\fP (const \fBprivate_key\fP &)=default"
.br
.ti -1c
.RI "\fBprivate_key\fP & \fBoperator=\fP (const \fBprivate_key\fP &)=default"
.br
.ti -1c
.RI "\fBpublic_key\fP \fBget_public_key\fP () const"
.br
.ti -1c
.RI "\fBsignature\fP \fBsign\fP (const \fBsha256\fP &digest, bool require_canonical=true) const"
.br
.ti -1c
.RI "\fBsha512\fP \fBgenerate_shared_secret\fP (const \fBpublic_key\fP &pub) const"
.br
.ti -1c
.RI "\fBprivate_key\fP (const string &base58str)"
.br
.ti -1c
.RI "\fBoperator string\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename KeyType  = ecc::private_key_shim> static \fBprivate_key\fP \fBgenerate\fP ()"
.br
.ti -1c
.RI "template<typename KeyType  = ecc::private_key_shim> static \fBprivate_key\fP \fBregenerate\fP (const typename KeyType::data_type &data)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "struct \fBreflector< private_key >\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBprivate_key\fP &\fBp1\fP, const \fBprivate_key\fP &\fBp2\fP)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBprivate_key\fP &\fBp1\fP, const \fBprivate_key\fP &\fBp2\fP)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBprivate_key\fP &\fBp1\fP, const \fBprivate_key\fP &\fBp2\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
