.TH "fc::crypto::generate_shared_secret_visitor" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::crypto::generate_shared_secret_visitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::visitor< sha512 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgenerate_shared_secret_visitor\fP (const \fBpublic_key::storage_type\fP &pub_storage)"
.br
.ti -1c
.RI "template<typename KeyType > \fBsha512\fP \fBoperator()\fP (const KeyType &key) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBpublic_key::storage_type\fP & \fB_pub_storage\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
