.TH "fc::crypto::signature" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::crypto::signature
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBstorage_type\fP = \fBstatic_variant\fP< \fBecc::signature_shim\fP, \fBr1::signature_shim\fP >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsignature\fP (\fBsignature\fP &&)=default"
.br
.ti -1c
.RI "\fBsignature\fP (const \fBsignature\fP &)=default"
.br
.ti -1c
.RI "\fBsignature\fP & \fBoperator=\fP (const \fBsignature\fP &)=default"
.br
.ti -1c
.RI "\fBsignature\fP (const string &base58str)"
.br
.ti -1c
.RI "\fBoperator string\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "struct \fBreflector< signature >\fP"
.br
.ti -1c
.RI "class \fBprivate_key\fP"
.br
.ti -1c
.RI "class \fBpublic_key\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBsignature\fP &\fBp1\fP, const \fBsignature\fP &\fBp2\fP)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBsignature\fP &\fBp1\fP, const \fBsignature\fP &\fBp2\fP)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBsignature\fP &\fBp1\fP, const \fBsignature\fP &\fBp2\fP)"
.br
.ti -1c
.RI "std::size_t \fBhash_value\fP (const \fBsignature\fP &b)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
