.TH "fc::detail::extract_op< A, U >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::detail::extract_op< A, U >
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBA\fP * \fBa\fP"
.br
.ti -1c
.RI "\fBU\fP * \fBu\fP"
.br
.ti -1c
.RI "decltype(*a >> *u) typedef \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
