.TH "fc::detail::rate_limited_tcp_read_operation" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::detail::rate_limited_tcp_read_operation
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::detail::rate_limited_operation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrate_limited_tcp_read_operation\fP (boost::asio::ip::tcp::socket &socket, char *buffer, size_t length, size_t offset, promise< size_t >::ptr completion_promise)"
.br
.ti -1c
.RI "\fBrate_limited_tcp_read_operation\fP (boost::asio::ip::tcp::socket &socket, const std::shared_ptr< char > &buffer, size_t length, size_t offset, promise< size_t >::ptr completion_promise)"
.br
.ti -1c
.RI "virtual void \fBperform_operation\fP () override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::asio::ip::tcp::socket & \fBsocket\fP"
.br
.ti -1c
.RI "char * \fBraw_buffer\fP"
.br
.ti -1c
.RI "std::shared_ptr< char > \fBshared_buffer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
