.TH "fc::detail::path_wrapper" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::detail::path_wrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpath_wrapper\fP (\fBpath\fP p)"
.br
.ti -1c
.RI "const \fBpath\fP * \fBoperator\->\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
