.TH "fc::detail::appender_factory_impl< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::detail::appender_factory_impl< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::appender_factory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBfc::shared_ptr\fP< \fBappender\fP > \fBcreate\fP (const \fBvariant\fP &args)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
