.TH "fc::detail::rate_limited_operation" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::detail::rate_limited_operation
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBfc::detail::rate_limited_tcp_read_operation\fP, and \fBfc::detail::rate_limited_tcp_write_operation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrate_limited_operation\fP (size_t length, size_t offset, promise< size_t >::ptr &&completion_promise)"
.br
.ti -1c
.RI "virtual void \fBperform_operation\fP ()=0"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBlength\fP"
.br
.ti -1c
.RI "size_t \fBoffset\fP"
.br
.ti -1c
.RI "size_t \fBpermitted_length\fP"
.br
.ti -1c
.RI "promise< size_t >::ptr \fBcompletion_promise\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
