.TH "fc::detail::callback_functor< void(Args...)>" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::detail::callback_functor< void(Args...)>
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void \fBresult_type\fP"
.br
.ti -1c
.RI "typedef void \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcallback_functor\fP (std::weak_ptr< \fBfc::api_connection\fP > con, uint64_t id)"
.br
.ti -1c
.RI "void \fBoperator()\fP (Args\&.\&.\&. args) const"
.br
.ti -1c
.RI "\fBcallback_functor\fP (std::weak_ptr< \fBfc::binary_api_connection\fP > con, uint64_t id)"
.br
.ti -1c
.RI "void \fBoperator()\fP (Args\&.\&.\&. args) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
