.TH "fc::detail::log_context_impl" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::detail::log_context_impl
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlog_level\fP \fBlevel\fP"
.br
.ti -1c
.RI "string \fBfile\fP"
.br
.ti -1c
.RI "uint64_t \fBline\fP"
.br
.ti -1c
.RI "string \fBmethod\fP"
.br
.ti -1c
.RI "string \fBthread_name\fP"
.br
.ti -1c
.RI "string \fBtask_name\fP"
.br
.ti -1c
.RI "string \fBhostname\fP"
.br
.ti -1c
.RI "string \fBcontext\fP"
.br
.ti -1c
.RI "\fBtime_point\fP \fBtimestamp\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
