.TH "fc::detail::log_message_impl" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::detail::log_message_impl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlog_message_impl\fP (\fBlog_context\fP &&ctx)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlog_context\fP \fBcontext\fP"
.br
.ti -1c
.RI "string \fBformat\fP"
.br
.ti -1c
.RI "\fBvariant_object\fP \fBargs\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
