.TH "fc::detail::actor_vtable_visitor< ThisPtr >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::detail::actor_vtable_visitor< ThisPtr >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename U > \fBactor_vtable_visitor\fP (fc::thread *t, \fBU\fP &&u)"
.br
.ti -1c
.RI "template<typename Function , typename MemberPtr > void \fBoperator()\fP (const char *name, Function &memb, MemberPtr m) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "fc::thread * \fB_thread\fP"
.br
.ti -1c
.RI "ThisPtr \fB_this\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
