.TH "fc::detail::url_impl" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::detail::url_impl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBparse\fP (const fc::string &s)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fB_proto\fP"
.br
.ti -1c
.RI "\fBostring\fP \fB_host\fP"
.br
.ti -1c
.RI "\fBostring\fP \fB_user\fP"
.br
.ti -1c
.RI "\fBostring\fP \fB_pass\fP"
.br
.ti -1c
.RI "\fBopath\fP \fB_path\fP"
.br
.ti -1c
.RI "\fBovariant_object\fP \fB_args\fP"
.br
.ti -1c
.RI "\fBfc::optional\fP< uint16_t > \fB_port\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
