.TH "fc::detail::mmap_struct_base" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::detail::mmap_struct_base
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mmap_struct\&.hpp>\fP
.PP
Inherited by \fBfc::mmap_struct< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBflush\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBopen\fP (const \fBfc::path\fP &file, size_t s, bool create)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBfc::file_mapping\fP > \fB_file_mapping\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBfc::mapped_region\fP > \fB_mapped_region\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBase\fP class used to hide common implementation details\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
