.TH "fc::detail::buffered_istream_impl" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::detail::buffered_istream_impl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbuffered_istream_impl\fP (istream_ptr is)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "istream_ptr \fB_istr\fP"
.br
.ti -1c
.RI "boost::asio::streambuf \fB_rdbuf\fP"
.br
.ti -1c
.RI "std::shared_ptr< char > \fB_shared_read_buffer\fP"
.br
.ti -1c
.RI "bool \fB_shared_read_buffer_in_use\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
