.TH "fc::detail::callback_functor< Signature >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::detail::callback_functor< Signature >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::function< Signature >::result_type \fBresult_type\fP"
.br
.ti -1c
.RI "typedef std::function< Signature >::result_type \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcallback_functor\fP (std::weak_ptr< \fBfc::api_connection\fP > con, uint64_t id)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> result_type \fBoperator()\fP (Args\&.\&.\&. args) const"
.br
.ti -1c
.RI "\fBcallback_functor\fP (std::weak_ptr< \fBfc::binary_api_connection\fP > con, uint64_t id)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> result_type \fBoperator()\fP (Args\&.\&.\&. args) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename Signature > template<typename\&.\&.\&. Args> \fBcallback_functor\fP< Signature >::result_type \fBfc::detail::callback_functor\fP< Signature >::operator() (Args\&.\&.\&. args) const"
TODO------------->>> pack args\&.\&.\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
