.TH "fc::directory_iterator" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::directory_iterator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdirectory_iterator\fP (const \fBfc::path\fP &p)"
.br
.ti -1c
.RI "\fBfc::path\fP \fBoperator*\fP () const"
.br
.ti -1c
.RI "\fBdetail::path_wrapper\fP \fBoperator\->\fP () const"
.br
.ti -1c
.RI "\fBdirectory_iterator\fP & \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBdirectory_iterator\fP & \fBoperator++\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBdirectory_iterator\fP &, const \fBdirectory_iterator\fP &)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBdirectory_iterator\fP &, const \fBdirectory_iterator\fP &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
