.TH "fc::exception_factory" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::exception_factory
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbase_exception_builder\fP"
.br
.ti -1c
.RI "struct \fBexception_builder\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > void \fBregister_exception\fP ()"
.br
.ti -1c
.RI "void NO_RETURN \fBrethrow\fP (const \fBexception\fP &e) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBexception_factory\fP & \fBinstance\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
