.TH "fc::exception_factory::base_exception_builder" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::exception_factory::base_exception_builder
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBfc::exception_factory::exception_builder< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual NO_RETURN void \fBrethrow\fP (const \fBexception\fP &e) const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
