.TH "fc::ecc::public_key_shim" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::ecc::public_key_shim
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <elliptic\&.hpp>\fP
.PP
Inherits \fBfc::crypto::shim< public_key_data >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Shims 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
