.TH "fc::equihash::proof" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::equihash::proof
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBproof\fP \fBhash\fP (uint32_t n, uint32_t k, \fBsha256\fP seed)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBn\fP"
.br
.ti -1c
.RI "uint32_t \fBk\fP"
.br
.ti -1c
.RI "\fBsha256\fP \fBseed\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< uint32_t > \fBinputs\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
