.TH "fc::enum_type< IntType, EnumType >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::enum_type< IntType, EnumType >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBenum_type\fP (\fBEnumType\fP t)"
.br
.ti -1c
.RI "\fBenum_type\fP (IntType t)"
.br
.ti -1c
.RI "\fBoperator IntType\fP () const"
.br
.ti -1c
.RI "\fBoperator EnumType\fP () const"
.br
.ti -1c
.RI "\fBoperator std::string\fP () const"
.br
.ti -1c
.RI "\fBenum_type\fP & \fBoperator=\fP (IntType i)"
.br
.ti -1c
.RI "\fBenum_type\fP & \fBoperator=\fP (\fBEnumType\fP i)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (\fBEnumType\fP i) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (\fBEnumType\fP i) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBenum_type\fP &e) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBenum_type\fP &e) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBenum_type\fP &e) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBenum_type\fP &e) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEnumType\fP \fBvalue\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBenum_type\fP &e, IntType i)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBenum_type\fP &e, \fBEnumType\fP i)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBenum_type\fP &e, const \fBenum_type\fP &i)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (IntType i, const \fBenum_type\fP &e)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBEnumType\fP i, const \fBenum_type\fP &e)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBenum_type\fP &e, IntType i)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBenum_type\fP &e, \fBEnumType\fP i)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBenum_type\fP &e, const \fBenum_type\fP &i)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
