.TH "fc::ecc::detail::public_key_impl" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::ecc::detail::public_key_impl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpublic_key_impl\fP (const \fBpublic_key_impl\fP &cpy) BOOST_NOEXCEPT"
.br
.ti -1c
.RI "\fBpublic_key_impl\fP (\fBpublic_key_impl\fP &&cpy) BOOST_NOEXCEPT"
.br
.ti -1c
.RI "\fBpublic_key_impl\fP & \fBoperator=\fP (const \fBpublic_key_impl\fP &pk) BOOST_NOEXCEPT"
.br
.ti -1c
.RI "\fBpublic_key_impl\fP & \fBoperator=\fP (\fBpublic_key_impl\fP &&pk) BOOST_NOEXCEPT"
.br
.ti -1c
.RI "\fBpublic_key_impl\fP (const \fBpublic_key_impl\fP &cpy) BOOST_NOEXCEPT"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBECDSA_SIG_recover_key_GFp\fP (EC_KEY *eckey, ECDSA_SIG *ecsig, const unsigned char *msg, int msglen, int recid, int check)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "EC_KEY * \fB_key\fP = nullptr"
.br
.ti -1c
.RI "\fBpublic_key_data\fP \fB_key\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
