.TH "fc::ecc::range_proof_info" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::ecc::range_proof_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBexp\fP"
.br
.ti -1c
.RI "int \fBmantissa\fP"
.br
.ti -1c
.RI "uint64_t \fBmin_value\fP"
.br
.ti -1c
.RI "uint64_t \fBmax_value\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
