.TH "fc::file_appender::impl" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::file_appender::impl
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::retainable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBimpl\fP (const \fBconfig\fP &c)"
.br
.ti -1c
.RI "void \fBrotate_files\fP (bool initializing=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconfig\fP \fBcfg\fP"
.br
.ti -1c
.RI "ofstream \fBout\fP"
.br
.ti -1c
.RI "boost::mutex \fBslock\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
