.TH "fc::file_appender::config" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::file_appender::config
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconfig\fP (const \fBfc::path\fP &p='log\&.txt')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "fc::string \fBformat\fP"
.br
.ti -1c
.RI "\fBfc::path\fP \fBfilename\fP"
.br
.ti -1c
.RI "bool \fBflush\fP = true"
.br
.ti -1c
.RI "bool \fBrotate\fP = false"
.br
.ti -1c
.RI "\fBmicroseconds\fP \fBrotation_interval\fP"
.br
.ti -1c
.RI "\fBmicroseconds\fP \fBrotation_limit\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
