.TH "fc::from_variant_visitor< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::from_variant_visitor< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfrom_variant_visitor\fP (const \fBvariant_object\fP &_vo, \fBT\fP &v)"
.br
.ti -1c
.RI "template<typename Member , class Class , Member Class::* member> void \fBoperator()\fP (const char *name) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBvariant_object\fP & \fBvo\fP"
.br
.ti -1c
.RI "\fBT\fP & \fBval\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
