.TH "fc::file_appender" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::file_appender
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::appender\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBconfig\fP"
.br
.ti -1c
.RI "class \fBimpl\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfile_appender\fP (const \fBvariant\fP &args)"
.br
.ti -1c
.RI "virtual void \fBlog\fP (const \fBlog_message\fP &m) override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
