.TH "fc::fwd< T, S, Align >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::fwd< T, S, Align > \- Used to forward declare value types\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fwd\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename U > \fBfwd\fP (\fBU\fP &&u)"
.br
.ti -1c
.RI "template<typename U , typename V > \fBfwd\fP (\fBU\fP &&u, \fBV\fP &&v)"
.br
.ti -1c
.RI "template<typename U , typename V , typename X , typename Y > \fBfwd\fP (\fBU\fP &&u, \fBV\fP &&v, \fBX\fP &&, \fBY\fP &&)"
.br
.ti -1c
.RI "\fBfwd\fP (const \fBfwd\fP &f)"
.br
.ti -1c
.RI "\fBfwd\fP (\fBfwd\fP &&f)"
.br
.ti -1c
.RI "\fBoperator const T &\fP () const"
.br
.ti -1c
.RI "\fBoperator T &\fP ()"
.br
.ti -1c
.RI "\fBT\fP & \fBoperator*\fP ()"
.br
.ti -1c
.RI "const \fBT\fP & \fBoperator*\fP () const"
.br
.ti -1c
.RI "const \fBT\fP * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "\fBT\fP * \fBoperator\->\fP ()"
.br
.ti -1c
.RI "bool \fBoperator!\fP () const"
.br
.ti -1c
.RI "template<typename U > \fBT\fP & \fBoperator=\fP (\fBU\fP &&u)"
.br
.ti -1c
.RI "\fBT\fP & \fBoperator=\fP (\fBfwd\fP &&u)"
.br
.ti -1c
.RI "\fBT\fP & \fBoperator=\fP (const \fBfwd\fP &u)"
.br
.ti -1c
.RI "template<typename T , unsigned int S, typename A > \fBfwd\fP (const \fBfwd\fP< \fBT\fP, \fBS\fP, \fBA\fP > &f)"
.br
.ti -1c
.RI "template<typename T , unsigned int S, typename A > \fBfwd\fP (\fBfwd\fP< \fBT\fP, \fBS\fP, \fBA\fP > &&f)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, unsigned int S, typename Align = double>
.br
class fc::fwd< T, S, Align >"
Used to forward declare value types\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
