.TH "fc::gelf_appender" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::gelf_appender
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::appender\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBconfig\fP"
.br
.ti -1c
.RI "class \fBimpl\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgelf_appender\fP (const \fBvariant\fP &args)"
.br
.ti -1c
.RI "void \fBinitialize\fP (boost::asio::io_service &io_service) override"
.br
.RI "Required for name resolution and socket initialization\&. "
.ti -1c
.RI "virtual void \fBlog\fP (const \fBlog_message\fP &m) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void fc::gelf_appender::initialize (boost::asio::io_service & io_service)\fC [override]\fP, \fC [virtual]\fP"

.PP
Required for name resolution and socket initialization\&. 
.PP
\fBWarning:\fP
.RS 4
If this method is not called, this appender will log nothing\&.
.RE
.PP
In a single-threaded world with a boost::io_service that's not owned by this library, ugly things are required\&. Tough\&. 
.PP
Implements \fBfc::appender\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
