.TH "fc::generic_api" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::generic_api
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Api > \fBgeneric_api\fP (const Api &a, const std::shared_ptr< \fBfc::api_connection\fP > &c)"
.br
.ti -1c
.RI "\fBgeneric_api\fP (const \fBgeneric_api\fP &cpy)=delete"
.br
.ti -1c
.RI "\fBvariant\fP \fBcall\fP (const string &name, const \fBvariants\fP &args)"
.br
.ti -1c
.RI "\fBvariant\fP \fBcall\fP (uint32_t method_id, const \fBvariants\fP &args)"
.br
.ti -1c
.RI "std::weak_ptr< \fBfc::api_connection\fP > \fBget_connection\fP ()"
.br
.ti -1c
.RI "\fBstd::vector\fP< std::string > \fBget_method_names\fP () const"
.br
.ti -1c
.RI "template<typename Api > \fBgeneric_api\fP (const Api &a, const std::shared_ptr< \fBfc::binary_api_connection\fP > &c)"
.br
.ti -1c
.RI "\fBgeneric_api\fP (const \fBgeneric_api\fP &cpy)=delete"
.br
.ti -1c
.RI "\fBvector\fP< char > \fBcall\fP (const string &name, const \fBvector\fP< char > &args)"
.br
.ti -1c
.RI "\fBvector\fP< char > \fBcall\fP (uint32_t method_id, const \fBvector\fP< char > &args)"
.br
.ti -1c
.RI "std::weak_ptr< \fBfc::binary_api_connection\fP > \fBget_connection\fP ()"
.br
.ti -1c
.RI "\fBstd::vector\fP< std::string > \fBget_method_names\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "struct \fBapi_visitor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
