.TH "fc::gelf_appender::config" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::gelf_appender::config
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBendpoint\fP = '127\&.0\&.0\&.1:12201'"
.br
.ti -1c
.RI "string \fBhost\fP = 'fc'"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
