.TH "fc::http::detail::websocket_tls_server_impl" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::http::detail::websocket_tls_server_impl
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBstd::map\fP< connection_hdl, websocket_connection_ptr, std::owner_less< connection_hdl > > \fBcon_map\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwebsocket_tls_server_impl\fP (const string &server_pem, const string &ssl_password)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcon_map\fP \fB_connections\fP"
.br
.ti -1c
.RI "fc::thread & \fB_server_thread\fP"
.br
.ti -1c
.RI "\fBwebsocket_tls_server_type\fP \fB_server\fP"
.br
.ti -1c
.RI "on_connection_handler \fB_on_connection\fP"
.br
.ti -1c
.RI "void_promise_ptr \fB_closed\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
