.TH "fc::http::server::impl" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::http::server::impl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBimpl\fP (const \fBfc::ip::endpoint\fP &p)"
.br
.ti -1c
.RI "void \fBaccept_loop\fP ()"
.br
.ti -1c
.RI "void \fBhandle_connection\fP (const http::connection_ptr &c, std::function< void(const http::request &, const server::response &s)> do_on_req)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "fc::future< void > \fBaccept_complete\fP"
.br
.ti -1c
.RI "std::function< void(const http::request &, const server::response &s)> \fBon_req\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< fc::future< void > > \fBrequests_in_progress\fP"
.br
.ti -1c
.RI "fc::tcp_server \fBtcp_serv\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
