.TH "fc::http::detail::websocket_connection_impl< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::http::detail::websocket_connection_impl< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits websocket_connection\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwebsocket_connection_impl\fP (\fBT\fP con)"
.br
.ti -1c
.RI "virtual void \fBsend_message\fP (const std::string &message) override"
.br
.ti -1c
.RI "virtual void \fBclose\fP (int64_t code, const std::string &reason) override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP \fB_ws_connection\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
