.TH "fc::http::connection::impl" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::http::connection::impl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBread_until\fP (char *buffer, char *end, char c='\\n')"
.br
.ti -1c
.RI "fc::http::reply \fBparse_reply\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "fc::tcp_socket \fBsock\fP"
.br
.ti -1c
.RI "\fBfc::ip::endpoint\fP \fBep\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
