.TH "fc::http::detail::websocket_tls_client_impl" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::http::detail::websocket_tls_client_impl
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBwebsocket_tls_client_type::message_ptr\fP \fBmessage_ptr\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwebsocket_tls_client_impl\fP (const std::string &ca_filename)"
.br
.ti -1c
.RI "std::string \fBget_host\fP () const"
.br
.ti -1c
.RI "void \fBsetup_peer_verify\fP (context_ptr &ctx, const std::string &ca_filename)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fB_shutting_down\fP = false"
.br
.ti -1c
.RI "void_promise_ptr \fB_connected\fP"
.br
.ti -1c
.RI "void_promise_ptr \fB_closed\fP"
.br
.ti -1c
.RI "fc::thread & \fB_client_thread\fP"
.br
.ti -1c
.RI "\fBwebsocket_tls_client_type\fP \fB_client\fP"
.br
.ti -1c
.RI "websocket_connection_ptr \fB_connection\fP"
.br
.ti -1c
.RI "std::string \fB_uri\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
