.TH "fc::if_enum< fc::true_type >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::if_enum< fc::true_type >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > static void \fBto_variant\fP (const \fBT\fP &o, \fBfc::variant\fP &v)"
.br
.ti -1c
.RI "template<typename T > static void \fBfrom_variant\fP (const \fBfc::variant\fP &v, \fBT\fP &o)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
