.TH "fc::identity_member" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::identity_member
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename R , typename C , typename P , typename\&.\&.\&. Args> static std::function< R(Args\&.\&.\&.)> \fBfunctor\fP (\fBP\fP &&p, R(C::*mem_func)(Args\&.\&.\&.))"
.br
.ti -1c
.RI "template<typename R , typename C , typename P , typename\&.\&.\&. Args> static std::function< R(Args\&.\&.\&.)> \fBfunctor\fP (\fBP\fP &&p, R(C::*mem_func)(Args\&.\&.\&.) const)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
