.TH "fc::impl::copy_construct< StaticVariant >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::impl::copy_construct< StaticVariant >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcopy_construct\fP (StaticVariant &s)"
.br
.ti -1c
.RI "template<typename T > void \fBoperator()\fP (const \fBT\fP &v) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "StaticVariant & \fBsv\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
