.TH "fc::logger::impl" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::logger::impl
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::retainable\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "fc::string \fB_name\fP"
.br
.ti -1c
.RI "\fBlogger\fP \fB_parent\fP"
.br
.ti -1c
.RI "bool \fB_enabled\fP"
.br
.ti -1c
.RI "bool \fB_additivity\fP"
.br
.ti -1c
.RI "\fBlog_level\fP \fB_level\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBappender::ptr\fP > \fB_appenders\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
