.TH "fc::log_message" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::log_message \- aggregates a message along with the context and associated meta-information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <log_message\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlog_message\fP (\fBlog_context\fP ctx, std::string format, \fBvariant_object\fP args=\fBvariant_object\fP())"
.br
.ti -1c
.RI "\fBlog_message\fP (const \fBvariant\fP &v)"
.br
.ti -1c
.RI "\fBvariant\fP \fBto_variant\fP () const"
.br
.ti -1c
.RI "string \fBget_message\fP () const"
.br
.ti -1c
.RI "\fBlog_context\fP \fBget_context\fP () const"
.br
.ti -1c
.RI "string \fBget_format\fP () const"
.br
.ti -1c
.RI "\fBvariant_object\fP \fBget_data\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
aggregates a message along with the context and associated meta-information\&. 


.PP
\fBNote:\fP
.RS 4
\fBlog_message\fP has reference semantics, all copies refer to the same log message and the message is read-only after construction\&.
.RE
.PP
When converted to JSON, \fBlog_message\fP has the following form: 
.PP
.nf
{
   "context" : { \&.\&.\&. },
   "format"  : "string with ${keys}",
   "data"    : { "keys" : "values" }
}

.fi
.PP
.PP
\fBSee also:\fP
.RS 4
\fBFC_LOG_MESSAGE\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "fc::log_message::log_message (\fBlog_context\fP ctx, std::string format, \fBvariant_object\fP args = \fC\fBvariant_object\fP()\fP)"

.PP
\fBParameters:\fP
.RS 4
\fIctx\fP - generally provided using the \fBFC_LOG_CONTEXT(LEVEL)\fP macro 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
