.TH "fc::log_context" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::log_context \- provides information about where and when a log message was generated\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <log_message\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlog_context\fP (\fBlog_level\fP ll, const char *file, uint64_t line, const char *method)"
.br
.ti -1c
.RI "\fBlog_context\fP (const \fBvariant\fP &v)"
.br
.ti -1c
.RI "\fBvariant\fP \fBto_variant\fP () const"
.br
.ti -1c
.RI "string \fBget_file\fP () const"
.br
.ti -1c
.RI "uint64_t \fBget_line_number\fP () const"
.br
.ti -1c
.RI "string \fBget_method\fP () const"
.br
.ti -1c
.RI "string \fBget_thread_name\fP () const"
.br
.ti -1c
.RI "string \fBget_task_name\fP () const"
.br
.ti -1c
.RI "string \fBget_host_name\fP () const"
.br
.ti -1c
.RI "\fBtime_point\fP \fBget_timestamp\fP () const"
.br
.ti -1c
.RI "\fBlog_level\fP \fBget_log_level\fP () const"
.br
.ti -1c
.RI "string \fBget_context\fP () const"
.br
.ti -1c
.RI "void \fBappend_context\fP (const fc::string &c)"
.br
.ti -1c
.RI "string \fBto_string\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
provides information about where and when a log message was generated\&. 


.PP
\fBSee also:\fP
.RS 4
\fBFC_LOG_CONTEXT\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
