.TH "fc::local_binary_api_connection" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::local_binary_api_connection
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::binary_api_connection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBresult_type\fP \fBsend_call\fP (api_id_type api_id, string method_name, \fBparams_type\fP args=\fBparams_type\fP()) override"
.br
.ti -1c
.RI "virtual \fBresult_type\fP \fBsend_callback\fP (uint64_t callback_id, \fBparams_type\fP args=\fBparams_type\fP()) override"
.br
.ti -1c
.RI "virtual void \fBsend_notice\fP (uint64_t callback_id, \fBparams_type\fP args=\fBparams_type\fP()) override"
.br
.ti -1c
.RI "void \fBset_remote_connection\fP (const std::shared_ptr< \fBfc::binary_api_connection\fP > &rc)"
.br
.ti -1c
.RI "const std::shared_ptr< \fBfc::binary_api_connection\fP > & \fBremote_connection\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBfc::binary_api_connection\fP > \fB_remote_connection\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBresult_type\fP fc::local_binary_api_connection::send_call (api_id_type api_id, string method_name, \fBparams_type\fP args = \fC\fBparams_type\fP()\fP)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"
makes calls to the remote server 
.PP
Implements \fBfc::binary_api_connection\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
