.TH "fc::mmap_struct< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::mmap_struct< T > \- \fBA\fP struct that has been mapped from a file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mmap_struct\&.hpp>\fP
.PP
Inherits \fBfc::detail::mmap_struct_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBopen\fP (const \fBfc::path\fP &file, bool create=false)"
.br
.ti -1c
.RI "\fBT\fP * \fBoperator\->\fP ()"
.br
.ti -1c
.RI "const \fBT\fP * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "\fBT\fP & \fBoperator*\fP ()"
.br
.ti -1c
.RI "const \fBT\fP & \fBoperator*\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class fc::mmap_struct< T >"
\fBA\fP struct that has been mapped from a file\&. 


.PP
\fBNote:\fP
.RS 4
\fBT\fP must be POD 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void \fBfc::mmap_struct\fP< \fBT\fP >::open (const \fBfc::path\fP & file, bool create = \fCfalse\fP)\fC [inline]\fP"
Create the file if it does not exist or is of the wrong size if create is true, then maps the file to memory\&.
.PP
\fBExceptions:\fP
.RS 4
\fIan\fP exception if the file does not exist or is the wrong size and create is false 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
