.TH "fc::mapped_region" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::mapped_region
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmapped_region\fP (const \fBfile_mapping\fP &fm, mode_t m, uint64_t start, size_t size)"
.br
.ti -1c
.RI "\fBmapped_region\fP (const \fBfile_mapping\fP &fm, mode_t m)"
.br
.ti -1c
.RI "void \fBflush\fP ()"
.br
.ti -1c
.RI "void * \fBget_address\fP () const"
.br
.ti -1c
.RI "size_t \fBget_size\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
