.TH "fc::microseconds" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::microseconds
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmicroseconds\fP (int64_t c=0)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBmicroseconds\fP &c) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBmicroseconds\fP &c) const"
.br
.ti -1c
.RI "\fBmicroseconds\fP & \fBoperator+=\fP (const \fBmicroseconds\fP &c)"
.br
.ti -1c
.RI "\fBmicroseconds\fP & \fBoperator\-=\fP (const \fBmicroseconds\fP &c)"
.br
.ti -1c
.RI "int64_t \fBcount\fP () const"
.br
.ti -1c
.RI "int64_t \fBto_seconds\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBmicroseconds\fP \fBmaximum\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBtime_point\fP"
.br
.ti -1c
.RI "\fBmicroseconds\fP \fBoperator+\fP (const \fBmicroseconds\fP &l, const \fBmicroseconds\fP &r)"
.br
.ti -1c
.RI "\fBmicroseconds\fP \fBoperator\-\fP (const \fBmicroseconds\fP &l, const \fBmicroseconds\fP &r)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBmicroseconds\fP &a, const \fBmicroseconds\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBmicroseconds\fP &a, const \fBmicroseconds\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBmicroseconds\fP &a, const \fBmicroseconds\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBmicroseconds\fP &a, const \fBmicroseconds\fP &b)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
