.TH "fc::private_key" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::private_key
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprivate_key\fP (const \fBbytes\fP &d)"
.br
.ti -1c
.RI "\fBprivate_key\fP (const \fBprivate_key\fP &k)"
.br
.ti -1c
.RI "\fBprivate_key\fP (\fBprivate_key\fP &&k)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "\fBprivate_key\fP & \fBoperator=\fP (const \fBprivate_key\fP &p)"
.br
.ti -1c
.RI "\fBprivate_key\fP & \fBoperator=\fP (\fBprivate_key\fP &&p)"
.br
.ti -1c
.RI "void \fBsign\fP (const \fBsha1\fP &digest, \fBarray\fP< char, 2048/8 > &sig) const"
.br
.ti -1c
.RI "\fBsignature\fP \fBsign\fP (const \fBsha1\fP &digest) const"
.br
.ti -1c
.RI "\fBsignature\fP \fBsign\fP (const \fBsha256\fP &digest) const"
.br
.ti -1c
.RI "\fBbytes\fP \fBdecrypt\fP (const char *\fBbytes\fP, size_t len) const"
.br
.ti -1c
.RI "\fBbytes\fP \fBdecrypt\fP (const \fBbytes\fP &) const"
.br
.ti -1c
.RI "\fBbytes\fP \fBencrypt\fP (const \fBbytes\fP &) const"
.br
.ti -1c
.RI "\fBbytes\fP \fBserialize\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "void \fBgenerate_key_pair\fP (\fBpublic_key\fP &, \fBprivate_key\fP &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
