.TH "fc::process" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::process \- start and manage an local process  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <process\&.hpp>\fP
.PP
Inherits \fBfc::iprocess\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBimpl\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBiprocess\fP & \fBexec\fP (const \fBfc::path\fP &exe, \fBstd::vector\fP< std::string > args, const \fBfc::path\fP &work_dir=\fBfc::path\fP(), int opts=open_all)"
.br
.ti -1c
.RI "virtual int \fBresult\fP (const \fBmicroseconds\fP &timeout=microseconds::maximum())"
.br
.ti -1c
.RI "virtual void \fBkill\fP ()"
.br
.ti -1c
.RI "virtual fc::buffered_ostream_ptr \fBin_stream\fP ()"
.br
.RI "returns a stream that writes to the process' stdin "
.ti -1c
.RI "virtual fc::buffered_istream_ptr \fBout_stream\fP ()"
.br
.RI "returns a stream that reads from the process' stdout "
.ti -1c
.RI "virtual fc::buffered_istream_ptr \fBerr_stream\fP ()"
.br
.RI "returns a stream that reads from the process' stderr "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
start and manage an local process 


.PP
\fBNote:\fP
.RS 4
this class implements reference semantics\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBiprocess\fP & fc::process::exec (const \fBfc::path\fP & exe, \fBstd::vector\fP< std::string > args, const \fBfc::path\fP & work_dir = \fC\fBfc::path\fP()\fP, int opts = \fCopen_all\fP)\fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
*this 
.RE
.PP

.PP
Implements \fBfc::iprocess\fP\&.
.SS "void fc::process::kill ()\fC [virtual]\fP"
Forcefully kills the process\&. 
.PP
Implements \fBfc::iprocess\fP\&.
.SS "int fc::process::result (const \fBmicroseconds\fP & timeout = \fCmicroseconds::maximum()\fP)\fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
blocks until the process exits 
.RE
.PP

.PP
Implements \fBfc::iprocess\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
