.TH "fc::public_key" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::public_key
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpublic_key\fP (const \fBbytes\fP &d)"
.br
.ti -1c
.RI "\fBpublic_key\fP (const \fBpublic_key\fP &k)"
.br
.ti -1c
.RI "\fBpublic_key\fP (\fBpublic_key\fP &&k)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "\fBpublic_key\fP & \fBoperator=\fP (const \fBpublic_key\fP &p)"
.br
.ti -1c
.RI "\fBpublic_key\fP & \fBoperator=\fP (\fBpublic_key\fP &&p)"
.br
.ti -1c
.RI "bool \fBverify\fP (const \fBsha1\fP &digest, const \fBarray\fP< char, 2048/8 > &sig) const"
.br
.ti -1c
.RI "bool \fBverify\fP (const \fBsha1\fP &digest, const \fBsignature\fP &sig) const"
.br
.ti -1c
.RI "bool \fBverify\fP (const \fBsha256\fP &digest, const \fBsignature\fP &sig) const"
.br
.ti -1c
.RI "\fBbytes\fP \fBencrypt\fP (const char *data, size_t len) const"
.br
.ti -1c
.RI "\fBbytes\fP \fBencrypt\fP (const \fBbytes\fP &) const"
.br
.ti -1c
.RI "\fBbytes\fP \fBdecrypt\fP (const \fBbytes\fP &) const"
.br
.ti -1c
.RI "\fBbytes\fP \fBserialize\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "void \fBgenerate_key_pair\fP (\fBpublic_key\fP &, \fBprivate_key\fP &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
