.TH "fc::reflector< T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::reflector< T > \- defines visit functions for \fBT\fP Unless this is specialized, visit() will not be defined for \fBT\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reflect\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBT\fP \fBtype\fP"
.br
.ti -1c
.RI "typedef \fBfc::false_type\fP \fBis_defined\fP"
.br
.ti -1c
.RI "typedef \fBfc::false_type\fP \fBis_enum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct fc::reflector< T >"
defines visit functions for \fBT\fP Unless this is specialized, visit() will not be defined for \fBT\fP\&. 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fI\fBT\fP\fP - the type that will be visited\&.
.RE
.PP
The \fBFC_REFLECT(TYPE,MEMBERS)\fP or FC_STATIC_REFLECT_DERIVED(TYPE,BASES,MEMBERS) macro is used to specialize this class for your type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
