.TH "fc::raw::detail::unpack_object_visitor< Stream, Class >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::raw::detail::unpack_object_visitor< Stream, Class >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBunpack_object_visitor\fP (\fBClass\fP &_c, Stream &_s)"
.br
.ti -1c
.RI "template<typename T , typename C , TC::* p> void \fBoperator()\fP (const char *name) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
