.TH "fc::raw::variant_packer< Stream >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::raw::variant_packer< Stream >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::variant::visitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvariant_packer\fP (Stream &_s)"
.br
.ti -1c
.RI "virtual void \fBhandle\fP () const"
.br
.RI "handles null_type variants "
.ti -1c
.RI "virtual void \fBhandle\fP (const int64_t &v) const"
.br
.ti -1c
.RI "virtual void \fBhandle\fP (const uint64_t &v) const"
.br
.ti -1c
.RI "virtual void \fBhandle\fP (const double &v) const"
.br
.ti -1c
.RI "virtual void \fBhandle\fP (const bool &v) const"
.br
.ti -1c
.RI "virtual void \fBhandle\fP (const string &v) const"
.br
.ti -1c
.RI "virtual void \fBhandle\fP (const \fBvariant_object\fP &v) const"
.br
.ti -1c
.RI "virtual void \fBhandle\fP (const \fBvariants\fP &v) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Stream & \fBs\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
