.TH "fc::rpc::detail::json_connection_impl" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::rpc::detail::json_connection_impl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBjson_connection_impl\fP (fc::buffered_istream_ptr &&in, fc::buffered_ostream_ptr &&out)"
.br
.ti -1c
.RI "void \fBsend_result\fP (\fBvariant\fP id, \fBvariant\fP result)"
.br
.ti -1c
.RI "void \fBsend_error\fP (\fBvariant\fP id, \fBfc::exception\fP &e)"
.br
.ti -1c
.RI "void \fBhandle_message\fP (const \fBvariant_object\fP &obj)"
.br
.ti -1c
.RI "void \fBread_loop\fP ()"
.br
.ti -1c
.RI "void \fBclose\fP (fc::exception_ptr e)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "fc::buffered_istream_ptr \fB_in\fP"
.br
.ti -1c
.RI "fc::buffered_ostream_ptr \fB_out\fP"
.br
.ti -1c
.RI "fc::future< void > \fB_done\fP"
.br
.ti -1c
.RI "fc::future< void > \fB_handle_message_future\fP"
.br
.ti -1c
.RI "bool \fB_eof\fP"
.br
.ti -1c
.RI "uint64_t \fB_next_id\fP"
.br
.ti -1c
.RI "boost::unordered_map< uint64_t, fc::promise< \fBvariant\fP >::ptr > \fB_awaiting\fP"
.br
.ti -1c
.RI "boost::unordered_map< std::string, json_connection::method > \fB_methods\fP"
.br
.ti -1c
.RI "boost::unordered_map< std::string, json_connection::named_param_method > \fB_named_param_methods\fP"
.br
.ti -1c
.RI "fc::mutex \fB_write_mutex\fP"
.br
.ti -1c
.RI "std::function< void(fc::exception_ptr)> \fB_on_close\fP"
.br
.ti -1c
.RI "\fBlogger\fP \fB_logger\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void fc::rpc::detail::json_connection_impl::read_loop ()\fC [inline]\fP"
ilog( 'input: ${in}', ('in', v ) ); 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
