.TH "fc::rpc::cli" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::rpc::cli
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cli\&.hpp>\fP
.PP
Inherits \fBfc::api_connection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBvariant\fP \fBsend_call\fP (api_id_type api_id, string method_name, \fBvariants\fP args=\fBvariants\fP())"
.br
.ti -1c
.RI "virtual \fBvariant\fP \fBsend_callback\fP (uint64_t callback_id, \fBvariants\fP args=\fBvariants\fP())"
.br
.ti -1c
.RI "virtual void \fBsend_notice\fP (uint64_t callback_id, \fBvariants\fP args=\fBvariants\fP())"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBwait\fP ()"
.br
.ti -1c
.RI "void \fBformat_result\fP (const string &method, std::function< string(\fBvariant\fP, const \fBvariants\fP &)> formatter)"
.br
.ti -1c
.RI "virtual void \fBgetline\fP (const fc::string &prompt, fc::string &line)"
.br
.ti -1c
.RI "void \fBset_prompt\fP (const string &prompt)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Provides a simple wrapper for RPC calls to a given interface\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBvariant\fP fc::rpc::cli::send_call (api_id_type api_id, string method_name, \fBvariants\fP args = \fC\fBvariants\fP()\fP)\fC [virtual]\fP"
makes calls to the remote server 
.PP
Implements \fBfc::api_connection\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
