.TH "fc::retainable" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::retainable \- used to create reference counted types\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shared_ptr\&.hpp>\fP
.PP
Inherited by \fBfc::appender\fP, \fBfc::appender_factory\fP, \fBfc::file_appender::impl\fP, \fBfc::gelf_appender::impl\fP, \fBfc::http::server::response::impl\fP, \fBfc::logger::impl\fP, and \fBfc::udp_socket::impl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBretain\fP ()"
.br
.ti -1c
.RI "void \fBrelease\fP ()"
.br
.ti -1c
.RI "int32_t \fBretain_count\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
used to create reference counted types\&. 

Must be a virtual base class that is initialized with the 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
