.TH "fc::raw::detail::if_reflected< IsReflected >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::raw::detail::if_reflected< IsReflected >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Stream , typename T > static void \fBpack\fP (Stream &s, const \fBT\fP &v)"
.br
.ti -1c
.RI "template<typename Stream , typename T > static void \fBunpack\fP (Stream &s, \fBT\fP &v)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
