.TH "fc::rpc::websocket_api_connection" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::rpc::websocket_api_connection
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfc::api_connection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwebsocket_api_connection\fP (fc::http::websocket_connection &c)"
.br
.ti -1c
.RI "virtual \fBvariant\fP \fBsend_call\fP (api_id_type api_id, string method_name, \fBvariants\fP args=\fBvariants\fP()) override"
.br
.ti -1c
.RI "virtual \fBvariant\fP \fBsend_callback\fP (uint64_t callback_id, \fBvariants\fP args=\fBvariants\fP()) override"
.br
.ti -1c
.RI "virtual void \fBsend_notice\fP (uint64_t callback_id, \fBvariants\fP args=\fBvariants\fP()) override"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBon_message\fP (const std::string &message, bool send_message=true)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "fc::http::websocket_connection & \fB_connection\fP"
.br
.ti -1c
.RI "fc::rpc::state \fB_rpc_state\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBvariant\fP fc::rpc::websocket_api_connection::send_call (api_id_type api_id, string method_name, \fBvariants\fP args = \fC\fBvariants\fP()\fP)\fC [override]\fP, \fC [virtual]\fP"
makes calls to the remote server 
.PP
Implements \fBfc::api_connection\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
