.TH "fc::raw::unpack_static_variant< Stream >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::raw::unpack_static_variant< Stream >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBunpack_static_variant\fP (Stream &s)"
.br
.ti -1c
.RI "template<typename T > void \fBoperator()\fP (\fBT\fP &v) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Stream & \fBstream\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
