.TH "fc::size_stream" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::size_stream
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iobuffer\&.hpp>\fP
.PP
Inherits ostream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsize_stream\fP (size_t s=0)"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "size_t \fBseek\fP (size_t pos)"
.br
.ti -1c
.RI "virtual size_t \fBwritesome\fP (const char *, size_t len)"
.br
.ti -1c
.RI "virtual void \fBclose\fP ()"
.br
.ti -1c
.RI "virtual void \fBflush\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Records the size, but discards the data\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
