.TH "fc::scoped_exit< Callback >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::scoped_exit< Callback >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename C > \fBscoped_exit\fP (\fBC\fP &&c)"
.br
.ti -1c
.RI "\fBscoped_exit\fP (\fBscoped_exit\fP &&mv)"
.br
.ti -1c
.RI "\fBscoped_exit\fP (const \fBscoped_exit\fP &)=delete"
.br
.ti -1c
.RI "\fBscoped_exit\fP & \fBoperator=\fP (const \fBscoped_exit\fP &)=delete"
.br
.ti -1c
.RI "void \fBcancel\fP ()"
.br
.ti -1c
.RI "\fBscoped_exit\fP & \fBoperator=\fP (\fBscoped_exit\fP &&mv)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
