.TH "fc::sblock" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::sblock
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsblock\fP (unsigned int l=0, unsigned int r=0)"
.br
.ti -1c
.RI "\fBsblock\fP (const \fBsblock\fP &roBlock)"
.br
.ti -1c
.RI "\fBsblock\fP & \fBoperator^=\fP (\fBsblock\fP &b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBm_uil\fP"
.br
.ti -1c
.RI "unsigned int \fBm_uir\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
