.TH "fc::signed_int" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::signed_int \- serializes a 32 bit signed interger in as few bytes as possible  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <varint\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsigned_int\fP (int32_t v=0)"
.br
.ti -1c
.RI "\fBoperator int32_t\fP () const"
.br
.ti -1c
.RI "template<typename T > \fBsigned_int\fP & \fBoperator=\fP (const \fBT\fP &v)"
.br
.ti -1c
.RI "\fBsigned_int\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBsigned_int\fP & \fBoperator++\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBvalue\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBsigned_int\fP &i, const int32_t &v)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const int32_t &i, const \fBsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBsigned_int\fP &i, const \fBsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBsigned_int\fP &i, const int32_t &v)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const int32_t &i, const \fBsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBsigned_int\fP &i, const \fBsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBsigned_int\fP &i, const int32_t &v)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const int32_t &i, const \fBsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBsigned_int\fP &i, const \fBsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBsigned_int\fP &i, const int32_t &v)"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const int32_t &i, const \fBsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBsigned_int\fP &i, const \fBsigned_int\fP &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
serializes a 32 bit signed interger in as few bytes as possible 

Uses the google protobuf algorithm for seralizing signed numbers 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
