.TH "fc::temp_file" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::temp_file
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <filesystem\&.hpp>\fP
.PP
Inherits \fBfc::temp_file_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtemp_file\fP (\fBtemp_file\fP &&\fBother\fP)"
.br
.ti -1c
.RI "\fBtemp_file\fP & \fBoperator=\fP (\fBtemp_file\fP &&\fBother\fP)"
.br
.ti -1c
.RI "\fBtemp_file\fP (const \fBfc::path\fP &tempFolder=fc::temp_directory_path(), bool create=false)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBClass\fP which creates a temporary directory inside an existing temporary directory\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
