.TH "fc::time_point_sec" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::time_point_sec
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <time\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtime_point_sec\fP (uint32_t seconds)"
.br
.ti -1c
.RI "\fBtime_point_sec\fP (const \fBtime_point\fP &t)"
.br
.ti -1c
.RI "\fBoperator time_point\fP () const"
.br
.ti -1c
.RI "uint32_t \fBsec_since_epoch\fP () const"
.br
.ti -1c
.RI "\fBtime_point_sec\fP \fBoperator=\fP (const \fBfc::time_point\fP &t)"
.br
.ti -1c
.RI "\fBtime_point_sec\fP & \fBoperator+=\fP (uint32_t m)"
.br
.ti -1c
.RI "\fBtime_point_sec\fP & \fBoperator+=\fP (\fBmicroseconds\fP m)"
.br
.ti -1c
.RI "\fBtime_point_sec\fP & \fBoperator+=\fP (\fBtime_point_sec\fP m)"
.br
.ti -1c
.RI "\fBtime_point_sec\fP & \fBoperator\-=\fP (uint32_t m)"
.br
.ti -1c
.RI "\fBtime_point_sec\fP & \fBoperator\-=\fP (\fBmicroseconds\fP m)"
.br
.ti -1c
.RI "\fBtime_point_sec\fP & \fBoperator\-=\fP (\fBtime_point_sec\fP m)"
.br
.ti -1c
.RI "\fBtime_point_sec\fP \fBoperator+\fP (uint32_t offset) const"
.br
.ti -1c
.RI "\fBtime_point_sec\fP \fBoperator\-\fP (uint32_t offset) const"
.br
.ti -1c
.RI "fc::string \fBto_non_delimited_iso_string\fP () const"
.br
.ti -1c
.RI "fc::string \fBto_iso_string\fP () const"
.br
.ti -1c
.RI "\fBoperator fc::string\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBtime_point_sec\fP \fBmaximum\fP ()"
.br
.ti -1c
.RI "static \fBtime_point_sec\fP \fBmin\fP ()"
.br
.ti -1c
.RI "static \fBtime_point_sec\fP \fBfrom_iso_string\fP (const fc::string &s)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBtime_point_sec\fP &a, const \fBtime_point_sec\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBtime_point_sec\fP &a, const \fBtime_point_sec\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBtime_point_sec\fP &a, const \fBtime_point_sec\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBtime_point_sec\fP &a, const \fBtime_point_sec\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBtime_point_sec\fP &a, const \fBtime_point_sec\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBtime_point_sec\fP &a, const \fBtime_point_sec\fP &b)"
.br
.ti -1c
.RI "\fBtime_point\fP \fBoperator+\fP (const \fBtime_point_sec\fP &t, const \fBmicroseconds\fP &m)"
.br
.ti -1c
.RI "\fBtime_point\fP \fBoperator\-\fP (const \fBtime_point_sec\fP &t, const \fBmicroseconds\fP &m)"
.br
.ti -1c
.RI "\fBmicroseconds\fP \fBoperator\-\fP (const \fBtime_point_sec\fP &t, const \fBtime_point_sec\fP &m)"
.br
.ti -1c
.RI "\fBmicroseconds\fP \fBoperator\-\fP (const \fBtime_point\fP &t, const \fBtime_point_sec\fP &m)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP lower resolution \fBtime_point\fP accurate only to seconds from 1970 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
