.TH "fc::tcp_socket::impl" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::tcp_socket::impl
.SH SYNOPSIS
.br
.PP
.PP
Inherits tcp_socket_io_hooks\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual size_t \fBreadsome\fP (boost::asio::ip::tcp::socket &socket, char *buffer, size_t length) override"
.br
.ti -1c
.RI "virtual size_t \fBreadsome\fP (boost::asio::ip::tcp::socket &socket, const std::shared_ptr< char > &buffer, size_t length, size_t offset) override"
.br
.ti -1c
.RI "virtual size_t \fBwritesome\fP (boost::asio::ip::tcp::socket &socket, const char *buffer, size_t length) override"
.br
.ti -1c
.RI "virtual size_t \fBwritesome\fP (boost::asio::ip::tcp::socket &socket, const std::shared_ptr< const char > &buffer, size_t length, size_t offset) override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "future< size_t > \fB_write_in_progress\fP"
.br
.ti -1c
.RI "future< size_t > \fB_read_in_progress\fP"
.br
.ti -1c
.RI "boost::asio::ip::tcp::socket \fB_sock\fP"
.br
.ti -1c
.RI "tcp_socket_io_hooks * \fB_io_hooks\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
