.TH "fc::time_point" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::time_point
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtime_point\fP (\fBmicroseconds\fP e=\fBmicroseconds\fP())"
.br
.ti -1c
.RI "\fBoperator fc::string\fP () const"
.br
.ti -1c
.RI "const \fBmicroseconds\fP & \fBtime_since_epoch\fP () const"
.br
.ti -1c
.RI "uint32_t \fBsec_since_epoch\fP () const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBtime_point\fP &t) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBtime_point\fP &t) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBtime_point\fP &t) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBtime_point\fP &t) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBtime_point\fP &t) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBtime_point\fP &t) const"
.br
.ti -1c
.RI "\fBtime_point\fP & \fBoperator+=\fP (const \fBmicroseconds\fP &m)"
.br
.ti -1c
.RI "\fBtime_point\fP & \fBoperator\-=\fP (const \fBmicroseconds\fP &m)"
.br
.ti -1c
.RI "\fBtime_point\fP \fBoperator+\fP (const \fBmicroseconds\fP &m) const"
.br
.ti -1c
.RI "\fBtime_point\fP \fBoperator+\fP (const \fBtime_point\fP &m) const"
.br
.ti -1c
.RI "\fBtime_point\fP \fBoperator\-\fP (const \fBmicroseconds\fP &m) const"
.br
.ti -1c
.RI "\fBmicroseconds\fP \fBoperator\-\fP (const \fBtime_point\fP &m) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBtime_point\fP \fBnow\fP ()"
.br
.ti -1c
.RI "static \fBtime_point\fP \fBmaximum\fP ()"
.br
.ti -1c
.RI "static \fBtime_point\fP \fBmin\fP ()"
.br
.ti -1c
.RI "static \fBtime_point\fP \fBfrom_iso_string\fP (const fc::string &s)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
