.TH "fc::unsigned_int" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::unsigned_int
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBunsigned_int\fP (uint32_t v=0)"
.br
.ti -1c
.RI "template<typename T > \fBunsigned_int\fP (\fBT\fP v)"
.br
.ti -1c
.RI "template<typename T > \fBoperator T\fP () const"
.br
.ti -1c
.RI "\fBunsigned_int\fP & \fBoperator=\fP (int32_t v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBvalue\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBunsigned_int\fP &i, const uint32_t &v)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const uint32_t &i, const \fBunsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBunsigned_int\fP &i, const \fBunsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBunsigned_int\fP &i, const uint32_t &v)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const uint32_t &i, const \fBunsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBunsigned_int\fP &i, const \fBunsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBunsigned_int\fP &i, const uint32_t &v)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const uint32_t &i, const \fBunsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBunsigned_int\fP &i, const \fBunsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBunsigned_int\fP &i, const uint32_t &v)"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const uint32_t &i, const \fBunsigned_int\fP &v)"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBunsigned_int\fP &i, const \fBunsigned_int\fP &v)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
