.TH "fc::udt_epoll_service" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::udt_epoll_service
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpoll_loop\fP ()"
.br
.ti -1c
.RI "void \fBnotify_read\fP (int udt_socket_id, const promise< void >::ptr &p)"
.br
.ti -1c
.RI "void \fBnotify_write\fP (int udt_socket_id, const promise< void >::ptr &p)"
.br
.ti -1c
.RI "void \fBremove\fP (int udt_socket_id)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
