.TH "fc::vtable_copy_visitor< OtherType >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::vtable_copy_visitor< OtherType >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef OtherType \fBother_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvtable_copy_visitor\fP (OtherType &s)"
.br
.ti -1c
.RI "template<typename R , typename MemberPtr , typename\&.\&.\&. Args> void \fBoperator()\fP (const char *name, std::function< R(Args\&.\&.\&.)> &memb, MemberPtr m) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "OtherType & \fB_source\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
