.TH "fc::variant_stream" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fc::variant_stream
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <variant_stream\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvariant_stream\fP (size_t s)"
.br
.ti -1c
.RI "int64_t \fBfree\fP ()"
.br
.ti -1c
.RI "int64_t \fBclaim\fP (int64_t \fBnum\fP)"
.br
.ti -1c
.RI "int64_t \fBpublish\fP (int64_t pos)"
.br
.ti -1c
.RI "int64_t \fBwait_free\fP ()"
.br
.ti -1c
.RI "\fBvariant\fP & \fBget\fP (int64_t pos)"
.br
.ti -1c
.RI "int64_t \fBbegin\fP ()"
.br
.ti -1c
.RI "int64_t \fBend\fP ()"
.br
.ti -1c
.RI "int64_t \fBwait\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Thread-safe, circular buffer for passing variants between threads\&. 
.SH "Member Function Documentation"
.PP 
.SS "int64_t fc::variant_stream::begin ()"
consumer api 
.SS "int64_t fc::variant_stream::free ()"
producer api 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
