.TH "find_container< C >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
find_container< C >
.SH SYNOPSIS
.br
.PP
.PP
Inherits front_insert_iterator< C >, and back_insert_iterator< C >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfind_container\fP (\fBC\fP &c)"
.br
.ti -1c
.RI "void \fBtest\fP ()"
.br
.ti -1c
.RI "\fBfind_container\fP (\fBC\fP &c)"
.br
.ti -1c
.RI "void \fBtest\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
