.TH "fixed_key" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fixed_key
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::fixed_key< Size >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<size_t Size> bool \fBaacio::operator==\fP (const \fBfixed_key\fP< Size > &c1, const \fBfixed_key\fP< Size > &c2)"
.br
.RI "Compares two \fBfixed_key\fP variables c1 and c2\&. "
.ti -1c
.RI "template<size_t Size> bool \fBaacio::operator!=\fP (const \fBfixed_key\fP< Size > &c1, const \fBfixed_key\fP< Size > &c2)"
.br
.RI "Compares two \fBfixed_key\fP variables c1 and c2\&. "
.ti -1c
.RI "template<size_t Size> bool \fBaacio::operator>\fP (const \fBfixed_key\fP< Size > &c1, const \fBfixed_key\fP< Size > &c2)"
.br
.RI "Compares two \fBfixed_key\fP variables c1 and c2\&. "
.ti -1c
.RI "template<size_t Size> bool \fBaacio::operator<\fP (const \fBfixed_key\fP< Size > &c1, const \fBfixed_key\fP< Size > &c2)"
.br
.RI "Compares two \fBfixed_key\fP variables c1 and c2\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "template<size_t Size> bool aacio::operator!= (const \fBfixed_key\fP< Size > & c1, const \fBfixed_key\fP< Size > & c2)"

.PP
Compares two \fBfixed_key\fP variables c1 and c2\&. Lexicographically compares two \fBfixed_key\fP variables c1 and c2 
.PP
\fBReturns:\fP
.RS 4
if c1 != c2, return true, otherwise false 
.RE
.PP

.SS "template<size_t Size> bool aacio::operator< (const \fBfixed_key\fP< Size > & c1, const \fBfixed_key\fP< Size > & c2)"

.PP
Compares two \fBfixed_key\fP variables c1 and c2\&. Lexicographically compares two \fBfixed_key\fP variables c1 and c2 
.PP
\fBReturns:\fP
.RS 4
if c1 < c2, return true, otherwise false 
.RE
.PP

.SS "template<size_t Size> bool aacio::operator== (const \fBfixed_key\fP< Size > & c1, const \fBfixed_key\fP< Size > & c2)"

.PP
Compares two \fBfixed_key\fP variables c1 and c2\&. Lexicographically compares two \fBfixed_key\fP variables c1 and c2 
.PP
\fBReturns:\fP
.RS 4
if c1 == c2, return true, otherwise false 
.RE
.PP

.SS "template<size_t Size> bool aacio::operator> (const \fBfixed_key\fP< Size > & c1, const \fBfixed_key\fP< Size > & c2)"

.PP
Compares two \fBfixed_key\fP variables c1 and c2\&. Lexicographically compares two \fBfixed_key\fP variables c1 and c2 
.PP
\fBReturns:\fP
.RS 4
if c1 > c2, return true, otherwise false 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
