.TH "Foo" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Foo
.SH SYNOPSIS
.br
.PP
.PP
Inherits enable_shared_from_this< Foo >\&.
.PP
Inherited by \fBBar\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBzero\fP () const"
.br
.ti -1c
.RI "int \fBidentity\fP (int v) const"
.br
.ti -1c
.RI "int \fBsum\fP (int a, int b) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnon_default_constructible\fP< int > \fBa\fP"
.br
.ti -1c
.RI "\fBoptional_like\fP< int > \fBa\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
