.TH "forward_iterator< It >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
forward_iterator< It >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::forward_iterator_tag \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef std::iterator_traits< It >::value_type \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef std::iterator_traits< It >::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef It \fBpointer\fP"
.br
.ti -1c
.RI "typedef std::iterator_traits< It >::reference \fBreference\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 It \fBbase\fP () const"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBforward_iterator\fP (It it)"
.br
.ti -1c
.RI "template<class U > TEST_CONSTEXPR_CXX14 \fBforward_iterator\fP (const \fBforward_iterator\fP< \fBU\fP > &u)"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 reference \fBoperator*\fP () const"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 pointer \fBoperator\->\fP () const"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBforward_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBforward_iterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "template<class T > void \fBoperator,\fP (\fBT\fP const &) DELETE_FUNCTION"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<class U > class \fBforward_iterator\fP"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 bool \fBoperator==\fP (const \fBforward_iterator\fP &x, const \fBforward_iterator\fP &y)"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 bool \fBoperator!=\fP (const \fBforward_iterator\fP &x, const \fBforward_iterator\fP &y)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
