.TH "FromOptionalType" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FromOptionalType
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBOpt\fP = std::optional< \fBFromOptionalType\fP >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFromOptionalType\fP (\fBFromOptionalType\fP const &)=delete"
.br
.ti -1c
.RI "template<class Dummy  = void> constexpr \fBFromOptionalType\fP (Opt &)"
.br
.ti -1c
.RI "template<class Dummy  = void> constexpr \fBFromOptionalType\fP & \fBoperator=\fP (Opt &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
