.TH "functor1" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
functor1
.SH SYNOPSIS
.br
.PP
.PP
Inherits unary_function< int, char >, unary_function< int, char >, unary_function< int, char >, unary_function< int, char >, unary_function< int, char >, unary_function< int, char >, and unary_function< int, char >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
