.TH "functor4" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
functor4
.SH SYNOPSIS
.br
.PP
.PP
Inherits unary_function< char, int >, binary_function< char, int, double >, unary_function< int, int >, binary_function< char, int, double >, unary_function< int, int >, and binary_function< char, int, double >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
