.TH "Functor03" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Functor03
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void *& \fBR\fP"
.br
.ti -1c
.RI "typedef \fBFunctor03\fP \fBC\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBF\fP (()) \fBF\fP((\fBA0\fP &)"
.br
.ti -1c
.RI "template<class A0 > \fBF\fP ((\fBA0\fP &, \fBA1\fP &), template< class \fBA0\fP, class \fBA1\fP >) \fBF\fP((\fBA0\fP &"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
