.TH "func< R >::promise_type" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
func< R >::promise_type
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfunc\fP \fBget_return_object\fP ()"
.br
.ti -1c
.RI "suspend_always \fBinitial_suspend\fP ()"
.br
.ti -1c
.RI "suspend_never \fBfinal_suspend\fP ()"
.br
.ti -1c
.RI "void \fBreturn_void\fP ()"
.br
.ti -1c
.RI "template<typename F > suspend_always \fByield_value\fP (\fBF\fP &&f)"
.br
.ti -1c
.RI "void \fBunhandled_exception\fP ()"
.br
.ti -1c
.RI "\fBfunc\fP \fBget_return_object\fP ()"
.br
.ti -1c
.RI "suspend_always \fBinitial_suspend\fP ()"
.br
.ti -1c
.RI "suspend_always \fBfinal_suspend\fP ()"
.br
.ti -1c
.RI "void \fBreturn_value\fP (R v)"
.br
.ti -1c
.RI "void \fBunhandled_exception\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBInput\fP * \fBI\fP"
.br
.ti -1c
.RI "R \fBresult\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
