.TH "G< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G< T >
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrebind\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP (int i, double j)"
.br
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP (int i, double j)"
.br
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "void \fBoperator()\fP (int i, double j)"
.br
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "void \fBoperator()\fP (int i, double j)"
.br
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "void \fBoperator()\fP (int i, double j)"
.br
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBG\fP (const \fBG\fP &g)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBn_alive\fP = 0"
.br
.ti -1c
.RI "static bool \fBop_run\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
