.TH "gbench" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gbench
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBreport\fP"
.br
.ti -1c
.RI " \fButil\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Google Benchmark tooling
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
