.TH "gen" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gen
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::ptrdiff_t \fBoperator()\fP (std::ptrdiff_t n)"
.br
.ti -1c
.RI "std::ptrdiff_t \fBoperator()\fP (std::ptrdiff_t n)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
