.TH "libraries/chain/include/aacio/chain/contracts/genesis_state.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/include/aacio/chain/contracts/genesis_state.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/chain_config\&.hpp>\fP
.br
\fC#include <aacio/chain/types\&.hpp>\fP
.br
\fC#include <aacio/chain/immutable_chain_parameters\&.hpp>\fP
.br
\fC#include <fc/crypto/sha256\&.hpp>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaacio::chain::contracts::genesis_state_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
