.TH "libraries/chain/contracts/genesis_state.cpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/contracts/genesis_state.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/contracts/genesis_state\&.hpp>\fP
.br
\fC#include <fc/smart_ref_impl\&.hpp>\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
