.TH "libraries/chain/get_config.cpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/get_config.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/get_config\&.hpp>\fP
.br
\fC#include <aacio/chain/config\&.hpp>\fP
.br
\fC#include <aacio/chain/types\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfc::variant_object\fP \fBaacio::chain::get_config\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "\fBfc::variant_object\fP aacio::chain::get_config ()"
TODO: add extra config parms 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
