.TH "getting_started" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getting_started \- Getting Started 
WebSocket++ code is available on github at https://github.com/zaphoyd/websocketpp The official project homepage lives at http://www.zaphoyd.com/websocketpp
.PP
The git repository is organized into several directories:
.PP
.IP "\(bu" 2
\fBdocs\fP: This documentation
.IP "\(bu" 2
\fBexamples\fP: Example programs that demonstrate how to build basic versions of some commonly used patterns for WebSocket clients and servers\&.
.IP "\(bu" 2
\fBtest\fP: Unit tests that confirm that the code you have works properly and help detect platform specific issues\&.
.IP "\(bu" 2
\fBtutorials\fP: Detailed walkthroughs of a select set of the example programs\&.
.IP "\(bu" 2
\fBwebsocketpp\fP: All of the library code and default configuration files\&.
.PP
.PP
WebSocket++ is a header only library\&. You can start using it by including the websocketpp source directory in your project's include path and including the appropriate WebSocket++ headers in your program\&. You may also need to include and/or link to appropriate Boost/system libraries\&. TODO: More information: Building a program with WebSocket++, Walkthroughs of the example programs
.PP
WebSocket++ includes cmake and scons scripts for building the examples and unit tests\&. Neither system is needed unless you want to build tests or examples in an automated fashion\&.
.PP
\fBUsage questions\fP should be posted to the project mailing list at http://groups.google.com/group/websocketpp/ or the IRC channel (#websocketpp on freenode)\&.
.PP
\fBBugs and issues\fP should be posted to the project GitHub issues queue: https://github.com/zaphoyd/websocketpp/issues\&.
.PP
\fBPull requests\fP on GitHub are welcome\&. Please make them against the \fCdevelop\fP branch\&.
.PP
WebSocket++ is written and maintained by Peter Thorson\&. You can contact me via GitHub messaging, IRC, or via email at websocket@zaphoyd.com\&. 
