.TH "libraries/utilities/include/aacio/utilities/git_revision.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/utilities/include/aacio/utilities/git_revision.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const char *const \fBaacio::utilities::git_revision_sha\fP"
.br
.ti -1c
.RI "const uint32_t \fBaacio::utilities::git_revision_unix_timestamp\fP"
.br
.ti -1c
.RI "const char *const \fBaacio::utilities::git_revision_description\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
