.TH "goroutine" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
goroutine
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpromise_type\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBschedule\fP (coroutine_handle<> &rh)"
.br
.ti -1c
.RI "static void \fBgo\fP (\fBgoroutine\fP)"
.br
.ti -1c
.RI "static void \fBrun_one\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int const \fBN\fP = 10"
.br
.ti -1c
.RI "static int \fBcount\fP"
.br
.ti -1c
.RI "static coroutine_handle \fBstack\fP [N]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
