.TH "HeapInfo" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HeapInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBvalid\fP"
.br
.ti -1c
.RI "bool \fBunsign\fP"
.br
.ti -1c
.RI "bool \fBfloaty\fP"
.br
.ti -1c
.RI "int \fBbits\fP"
.br
.ti -1c
.RI "AsmType \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
