.TH "programs/claac/help_text.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
programs/claac/help_text.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <fc/exception/exception\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBaacio::client::help::print_recognized_errors\fP (const \fBfc::exception\fP &e, const bool verbose_errors)"
.br
.ti -1c
.RI "bool \fBaacio::client::help::print_help_text\fP (const \fBfc::exception\fP &e)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
