.TH "plugins/http_plugin/include/aacio/http_plugin/http_plugin.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/http_plugin/include/aacio/http_plugin/http_plugin.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <appbase/application\&.hpp>\fP
.br
\fC#include <fc/exception/exception\&.hpp>\fP
.br
\fC#include <fc/reflect/reflect\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::http_plugin\fP"
.br
.ti -1c
.RI "struct \fBaacio::error_results\fP"
.br
.RI "Structure used to create JSON error responses\&. "
.ti -1c
.RI "struct \fBaacio::error_results::error_info\fP"
.br
.ti -1c
.RI "struct \fBaacio::error_results::error_info::error_detail\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBaacio::url_response_callback\fP = std::function< void(int, string)>"
.br
.RI "\fBA\fP callback function provided to a URL handler to allow it to specify the HTTP response code and body\&. "
.ti -1c
.RI "using \fBaacio::url_handler\fP = std::function< void(string, string, url_response_callback)>"
.br
.RI "Callback type for a URL handler\&. "
.ti -1c
.RI "using \fBaacio::api_description\fP = \fBstd::map\fP< string, url_handler >"
.br
.RI "An API, containing URLs and handlers\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "using \fBaacio::api_description\fP = typedef \fBstd::map\fP<string, url_handler>"

.PP
An API, containing URLs and handlers\&. An API is composed of several calls, where each call has a URL and a handler\&. The URL is the path on the web server that triggers the call, and the handler is the function which implements the API call 
.SS "using \fBaacio::url_handler\fP = typedef std::function<void(string,string,url_response_callback)>"

.PP
Callback type for a URL handler\&. URL handlers have this type
.PP
The handler must gaurantee that \fBurl_response_callback()\fP is called; otherwise, the connection will hang and result in a memory leak\&.
.PP
Arguments: url, request_body, response_callback 
.SS "using \fBaacio::url_response_callback\fP = typedef std::function<void(int,string)>"

.PP
\fBA\fP callback function provided to a URL handler to allow it to specify the HTTP response code and body\&. Arguments: response_code, response_body 
.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
