.TH "identity::contract< DeployToAccount >::certprop" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
identity::contract< DeployToAccount >::certprop
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::action_meta< code, N(certprop) >\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "account_name \fBbill_storage_to\fP"
.br
.RI "account which is paying for storage "
.ti -1c
.RI "account_name \fBcertifier\fP"
.br
.ti -1c
.RI "identity_name \fBidentity\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBcertvalue\fP > \fBvalues\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
