.TH "identity< _Tp >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
identity< _Tp >
.SH SYNOPSIS
.br
.PP
.PP
Inherits unary_function< _Tp, _Tp >, unary_function< _Tp, _Tp >, unary_function< _Tp, _Tp >, and unary_function< _Tp, _Tp >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = Tp"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr const _Tp & \fBoperator()\fP (const _Tp &__x) const"
.br
.ti -1c
.RI "constexpr const _Tp & \fBoperator()\fP (const _Tp &__x) const"
.br
.ti -1c
.RI "constexpr const _Tp & \fBoperator()\fP (const _Tp &__x) const"
.br
.ti -1c
.RI "constexpr const _Tp & \fBoperator()\fP (const _Tp &__x) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
