.TH "identity< void >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
identity< void >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class _Tp > constexpr auto \fBoperator()\fP (_Tp &&__x) const _NOEXCEPT_(noexcept(_VSTD::forward< _Tp >(__x))) \-> decltype(_VSTD::forward< _Tp >(__x))"
.br
.ti -1c
.RI "template<class _Tp > constexpr auto \fBoperator()\fP (_Tp &&__x) const _NOEXCEPT_(noexcept(_VSTD::forward< _Tp >(__x))) \-> decltype(_VSTD::forward< _Tp >(__x))"
.br
.ti -1c
.RI "template<class _Tp > constexpr auto \fBoperator()\fP (_Tp &&__x) const _NOEXCEPT_(noexcept(_VSTD::forward< _Tp >(__x))) \-> decltype(_VSTD::forward< _Tp >(__x))"
.br
.ti -1c
.RI "template<class _Tp > constexpr auto \fBoperator()\fP (_Tp &&__x) const _NOEXCEPT_(noexcept(_VSTD::forward< _Tp >(__x))) \-> decltype(_VSTD::forward< _Tp >(__x))"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
