.TH "identity::contract< DeployToAccount >::certrow" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
identity::contract< DeployToAccount >::certrow
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint64_t \fBprimary_key\fP () const"
.br
.ti -1c
.RI "key256 \fBget_key\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static key256 \fBkey\fP (uint64_t property, uint64_t trusted, uint64_t certifier)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBid\fP"
.br
.ti -1c
.RI "property_name \fBproperty\fP"
.br
.ti -1c
.RI "uint64_t \fBtrusted\fP"
.br
.ti -1c
.RI "account_name \fBcertifier\fP"
.br
.ti -1c
.RI "uint8_t \fBconfidence\fP = 0"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "\fBvector\fP< char > \fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
