.TH "identity::contract< DeployToAccount >::settrust" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
identity::contract< DeployToAccount >::settrust
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::action_meta< code, N(settrust) >\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "account_name \fBtrustor\fP"
.br
.RI "the account authorizing the trust "
.ti -1c
.RI "account_name \fBtrusting\fP"
.br
.RI "the account receiving the trust "
.ti -1c
.RI "uint8_t \fBtrust\fP = 0"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
