.TH "identity::contract< DeployToAccount >::certvalue" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
identity::contract< DeployToAccount >::certvalue
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "property_name \fBproperty\fP"
.br
.RI "name of property, base32 encoded i64 "
.ti -1c
.RI "string \fBtype\fP"
.br
.RI "defines type serialized in data "
.ti -1c
.RI "\fBvector\fP< char > \fBdata\fP"
.br
.ti -1c
.RI "string \fBmemo\fP"
.br
.RI "meta data documenting basis of certification "
.ti -1c
.RI "uint8_t \fBconfidence\fP = 1"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<uint64_t DeployToAccount> uint8_t \fBidentity::contract\fP< DeployToAccount >::certvalue::confidence = 1"
used to define liability for lies, 0 to delete 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
