.TH "impaired_network.ImpairedNetwork" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
impaired_network.ImpairedNetwork
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBmaxIndex\fP (self)"
.br
.ti -1c
.RI "def \fBexecute\fP (self, cmdInd, \fBnode\fP, testerAccount, aacio)"
.br
.ti -1c
.RI "def \fBon_exit\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBcmd\fP = 'tc qdisc add dev {dev} root tbf limit 65536 burst 65536 rate'"
.br
.ti -1c
.RI "list \fBargs\fP = ['1mbps','500kbps','100kbps','10kbps','1kbps']"
.br
.ti -1c
.RI "string \fBresetcmd\fP = 'tc qdisc del dev {dev} root'"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
