.TH "Implicit" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Implicit
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImplicit\fP (int)"
.br
.ti -1c
.RI "\fBImplicit\fP (int, int, int)"
.br
.ti -1c
.RI "\fBImplicit\fP (std::initializer_list< int >, int)"
.br
.ti -1c
.RI "\fBImplicit\fP (int)"
.br
.ti -1c
.RI "\fBImplicit\fP (int) noexcept"
.br
.ti -1c
.RI "\fBImplicit\fP (int x)"
.br
.ti -1c
.RI "\fBImplicit\fP (int x)"
.br
.ti -1c
.RI "\fBImplicit\fP (int x)"
.br
.ti -1c
.RI "\fBImplicit\fP (int x)"
.br
.ti -1c
.RI "\fBImplicit\fP (int)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
