.TH "indirect_less" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
indirect_less
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class P > bool \fBoperator()\fP (const \fBP\fP &x, const \fBP\fP &y)"
.br
.ti -1c
.RI "template<class P > bool \fBoperator()\fP (const \fBP\fP &x, const \fBP\fP &y)"
.br
.ti -1c
.RI "template<class P > bool \fBoperator()\fP (const \fBP\fP &x, const \fBP\fP &y)"
.br
.ti -1c
.RI "template<class P > bool \fBoperator()\fP (const \fBP\fP &x, const \fBP\fP &y)"
.br
.ti -1c
.RI "template<class P > bool \fBoperator()\fP (const \fBP\fP &x, const \fBP\fP &y)"
.br
.ti -1c
.RI "template<class P > bool \fBoperator()\fP (const \fBP\fP &x, const \fBP\fP &y)"
.br
.ti -1c
.RI "template<class P > bool \fBoperator()\fP (const \fBP\fP &x, const \fBP\fP &y)"
.br
.ti -1c
.RI "template<class P > bool \fBoperator()\fP (const \fBP\fP &x, const \fBP\fP &y)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
