.TH "inflate_state" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inflate_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtinfl_decompressor\fP \fBm_decomp\fP"
.br
.ti -1c
.RI "mz_uint \fBm_dict_ofs\fP"
.br
.ti -1c
.RI "mz_uint \fBm_dict_avail\fP"
.br
.ti -1c
.RI "mz_uint \fBm_first_call\fP"
.br
.ti -1c
.RI "mz_uint \fBm_has_flushed\fP"
.br
.ti -1c
.RI "int \fBm_window_bits\fP"
.br
.ti -1c
.RI "mz_uint8 \fBm_dict\fP [TINFL_LZ_DICT_SIZE]"
.br
.ti -1c
.RI "tinfl_status \fBm_last_status\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
