.TH "InitList" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InitList
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBInitList\fP (std::initializer_list< int > il)"
.br
.ti -1c
.RI "constexpr \fBInitList\fP (std::initializer_list< int > il)"
.br
.ti -1c
.RI "constexpr \fBInitList\fP (std::initializer_list< int > il)"
.br
.ti -1c
.RI "constexpr \fBInitList\fP (std::initializer_list< int > il)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::size_t \fBsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
