.TH "input_iterator< It >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
input_iterator< It >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::input_iterator_tag \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef std::iterator_traits< It >::value_type \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef std::iterator_traits< It >::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef It \fBpointer\fP"
.br
.ti -1c
.RI "typedef std::iterator_traits< It >::reference \fBreference\fP"
.br
.ti -1c
.RI "typedef std::input_iterator_tag \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef Traits::value_type \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef Traits::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef It \fBpointer\fP"
.br
.ti -1c
.RI "typedef Traits::reference \fBreference\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinput_iterator\fP (It it)"
.br
.ti -1c
.RI "reference \fBoperator*\fP () const"
.br
.ti -1c
.RI "pointer \fBoperator\->\fP () const"
.br
.ti -1c
.RI "\fBinput_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBinput_iterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 It \fBbase\fP () const"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBinput_iterator\fP (It it)"
.br
.ti -1c
.RI "template<class U , class T > TEST_CONSTEXPR_CXX14 \fBinput_iterator\fP (const \fBinput_iterator\fP< \fBU\fP, \fBT\fP > &u)"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 reference \fBoperator*\fP () const"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 pointer \fBoperator\->\fP () const"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBinput_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBinput_iterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "template<class T > void \fBoperator,\fP (\fBT\fP const &) DELETE_FUNCTION"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<class U , class T > class \fBinput_iterator\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBinput_iterator\fP &x, const \fBinput_iterator\fP &y)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBinput_iterator\fP &x, const \fBinput_iterator\fP &y)"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 bool \fBoperator==\fP (const \fBinput_iterator\fP &x, const \fBinput_iterator\fP &y)"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 bool \fBoperator!=\fP (const \fBinput_iterator\fP &x, const \fBinput_iterator\fP &y)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
