.TH "libraries/chain/include/aacio/chain/internal_exceptions.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/include/aacio/chain/internal_exceptions.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <fc/exception/exception\&.hpp>\fP
.br
\fC#include <aacio/chain/exceptions\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAAC_DECLARE_INTERNAL_EXCEPTION\fP(exc_name,  seqnum,  msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define AAC_DECLARE_INTERNAL_EXCEPTION(exc_name, seqnum, msg)"
\fBValue:\fP
.PP
.nf
FC_DECLARE_DERIVED_EXCEPTION(                                      \
      internal_ ## exc_name,                                          \
      aacio::chain::internal_exception,                            \
      3990000 + seqnum,                                               \
      msg                                                             \
      )
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
