.TH "Intrinsics::Memory" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Intrinsics::Memory
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "RUNTIME_API \fBMemory\fP (const char *inName, const \fBIR::MemoryType\fP &inType)"
.br
.ti -1c
.RI "\fBoperator Runtime::MemoryInstance *\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
