.TH "Intrinsics::GenericGlobal< type, false >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Intrinsics::GenericGlobal< type, false >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIntrinsics::Global\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBIR::ValueTypeInfo\fP< type >::\fBValue\fP \fBValue\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericGlobal\fP (const char *inName, \fBValue\fP inValue)"
.br
.ti -1c
.RI "\fBoperator Value\fP () const"
.br
.ti -1c
.RI "void \fBreset\fP (\fBValue\fP inValue)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
