.TH "Intrinsics::Table" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Intrinsics::Table
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "RUNTIME_API \fBTable\fP (const char *inName, const \fBIR::TableType\fP &inType)"
.br
.ti -1c
.RI "\fBoperator Runtime::TableInstance *\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
