.TH "Intrinsics::Global" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Intrinsics::Global
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBIntrinsics::GenericGlobal< type, isMutable >\fP, and \fBIntrinsics::GenericGlobal< type, false >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "RUNTIME_API \fBGlobal\fP (const char *inName, \fBIR::GlobalType\fP inType)"
.br
.ti -1c
.RI "RUNTIME_API void \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRuntime::GlobalInstance\fP * \fBglobal\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "void * \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
