.TH "ipc_perm" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ipc_perm
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "key_t \fB__ipc_perm_key\fP"
.br
.ti -1c
.RI "uid_t \fBuid\fP"
.br
.ti -1c
.RI "gid_t \fBgid\fP"
.br
.ti -1c
.RI "uid_t \fBcuid\fP"
.br
.ti -1c
.RI "gid_t \fBcgid\fP"
.br
.ti -1c
.RI "mode_t \fBmode\fP"
.br
.ti -1c
.RI "int \fB__ipc_perm_seq\fP"
.br
.ti -1c
.RI "long \fB__pad1\fP"
.br
.ti -1c
.RI "long \fB__pad2\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
