.TH "IR::CodeValidationStreamImpl" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR::CodeValidationStreamImpl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCodeValidationStreamImpl\fP (const \fBModule\fP &module, const \fBFunctionDef\fP &functionDef)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFunctionValidationContext\fP \fBfunctionContext\fP"
.br
.ti -1c
.RI "\fBOperatorPrinter\fP \fBoperatorPrinter\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
