.TH "IR::DisassemblyNames" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR::DisassemblyNames
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFunction\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::vector\fP< std::string > \fBtypes\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBFunction\fP > \fBfunctions\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< std::string > \fBtables\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< std::string > \fBmemories\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< std::string > \fBglobals\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
