.TH "IR::Import< Type >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR::Import< Type >
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBType\fP \fBtype\fP"
.br
.ti -1c
.RI "std::string \fBmoduleName\fP"
.br
.ti -1c
.RI "std::string \fBexportName\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
