.TH "IR::LoadOrStoreImm< naturalAlignmentLog2 >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR::LoadOrStoreImm< naturalAlignmentLog2 >
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "U8 \fBalignmentLog2\fP"
.br
.ti -1c
.RI "U32 \fBoffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
