.TH "IR::Module" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR::Module
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::vector\fP< const \fBFunctionType\fP * > \fBtypes\fP"
.br
.ti -1c
.RI "\fBIndexSpace\fP< \fBFunctionDef\fP, \fBIndexedFunctionType\fP > \fBfunctions\fP"
.br
.ti -1c
.RI "\fBIndexSpace\fP< \fBTableDef\fP, \fBTableType\fP > \fBtables\fP"
.br
.ti -1c
.RI "\fBIndexSpace\fP< \fBMemoryDef\fP, \fBMemoryType\fP > \fBmemories\fP"
.br
.ti -1c
.RI "\fBIndexSpace\fP< \fBGlobalDef\fP, \fBGlobalType\fP > \fBglobals\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBExport\fP > \fBexports\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBDataSegment\fP > \fBdataSegments\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBTableSegment\fP > \fBtableSegments\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBUserSection\fP > \fBuserSections\fP"
.br
.ti -1c
.RI "Uptr \fBstartFunctionIndex\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
