.TH "IR::OperatorDecoderStream" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR::OperatorDecoderStream
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOperatorDecoderStream\fP (const \fBstd::vector\fP< U8 > &codeBytes)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "template<typename Visitor > Visitor::Result \fBdecodeOp\fP (Visitor &visitor)"
.br
.ti -1c
.RI "template<typename Visitor > Visitor::Result \fBdecodeOpWithoutConsume\fP (Visitor &visitor)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
