.TH "IR::SizeConstraints" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR::SizeConstraints
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "U64 \fBmin\fP"
.br
.ti -1c
.RI "U64 \fBmax\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSizeConstraints\fP &left, const \fBSizeConstraints\fP &right)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBSizeConstraints\fP &left, const \fBSizeConstraints\fP &right)"
.br
.ti -1c
.RI "bool \fBisSubset\fP (const \fBSizeConstraints\fP &super, const \fBSizeConstraints\fP &sub)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
