.TH "IR::TableType" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR::TableType
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTableType\fP (TableElementType inElementType, bool inIsShared, \fBSizeConstraints\fP inSize)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TableElementType \fBelementType\fP"
.br
.ti -1c
.RI "bool \fBisShared\fP"
.br
.ti -1c
.RI "\fBSizeConstraints\fP \fBsize\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBTableType\fP &left, const \fBTableType\fP &right)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBTableType\fP &left, const \fBTableType\fP &right)"
.br
.ti -1c
.RI "bool \fBisSubset\fP (const \fBTableType\fP &super, const \fBTableType\fP &sub)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
