.TH "is_specialization< Templ< ID1 >, Other >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_specialization< Templ< ID1 >, Other >
.SH SYNOPSIS
.br
.PP
.PP
Inherits false_type, and false_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
