.TH "IsSmallObject< _Tp >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsSmallObject< _Tp >
.SH SYNOPSIS
.br
.PP
.PP
Inherits declval< Type &>value, and true\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "return \fBtrue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
