.TH "IteratorDebugChecks::BasicContainerChecks< Container, CT, Helper >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IteratorDebugChecks::BasicContainerChecks< Container, CT, Helper >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBvalue_type\fP = typename Container::value_type"
.br
.ti -1c
.RI "using \fBiterator\fP = typename Container::iterator"
.br
.ti -1c
.RI "using \fBconst_iterator\fP = typename Container::const_iterator"
.br
.ti -1c
.RI "using \fBallocator_type\fP = typename Container::allocator_type"
.br
.ti -1c
.RI "using \fBtraits\fP = std::iterator_traits< iterator >"
.br
.ti -1c
.RI "using \fBcategory\fP = typename traits::iterator_category"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBrun\fP ()"
.br
.ti -1c
.RI "static void \fBrun_iterator_tests\fP ()"
.br
.ti -1c
.RI "static void \fBrun_container_tests\fP ()"
.br
.ti -1c
.RI "static void \fBrun_allocator_aware_tests\fP ()"
.br
.ti -1c
.RI "static Container \fBmakeContainer\fP (int size, allocator_type \fBA\fP=allocator_type())"
.br
.ti -1c
.RI "static value_type \fBmakeValueType\fP (int value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr bool \fBIsBiDir\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<class Container, ContainerType CT, class Helper = ContainerDebugHelper<Container>> constexpr bool \fBIteratorDebugChecks::BasicContainerChecks\fP< Container, CT, Helper >::IsBiDir\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
      std::is_convertible<category, std::bidirectional_iterator_tag>::value
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
