.TH "libraries/utilities/include/aacio/utilities/key_conversion.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/utilities/include/aacio/utilities/key_conversion.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <fc/crypto/elliptic\&.hpp>\fP
.br
\fC#include <fc/optional\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBaacio::utilities::key_to_wif\fP (const \fBfc::sha256\fP &private_secret)"
.br
.ti -1c
.RI "std::string \fBaacio::utilities::key_to_wif\fP (const \fBfc::ecc::private_key\fP &key)"
.br
.ti -1c
.RI "\fBfc::optional\fP< \fBfc::ecc::private_key\fP > \fBaacio::utilities::wif_to_key\fP (const std::string &wif_key)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
