.TH "L1" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
L1
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBlock\fP ()"
.br
.ti -1c
.RI "bool \fBtry_lock\fP ()"
.br
.ti -1c
.RI "void \fBunlock\fP ()"
.br
.ti -1c
.RI "bool \fBlocked\fP () const"
.br
.ti -1c
.RI "bool \fBtry_lock\fP ()"
.br
.ti -1c
.RI "void \fBunlock\fP ()"
.br
.ti -1c
.RI "bool \fBlocked\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
