.TH "large_type< Dummy >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
large_type< Dummy >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlarge_type\fP (int val=0)"
.br
.ti -1c
.RI "\fBlarge_type\fP (int, int val, int)"
.br
.ti -1c
.RI "\fBlarge_type\fP (std::initializer_list< int > il)"
.br
.ti -1c
.RI "\fBlarge_type\fP (\fBlarge_type\fP const &\fBother\fP)"
.br
.ti -1c
.RI "\fBlarge_type\fP (\fBlarge_type\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBlarge_type\fP (\fBlarge_type\fP &&\fBother\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBcount\fP = 0"
.br
.ti -1c
.RI "static int \fBcopied\fP = 0"
.br
.ti -1c
.RI "static int \fBmoved\fP = 0"
.br
.ti -1c
.RI "static int \fBconst_copied\fP = 0"
.br
.ti -1c
.RI "static int \fBnon_const_copied\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
