.TH "lconv" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lconv
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBdecimal_point\fP"
.br
.ti -1c
.RI "char * \fBthousands_sep\fP"
.br
.ti -1c
.RI "char * \fBgrouping\fP"
.br
.ti -1c
.RI "char * \fBint_curr_symbol\fP"
.br
.ti -1c
.RI "char * \fBcurrency_symbol\fP"
.br
.ti -1c
.RI "char * \fBmon_decimal_point\fP"
.br
.ti -1c
.RI "char * \fBmon_thousands_sep\fP"
.br
.ti -1c
.RI "char * \fBmon_grouping\fP"
.br
.ti -1c
.RI "char * \fBpositive_sign\fP"
.br
.ti -1c
.RI "char * \fBnegative_sign\fP"
.br
.ti -1c
.RI "char \fBint_frac_digits\fP"
.br
.ti -1c
.RI "char \fBfrac_digits\fP"
.br
.ti -1c
.RI "char \fBp_cs_precedes\fP"
.br
.ti -1c
.RI "char \fBp_sep_by_space\fP"
.br
.ti -1c
.RI "char \fBn_cs_precedes\fP"
.br
.ti -1c
.RI "char \fBn_sep_by_space\fP"
.br
.ti -1c
.RI "char \fBp_sign_posn\fP"
.br
.ti -1c
.RI "char \fBn_sign_posn\fP"
.br
.ti -1c
.RI "char \fBint_p_cs_precedes\fP"
.br
.ti -1c
.RI "char \fBint_p_sep_by_space\fP"
.br
.ti -1c
.RI "char \fBint_n_cs_precedes\fP"
.br
.ti -1c
.RI "char \fBint_n_sep_by_space\fP"
.br
.ti -1c
.RI "char \fBint_p_sign_posn\fP"
.br
.ti -1c
.RI "char \fBint_n_sign_posn\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
