.TH "libcxx.test.format.LibcxxTestFormat" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcxx.test.format.LibcxxTestFormat
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, cxx, use_verify_for_fail, execute_external, executor, exec_env)"
.br
.ti -1c
.RI "def \fBgetTestsInDirectory\fP (self, testSuite, path_in_suite, litConfig, localConfig)"
.br
.ti -1c
.RI "def \fBexecute\fP (self, \fBtest\fP, lit_config)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcxx\fP"
.br
.ti -1c
.RI "\fBuse_verify_for_fail\fP"
.br
.ti -1c
.RI "\fBexecute_external\fP"
.br
.ti -1c
.RI "\fBexecutor\fP"
.br
.ti -1c
.RI "\fBexec_env\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Custom test format handler for use with the test format use by libc++.

Tests fall into two categories:
  FOO.pass.cpp - Executable test which should compile, run, and exit with
                 code 0.
  FOO.fail.cpp - Negative test case which is expected to fail compilation.
  FOO.sh.cpp   - A test that uses LIT's ShTest format.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
