.TH "libcxx.util.ExecuteCommandTimeoutException" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcxx.util.ExecuteCommandTimeoutException
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, msg, out, err, exitCode)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmsg\fP"
.br
.ti -1c
.RI "\fBout\fP"
.br
.ti -1c
.RI "\fBerr\fP"
.br
.ti -1c
.RI "\fBexitCode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
