.TH "libcxx.test.executor.Executor" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcxx.test.executor.Executor
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBlibcxx\&.test\&.executor\&.LocalExecutor\fP, \fBlibcxx\&.test\&.executor\&.PostfixExecutor\fP, \fBlibcxx\&.test\&.executor\&.PrefixExecutor\fP, and \fBlibcxx\&.test\&.executor\&.RemoteExecutor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBrun\fP (self, exe_path, cmd, local_cwd, file_deps=None, env=None)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def libcxx\&.test\&.executor\&.Executor\&.run ( self,  exe_path,  cmd,  local_cwd,  file_deps = \fCNone\fP,  env = \fCNone\fP)"

.PP
.nf
Execute a command.
    Be very careful not to change shared state in this function.
    Executor objects are shared between python processes in `lit -jN`.
Args:
    exe_path: str:    Local path to the executable to be run
    cmd: [str]:       subprocess.call style command
    local_cwd: str:   Local path to the working directory
    file_deps: [str]: Files required by the test
    env: {str: str}:  Environment variables to execute under
Returns:
    cmd, out, err, exitCode

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
