.TH "libcxx.test.executor.LocalExecutor" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcxx.test.executor.LocalExecutor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlibcxx\&.test\&.executor\&.Executor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBrun\fP (self, exe_path, cmd=None, work_dir='\&.', file_deps=None, env=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBis_windows\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
