.TH "libcxx.test.target_info.DarwinLocalTI" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcxx.test.target_info.DarwinLocalTI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlibcxx\&.test\&.target_info\&.DefaultTargetInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, full_config)"
.br
.ti -1c
.RI "def \fBis_host_macosx\fP (self)"
.br
.ti -1c
.RI "def \fBget_macosx_version\fP (self)"
.br
.ti -1c
.RI "def \fBget_sdk_version\fP (self, name)"
.br
.ti -1c
.RI "def \fBget_platform\fP (self)"
.br
.ti -1c
.RI "def \fBadd_locale_features\fP (self, features)"
.br
.ti -1c
.RI "def \fBadd_cxx_compile_flags\fP (self, flags)"
.br
.ti -1c
.RI "def \fBadd_cxx_link_flags\fP (self, flags)"
.br
.ti -1c
.RI "def \fBconfigure_env\fP (self, env)"
.br
.ti -1c
.RI "def \fBallow_cxxabi_link\fP (self)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
