.TH "libcxx.test.executor.PrefixExecutor" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcxx.test.executor.PrefixExecutor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlibcxx\&.test\&.executor\&.Executor\fP\&.
.PP
Inherited by \fBlibcxx\&.test\&.executor\&.TimeoutExecutor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, commandPrefix, chain)"
.br
.ti -1c
.RI "def \fBrun\fP (self, exe_path, cmd=None, work_dir='\&.', file_deps=None, env=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcommandPrefix\fP"
.br
.ti -1c
.RI "\fBchain\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Prefix an executor with some other command wrapper.

Most useful for setting ulimits on commands, or running an emulator like
qemu and valgrind.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
