.TH "libcxx.test.executor.PostfixExecutor" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcxx.test.executor.PostfixExecutor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlibcxx\&.test\&.executor\&.Executor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, commandPostfix, chain)"
.br
.ti -1c
.RI "def \fBrun\fP (self, exe_path, cmd=None, work_dir='\&.', file_deps=None, env=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcommandPostfix\fP"
.br
.ti -1c
.RI "\fBchain\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Postfix an executor with some args.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
