.TH "libcxx.test.executor.RemoteExecutor" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcxx.test.executor.RemoteExecutor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlibcxx\&.test\&.executor\&.Executor\fP\&.
.PP
Inherited by \fBlibcxx\&.test\&.executor\&.SSHExecutor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBremote_temp_dir\fP (self)"
.br
.ti -1c
.RI "def \fBremote_temp_file\fP (self)"
.br
.ti -1c
.RI "def \fBcopy_in\fP (self, local_srcs, remote_dsts)"
.br
.ti -1c
.RI "def \fBdelete_remote\fP (self, remote)"
.br
.ti -1c
.RI "def \fBrun\fP (self, exe_path, cmd=None, work_dir='\&.', file_deps=None, env=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlocal_run\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
