.TH "libcxx.test.executor.TimeoutExecutor" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcxx.test.executor.TimeoutExecutor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlibcxx\&.test\&.executor\&.PrefixExecutor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, duration, chain)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
.nf
Execute another action under a timeout.

Deprecated. http://reviews.llvm.org/D6584 adds timeouts to LIT.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
