.TH "libcxx.test.target_info.FreeBSDLocalTI" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcxx.test.target_info.FreeBSDLocalTI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlibcxx\&.test\&.target_info\&.DefaultTargetInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, full_config)"
.br
.ti -1c
.RI "def \fBadd_locale_features\fP (self, features)"
.br
.ti -1c
.RI "def \fBadd_cxx_link_flags\fP (self, flags)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
