.TH "Lit" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lit
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLit\fP (const \fBNFA::CharSet\fP &inCharSet)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNFA::CharSet\fP \fBcharSet\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
