.TH "LLVMJIT::NullResolver" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LLVMJIT::NullResolver
.SH SYNOPSIS
.br
.PP
.PP
Inherits JITSymbolResolver\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual llvm::JITSymbol \fBfindSymbol\fP (const std::string &name) override"
.br
.ti -1c
.RI "virtual llvm::JITSymbol \fBfindSymbolInLogicalDylib\fP (const std::string &name) override"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBNullResolver\fP \fBsingleton\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
