.TH "LLVMJIT::EmitModuleContext" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LLVMJIT::EmitModuleContext
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEmitModuleContext\fP (const \fBModule\fP &inModule, \fBModuleInstance\fP *inModuleInstance)"
.br
.ti -1c
.RI "llvm::Module * \fBemit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBModule\fP & \fBmodule\fP"
.br
.ti -1c
.RI "\fBModuleInstance\fP * \fBmoduleInstance\fP"
.br
.ti -1c
.RI "llvm::Module * \fBllvmModule\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< llvm::Function * > \fBfunctionDefs\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< llvm::Constant * > \fBimportedFunctionPointers\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< llvm::Constant * > \fBglobalPointers\fP"
.br
.ti -1c
.RI "llvm::Constant * \fBdefaultTablePointer\fP"
.br
.ti -1c
.RI "llvm::Constant * \fBdefaultTableMaxElementIndex\fP"
.br
.ti -1c
.RI "llvm::Constant * \fBdefaultMemoryBase\fP"
.br
.ti -1c
.RI "llvm::Constant * \fBdefaultMemoryEndOffset\fP"
.br
.ti -1c
.RI "llvm::DIBuilder \fBdiBuilder\fP"
.br
.ti -1c
.RI "llvm::DICompileUnit * \fBdiCompileUnit\fP"
.br
.ti -1c
.RI "llvm::DIFile * \fBdiModuleScope\fP"
.br
.ti -1c
.RI "llvm::DIType * \fBdiValueTypes\fP [(Uptr) ValueType::num]"
.br
.ti -1c
.RI "llvm::MDNode * \fBlikelyFalseBranchWeights\fP"
.br
.ti -1c
.RI "llvm::MDNode * \fBlikelyTrueBranchWeights\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
