.TH "LLVMJIT::EmitFunctionContext::ControlContext" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LLVMJIT::EmitFunctionContext::ControlContext
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP : U8 { \fBfunction\fP, \fBblock\fP, \fBifThen\fP, \fBifElse\fP, \fBloop\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBType\fP \fBtype\fP"
.br
.ti -1c
.RI "llvm::BasicBlock * \fBendBlock\fP"
.br
.ti -1c
.RI "llvm::PHINode * \fBendPHI\fP"
.br
.ti -1c
.RI "llvm::BasicBlock * \fBelseBlock\fP"
.br
.ti -1c
.RI "ResultType \fBresultType\fP"
.br
.ti -1c
.RI "Uptr \fBouterStackSize\fP"
.br
.ti -1c
.RI "Uptr \fBouterBranchTargetStackSize\fP"
.br
.ti -1c
.RI "bool \fBisReachable\fP"
.br
.ti -1c
.RI "bool \fBisElseReachable\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
