.TH "LLVMJIT::JITModule" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LLVMJIT::JITModule
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLLVMJIT::JITUnit\fP, and \fBLLVMJIT::JITModuleBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJITModule\fP (\fBModuleInstance\fP *inModuleInstance)"
.br
.ti -1c
.RI "void \fBnotifySymbolLoaded\fP (const char *name, Uptr baseAddress, Uptr numBytes, \fBstd::map\fP< U32, U32 > &&offsetToOpIndexMap) override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBModuleInstance\fP * \fBmoduleInstance\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBJITSymbol\fP * > \fBfunctionDefSymbols\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
