.TH "LLVMJIT::EmitFunctionContext::BranchTarget" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LLVMJIT::EmitFunctionContext::BranchTarget
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ResultType \fBargumentType\fP"
.br
.ti -1c
.RI "llvm::BasicBlock * \fBblock\fP"
.br
.ti -1c
.RI "llvm::PHINode * \fBphi\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
