.TH "locale" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
locale
.SH SYNOPSIS
.br
.PP
.PP
Inherits __imp public facet\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__imp\fP (size_t refs=0)"
.br
.ti -1c
.RI "\fB__imp\fP (const string &name, size_t refs=0)"
.br
.ti -1c
.RI "\fB__imp\fP (const __imp &)"
.br
.ti -1c
.RI "\fB__imp\fP (const __imp &, const string &, locale::category c)"
.br
.ti -1c
.RI "\fB__imp\fP (const __imp &\fBother\fP, const __imp &one, locale::category c)"
.br
.ti -1c
.RI "\fB__imp\fP (const __imp &, facet *f, long id)"
.br
.ti -1c
.RI "const string & \fBname\fP () const"
.br
.ti -1c
.RI "bool \fBhas_facet\fP (long id) const"
.br
.ti -1c
.RI "const locale::facet * \fBuse_facet\fP (long id) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const \fBlocale\fP & \fBmake_classic\fP ()"
.br
.ti -1c
.RI "static \fBlocale\fP & \fBmake_global\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
