.TH "programs/claac/localize.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
programs/claac/localize.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <libintl\&.h>\fP
.br
\fC#include <fc/variant\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_\fP(str)   str"
.br
.ti -1c
.RI "#define \fBlocalized\fP(str, \&.\&.\&.)   localized_with_variant((str), \fBfc::mutable_variant_object\fP() __VA_ARGS__ )"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "auto \fBaacio::client::localize::localized_with_variant\fP (const char *raw_fmt, const \fBfc::variant_object\fP &args)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
