.TH "lossy_network.LossyNetwork" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lossy_network.LossyNetwork
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBmaxIndex\fP (self)"
.br
.ti -1c
.RI "def \fBexecute\fP (self, cmdInd, \fBnode\fP, testerAccount, aacio)"
.br
.ti -1c
.RI "def \fBon_exit\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBcmd\fP = 'tc qdisc add dev {dev} root netem loss'"
.br
.ti -1c
.RI "list \fBargs\fP = ['0%', '1%', '10%', '50%', '90%', '99%']"
.br
.ti -1c
.RI "string \fBresetcmd\fP = 'tc qdisc del dev {dev} root'"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
