.TH "tests/common/main.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/common/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <boost/test/included/unit_test\&.hpp>\fP
.br
\fC#include <fc/log/logger\&.hpp>\fP
.br
\fC#include <aacio/chain/exceptions\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtranslate_fc_exception\fP (const \fBfc::exception\fP &e)"
.br
.ti -1c
.RI "boost::unit_test::test_suite * \fBinit_unit_test_suite\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
