.TH "MakeTestType< CharT >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakeTestType< CharT >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBvalue_type\fP = CharT"
.br
.ti -1c
.RI "using \fBstring_type\fP = std::basic_string< CharT >"
.br
.ti -1c
.RI "using \fBstring_type2\fP = std::basic_string< CharT, std::char_traits< CharT >, min_allocator< CharT > >"
.br
.ti -1c
.RI "using \fBstring_view_type\fP = std::basic_string_view< CharT >"
.br
.ti -1c
.RI "using \fBstring_view_type2\fP = std::basic_string_view< CharT, \fBconstexpr_char_traits\fP< CharT > >"
.br
.ti -1c
.RI "using \fBcstr_type\fP = CharT *const"
.br
.ti -1c
.RI "using \fBconst_cstr_type\fP = const CharT *"
.br
.ti -1c
.RI "using \fBarray_type\fP = CharT[25]"
.br
.ti -1c
.RI "using \fBconst_array_type\fP = const CharT[25]"
.br
.ti -1c
.RI "using \fBiter_type\fP = \fBinput_iterator\fP< CharT * >"
.br
.ti -1c
.RI "using \fBbad_iter_type\fP = \fBinput_iterator\fP< signed char * >"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class TestT > static void \fBAssertPathable\fP ()"
.br
.ti -1c
.RI "template<class TestT > static void \fBAssertNotPathable\fP ()"
.br
.ti -1c
.RI "static void \fBTest\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
