.TH "malloc_allocator< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
malloc_allocator< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBmalloc_allocator_base\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class U > \fBmalloc_allocator\fP (\fBmalloc_allocator\fP< \fBU\fP >) TEST_NOEXCEPT"
.br
.ti -1c
.RI "\fBT\fP * \fBallocate\fP (std::size_t n)"
.br
.ti -1c
.RI "void \fBdeallocate\fP (\fBT\fP *p, std::size_t)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (\fBmalloc_allocator\fP, \fBmalloc_allocator\fP)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBmalloc_allocator\fP x, \fBmalloc_allocator\fP y)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
