.TH "margin" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
margin
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBasset\fP \fBlent\fP"
.br
.ti -1c
.RI "symbol_type \fBcollateral_symbol\fP"
.br
.ti -1c
.RI "real_type \fBleast_collateralized_rate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
