.TH "margin_state" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
margin_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBextended_asset\fP \fBtotal_lendable\fP"
.br
.ti -1c
.RI "\fBextended_asset\fP \fBtotal_lent\fP"
.br
.ti -1c
.RI "double \fBleast_collateralized\fP = 0"
.br
.ti -1c
.RI "double \fBinterest_shares\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
