.TH "contracts/aaciolib/math.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/aaciolib/math.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aaciolib/math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaacio::uint128\fP"
.br
.RI "\fBA\fP struct that wraps \fBuint128\fP integer and defines common operator overloads\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBaacio::multeq\fP (uint128_t &self, const uint128_t &\fBother\fP)"
.br
.RI "wraps multeq_i128 from \fBMath C API\fP "
.ti -1c
.RI "void \fBaacio::diveq\fP (uint128_t &self, const uint128_t &\fBother\fP)"
.br
.RI "wraps diveq_i128 from \fBMath C API\fP "
.ti -1c
.RI "template<typename T > \fBT\fP \fBaacio::min\fP (const \fBT\fP &a, const \fBT\fP &b)"
.br
.RI "Defined similar to \fBstd::min()\fP "
.ti -1c
.RI "template<typename T > \fBT\fP \fBaacio::max\fP (const \fBT\fP &a, const \fBT\fP &b)"
.br
.RI "Define similar to \fBstd::max()\fP "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
