.TH "md_contracts_aaciolib_mainpage" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_contracts_aaciolib_mainpage \- Welcome to the AAC\&.IO Documentation 

.PP
\fBNote:\fP
.RS 4
This documentation is in progress and subject to change due to rapid development\&. Please report inaccuracies identified to the \fCAAC\&.IO Developer Telegram Group\fP
.RE
.PP
.SS "AAC\&.IO"
.PP
.IP "\(bu" 2
\fCAdditional resources - Github Readme\fP
.PP
.PP
.SS "Smart Contract Developers"
.PP
.IP "\(bu" 2
\fBRPC Interface\fP
.IP "\(bu" 2
\fBSmart Contract API Reference\fP
.IP "  \(bu" 4
\fBAccount API\fP - Define API for querying account data
.IP "  \(bu" 4
\fBChain API\fP - Define API for querying internal chain state
.IP "  \(bu" 4
\fBDatabase API\fP - APIs that store and retreive data on the blockchainAAC\&.IO organizes data according to the following broad structure
.IP "  \(bu" 4
\fBMath API\fP - Defines common math function
.IP "  \(bu" 4
\fBAction API\fP - Defines API for querying action properties
.IP "  \(bu" 4
\fBmemoryapi\fP - Defines common memory functions
.IP "  \(bu" 4
\fBConsole API\fP - Enables applications to log/print text messages
.IP "  \(bu" 4
\fBSystem API\fP - Define API for interating with system level intrinsics
.IP "  \(bu" 4
\fBToken API\fP - Defines the ABI for interfacing with standard-compatible token messages and database tables
.IP "  \(bu" 4
\fBtransaction API\fP - Define API for sending transactions and inline messages
.IP "  \(bu" 4
\fBBuiltin Types\fP - Specifies typedefs and aliases 
.PP

.PP

