.TH "md_contracts_aacio.system__r_e_a_d_m_e" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_contracts_aacio.system__r_e_a_d_m_e \- aacio\&.system 
This contract enables users to stake tokens, and then configure and vote on producers and worker proposals\&.
.PP
Users can also proxy their voting influence to other users\&.
.PP
The state of this contract is read to determine the 31 active block producers\&.
.PP
Actions: The naming convention is codeaccount::actionname followed by a list of paramters\&.
.PP
Indicates that a particular account wishes to become a producer 
.SS "aacio\&.system::cfgproducer account config"
.PP
.IP "\(bu" 2
\fBaccount\fP the producer account to update
.IP "\(bu" 2
updates the configuration settings for a particular producer, these
.PP
.PP
\fBStorage\fP changes are billed to 'account'
.PP
.SS "aacio\&.system::okproducer account producer vote"
.PP
.IP "\(bu" 2
\fBaccount\fP the account which is doing the voting
.IP "\(bu" 2
\fBproducer\fP the producer which is being voted for (or unvoted for)
.IP "\(bu" 2
\fBvote\fP true if the producer should be voted for, false if not
.PP
.PP
Each account has a maximum number of votes it can maintain\&. \fBStorage\fP changes will be billed to 'account'
.PP
.SS "aacio\&.system::setproxy account proxy"
.PP
.IP "\(bu" 2
\fBaccount\fP the account which is updating it's proxy
.IP "\(bu" 2
\fBproxy\fP the account which will have the power to vote account's stake
.PP
.PP
All current votes are removed and a new proxy link is created\&. The votes for every producer the proxy has voted for are updated immediately\&.
.PP
\fBStorage\fP changes will be billed to 'account'
.PP
.SS "aacio\&.system::unstake account quantity"
.PP
.IP "\(bu" 2
\fBaccount\fP - the account which is requesting their balance be unstaked
.IP "\(bu" 2
\fBquantity\fP - the quantity which will be unstaked, unstaked tokens lose voting influence immediately
.IP "\(bu" 2
in order to unstake tokens, an account must request them\&. The user will receive them over time via weekly withdraws\&. The length of time will be configured by the median time as set by the active producers\&.
.IP "\(bu" 2
If this is called while in the process of unstaking, the currently pending unstake is canceled as if quantity were 0, then it is applied as if a new unstake request was made\&.
.IP "\(bu" 2
all producers this 'from' has voted for will have their votes updated immediately\&.
.IP "\(bu" 2
bandwidth and storage for the deferred transaction will be billed to 'from'
.PP
.PP
.SS "aacio\&.system::withdraw account"
.PP
.IP "\(bu" 2
this action can only be triggered by aacio\&.system via a deferred transaction generated by unstake
.IP "\(bu" 2
this will generate an inline aacio\&.token::transfer call from=aacio\&.system to=account and amount equal to the next withdraw increment
.IP "\(bu" 2
this will generate another deferred withdraw to continue the process if there are still withdraws to be made
.PP
.PP
.SS "aacio\&.system::transfer from to amount memo"
.PP
.IP "\(bu" 2
decrements balance of from if amount <= balance
.IP "\(bu" 2
increments balance of to by amount
.IP "\(bu" 2
memo is ignored
.PP
.PP
.SS "aacio\&.system::stakevote account amount"
.PP
.IP "\(bu" 2
the primary currency of aacio is controlled by the token contract which enables users to transfer balances from one user to another\&. The receiver is notified on incoming balances and the vote contract will stake the tokens on receipt\&.
.IP "\(bu" 2
all producers this 'from' has voted for will have their votes updated immediately\&.
.PP
.PP
.SS "aacio\&.system::onblock account blocktime blocknum"
.PP
.IP "\(bu" 2
this special action is triggered when a block is applied by the given producer and cannot be generated from any other source\&. It is used to pay producers and calculate missed blocks of other producers\&.
.IP "\(bu" 2
producer pay is deposited into the producer's stake balance and can be withdrawn over time\&.
.IP "\(bu" 2
if blocknum is the start of a new round this may update the active producer config from the producer votes\&.
.PP
.PP
.SS "aacio\&.system::freeze producer accounts true|false"
.PP
.IP "\(bu" 2
requires permission of the  account
.IP "\(bu" 2
if an account is frozen, all authorizations of that account are rejected and the code for that account will not be run
.PP
.PP
.SS "aacio\&.system::paystandby producer"
.PP
.IP "\(bu" 2
every block some amount of tokens is paid
.IP "\(bu" 2
at most once per day a producer may claim a percentage of the standby pay equal to their totalvotes / allvotes 
.PP

