.TH "md_externals_binaryen__contributing" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_externals_binaryen__contributing \- Contributing to WebAssembly 
Interested in participating? Please follow \fBhttps:\fP//github\&.com/WebAssembly/design/blob/master/Contributing\&.md 'the same contributing guidelines as the design repository'\&.
.PP
Also, please be sure to read \fBthe README\&.md\fP for this repository\&. 
