.TH "md_libraries_fc_vendor_websocketpp_tutorials_broadcast_tutorial_broadcast_tutorial" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_libraries_fc_vendor_websocketpp_tutorials_broadcast_tutorial_broadcast_tutorial \- Broadcast Tutorial 
This tutorial will dig into some more nitty gritty details on how to build high scalability, high performance websocket servers for broadcast like workflows\&.
.PP
Will go into features like:
.IP "\(bu" 2
minimizing work done in handlers
.IP "\(bu" 2
using asio thread pool mode
.IP "\(bu" 2
teaming multiple endpoints
.IP "\(bu" 2
setting accept queue depth
.IP "\(bu" 2
tuning compile time buffer sizes
.IP "\(bu" 2
prepared messages
.IP "\(bu" 2
flow control
.IP "\(bu" 2
basic operating system level tuning, particularly increasing file descriptor limits\&.
.IP "\(bu" 2
measuring performance with wsperf / autobahn
.IP "\(bu" 2
tuning permessage-deflate compression settings 
.PP

