.TH "md_libraries_fc_vendor_websocketpp_readme" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_libraries_fc_vendor_websocketpp_readme \- WebSocket++ (0\&.7\&.0) 
WebSocket++ is a header only C++ library that implements RFC6455 The WebSocket Protocol\&. It allows integrating WebSocket client and server functionality into C++ programs\&. It uses interchangeable network transport modules including one based on raw char buffers, one based on C++ iostreams, and one based on Asio (either via Boost or standalone)\&. End users can write additional transport policies to support other networking or event libraries as needed\&.
.PP
.SH "Major Features "
.PP
.PP
.IP "\(bu" 2
Full support for RFC6455
.IP "\(bu" 2
Partial support for Hixie 76 / Hybi 00, 07-17 draft specs (server only)
.IP "\(bu" 2
Message/event based interface
.IP "\(bu" 2
Supports secure WebSockets (TLS), IPv6, and explicit proxies\&.
.IP "\(bu" 2
Flexible dependency management (C++11 Standard Library or Boost)
.IP "\(bu" 2
Interchangeable network transport modules (raw, iostream, Asio, or custom)
.IP "\(bu" 2
Portable/cross platform (Posix/Windows, 32/64bit, Intel/ARM/PPC)
.IP "\(bu" 2
Thread-safe
.PP
.PP
.SH "Get Involved "
.PP
.PP
\fC\fP.PP
\fBProject Website\fP http://www.zaphoyd.com/websocketpp/
.PP
\fBUser Manual\fP http://www.zaphoyd.com/websocketpp/manual/
.PP
\fBGitHub Repository\fP https://github.com/zaphoyd/websocketpp/
.PP
GitHub pull requests should be submitted to the \fCdevelop\fP branch\&.
.PP
\fBAnnouncements Mailing List\fP http://groups.google.com/group/websocketpp-announcements/
.PP
\fBIRC Channel\fP \fBwebsocketpp\fP (freenode)
.PP
\fBDiscussion / Development / Support Mailing List / Forum\fP http://groups.google.com/group/websocketpp/
.PP
.SH "Author "
.PP
.PP
Peter Thorson - websocketpp@zaphoyd.com 
