.TH "md_libraries_softfloat__r_e_a_d_m_e" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_libraries_softfloat__r_e_a_d_m_e \- Package Overview for Berkeley SoftFloat Release 3e 
John R\&. Hauser
.br
 2018 January 20
.PP
Berkeley SoftFloat is a software implementation of binary floating-point that conforms to the IEEE Standard for Floating-Point Arithmetic\&. SoftFloat is distributed in the form of \fBC\fP source code\&. Building the SoftFloat sources generates a library file (typically \fCsoftfloat\&.a\fP or \fClibsoftfloat\&.a\fP) containing the floating-point subroutines\&.
.PP
The SoftFloat package is documented in the following files in the \fCdoc\fP subdirectory:
.PP
.IP "\(bu" 2
\fCSoftFloat\&.html\fP Documentation for using the SoftFloat functions\&.
.IP "\(bu" 2
\fCSoftFloat-source\&.html\fP Documentation for building SoftFloat\&.
.IP "\(bu" 2
\fCSoftFloat-history\&.html\fP History of the major changes to SoftFloat\&.
.PP
.PP
Other files in the package comprise the source code for SoftFloat\&. 
