.TH "md_libraries_fc_vendor_websocketpp_tutorials_chat_tutorial_chat_tutorial" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_libraries_fc_vendor_websocketpp_tutorials_chat_tutorial_chat_tutorial \- Chat Tutorial 
Goals of this tutorial:
.IP "\(bu" 2
Implement a realtime websocket chat server
.PP
.PP
Server
.IP "\(bu" 2
Nicknames
.IP "\(bu" 2
Channels
.IP "\(bu" 2
Subprotocol
.IP "\(bu" 2
Origin restrictions
.IP "\(bu" 2
HTTP statistics page 
.PP

