.TH "md_myscripts_aac-test-py_readme" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_myscripts_aac-test-py_readme \- readme 
walt_and_bois\&.py 如果还未设置系统智能合约和钱包创建，先执行此脚本，否则，请忽略此脚本。 注意：walt_and_bios\&.py需要放在/build/programs/cleos/下面执行
.PP
gen_keys\&.py 自动生成账户名，并为每个账户生成两个公/私密钥对。生成的帐户名和密钥对写入acc_keys文件保存。 脚本可以带1-2个参数： 参数1，要生成多少个账户。默认值是3 参数2，帐户名的共同前缀。默认值是“a” 例子：\&./gen_keys\&.py 10 li 该命令生成10个账户，账户名分别为 lia、lib、lic、\&.\&.\&.\&.\&.\&.、lij
.PP
acc_keys 保存账户和密钥对的文本文件，每一行保存一个账户的密钥信息，信息项之间采用逗号分隔，格式如下所示： account_name,private_key1,public_key1,private_key2,public_key2
.PP
imp_pri_keys\&.py 读取acc_keys文件，将所有的私钥导入钱包。
.PP
cre_acc\&.py 读取acc_keys文件，使用帐户名和公钥在链上创建账户。
.PP
acc_transfer\&.py 账户之间相互转账，运行前请确保已经上传currency智能合约，并创建了足够数量的CUR币。 脚本的逻辑为：读取acc_keys文件，获得所有帐户名，为每位账户发放一定数量的CUR币。 然后第0账户向第1账户转账，第1账户向第2账户转账，依次类推，最后第n-1账户向第0账户转账，形成一个转账环。 每两次转账之间有一个睡眠时间，修改这个时间可调节tansaction发生的强度。 
