.TH "md_myscripts_vote-test-scripts_readme-vote" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_myscripts_vote-test-scripts_readme-vote \- readme-vote 
测试Dawn3\&.0，主测投票功能 1、walt_and_bois\&.py 
.br
创建钱包和系统智能合约并进行初始化配置 2、imp_pri_keys\&.py 导入acc_keys文件中的全部私钥 3、cre_acc\&.py 创建52个账户（26个producer,26个用来给producer投票的账户），账户和密钥信息在acc_keys文件中读取 4、issue_aac\&.py 发行AAC，给新创建的52个账户发放AAC，每个账户1000000\&.0000 AAC 5、reg_producers\&.py 为26个producer账户进行注册,账户信息在acc_keys文件读取和16进制公钥信息在bp_keys文件中读取 6、voter_stake\&.py 投票账户进行押注操作，账户信息在acc_keys文件中读取，押注金额vo\&.a到vo\&.z 26个投票账户的金额是（100\&.0000EOS---125\&.0000EOS） 7、vote_bp21\&.py 21个voter账户（vo\&.a\&.\&.\&.vo\&.u）为21个producer账户(bp\&.a\&.\&.\&.bp\&.u)进行一对一投票,投票成功后，producer打块顺序为bp\&.u\&.\&.\&.bp\&.a 8、vote_bp22-26\&.py 5个voter账户（vo\&.v\&.\&.\&.vo\&.z）为5个producer账户（bp\&.v\&.\&.\&.bp\&.z）进行一对一投票,投票成功后，bp\&.v\&.\&.\&.bp\&.z会把bp\&.a\&.\&.\&.bp\&.e挤掉， producer的出块顺序为:bp\&.z,bp\&.y,bp\&.x,bp\&.w,bp\&.v,bp\&.u\&.\&.\&.\&.\&.\&.bp\&.g,bp\&.f
.PP
9、config\&.ini文件放到配置文件应该放到的位置： macos ~/Library/Application Support/aacio/nodeos/config Linux:~/\&.local/share/aacio/noedeos/config 10、acc_keys文件是生成好的账户和密钥信息，26个producers,26个voters 11、bp_keys文件存放的是producers的账户的active公钥信息，16进制编码，regproducer操作使用。 
