.TH "md_programs_snapshot_readme" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_programs_snapshot_readme \- AACIO Genesis 
Tools used to initialize a genesis block for the AAC Platform
.PP
.SS "Tools"
.PP
.IP "\(bu" 2
Snapshot Generator (\fCreadme\fP) - Generates a snapshot from the AAC Crowdsale and Token contracts (saves a snapshot\&.csv and snapshot\&.json [metadata] into root directory of project)
.IP "\(bu" 2
\fCGenesis Block Generator\fP (\fCreadme\fP) - Enables configuration of a well-formed genesis\&.json file from a snapshot\&.csv\&.
.IP "\(bu" 2
\fCAccount Name Lookup\fP Look up the generated account name that was included in the genesis block with either your ETH address or AAC key
.IP "\(bu" 2
AAC Genesis \fBKey\fP Utility (\fCreadme\fP) - Offline AAC key gen and validator
.IP "\(bu" 2
\fISnapshot Frontend (planned)\fP
.PP
.PP
.SS "Useful Files"
.PP
.IP "\(bu" 2
\fBsnapshot\&.csv\fP Comma-delimited distribution list
.IP "\(bu" 2
\fBsnapshot\&.json\fP Meta data for the snapshot in the repo, describes the parameters of snapshot, some statistics and data for debugging 
.PP

