.TH "md_plugins_txn_test_gen_plugin__r_e_a_d_m_e" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_plugins_txn_test_gen_plugin__r_e_a_d_m_e \- txn 
This plugin provides a way to generate a given amount of transactions per second against the currency contract\&. It runs internally to aacd to reduce overhead\&.
.PP
.SS "Setup"
.PP
Create the two accounts used for transactions and set the currency contract code\&. Must give account & private key used for creation\&.
.PP
.PP
.nf
curl --data-binary '["inita", "5Jgm1N6jp3iNbFM45kPtj66xmbqT9fSuVJgPWfnCSPgQanvW6mJ"]' http://localhost:7777/v1/txn_test_gen/create_test_accounts
.fi
.PP
.PP
.SS "Starting/Stopping"
.PP
Start generation:
.PP
.PP
.nf
curl --data-binary '["one", 20, 16]' http://localhost:7777/v1/txn_test_gen/start_generation
.fi
.PP
.PP
First parameter is some 'salt' added to the transaction memos to ensure if this test is being run on other nodes concurrently no identical transactions are created\&. The second parameter is the frequency in milliseconds to wake up and send transactions\&. The third parameter is how many transactions to send on each wake up (must be an even number)\&. There are some constraints on these numbers to prevent anything too wild\&.
.PP
Stop generation
.PP
.PP
.nf
curl http://localhost:7777/v1/txn_test_gen/stop_generation
.fi
.PP
.PP
Generation of transactions is also stopped if a transaction fails to be accepted for any reason\&. 
