.TH "md_programs_snapshot_tools_genesis_readme" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_programs_snapshot_tools_genesis_readme \- Genesis Block Configurator 
Simple interface to generate a \fIgenesis block\fP from the committed snapshot to this repository\&. Can be used to configure and generate a genesis block from any properly formatted snapshot\&.csv\&.
.PP
The genesis block configurator can be accessed \fChere\fP 
