.TH "md_programs_snapshot_tools_snapshot_readme" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_programs_snapshot_tools_snapshot_readme \- Genesis Tools: Snapshot 

.IP "\(bu" 2
\fCInstallation\fP
.IP "  \(bu" 4
\fCDocker\fP
.IP "  \(bu" 4
\fCManual\fP
.PP

.IP "\(bu" 2
\fCUsage\fP
.IP "\(bu" 2
\fCDevelopment\fP
.IP "\(bu" 2
\fCHow it Works\fP
.IP "  \(bu" 4
\fCHigh Level\fP
.IP "  \(bu" 4
\fCLow Level\fP
.PP

.IP "\(bu" 2
\fCLogic differences between mainnet and testnet\fP
.PP
.PP
.SS "Snapshot Generator"
.PP
.SS "Installation"
.PP
.SS "Docker Installation and Usage"
.PP
\fIDocker installation is a work in progress\fP
.PP
.SS "Manual Installation"
.PP
Manual install is recommended for advanced users only\&.
.PP
.SS "Prerequisites"
.PP
.IP "1." 4
MySQL
.IP "2." 4
Redis-Server
.IP "3." 4
Parity 1\&.7\&.8 (Recommended) or Geth
.IP "4." 4
\fBNode\fP v0\&.6\&.X
.PP
.PP
.SS "System requirements"
.PP
.IP "1." 4
8GB Ram Recommended, can make due with 4gb
.IP "2." 4
Fast processor recommended
.IP "3." 4
SSD recommended
.PP
.PP
 
.SS "User Configurable Options"
.PP
There are three methods for configuration
.IP "1." 4
\fIConfig File\fP (recommended)
.IP "2." 4
\fIUser Prompt\fP, fast if your using default mysql, redis and web3 settings\&.
.IP "3." 4
\fICLI\fP args, will override \fIPrompt\fP
.PP
.IP "\(bu" 2
\fCperiod\fP (integer) The period to sync to, it will sync to the last block of any given period\&.
.IP "\(bu" 2
\fCinclude_b1\fP (true, false) Include block\&.one distribution
.IP "\(bu" 2
\fCfallback\fP (true, false) Use fallback registration
.IP "\(bu" 2
\fCcache\fP (true, false) Will cache successful fallbacks, including full paper trail: Block number, address, transaction, public key and generated AAC key\&. Can speed up the slow fallback method if running several times\&.
.IP "\(bu" 2
\fCeth_node_type\fP (http, ipc , ws) [default: http] Based on testing, IPC is recommended for performance
.IP "\(bu" 2
\fCeth_node_path\fP (valid host/path) Relative to type as defined above
.IP "\(bu" 2
\fCredis_host\fP
.IP "\(bu" 2
\fCredis_port\fP
.IP "\(bu" 2
\fCmysql_db\fP
.IP "\(bu" 2
\fCmysql_user\fP
.IP "\(bu" 2
\fCmysql_pass\fP
.IP "\(bu" 2
\fCmysql_host\fP
.IP "\(bu" 2
\fCmysql_port\fP
.PP
.PP
.SS "Important notes on Parity"
.PP
Since Parity v1\&.7\&.8 \fC--warp\fP is enabled by default, it is \fBabsolutely necessary\fP that you include the flag \fC--no-warp\fP\&. Warping will skip over historical data that the snapshot requires, tricking web3 into thinking the chain is synced when it is not\&. Warping is useful for miners, whereas for this situation it is poison and will throw errors/produce an inaccurate snapshot\&.
.PP
.SS "Manual Install Usage"
.PP
.IP "1." 4
Configure using one of three available options
.IP "2." 4
Import schema into mysql database, found in \fC/bin/schema\&.sql\fP (Sequalize Migrate presently not configured)
.IP "3." 4
Install dependencies \fCnpm install\fP
.IP "4." 4
Make sure all systems are go
.IP "  1." 6
Parity is running with RPC ports accessible to application
.IP "  2." 6
Mysql is running
.IP "  3." 6
Redis is running (\fCbash: redis-server\fP)
.PP

.PP
.IP "4." 4
Run script \fCnode snapshot\&.js\fP from \fBproject root\fP
.IP "5." 4
Go outside or to bed\&.
.PP
.PP
.SS "Notes"
.PP
.IP "\(bu" 2
For your convenience, if web3 is syncing, the app will attempt to start every 30 seconds until it Parity is fully synced
.IP "\(bu" 2
If parity crashes, you'll need to start over\&.
.PP
.PP
.SS "How it Works"
.PP
.SS "High Level"
.PP
The snapshot parameters this software proposes are as follows
.PP
.IP "1." 4
All data is constrained by block range determined by period (for testnet)
.PP
.IP "1." 4
AAC Balance of an address must be greater-than or equal to one AAC to be considered for inclusion in Genesis block
.IP "2." 4
An AAC key must be associated to an account either by registration or fallback
.IP "3." 4
Contract addresses are not included in the distribution, public keys derived from contracts have no matching private key as the public key is generated by EVM\&.
.PP
.IP "3." 4
If an ethereum address sent AAC ERC20 tokens to the AAC Crowdsale or AAC Token contract within the block range of the snapshot, these tokens are allocated to the respective address\&.
.IP "4." 4
If an address has unclaimed AAC in the AAC Crowdsale contract within block range, these tokens are allocated to the respective address\&.
.PP
.PP
 
.SS "Low Level"
.PP
The script employs strict patterns to encourage predictable output, often at the expense of performance\&. The pattern is \fIaggregate - calculate - validate\fP and closely resembles an ETL or \fIextract, transform and load\fP pattern\&. This decision came after numerous iterations and determining that debugging from state was more efficient than debugging from logs\&.
.PP
Below is the script transposed to plain english\&.
.PP
.IP "1." 4
User Configured Parameters are set through one of three methods\&.
.IP "2." 4
Check Connections to MySQL, Redis and Web3
.IP "3." 4
Truncate Databases
.IP "4." 4
Generate Period Map
.IP "  1." 6
Used to define block ranges of periods
.IP "  2." 6
Determines the block range that the snapshot is based upon
.PP

.IP "5." 4
Set Application State Variables (including user configurations)
.PP
.IP "5." 4
Sync history of token and crowdsale contract\&.
.IP "  1." 6
AAC Transfers
.IP "  2." 6
Buys
.IP "  3." 6
Claims
.IP "  4." 6
Registrations
.IP "  5." 6
Reclaimable Transfers
.PP

.PP
.IP "2." 4
Compile list of every address that has ever had an AAC balance, for each address:
.IP "  1." 6
\fBAggregate\fP relevant txs
.IP "    1." 8
Claims and Buys, required for Unclaimed Balance Calculation
.IP "    2." 8
Transfers, all incoming and outgoing tx from address
.IP "    3." 8
Reclaimable Transfers, every reclaimable has a corresponding transfer [special case]
.IP "    4." 8
The last registration transaction to occur within defined block range
.PP

.IP "  2." 6
Calculate
.IP "    1." 8
Sum Wallet Balance (sum(transfers_in) - sum(transfers_out))
.IP "    2." 8
Calculate Unclaimed Balance
.IP "    3." 8
Sum Reclaimed Transfer Balances
.IP "    4." 8
Sum Balances
.IP "    5." 8
Convert balances from gwei
.PP

.IP "  3." 6
Validate
.IP "    1." 8
Check Wallet Balance
.IP "    2." 8
Validate AAC \fBKey\fP, if valid set \fCregistered\fP to \fCtrue\fP
.IP "    3." 8
If AAC key error, save error to column \fCregister_error\fP
.IP "    4." 8
If all validated, set \fCvalid\fP to true\&.
.PP

.IP "  5." 6
Process
.IP "    6." 8
Save every wallet regardless of validation or balance to \fCwallets\fP table
.PP

.IP "  6." 6
Fallback \fIif \fCbalance is gte 1\fP and \fCregister_error is not null\fP\fP
.IP "    1." 8
Fast Fallback
.IP "      1." 10
Check database for any outgoing transactions (or keys cache), if found\&.\&.\&.
.IP "        1." 12
Query TX and grab Ethereum public key
.IP "        2." 12
Generate and validate AAC \fBKey\fP
.IP "        3." 12
If found and valid, set \fCvalid\fP to \fCtrue\fP otherwise save error into \fCfallback_error\fP column
.PP

.PP

.PP

.PP

.PP
.PP
Slow fallback
.IP "1." 4
Obtain list of unique addresses with balance gte 1 AAC and no AAC key and save them as keys in index (redis is used as index)
.IP "2." 4
Scan every \fCfrom\fP value in every transaction transaction included in every block between block 0 to end of block range for snapshot for against \fIindex\fP
.IP "3." 4
If public key is found, execute fallback registration and revalidate entry, update database row appropriately
.PP
.PP
\fBTest\fP
.IP "1." 4
Daily Totals from DB against daily totals from AAC Utility Contract, failure here would not fail the below tests, but would instead result in inaccurate unclaimed balances\&. Difficult problem to detect without this test\&.
.IP "2." 4
Total Supply, margin of error should be low due to \fIdust\fP from rounding (generally 0\&.00000001%)
.IP "3." 4
Negative Balances, there should be \fBzero\fP negative balances
.PP
.PP
Output
.IP "1." 4
\fBsnapshot\&.csv\fP - comma-delimited list of ETH addresses, AAC keys and Total Balances (user, key, balance respectively)
.IP "  1." 6
Move all valid entries from db state to a snapshot table, ordered by balance DESC\&.
.IP "  2." 6
Generate snapshot\&.csv from table
.PP

.PP
.PP
\fBsnapshot\&.json\fP - Snapshot meta data
.PP
.IP "1." 4
Snapshot parameters
.IP "2." 4
\fBTest\fP results
.IP "3." 4
General Statistics
.IP "4." 4
Generate MD5 Checksums
.IP "  1." 6
From generated \fBsnapshot\&.csv\fP file, useful for debugging and auditing
.IP "  2." 6
From mysql checksum for every table in database (useful for debugging)
.PP

.IP "5." 4
Pass any other useful state variables into object
.PP
.PP
With the output, you can use the Genesis Generator to create a well-formed genesis\&.json file for the AAC platform\&.
.PP
 
.SS "Development"
.PP
.IP "\(bu" 2
Do all you work in a separate branch, and submit a pull request\&. PR's containing changes to snapshot\&.csv will not be accepted without proof of accuracy and detailed information on the anomaly that was solved\&. 
.br
- Write your own snapshot script! Use the same high level parameters and see if your generated snapshot\&.csv is the same checksum as the one generated by this script\&. This script was written as a baseline, where accuracy and ability to extend as a service were priority\&. Write a faster one\&.
.IP "\(bu" 2
Share your results or ask questions in \fCTelegram\fP
.PP
.PP
 
.SS "Difference between Testnet and Mainnet"
.PP
There are some differences between testnet and mainnet snapshots that need to be mentioned\&.
.PP
.IP "\(bu" 2
Testnet snapshots will produce accurate output based on period by constraining all blockchain activity to that range\&. This means that some seemingly superfluous calculations are conducted for testnet
.IP "  \(bu" 4
Balances are calculated cumulatively, instead of using \fCbalanceOf\fP method in Token Contract
.IP "  \(bu" 4
AAC \fBKey\fP Registration is concluded by last registration within the block range\&.
.PP

.IP "\(bu" 2
Mainnet simplifies a few things\&. However, it would be recommended that a cutoff block be enforced to encourage network consensus (primarily for registration transactions)
.IP "  \(bu" 4
Balances are not calculated but inferred from state returned by \fCbalanceOf\fP function in Token Contract\&.
.IP "  \(bu" 4
AAC key registration is inferred from state returned by \fCkeys\fP map in Crowdsale Contract\&. 
.PP

.PP

