.TH "md_scripts_abi_to_rc_rc-overview-template" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_scripts_abi_to_rc_rc-overview-template \- Smart Contract - `$contract` 
This is an overview of the actions for the \fC$contract\fP smart contract\&. This Contract is legally binding and can be used in the event of a dispute\&. Disputes shall be settled through the standard arbitration process established by AAC\&.IO\&.
.PP
.SS "Description"
.PP
The \fC$contract\fP contract\&.\&.\&.
.PP
.SS "$action_header, $input_header and Input $type_header"
.PP
The table below contains the \fC$action\fP, \fC$input\fP and \fCinput $type\fP for the \fC$contract\fP contract\&.
.PP
| Action | Input | Input \fBType\fP | |:--|:--|:--| 
