.TH "memorycppapi" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
memorycppapi \- Defines common memory functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::memory_manager\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBaacio::memory_manager::memory::init\fP (char *const mem_heap, uint32_t size)"
.br
.ti -1c
.RI "uint32_t \fBaacio::memory_manager::memory::is_init\fP () const"
.br
.ti -1c
.RI "uint32_t \fBaacio::memory_manager::memory::is_in_heap\fP (const char *const ptr) const"
.br
.ti -1c
.RI "uint32_t \fBaacio::memory_manager::memory::is_capacity_remaining\fP () const"
.br
.ti -1c
.RI "char * \fBaacio::memory_manager::memory::malloc\fP (uint32_t size)"
.br
.ti -1c
.RI "char * \fBaacio::memory_manager::memory::malloc_from_freed\fP (uint32_t size)"
.br
.ti -1c
.RI "char * \fBaacio::memory_manager::memory::realloc_in_place\fP (char *const ptr, uint32_t size, uint32_t *orig_ptr_size)"
.br
.ti -1c
.RI "void \fBaacio::memory_manager::memory::free\fP (char *ptr)"
.br
.ti -1c
.RI "void \fBaacio::memory_manager::memory::cleanup_remaining\fP ()"
.br
.ti -1c
.RI "bool \fBaacio::memory_manager::memory::expand_memory\fP (char *exp_mem, uint32_t size)"
.br
.ti -1c
.RI "\fBaacio::memory_manager::memory::buffer_ptr::buffer_ptr\fP (void *ptr, const char *const heap_end)"
.br
.ti -1c
.RI "\fBaacio::memory_manager::memory::buffer_ptr::buffer_ptr\fP (void *ptr, uint32_t buff_size, const char *const heap_end)"
.br
.ti -1c
.RI "uint32_t \fBaacio::memory_manager::memory::buffer_ptr::size\fP () const"
.br
.ti -1c
.RI "char * \fBaacio::memory_manager::memory::buffer_ptr::next_ptr\fP () const"
.br
.ti -1c
.RI "void \fBaacio::memory_manager::memory::buffer_ptr::size\fP (uint32_t val)"
.br
.ti -1c
.RI "char * \fBaacio::memory_manager::memory::buffer_ptr::end\fP () const"
.br
.ti -1c
.RI "char * \fBaacio::memory_manager::memory::buffer_ptr::ptr\fP () const"
.br
.ti -1c
.RI "void \fBaacio::memory_manager::memory::buffer_ptr::mark_alloc\fP ()"
.br
.ti -1c
.RI "void \fBaacio::memory_manager::memory::buffer_ptr::mark_free\fP ()"
.br
.ti -1c
.RI "bool \fBaacio::memory_manager::memory::buffer_ptr::is_alloc\fP () const"
.br
.ti -1c
.RI "bool \fBaacio::memory_manager::memory::buffer_ptr::merge_contiguous_if_available\fP (uint32_t needed_size)"
.br
.ti -1c
.RI "bool \fBaacio::memory_manager::memory::buffer_ptr::merge_contiguous\fP (uint32_t needed_size)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmemory_manager\fP \fBaacio::memory_heap\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "void * \fBaacio::memory_manager::malloc\fP (size_t size)"
.br
.ti -1c
.RI "void * \fBaacio::memory_manager::calloc\fP (size_t count, size_t size)"
.br
.ti -1c
.RI "void * \fBaacio::memory_manager::realloc\fP (void *ptr, size_t size)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines common memory functions\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
