.TH "tests/tests/message_buffer_tests.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/tests/message_buffer_tests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/net_plugin/message_buffer\&.hpp>\fP
.br
\fC#include <boost/test/unit_test\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBaacio::mb_size\fP (boost::asio::mutable_buffer &mb)"
.br
.ti -1c
.RI "void * \fBaacio::mb_data\fP (boost::asio::mutable_buffer &mb)"
.br
.ti -1c
.RI "\fBaacio::BOOST_AUTO_TEST_CASE\fP (message_buffer_construction)"
.br
.RI "\fBTest\fP default construction and buffer sequence generation\&. "
.ti -1c
.RI "\fBaacio::BOOST_AUTO_TEST_CASE\fP (message_buffer_growth)"
.br
.RI "\fBTest\fP buffer growth and shrinking\&. "
.ti -1c
.RI "\fBaacio::BOOST_AUTO_TEST_CASE\fP (message_buffer_peek_read)"
.br
.RI "\fBTest\fP peek and read across multiple buffers\&. "
.ti -1c
.RI "\fBaacio::BOOST_AUTO_TEST_CASE\fP (message_buffer_write_ptr_to_end)"
.br
.RI "\fBTest\fP automatic allocation when advancing the read_ptr to the end\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr auto \fBaacio::def_buffer_size_mb\fP = 4"
.br
.ti -1c
.RI "constexpr auto \fBaacio::def_buffer_size\fP = 1024*1024*def_buffer_size_mb"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
