.TH "plugins/net_plugin/include/aacio/net_plugin/message_buffer.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/net_plugin/include/aacio/net_plugin/message_buffer.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <boost/asio/ip/tcp\&.hpp>\fP
.br
\fC#include <boost/pool/object_pool\&.hpp>\fP
.br
\fC#include <fc/io/raw\&.hpp>\fP
.br
\fC#include <deque>\fP
.br
\fC#include <array>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::mb_datastream< buffer_len >\fP"
.br
.ti -1c
.RI "class \fBaacio::message_buffer< buffer_len >\fP"
.br
.RI "abstraction for a message buffer that spans a chain of physical buffers "
.ti -1c
.RI "class \fBaacio::mb_datastream< buffer_len >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
