.TH "minig::promise_type" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
minig::promise_type
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "suspend_always \fByield_value\fP (int value)"
.br
.ti -1c
.RI "suspend_always \fBinitial_suspend\fP ()"
.br
.ti -1c
.RI "suspend_always \fBfinal_suspend\fP ()"
.br
.ti -1c
.RI "\fBminig\fP \fBget_return_object\fP ()"
.br
.ti -1c
.RI "void \fBreturn_void\fP ()"
.br
.ti -1c
.RI "void \fBunhandled_exception\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcurrent_value\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
