.TH "tests/tests/misc_tests.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/tests/misc_tests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/chain_config\&.hpp>\fP
.br
\fC#include <aacio/chain/authority_checker\&.hpp>\fP
.br
\fC#include <aacio/chain/authority\&.hpp>\fP
.br
\fC#include <aacio/chain/types\&.hpp>\fP
.br
\fC#include <aacio/chain/asset\&.hpp>\fP
.br
\fC#include <aacio/testing/tester\&.hpp>\fP
.br
\fC#include <aacio/utilities/key_conversion\&.hpp>\fP
.br
\fC#include <aacio/utilities/rand\&.hpp>\fP
.br
\fC#include <fc/io/json\&.hpp>\fP
.br
\fC#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaacio::permission_visitor\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTESTER\fP   validating_tester"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBaacio::BOOST_AUTO_TEST_CASE\fP (json_from_string_test)"
.br
.RI "\fBTest\fP processing of unbalanced strings\&. "
.ti -1c
.RI "\fBaacio::BOOST_AUTO_TEST_CASE\fP (deterministic_randomness)"
.br
.RI "\fBTest\fP that our deterministic random shuffle algorithm gives the same results in all environments\&. "
.ti -1c
.RI "\fBaacio::BOOST_AUTO_TEST_CASE\fP (deterministic_distributions)"
.br
.ti -1c
.RI "\fBaacio::BOOST_AUTO_TEST_CASE\fP (\fBauthority_checker\fP)"
.br
.ti -1c
.RI "\fBaacio::BOOST_AUTO_TEST_CASE\fP (alphabetic_sort)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
