.TH "MismatchType" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MismatchType
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMismatchType\fP (int)"
.br
.ti -1c
.RI "\fBMismatchType\fP (char *)"
.br
.ti -1c
.RI "\fBMismatchType\fP (int *)=delete"
.br
.ti -1c
.RI "\fBMismatchType\fP & \fBoperator=\fP (int)"
.br
.ti -1c
.RI "\fBMismatchType\fP & \fBoperator=\fP (int *)"
.br
.ti -1c
.RI "\fBMismatchType\fP & \fBoperator=\fP (char *)=delete"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
