.TH "MixedArena" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MixedArena
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcashew::GlobalMixedArena\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void * \fBallocSpace\fP (size_t size)"
.br
.ti -1c
.RI "template<class T > \fBT\fP * \fBalloc\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::vector\fP< char * > \fBchunks\fP"
.br
.ti -1c
.RI "size_t \fBchunkSize\fP = 32768"
.br
.ti -1c
.RI "size_t \fBindex\fP"
.br
.ti -1c
.RI "std::thread::id \fBthreadId\fP"
.br
.ti -1c
.RI "std::atomic< \fBMixedArena\fP * > \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
