.TH "mock_endpoint" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mock_endpoint
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwebsocketpp::transport::asio::endpoint< config >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBwebsocketpp::transport::asio::endpoint\fP< \fBconfig\fP > \fBbase\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBconnect\fP (std::string u)"
.br
.ti -1c
.RI "void \fBhandle_connect\fP (connection_ptr con, websocketpp::lib::error_code const &ec)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "connection_ptr \fBm_con\fP"
.br
.ti -1c
.RI "\fBconfig::alog_type\fP \fBalog\fP"
.br
.ti -1c
.RI "\fBconfig::elog_type\fP \fBelog\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
