.TH "mock_con" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mock_con
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwebsocketpp::transport::asio::connection< config >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBwebsocketpp::transport::asio::connection\fP< \fBconfig\fP > \fBbase\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmock_con\fP (bool a, \fBconfig::alog_type\fP &b, \fBconfig::elog_type\fP &c)"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBhandle_start\fP (const websocketpp::lib::error_code &ec)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
