.TH "plugins/mongo_db_plugin/mongo_db_plugin.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/mongo_db_plugin/mongo_db_plugin.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/mongo_db_plugin/mongo_db_plugin\&.hpp>\fP
.br
\fC#include <aacio/chain/contracts/chain_initializer\&.hpp>\fP
.br
\fC#include <aacio/chain/config\&.hpp>\fP
.br
\fC#include <aacio/chain/exceptions\&.hpp>\fP
.br
\fC#include <aacio/chain/transaction\&.hpp>\fP
.br
\fC#include <aacio/chain/types\&.hpp>\fP
.br
\fC#include <fc/io/json\&.hpp>\fP
.br
\fC#include <fc/variant\&.hpp>\fP
.br
\fC#include <boost/thread/thread\&.hpp>\fP
.br
\fC#include <boost/thread/mutex\&.hpp>\fP
.br
\fC#include <boost/thread/condition_variable\&.hpp>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <bsoncxx/builder/basic/kvp\&.hpp>\fP
.br
\fC#include <bsoncxx/builder/basic/document\&.hpp>\fP
.br
\fC#include <bsoncxx/builder/stream/document\&.hpp>\fP
.br
\fC#include <bsoncxx/json\&.hpp>\fP
.br
\fC#include <mongocxx/client\&.hpp>\fP
.br
\fC#include <mongocxx/instance\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::mongo_db_plugin_impl\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBfc\fP"
.br
.RI "aacio::chain "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
