.TH "plugins/mongo_db_plugin/include/aacio/mongo_db_plugin/mongo_db_plugin.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/mongo_db_plugin/include/aacio/mongo_db_plugin/mongo_db_plugin.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain_plugin/chain_plugin\&.hpp>\fP
.br
\fC#include <appbase/application\&.hpp>\fP
.br
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::mongo_db_plugin\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBaacio::mongo_db_plugin_impl_ptr\fP = std::shared_ptr< class mongo_db_plugin_impl >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
