.TH "MoveAssignable" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoveAssignable
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveAssignable\fP & \fBoperator=\fP (\fBMoveAssignable\fP const &)=delete"
.br
.ti -1c
.RI "\fBMoveAssignable\fP & \fBoperator=\fP (\fBMoveAssignable\fP &&)=default"
.br
.ti -1c
.RI "\fBMoveAssignable\fP & \fBoperator=\fP (\fBMoveAssignable\fP const &)=delete"
.br
.ti -1c
.RI "\fBMoveAssignable\fP & \fBoperator=\fP (\fBMoveAssignable\fP &&)=default"
.br
.ti -1c
.RI "\fBMoveAssignable\fP & \fBoperator=\fP (\fBMoveAssignable\fP const &)=delete"
.br
.ti -1c
.RI "\fBMoveAssignable\fP & \fBoperator=\fP (\fBMoveAssignable\fP &&)=default"
.br
.ti -1c
.RI "\fBMoveAssignable\fP & \fBoperator=\fP (\fBMoveAssignable\fP const &)=delete"
.br
.ti -1c
.RI "\fBMoveAssignable\fP & \fBoperator=\fP (\fBMoveAssignable\fP &&)=default"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
