.TH "MoveOnlyOddNothrow" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoveOnlyOddNothrow
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveOnlyOddNothrow\fP (\fBMoveOnlyOddNothrow\fP &&) noexcept(false)"
.br
.ti -1c
.RI "\fBMoveOnlyOddNothrow\fP (const \fBMoveOnlyOddNothrow\fP &)=delete"
.br
.ti -1c
.RI "\fBMoveOnlyOddNothrow\fP & \fBoperator=\fP (\fBMoveOnlyOddNothrow\fP &&) noexcept=default"
.br
.ti -1c
.RI "\fBMoveOnlyOddNothrow\fP & \fBoperator=\fP (const \fBMoveOnlyOddNothrow\fP &)=delete"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
