.TH "MoveAssignableWrapper" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoveAssignableWrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveAssignableWrapper\fP (\fBMoveAssignableWrapper\fP const &)=delete"
.br
.ti -1c
.RI "\fBMoveAssignableWrapper\fP (\fBMoveAssignableWrapper\fP &&)=default"
.br
.ti -1c
.RI "\fBMoveAssignableWrapper\fP & \fBoperator=\fP (\fBMoveAssignableWrapper\fP const &)=delete"
.br
.ti -1c
.RI "\fBMoveAssignableWrapper\fP & \fBoperator=\fP (\fBMoveAssignableWrapper\fP &&)=default"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args> bool \fBoperator()\fP (Args &&\&.\&.\&.)"
.br
.ti -1c
.RI "\fBMoveAssignableWrapper\fP (bool x)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
