.TH "MoveOnly" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoveOnly
.SH SYNOPSIS
.br
.PP
.PP
Inherits DEFINE_BASEMoveOnly\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBBase\fP = DEFINE_BASE(\fBMoveOnly\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveOnly\fP (int data=1)"
.br
.ti -1c
.RI "\fBMoveOnly\fP (\fBMoveOnly\fP &&x)"
.br
.ti -1c
.RI "\fBMoveOnly\fP & \fBoperator=\fP (\fBMoveOnly\fP &&x)"
.br
.ti -1c
.RI "int \fBget\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBMoveOnly\fP &x) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBMoveOnly\fP &x) const"
.br
.ti -1c
.RI "\fBMoveOnly\fP (const \fBMoveOnly\fP &)=delete"
.br
.ti -1c
.RI "\fBMoveOnly\fP (\fBMoveOnly\fP &&)=default"
.br
.ti -1c
.RI "\fBMoveOnly\fP & \fBoperator=\fP (const \fBMoveOnly\fP &)=default"
.br
.ti -1c
.RI "\fBMoveOnly\fP (const \fBMoveOnly\fP &)=delete"
.br
.ti -1c
.RI "\fBMoveOnly\fP (\fBMoveOnly\fP &&)=default"
.br
.ti -1c
.RI "\fBMoveOnly\fP & \fBoperator=\fP (const \fBMoveOnly\fP &)=delete"
.br
.ti -1c
.RI "\fBMoveOnly\fP & \fBoperator=\fP (\fBMoveOnly\fP &&)=default"
.br
.ti -1c
.RI "\fBMoveOnly\fP (const \fBMoveOnly\fP &)=delete"
.br
.ti -1c
.RI "\fBMoveOnly\fP (\fBMoveOnly\fP &&)=default"
.br
.ti -1c
.RI "\fBMoveOnly\fP (int v)"
.br
.ti -1c
.RI "\fBMoveOnly\fP (const \fBMoveOnly\fP &)=delete"
.br
.ti -1c
.RI "\fBMoveOnly\fP (\fBMoveOnly\fP &&)=default"
.br
.ti -1c
.RI "DEFINE_EXPLICIT DEFINE_CONSTEXPR \fBMoveOnly\fP (\fBMoveOnly\fP &&) DEFINE_CTOR"
.br
.ti -1c
.RI "\fBMoveOnly\fP & \fBoperator=\fP (\fBMoveOnly\fP &&) DEFINE_ASSIGN"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
