.TH "MoveAssign" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoveAssign
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveAssign\fP (int v)"
.br
.ti -1c
.RI "\fBMoveAssign\fP (\fBMoveAssign\fP &&o)"
.br
.ti -1c
.RI "\fBMoveAssign\fP & \fBoperator=\fP (\fBMoveAssign\fP &&o)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBmove_construct\fP = 0"
.br
.ti -1c
.RI "static int \fBmove_assign\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
