.TH "msgcat" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msgcat
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBmsgcat\fP * \fBnext\fP"
.br
.ti -1c
.RI "const void * \fBmap\fP"
.br
.ti -1c
.RI "size_t \fBmap_size\fP"
.br
.ti -1c
.RI "void *volatile \fBplural_rule\fP"
.br
.ti -1c
.RI "volatile int \fBnplurals\fP"
.br
.ti -1c
.RI "struct \fBbinding\fP * \fBbinding\fP"
.br
.ti -1c
.RI "const struct \fB__locale_map\fP * \fBlm\fP"
.br
.ti -1c
.RI "int \fBcat\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
