.TH "msghdr" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msghdr
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBmsg_name\fP"
.br
.ti -1c
.RI "socklen_t \fBmsg_namelen\fP"
.br
.ti -1c
.RI "struct iovec * \fBmsg_iov\fP"
.br
.ti -1c
.RI "int \fBmsg_iovlen\fP"
.br
.ti -1c
.RI "void * \fBmsg_control\fP"
.br
.ti -1c
.RI "socklen_t \fBmsg_controllen\fP"
.br
.ti -1c
.RI "int \fBmsg_flags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
