.TH "msqid_ds" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msqid_ds
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBipc_perm\fP \fBmsg_perm\fP"
.br
.ti -1c
.RI "time_t \fBmsg_stime\fP"
.br
.ti -1c
.RI "int \fB__unused1\fP"
.br
.ti -1c
.RI "time_t \fBmsg_rtime\fP"
.br
.ti -1c
.RI "int \fB__unused2\fP"
.br
.ti -1c
.RI "time_t \fBmsg_ctime\fP"
.br
.ti -1c
.RI "int \fB__unused3\fP"
.br
.ti -1c
.RI "unsigned long \fBmsg_cbytes\fP"
.br
.ti -1c
.RI "msgqnum_t \fBmsg_qnum\fP"
.br
.ti -1c
.RI "msglen_t \fBmsg_qbytes\fP"
.br
.ti -1c
.RI "pid_t \fBmsg_lspid\fP"
.br
.ti -1c
.RI "pid_t \fBmsg_lrpid\fP"
.br
.ti -1c
.RI "unsigned long \fB__unused\fP [2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
