.TH "multi_index_test" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multi_index_test \- \fBmulti_index_test\fP  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlimit_order\fP"
.br
.ti -1c
.RI "class \fBmulti_index_test\fP"
.br
.ti -1c
.RI "struct \fBtest_k256\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBapply\fP (uint64_t receiver, uint64_t code, uint64_t \fBaction\fP)"
.br
.RI "The apply method implements the dispatch of events to this contract\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBmulti_index_test\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
