.TH "multi_index_test::limit_order" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multi_index_test::limit_order
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBprimary_key\fP () const"
.br
.ti -1c
.RI "uint64_t \fBget_expiration\fP () const"
.br
.ti -1c
.RI "uint128_t \fBget_price\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBid\fP"
.br
.ti -1c
.RI "uint64_t \fBpadding\fP = 0"
.br
.ti -1c
.RI "uint128_t \fBprice\fP"
.br
.ti -1c
.RI "uint64_t \fBexpiration\fP"
.br
.ti -1c
.RI "account_name \fBowner\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
