.TH "my_facetw" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_facetw
.SH SYNOPSIS
.br
.PP
.PP
Inherits Fw, Fw, Fw, Fw, Fw, Fw, Fw, Fw, Fw, and Fw\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmy_facetw\fP (std::size_t refs=0)"
.br
.ti -1c
.RI "\fBmy_facetw\fP (std::size_t refs=0)"
.br
.ti -1c
.RI "\fBmy_facetw\fP (std::size_t refs=0)"
.br
.ti -1c
.RI "\fBmy_facetw\fP (std::size_t refs=0)"
.br
.ti -1c
.RI "\fBmy_facetw\fP (std::size_t refs=0)"
.br
.ti -1c
.RI "\fBmy_facetw\fP (std::size_t refs=0)"
.br
.ti -1c
.RI "\fBmy_facetw\fP (std::size_t refs=0)"
.br
.ti -1c
.RI "\fBmy_facetw\fP (std::size_t refs=0)"
.br
.ti -1c
.RI "\fBmy_facetw\fP (std::size_t refs=0)"
.br
.ti -1c
.RI "\fBmy_facetw\fP (std::size_t refs=0)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
