.TH "my_numpunct" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_numpunct
.SH SYNOPSIS
.br
.PP
.PP
Inherits numpunct< char >, numpunct< char >, numpunct< char >, numpunct< char >, numpunct< char >, numpunct< char >, numpunct< char >, numpunct< char >, numpunct< char >, numpunct< char >, numpunct< char >, numpunct< char >, numpunct< char >, and numpunct< char >\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual string_type \fBdo_truename\fP () const"
.br
.ti -1c
.RI "virtual string_type \fBdo_falsename\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_decimal_point\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_thousands_sep\fP () const"
.br
.ti -1c
.RI "virtual std::string \fBdo_grouping\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_thousands_sep\fP () const"
.br
.ti -1c
.RI "virtual std::string \fBdo_grouping\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_decimal_point\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_thousands_sep\fP () const"
.br
.ti -1c
.RI "virtual std::string \fBdo_grouping\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_thousands_sep\fP () const"
.br
.ti -1c
.RI "virtual std::string \fBdo_grouping\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_thousands_sep\fP () const"
.br
.ti -1c
.RI "virtual std::string \fBdo_grouping\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_thousands_sep\fP () const"
.br
.ti -1c
.RI "virtual std::string \fBdo_grouping\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_decimal_point\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_thousands_sep\fP () const"
.br
.ti -1c
.RI "virtual std::string \fBdo_grouping\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_thousands_sep\fP () const"
.br
.ti -1c
.RI "virtual std::string \fBdo_grouping\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_thousands_sep\fP () const"
.br
.ti -1c
.RI "virtual std::string \fBdo_grouping\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_thousands_sep\fP () const"
.br
.ti -1c
.RI "virtual std::string \fBdo_grouping\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_thousands_sep\fP () const"
.br
.ti -1c
.RI "virtual std::string \fBdo_grouping\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_thousands_sep\fP () const"
.br
.ti -1c
.RI "virtual std::string \fBdo_grouping\fP () const"
.br
.ti -1c
.RI "virtual char_type \fBdo_thousands_sep\fP () const"
.br
.ti -1c
.RI "virtual std::string \fBdo_grouping\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
