.TH "my_struct_flat" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_struct_flat
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBa0\fP"
.br
.ti -1c
.RI "short \fBa1\fP"
.br
.ti -1c
.RI "int \fBa2\fP"
.br
.ti -1c
.RI "short \fBa3\fP"
.br
.ti -1c
.RI "short \fBa4\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
