.TH "my_struct" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBa0\fP"
.br
.ti -1c
.RI "\fBmy_struct_nested\fP \fBnested\fP"
.br
.ti -1c
.RI "short \fBa3_a4\fP [2]"
.br
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "char \fBc\fP"
.br
.ti -1c
.RI "double \fBd\fP"
.br
.ti -1c
.RI "std::string \fBs\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBcvalue\fP = 1000"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
