.TH "MyFixture" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyFixture
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbenchmark::Fixture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP (const ::\fBbenchmark::State\fP &state)"
.br
.ti -1c
.RI "void \fBTearDown\fP (const ::\fBbenchmark::State\fP &state)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::unique_ptr< int > \fBdata\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
