.TH "MyFuture" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyFuture
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpromise_type\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef promise_type::HandleT \fBHandleT\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyFuture\fP (HandleT h)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "coro::coroutine_handle< \fBpromise_type\fP > \fBp\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
