.TH "MyNS::A" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyNS::A
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBA\fP (\fBA\fP const &)=delete"
.br
.ti -1c
.RI "\fBA\fP & \fBoperator=\fP (\fBA\fP const &)=delete"
.br
.ti -1c
.RI "\fBA\fP (\fBA\fP const &)=delete"
.br
.ti -1c
.RI "\fBA\fP & \fBoperator=\fP (\fBA\fP const &)=delete"
.br
.ti -1c
.RI "\fBA\fP (\fBA\fP const &)=delete"
.br
.ti -1c
.RI "\fBA\fP & \fBoperator=\fP (\fBA\fP const &)=delete"
.br
.ti -1c
.RI "\fBA\fP (\fBA\fP const &)=delete"
.br
.ti -1c
.RI "\fBA\fP & \fBoperator=\fP (\fBA\fP const &)=delete"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
