.TH "MyNS::B" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyNS::B
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBB\fP (\fBB\fP const &)=delete"
.br
.ti -1c
.RI "\fBB\fP & \fBoperator=\fP (\fBB\fP const &)=delete"
.br
.ti -1c
.RI "\fBB\fP (\fBB\fP const &)=delete"
.br
.ti -1c
.RI "\fBB\fP & \fBoperator=\fP (\fBB\fP const &)=delete"
.br
.ti -1c
.RI "\fBB\fP (\fBB\fP const &)=delete"
.br
.ti -1c
.RI "\fBB\fP & \fBoperator=\fP (\fBB\fP const &)=delete"
.br
.ti -1c
.RI "\fBB\fP (\fBB\fP const &)=delete"
.br
.ti -1c
.RI "\fBB\fP & \fBoperator=\fP (\fBB\fP const &)=delete"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
