.TH "MySink" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySink
.SH SYNOPSIS
.br
.PP
.PP
Inherits sink\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::streamsize \fBwrite\fP (const char *s, std::streamsize n)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
