.TH "mz_stream_s" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mz_stream_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const unsigned char * \fBnext_in\fP"
.br
.ti -1c
.RI "unsigned int \fBavail_in\fP"
.br
.ti -1c
.RI "mz_ulong \fBtotal_in\fP"
.br
.ti -1c
.RI "unsigned char * \fBnext_out\fP"
.br
.ti -1c
.RI "unsigned int \fBavail_out\fP"
.br
.ti -1c
.RI "mz_ulong \fBtotal_out\fP"
.br
.ti -1c
.RI "char * \fBmsg\fP"
.br
.ti -1c
.RI "struct mz_internal_state * \fBstate\fP"
.br
.ti -1c
.RI "mz_alloc_func \fBzalloc\fP"
.br
.ti -1c
.RI "mz_free_func \fBzfree\fP"
.br
.ti -1c
.RI "void * \fBopaque\fP"
.br
.ti -1c
.RI "int \fBdata_type\fP"
.br
.ti -1c
.RI "mz_ulong \fBadler\fP"
.br
.ti -1c
.RI "mz_ulong \fBreserved\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
