.TH "mz_zip_array" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mz_zip_array
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBm_p\fP"
.br
.ti -1c
.RI "size_t \fBm_size\fP"
.br
.ti -1c
.RI "size_t \fBm_capacity\fP"
.br
.ti -1c
.RI "mz_uint \fBm_element_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
