.TH "mz_zip_writer_add_state" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mz_zip_writer_add_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmz_zip_archive\fP * \fBm_pZip\fP"
.br
.ti -1c
.RI "mz_uint64 \fBm_cur_archive_file_ofs\fP"
.br
.ti -1c
.RI "mz_uint64 \fBm_comp_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
