.TH "mz_zip_archive_file_stat" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mz_zip_archive_file_stat
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "mz_uint32 \fBm_file_index\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_central_dir_ofs\fP"
.br
.ti -1c
.RI "mz_uint16 \fBm_version_made_by\fP"
.br
.ti -1c
.RI "mz_uint16 \fBm_version_needed\fP"
.br
.ti -1c
.RI "mz_uint16 \fBm_bit_flag\fP"
.br
.ti -1c
.RI "mz_uint16 \fBm_method\fP"
.br
.ti -1c
.RI "time_t \fBm_time\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_crc32\fP"
.br
.ti -1c
.RI "mz_uint64 \fBm_comp_size\fP"
.br
.ti -1c
.RI "mz_uint64 \fBm_uncomp_size\fP"
.br
.ti -1c
.RI "mz_uint16 \fBm_internal_attr\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_external_attr\fP"
.br
.ti -1c
.RI "mz_uint64 \fBm_local_header_ofs\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_comment_size\fP"
.br
.ti -1c
.RI "char \fBm_filename\fP [MZ_ZIP_MAX_ARCHIVE_FILENAME_SIZE]"
.br
.ti -1c
.RI "char \fBm_comment\fP [MZ_ZIP_MAX_ARCHIVE_FILE_COMMENT_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
