.TH "nasty_mutex" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nasty_mutex
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnasty_mutex\fP * \fBoperator &\fP ()"
.br
.ti -1c
.RI "template<typename T > void \fBoperator,\fP (const \fBT\fP &)"
.br
.ti -1c
.RI "void \fBlock\fP ()"
.br
.ti -1c
.RI "bool \fBtry_lock\fP () TEST_NOEXCEPT"
.br
.ti -1c
.RI "void \fBunlock\fP () TEST_NOEXCEPT"
.br
.ti -1c
.RI "void \fBlock_shared\fP ()"
.br
.ti -1c
.RI "bool \fBtry_lock_shared\fP ()"
.br
.ti -1c
.RI "void \fBunlock_shared\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
