.TH "Nasty" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Nasty
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNasty\fP (int i)"
.br
.ti -1c
.RI "\fBNasty\fP * \fBoperator &\fP () const"
.br
.ti -1c
.RI "\fBNasty\fP (int i)"
.br
.ti -1c
.RI "\fBNasty\fP * \fBoperator &\fP () const"
.br
.ti -1c
.RI "\fBNasty\fP * \fBoperator&\fP () const"
.br
.ti -1c
.RI "\fBNasty\fP * \fBoperator&\fP () const"
.br
.ti -1c
.RI "\fBNasty\fP * \fBoperator&\fP () const"
.br
.ti -1c
.RI "\fBNasty\fP * \fBoperator&\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBi_\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBcounter_\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
