.TH "NCConvertingDeleter< T[]>" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NCConvertingDeleter< T[]>
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNCConvertingDeleter\fP (\fBNCConvertingDeleter\fP const &)=delete"
.br
.ti -1c
.RI "\fBNCConvertingDeleter\fP (\fBNCConvertingDeleter\fP &&)=default"
.br
.ti -1c
.RI "template<class U > \fBNCConvertingDeleter\fP (\fBNCConvertingDeleter\fP< \fBU\fP > &&)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBT\fP *) const"
.br
.ti -1c
.RI "\fBNCConvertingDeleter\fP (\fBNCConvertingDeleter\fP const &)=delete"
.br
.ti -1c
.RI "\fBNCConvertingDeleter\fP (\fBNCConvertingDeleter\fP &&)=default"
.br
.ti -1c
.RI "template<class U > \fBNCConvertingDeleter\fP (\fBNCConvertingDeleter\fP< \fBU\fP > &&)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBT\fP *) const"
.br
.ti -1c
.RI "\fBNCConvertingDeleter\fP (\fBNCConvertingDeleter\fP const &)=delete"
.br
.ti -1c
.RI "\fBNCConvertingDeleter\fP (\fBNCConvertingDeleter\fP &&)=default"
.br
.ti -1c
.RI "template<class U > \fBNCConvertingDeleter\fP (\fBNCConvertingDeleter\fP< \fBU\fP > &&)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBT\fP *) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
