.TH "NCGenericDeleter" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NCGenericDeleter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNCGenericDeleter\fP (\fBNCGenericDeleter\fP const &)=delete"
.br
.ti -1c
.RI "\fBNCGenericDeleter\fP (\fBNCGenericDeleter\fP &&)=default"
.br
.ti -1c
.RI "void \fBoperator()\fP (void *) const"
.br
.ti -1c
.RI "\fBNCGenericDeleter\fP (\fBNCGenericDeleter\fP const &)=delete"
.br
.ti -1c
.RI "\fBNCGenericDeleter\fP (\fBNCGenericDeleter\fP &&)=default"
.br
.ti -1c
.RI "void \fBoperator()\fP (void *) const"
.br
.ti -1c
.RI "\fBNCGenericDeleter\fP (\fBNCGenericDeleter\fP const &)=delete"
.br
.ti -1c
.RI "\fBNCGenericDeleter\fP (\fBNCGenericDeleter\fP &&)=default"
.br
.ti -1c
.RI "void \fBoperator()\fP (void *) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
