.TH "plugins/net_api_plugin/include/aacio/net_api_plugin/net_api_plugin.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/net_api_plugin/include/aacio/net_api_plugin/net_api_plugin.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/net_plugin/net_plugin\&.hpp>\fP
.br
\fC#include <aacio/http_plugin/http_plugin\&.hpp>\fP
.br
\fC#include <appbase/application\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::net_api_plugin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
