.TH "no_copy" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
no_copy
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBno_copy\fP (\fBno_copy\fP &&)"
.br
.ti -1c
.RI "\fBno_copy\fP (\fBno_copy\fP &&)"
.br
.ti -1c
.RI "\fBno_copy\fP (\fBno_copy\fP const &)=delete"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
