.TH "no_default_allocator< T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
no_default_allocator< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class U > \fBno_default_allocator\fP (\fBno_default_allocator\fP< \fBU\fP >) TEST_NOEXCEPT"
.br
.ti -1c
.RI "\fBT\fP * \fBallocate\fP (std::size_t n)"
.br
.ti -1c
.RI "void \fBdeallocate\fP (\fBT\fP *p, std::size_t)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBno_default_allocator\fP \fBcreate\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (\fBno_default_allocator\fP, \fBno_default_allocator\fP)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBno_default_allocator\fP x, \fBno_default_allocator\fP y)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
