.TH "NoCtors" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NoCtors
.SH SYNOPSIS
.br
.PP
.PP
Inherits DEFINE_BASENoCtors\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBBase\fP = DEFINE_BASE(\fBNoCtors\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "DEFINE_EXPLICIT \fBNoCtors\fP (\fBNoCtors\fP const &)=delete"
.br
.ti -1c
.RI "\fBNoCtors\fP & \fBoperator=\fP (\fBNoCtors\fP const &)=delete"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
