.TH "NoDefaultAllocator< T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NoDefaultAllocator< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits allocator< T >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrebind\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoDefaultAllocator\fP (int id_)"
.br
.ti -1c
.RI "template<typename U > \fBNoDefaultAllocator\fP (const \fBNoDefaultAllocator\fP< \fBU\fP > &a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
