.TH "NoDefault" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NoDefault
.SH SYNOPSIS
.br
.PP
.PP
Inherits DEFINE_BASENoDefault\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBBase\fP = DEFINE_BASE(\fBNoDefault\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoDefault\fP (int)"
.br
.ti -1c
.RI "constexpr \fBNoDefault\fP (int v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
