.TH "node_rt_info" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_rt_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBremote\fP"
.br
.ti -1c
.RI "string \fBpid_file\fP"
.br
.ti -1c
.RI "string \fBkill_cmd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
