.TH "Node" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBinary< inType >\fP, \fBLit\fP, and \fBUnary< inType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP * \fB__parent_unsafe\fP () const"
.br
.ti -1c
.RI "void \fB__set_parent\fP (\fBNode\fP *x)"
.br
.ti -1c
.RI "\fBNode\fP * \fB__parent_unsafe\fP () const"
.br
.ti -1c
.RI "void \fB__set_parent\fP (\fBNode\fP *x)"
.br
.ti -1c
.RI "\fBNode\fP * \fB__parent_unsafe\fP () const"
.br
.ti -1c
.RI "void \fB__set_parent\fP (\fBNode\fP *x)"
.br
.ti -1c
.RI "\fBNode\fP * \fB__parent_unsafe\fP () const"
.br
.ti -1c
.RI "void \fB__set_parent\fP (\fBNode\fP *x)"
.br
.ti -1c
.RI "\fBNode\fP (NodeType inType)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNode\fP * \fB__left_\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fB__right_\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fB__parent_\fP"
.br
.ti -1c
.RI "bool \fB__is_black_\fP"
.br
.ti -1c
.RI "const NodeType \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
