.TH "NonThrowingNonNoexceptType" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NonThrowingNonNoexceptType
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNonThrowingNonNoexceptType\fP (int v)"
.br
.ti -1c
.RI "\fBNonThrowingNonNoexceptType\fP (\fBNonThrowingNonNoexceptType\fP &&o) noexcept(false)"
.br
.ti -1c
.RI "\fBNonThrowingNonNoexceptType\fP & \fBoperator=\fP (\fBNonThrowingNonNoexceptType\fP &&) noexcept(false)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBmove_called\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
