.TH "noop::noop" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
noop::noop
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <noop\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBACTION\fP (\fBN\fP(\fBnoop\fP), anyaction)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBon\fP (const anyaction &act)"
.br
.in -1c
.SH "Detailed Description"
.PP 
noop contract All it does is require sender authorization\&. Actions: anyaction 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
