.TH "NotCopyable" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NotCopyable
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNotCopyable\fP (const \fBNotCopyable\fP &)=delete"
.br
.ti -1c
.RI "\fBNotCopyable\fP & \fBoperator=\fP (const \fBNotCopyable\fP &)=delete"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
