.TH "NTCopyAssign" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTCopyAssign
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBNTCopyAssign\fP (int v)"
.br
.ti -1c
.RI "\fBNTCopyAssign\fP (const \fBNTCopyAssign\fP &)=default"
.br
.ti -1c
.RI "\fBNTCopyAssign\fP (\fBNTCopyAssign\fP &&)=default"
.br
.ti -1c
.RI "\fBNTCopyAssign\fP & \fBoperator=\fP (const \fBNTCopyAssign\fP &that)"
.br
.ti -1c
.RI "\fBNTCopyAssign\fP & \fBoperator=\fP (\fBNTCopyAssign\fP &&)=delete"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
