.TH "NTCopy" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTCopy
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBNTCopy\fP (int v)"
.br
.ti -1c
.RI "\fBNTCopy\fP (const \fBNTCopy\fP &that)"
.br
.ti -1c
.RI "\fBNTCopy\fP (\fBNTCopy\fP &&)=delete"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
