.TH "NTMoveAssign" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTMoveAssign
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBNTMoveAssign\fP (int v)"
.br
.ti -1c
.RI "\fBNTMoveAssign\fP (const \fBNTMoveAssign\fP &)=default"
.br
.ti -1c
.RI "\fBNTMoveAssign\fP (\fBNTMoveAssign\fP &&)=default"
.br
.ti -1c
.RI "\fBNTMoveAssign\fP & \fBoperator=\fP (const \fBNTMoveAssign\fP &that)=default"
.br
.ti -1c
.RI "\fBNTMoveAssign\fP & \fBoperator=\fP (\fBNTMoveAssign\fP &&that)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
