.TH "Operation" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Operation
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOperation\fP (\fBElement\fP &element, \fBModuleInstance\fP *instanceInit, \fBSExpressionWasmBuilder\fP &builder)"
.br
.ti -1c
.RI "\fBLiteral\fP \fBoperate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBModuleInstance\fP * \fBinstance\fP"
.br
.ti -1c
.RI "\fBName\fP \fBoperation\fP"
.br
.ti -1c
.RI "\fBName\fP \fBname\fP"
.br
.ti -1c
.RI "\fBLiteralList\fP \fBarguments\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
