.TH "p2p_stress.StressNetwork" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p2p_stress.StressNetwork
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBmaxIndex\fP (self)"
.br
.ti -1c
.RI "def \fBrandAcctName\fP (self)"
.br
.ti -1c
.RI "def \fBexecute\fP (self, cmdInd, \fBnode\fP, ta, aacio)"
.br
.ti -1c
.RI "def \fBon_exit\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtrList\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBspeeds\fP = [1,5,10,30,60,100,500]"
.br
.ti -1c
.RI "int \fBsec\fP = 10"
.br
.ti -1c
.RI "int \fBmaxthreads\fP = 100"
.br
.ti -1c
.RI "list \fBtrList\fP = []"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
