.TH "externals/magic_get/include/boost/pfr.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
externals/magic_get/include/boost/pfr.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <boost/pfr/precise\&.hpp>\fP
.br
\fC#include <boost/pfr/flat\&.hpp>\fP
.br

.SH "Detailed Description"
.PP 
Includes all the Boost\&.PFR headers, except and 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
