.TH "poca_alloc< T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
poca_alloc< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef std::true_type \fBpropagate_on_container_copy_assignment\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpoca_alloc\fP (\fBalloc_imp\fP< \fBT\fP > *imp_)"
.br
.ti -1c
.RI "template<class U > \fBpoca_alloc\fP (const \fBpoca_alloc\fP< \fBU\fP > &\fBother\fP)"
.br
.ti -1c
.RI "\fBT\fP * \fBallocate\fP (std::size_t n)"
.br
.ti -1c
.RI "void \fBdeallocate\fP (\fBT\fP *p, std::size_t n)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBalloc_imp\fP< \fBT\fP > * \fBimp\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
