.TH "PointerIntHelper< 4 >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PointerIntHelper< 4 >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef I32 \fBIntType\fP"
.br
.ti -1c
.RI "typedef U32 \fBUnsignedIntType\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
