.TH "post_record" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
post_record
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpost_record\fP (uint32_t c=\fBnow\fP())"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Name \fBtable_id\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBtotal_votes\fP = 0"
.br
.ti -1c
.RI "uint64_t \fBclaimed_votes\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBcreated\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
