.TH "externals/magic_get/include/boost/pfr/precise.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
externals/magic_get/include/boost/pfr/precise.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <boost/pfr/precise/core\&.hpp>\fP
.br
\fC#include <boost/pfr/precise/functors\&.hpp>\fP
.br
\fC#include <boost/pfr/precise/ops\&.hpp>\fP
.br
\fC#include <boost/pfr/precise/io\&.hpp>\fP
.br
\fC#include <boost/pfr/precise/tuple_size\&.hpp>\fP
.br
\fC#include <boost/pfr/precise/functions_for\&.hpp>\fP
.br

.SH "Detailed Description"
.PP 
Includes all the Boost\&.PFR headers that do not define \fCflat_*\fP functions, except 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
