.TH "processor_setup_ext" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
processor_setup_ext
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprocessor_setup_ext\fP (bool \fBserver\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "websocketpp::lib::error_code \fBec\fP"
.br
.ti -1c
.RI "con_msg_manager_type::ptr \fBmsg_manager\fP"
.br
.ti -1c
.RI "stub_config::rng_type \fBrng\fP"
.br
.ti -1c
.RI "stub_config::request_type \fBreq\fP"
.br
.ti -1c
.RI "stub_config::response_type \fBres\fP"
.br
.ti -1c
.RI "\fBwebsocketpp::processor::hybi13\fP< \fBstub_config_ext\fP > \fBp\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
