.TH "plugins/producer_plugin/include/aacio/producer_plugin/producer_plugin.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/producer_plugin/include/aacio/producer_plugin/producer_plugin.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain_plugin/chain_plugin\&.hpp>\fP
.br
\fC#include <appbase/application\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::producer_plugin\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBblock_production_condition_enum\fP { \fBproduced\fP = 0, \fBnot_synced\fP = 1, \fBnot_my_turn\fP = 2, \fBnot_time_yet\fP = 3, \fBno_private_key\fP = 4, \fBlow_participation\fP = 5, \fBlag\fP = 6, \fBexception_producing_block\fP = 7 }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
