.TH "contracts/proxy/proxy.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/proxy/proxy.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <proxy/proxy\&.hpp>\fP
.br
\fC#include <aacio\&.system/aacio\&.system\&.hpp>\fP
.br
\fC#include <aaciolib/transaction\&.hpp>\fP
.br
\fC#include <aaciolib/currency\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBproxy::configs::get\fP (\fBconfig\fP &out, const account_name &self)"
.br
.ti -1c
.RI "void \fBproxy::configs::store\fP (const \fBconfig\fP &in, const account_name &self)"
.br
.ti -1c
.RI "template<typename T > void \fBproxy::apply_transfer\fP (uint64_t receiver, account_name code, const \fBT\fP &transfer)"
.br
.ti -1c
.RI "void \fBproxy::apply_setowner\fP (uint64_t receiver, set_owner params)"
.br
.ti -1c
.RI "template<size_t \&.\&.\&. Args> void \fBproxy::apply_onerror\fP (uint64_t receiver, const \fBdeferred_transaction\fP &failed_dtrx)"
.br
.ti -1c
.RI "void \fBapply\fP (uint64_t receiver, uint64_t code, uint64_t \fBaction\fP)"
.br
.RI "The apply method implements the dispatch of events to this contract\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
