.TH "pull_awaiter" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pull_awaiter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBawait_ready\fP ()"
.br
.ti -1c
.RI "void \fBawait_suspend\fP (coroutine_handle<> rh)"
.br
.ti -1c
.RI "int \fBawait_resume\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchannel\fP * \fBch\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
