.TH "rand1< UIntType, Min, Max >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rand1< UIntType, Min, Max >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef UIntType \fBresult_type\fP"
.br
.ti -1c
.RI "typedef UIntType \fBresult_type\fP"
.br
.ti -1c
.RI "typedef UIntType \fBresult_type\fP"
.br
.ti -1c
.RI "typedef UIntType \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrand1\fP (result_type sd=Min)"
.br
.ti -1c
.RI "result_type \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBrand1\fP (result_type sd=Min)"
.br
.ti -1c
.RI "result_type \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBrand1\fP (result_type sd=Min)"
.br
.ti -1c
.RI "result_type \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBrand1\fP (result_type sd=Min)"
.br
.ti -1c
.RI "result_type \fBoperator()\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static TEST_CONSTEXPR result_type \fBmin\fP ()"
.br
.ti -1c
.RI "static TEST_CONSTEXPR result_type \fBmax\fP ()"
.br
.ti -1c
.RI "static TEST_CONSTEXPR result_type \fBmin\fP ()"
.br
.ti -1c
.RI "static TEST_CONSTEXPR result_type \fBmax\fP ()"
.br
.ti -1c
.RI "static TEST_CONSTEXPR result_type \fBmin\fP ()"
.br
.ti -1c
.RI "static TEST_CONSTEXPR result_type \fBmax\fP ()"
.br
.ti -1c
.RI "static TEST_CONSTEXPR result_type \fBmin\fP ()"
.br
.ti -1c
.RI "static TEST_CONSTEXPR result_type \fBmax\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
