.TH "random_access_iterator< It >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
random_access_iterator< It >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::random_access_iterator_tag \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef std::iterator_traits< It >::value_type \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef std::iterator_traits< It >::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef It \fBpointer\fP"
.br
.ti -1c
.RI "typedef std::iterator_traits< It >::reference \fBreference\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 It \fBbase\fP () const"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBrandom_access_iterator\fP (It it)"
.br
.ti -1c
.RI "template<class U > TEST_CONSTEXPR_CXX14 \fBrandom_access_iterator\fP (const \fBrandom_access_iterator\fP< \fBU\fP > &u)"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 reference \fBoperator*\fP () const"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 pointer \fBoperator\->\fP () const"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBrandom_access_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBrandom_access_iterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBrandom_access_iterator\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBrandom_access_iterator\fP \fBoperator\-\-\fP (int)"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBrandom_access_iterator\fP & \fBoperator+=\fP (difference_type n)"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBrandom_access_iterator\fP \fBoperator+\fP (difference_type n) const"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBrandom_access_iterator\fP & \fBoperator\-=\fP (difference_type n)"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBrandom_access_iterator\fP \fBoperator\-\fP (difference_type n) const"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 reference \fBoperator[]\fP (difference_type n) const"
.br
.ti -1c
.RI "template<class T > void \fBoperator,\fP (\fBT\fP const &) DELETE_FUNCTION"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<class U > class \fBrandom_access_iterator\fP"
.br
.ti -1c
.RI "TEST_CONSTEXPR_CXX14 \fBrandom_access_iterator\fP \fBoperator+\fP (difference_type n, \fBrandom_access_iterator\fP x)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
