.TH "rapid_cxx_test::test_outcome" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rapid_cxx_test::test_outcome
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_outcome\fP (failure_type_t type1, const char *file1, const char *func1, std::size_t line1, const char *expression1, const char *message1)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "failure_type_t \fBtype\fP"
.br
.ti -1c
.RI "const char * \fBfile\fP"
.br
.ti -1c
.RI "const char * \fBfunc\fP"
.br
.ti -1c
.RI "std::size_t \fBline\fP"
.br
.ti -1c
.RI "const char * \fBexpression\fP"
.br
.ti -1c
.RI "const char * \fBmessage\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
