.TH "rapid_cxx_test::failure_type" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rapid_cxx_test::failure_type
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBenum_type\fP { \fBnone\fP, \fBunsupported\fP, \fBwarn\fP, \fBcheck\fP, \fBrequire\fP, \fBassert\fP, \fBuncaught_exception\fP }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
