.TH "rapid_cxx_test::checkpoint" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rapid_cxx_test::checkpoint
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBfile\fP"
.br
.ti -1c
.RI "const char * \fBfunc\fP"
.br
.ti -1c
.RI "std::size_t \fBline\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
