.TH "rapid_cxx_test::test_reporter" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rapid_cxx_test::test_reporter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtest_case_begin\fP ()"
.br
.ti -1c
.RI "void \fBtest_case_end\fP ()"
.br
.ti -1c
.RI "void \fBreport\fP (\fBtest_outcome\fP o)"
.br
.ti -1c
.RI "\fBtest_outcome\fP \fBcurrent_failure\fP () const"
.br
.ti -1c
.RI "void \fBclear_failure\fP ()"
.br
.ti -1c
.RI "std::size_t \fBtest_case_count\fP () const"
.br
.ti -1c
.RI "std::size_t \fBtest_case_failure_count\fP () const"
.br
.ti -1c
.RI "std::size_t \fBunsupported_count\fP () const"
.br
.ti -1c
.RI "std::size_t \fBassertion_count\fP () const"
.br
.ti -1c
.RI "std::size_t \fBwarning_failure_count\fP () const"
.br
.ti -1c
.RI "std::size_t \fBcheck_failure_count\fP () const"
.br
.ti -1c
.RI "std::size_t \fBrequire_failure_count\fP () const"
.br
.ti -1c
.RI "std::size_t \fBfailure_count\fP () const"
.br
.ti -1c
.RI "void \fBprint_summary\fP (const char *suitename) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
