.TH "rapid_cxx_test::test_suite" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rapid_cxx_test::test_suite
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBtest_case\fP const  * \fBiterator\fP"
.br
.ti -1c
.RI "typedef iterator \fBconst_iterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_suite\fP (const char *xname)"
.br
.ti -1c
.RI "const char * \fBname\fP () const"
.br
.ti -1c
.RI "std::size_t \fBsize\fP () const"
.br
.ti -1c
.RI "\fBtest_case\fP const  & \fBoperator[]\fP (std::size_t i) const"
.br
.ti -1c
.RI "const_iterator \fBbegin\fP () const"
.br
.ti -1c
.RI "const_iterator \fBend\fP () const"
.br
.ti -1c
.RI "std::size_t \fBregister_test\fP (\fBtest_case\fP tc)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
