.TH "recursive_directory_iterator::__shared_imp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
recursive_directory_iterator::__shared_imp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "stack< \fB__dir_stream\fP > \fB__stack_\fP"
.br
.ti -1c
.RI "directory_options \fB__options_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
