.TH "remote_deploy" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
remote_deploy
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBssh_cmd\fP = '/usr/bin/ssh'"
.br
.ti -1c
.RI "string \fBscp_cmd\fP = '/usr/bin/scp'"
.br
.ti -1c
.RI "string \fBssh_identity\fP"
.br
.ti -1c
.RI "string \fBssh_args\fP"
.br
.ti -1c
.RI "bfs::path \fBlocal_config_file\fP = 'temp_config'"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
