.TH "RequireAllocationGuard" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RequireAllocationGuard
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRequireAllocationGuard\fP (std::size_t RequireAtLeast=1)"
.br
.ti -1c
.RI "void \fBrequireAtLeast\fP (std::size_t \fBN\fP)"
.br
.ti -1c
.RI "void \fBrequireExactly\fP (std::size_t \fBN\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
