.TH "Runtime::ModuleExportResolver" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Runtime::ModuleExportResolver
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRuntime::Resolver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModuleExportResolver\fP (const \fBIR::Module\fP &inModule, \fBModuleInstance\fP *inModuleInstance)"
.br
.ti -1c
.RI "bool \fBresolve\fP (const std::string &moduleName, const std::string &exportName, \fBIR::ObjectType\fP type, \fBObjectInstance\fP *&outObject) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
