.TH "Runtime::Value" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Runtime::Value
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRuntime::UntaggedValue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValue\fP (I32 inI32)"
.br
.ti -1c
.RI "\fBValue\fP (I64 inI64)"
.br
.ti -1c
.RI "\fBValue\fP (U32 inU32)"
.br
.ti -1c
.RI "\fBValue\fP (U64 inU64)"
.br
.ti -1c
.RI "\fBValue\fP (F32 inF32)"
.br
.ti -1c
.RI "\fBValue\fP (F64 inF64)"
.br
.ti -1c
.RI "\fBValue\fP (IR::ValueType inType, \fBUntaggedValue\fP inValue)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IR::ValueType \fBtype\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::string \fBasString\fP (const \fBValue\fP &value)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
