.TH "Runtime::IntrinsicResolver" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Runtime::IntrinsicResolver
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRuntime::Resolver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "RUNTIME_API bool \fBresolve\fP (const std::string &moduleName, const std::string &exportName, \fBIR::ObjectType\fP type, \fBObjectInstance\fP *&outObject) override"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static RUNTIME_API \fBIntrinsicResolver\fP \fBsingleton\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
