.TH "Runtime::FunctionInstance" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Runtime::FunctionInstance
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRuntime::GCObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionInstance\fP (\fBModuleInstance\fP *inModuleInstance, const \fBFunctionType\fP *inType, void *inNativeFunction=nullptr, const char *inDebugName='<unidentified \fBFunctionInstance\fP>')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBModuleInstance\fP * \fBmoduleInstance\fP"
.br
.ti -1c
.RI "const \fBFunctionType\fP * \fBtype\fP"
.br
.ti -1c
.RI "void * \fBnativeFunction\fP"
.br
.ti -1c
.RI "std::string \fBdebugName\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
