.TH "Runtime::GCObject" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Runtime::GCObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRuntime::ObjectInstance\fP\&.
.PP
Inherited by \fBRuntime::FunctionInstance\fP, \fBRuntime::GlobalInstance\fP, \fBRuntime::MemoryInstance\fP, \fBRuntime::ModuleInstance\fP, and \fBRuntime::TableInstance\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGCObject\fP (ObjectKind inKind)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
