.TH "Runtime::MemoryInstance" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Runtime::MemoryInstance
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRuntime::GCObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemoryInstance\fP (const \fBMemoryType\fP &inType)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMemoryType\fP \fBtype\fP"
.br
.ti -1c
.RI "U8 * \fBbaseAddress\fP"
.br
.ti -1c
.RI "std::atomic< Uptr > \fBnumPages\fP"
.br
.ti -1c
.RI "Uptr \fBendOffset\fP"
.br
.ti -1c
.RI "U8 * \fBreservedBaseAddress\fP"
.br
.ti -1c
.RI "Uptr \fBreservedNumPlatformPages\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBMemoryInstance\fP * \fBtheMemoryInstance\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
