.TH "RuntimeHelpers::MoveCrashes" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RuntimeHelpers::MoveCrashes
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveCrashes\fP (int v=0) noexcept"
.br
.ti -1c
.RI "\fBMoveCrashes\fP (\fBMoveCrashes\fP &&) noexcept"
.br
.ti -1c
.RI "\fBMoveCrashes\fP & \fBoperator=\fP (\fBMoveCrashes\fP &&) noexcept"
.br
.ti -1c
.RI "\fBMoveCrashes\fP & \fBoperator=\fP (int v) noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
