.TH "Runtime::Resolver" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Runtime::Resolver
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBaacio::chain::webassembly::common::root_resolver\fP, \fBRootResolver\fP, \fBRuntime::IntrinsicResolver\fP, \fBRuntime::LazyResolver\fP, \fBRuntime::ModuleExportResolver\fP, \fBRuntime::NullResolver\fP, and \fBTestScriptResolver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBresolve\fP (const std::string &moduleName, const std::string &exportName, \fBIR::ObjectType\fP type, \fBObjectInstance\fP *&outObject)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
