.TH "Runtime::ModuleInstance" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Runtime::ModuleInstance
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRuntime::GCObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModuleInstance\fP (\fBstd::vector\fP< \fBFunctionInstance\fP *> &&inFunctionImports, \fBstd::vector\fP< \fBTableInstance\fP *> &&inTableImports, \fBstd::vector\fP< \fBMemoryInstance\fP *> &&inMemoryImports, \fBstd::vector\fP< \fBGlobalInstance\fP *> &&inGlobalImports)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::map\fP< std::string, \fBObjectInstance\fP * > \fBexportMap\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBFunctionInstance\fP * > \fBfunctionDefs\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBFunctionInstance\fP * > \fBfunctions\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBTableInstance\fP * > \fBtables\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBMemoryInstance\fP * > \fBmemories\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBGlobalInstance\fP * > \fBglobals\fP"
.br
.ti -1c
.RI "\fBMemoryInstance\fP * \fBdefaultMemory\fP"
.br
.ti -1c
.RI "\fBTableInstance\fP * \fBdefaultTable\fP"
.br
.ti -1c
.RI "\fBLLVMJIT::JITModuleBase\fP * \fBjitModule\fP"
.br
.ti -1c
.RI "Uptr \fBstartFunctionIndex\fP = UINTPTR_MAX"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
