.TH "S< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits function< void()>, and function< void()>\&.
.PP
Inherited by \fBSD\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef short(* \fBFreeFunc\fP) (long)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBS\fP (int i)"
.br
.ti -1c
.RI "\fBS\fP (const \fBS\fP &rhs)"
.br
.ti -1c
.RI "\fBS\fP & \fBoperator=\fP (const \fBS\fP &rhs)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBS\fP &rhs) const"
.br
.ti -1c
.RI "int \fBget\fP () const"
.br
.ti -1c
.RI "\fBS\fP (int i)"
.br
.ti -1c
.RI "\fBS\fP (const \fBS\fP &rhs)"
.br
.ti -1c
.RI "\fBS\fP & \fBoperator=\fP (const \fBS\fP &rhs)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBS\fP &rhs) const"
.br
.ti -1c
.RI "int \fBget\fP () const"
.br
.ti -1c
.RI "\fBS\fP (\fBT\fP const &)"
.br
.ti -1c
.RI "\fBoperator FreeFunc\fP () const"
.br
.ti -1c
.RI "double \fBoperator()\fP (char, int &)"
.br
.ti -1c
.RI "double const  & \fBoperator()\fP (char, int &) const"
.br
.ti -1c
.RI "double volatile & \fBoperator()\fP (char, int &) volatile"
.br
.ti -1c
.RI "double const volatile & \fBoperator()\fP (char, int &) const volatile"
.br
.ti -1c
.RI "template<class T > \fBoperator T\fP () const"
.br
.ti -1c
.RI "\fBS\fP (int v)"
.br
.ti -1c
.RI "\fBS\fP (const \fBS\fP &rhs)"
.br
.ti -1c
.RI "\fBS\fP (int v)"
.br
.ti -1c
.RI "constexpr \fBS\fP (const \fBS\fP &rhs)"
.br
.ti -1c
.RI "constexpr \fBS\fP (const \fBS\fP &&rhs)"
.br
.ti -1c
.RI "\fBS\fP (int j)"
.br
.ti -1c
.RI "\fBS\fP * \fBoperator &\fP ()"
.br
.ti -1c
.RI "\fBS\fP const  * \fBoperator &\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (int x) const"
.br
.ti -1c
.RI "\fBS\fP (\fBS\fP const &)=default"
.br
.ti -1c
.RI "\fBS\fP (\fBS\fP &&)=default"
.br
.ti -1c
.RI "\fBS\fP & \fBoperator=\fP (\fBS\fP const &)=delete"
.br
.ti -1c
.RI "\fBS\fP & \fBoperator=\fP (\fBS\fP &&)=delete"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int * \fBi_\fP"
.br
.ti -1c
.RI "int \fBv_\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "\fBX\fP \fBx0\fP"
.br
.ti -1c
.RI "\fBX\fP \fBx1\fP"
.br
.ti -1c
.RI "int \fBx2\fP"
.br
.ti -1c
.RI "\fBX\fP \fBx3\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
