.TH "scripts.strip_local_names" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts.strip_local_names
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
.nf
Removes local names. When you don't care about local names but do want
to diff for structural changes, this can help.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
