.TH "semid_ds" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
semid_ds
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBipc_perm\fP \fBsem_perm\fP"
.br
.ti -1c
.RI "time_t \fBsem_otime\fP"
.br
.ti -1c
.RI "time_t \fB__unused1\fP"
.br
.ti -1c
.RI "time_t \fBsem_ctime\fP"
.br
.ti -1c
.RI "time_t \fB__unused2\fP"
.br
.ti -1c
.RI "unsigned short \fBsem_nsems\fP"
.br
.ti -1c
.RI "char \fB__sem_nsems_pad\fP [sizeof(time_t) \-sizeof(short)]"
.br
.ti -1c
.RI "time_t \fB__unused3\fP"
.br
.ti -1c
.RI "time_t \fB__unused4\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
