.TH "SequenceContainerChecks< Container, CT >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SequenceContainerChecks< Container, CT >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIteratorDebugChecks::BasicContainerChecks< Container, CT >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBBase\fP = \fBBasicContainerChecks\fP< Container, CT >"
.br
.ti -1c
.RI "using \fBvalue_type\fP = typename Container::value_type"
.br
.ti -1c
.RI "using \fBallocator_type\fP = typename Container::allocator_type"
.br
.ti -1c
.RI "using \fBiterator\fP = typename Container::iterator"
.br
.ti -1c
.RI "using \fBconst_iterator\fP = typename Container::const_iterator"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBrun\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
