.TH "Serialization::InputStream" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serialization::InputStream
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSerialization::MemoryInputStream\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBisInput\fP = true }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputStream\fP (const U8 *inNext, const U8 *inEnd)"
.br
.ti -1c
.RI "virtual Uptr \fBcapacity\fP () const =0"
.br
.ti -1c
.RI "const U8 * \fBadvance\fP (Uptr numBytes)"
.br
.ti -1c
.RI "const U8 * \fBpeek\fP (Uptr numBytes)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBgetMoreData\fP (Uptr numBytes)=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const U8 * \fBnext\fP"
.br
.ti -1c
.RI "const U8 * \fBend\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
