.TH "Serialization::MemoryInputStream" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serialization::MemoryInputStream
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSerialization::InputStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemoryInputStream\fP (const U8 *begin, Uptr numBytes)"
.br
.ti -1c
.RI "virtual Uptr \fBcapacity\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
