.TH "server_identities" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server_identities
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvector\fP< \fBserver_name_def\fP > \fBproducer\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBserver_name_def\fP > \fBnonprod\fP"
.br
.ti -1c
.RI "\fBvector\fP< string > \fBdb\fP"
.br
.ti -1c
.RI "string \fBdefault_aacio_home\fP"
.br
.ti -1c
.RI "\fBremote_deploy\fP \fBssh\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
