.TH "set_account_permission_subcommand" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
set_account_permission_subcommand
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBset_account_permission_subcommand\fP (CLI::App *accountCmd)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBaccountStr\fP"
.br
.ti -1c
.RI "string \fBpermissionStr\fP"
.br
.ti -1c
.RI "string \fBauthorityJsonOrFile\fP"
.br
.ti -1c
.RI "string \fBparentStr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
