.TH "sha256" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sha256
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBlen\fP"
.br
.ti -1c
.RI "uint32_t \fBh\fP [8]"
.br
.ti -1c
.RI "uint8_t \fBbuf\fP [64]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
