.TH "shm_info" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shm_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB__used_ids\fP"
.br
.ti -1c
.RI "unsigned long \fBshm_tot\fP"
.br
.ti -1c
.RI "unsigned long \fBshm_rss\fP"
.br
.ti -1c
.RI "unsigned long \fBshm_swp\fP"
.br
.ti -1c
.RI "unsigned long \fB__swap_attempts\fP"
.br
.ti -1c
.RI "unsigned long \fB__swap_successes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
