.TH "shmid_ds" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shmid_ds
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBipc_perm\fP \fBshm_perm\fP"
.br
.ti -1c
.RI "size_t \fBshm_segsz\fP"
.br
.ti -1c
.RI "time_t \fBshm_atime\fP"
.br
.ti -1c
.RI "int \fB__unused1\fP"
.br
.ti -1c
.RI "time_t \fBshm_dtime\fP"
.br
.ti -1c
.RI "int \fB__unused2\fP"
.br
.ti -1c
.RI "time_t \fBshm_ctime\fP"
.br
.ti -1c
.RI "int \fB__unused3\fP"
.br
.ti -1c
.RI "pid_t \fBshm_cpid\fP"
.br
.ti -1c
.RI "pid_t \fBshm_lpid\fP"
.br
.ti -1c
.RI "unsigned long \fBshm_nattch\fP"
.br
.ti -1c
.RI "unsigned long \fB__pad1\fP"
.br
.ti -1c
.RI "unsigned long \fB__pad2\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
