.TH "simpletoken" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simpletoken
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBaacio::contract\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsimpletoken\fP (account_name self)"
.br
.ti -1c
.RI "void \fBtransfer\fP (account_name from, account_name to, uint64_t quantity)"
.br
.ti -1c
.RI "void \fBissue\fP (account_name to, uint64_t quantity)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
