.TH "contracts/skeleton/skeleton.cpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/skeleton/skeleton.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <skeleton\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBapply\fP (uint64_t receiver, uint64_t code, uint64_t \fBaction\fP)"
.br
.RI "The apply method implements the dispatch of events to this contract\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void apply (uint64_t receiver, uint64_t code, uint64_t action)"

.PP
The apply method implements the dispatch of events to this contract\&. The init() and \fBapply()\fP methods must have \fBC\fP calling convention so that the blockchain can lookup and call these methods\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
