.TH "small_block_properties" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
small_block_properties
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbase_properties\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
