.TH "small_tracked_t" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
small_tracked_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsmall_tracked_t\fP (\fBsmall_tracked_t\fP const &) noexcept"
.br
.ti -1c
.RI "\fBsmall_tracked_t\fP (\fBsmall_tracked_t\fP &&) noexcept"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args> \fBsmall_tracked_t\fP (Args &&\&.\&.\&.)"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args> \fBsmall_tracked_t\fP (std::initializer_list< int >, Args &&\&.\&.\&.)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTypeID\fP const  * \fBarg_types\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
