.TH "contracts/social/social.cpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/social/social.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aac\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpost_action\fP"
.br
.ti -1c
.RI "struct \fBvote_action\fP"
.br
.ti -1c
.RI "struct \fBpost_record\fP"
.br
.ti -1c
.RI "struct \fBaccount\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBapply_social_post\fP ()"
.br
.ti -1c
.RI "void \fBapply_social_vote\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void apply_social_post ()"
When a user posts we create a record that tracks the total votes and the time it was created\&. \fBA\fP user can submit this action multiple times, but subsequent calls do nothing\&.
.PP
This method only does something when called in the context of the author, if any other contexts are notified 
.SS "void apply_social_vote ()"
This action is called when a user casts a vote, it requires that this code is executed in the context of both the voter and the author\&. When executed in the author's context it updates the vote total\&. When executed prevent the author's code from rejecting the potentially negative vote 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
