.TH "some_comp2< T >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
some_comp2< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBT\fP \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsome_comp2\fP (const \fBsome_comp2\fP &)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBT\fP &, const \fBT\fP &) const"
.br
.ti -1c
.RI "\fBsome_comp2\fP (const \fBsome_comp2\fP &)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBT\fP &, const \fBT\fP &) const"
.br
.ti -1c
.RI "\fBsome_comp2\fP (const \fBsome_comp2\fP &)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBT\fP &, const \fBT\fP &) const"
.br
.ti -1c
.RI "\fBsome_comp2\fP (const \fBsome_comp2\fP &)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBT\fP &, const \fBT\fP &) const"
.br
.ti -1c
.RI "\fBsome_comp2\fP (const \fBsome_comp2\fP &)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBT\fP &, const \fBT\fP &) const"
.br
.ti -1c
.RI "\fBsome_comp2\fP (const \fBsome_comp2\fP &)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBT\fP &, const \fBT\fP &) const"
.br
.ti -1c
.RI "\fBsome_comp2\fP (const \fBsome_comp2\fP &)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBT\fP &, const \fBT\fP &) const"
.br
.ti -1c
.RI "\fBsome_comp2\fP (const \fBsome_comp2\fP &)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBT\fP &, const \fBT\fP &) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
