.TH "tests/tests/special_accounts_tests.cpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/tests/special_accounts_tests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <boost/test/unit_test\&.hpp>\fP
.br
\fC#include <aacio/chain/chain_controller\&.hpp>\fP
.br
\fC#include <aacio/chain/exceptions\&.hpp>\fP
.br
\fC#include <aacio/chain/permission_object\&.hpp>\fP
.br
\fC#include <aacio/testing/tester\&.hpp>\fP
.br
\fC#include <aacio/utilities/tempdir\&.hpp>\fP
.br
\fC#include <fc/crypto/digest\&.hpp>\fP
.br
\fC#include <boost/range/algorithm/find\&.hpp>\fP
.br
\fC#include <boost/range/algorithm/find_if\&.hpp>\fP
.br
\fC#include <boost/range/algorithm/permutation\&.hpp>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBtester\fP = \fBaacio::testing::tester\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (accounts_exists, \fBtester\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
