.TH "statfs" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
statfs
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBf_type\fP"
.br
.ti -1c
.RI "unsigned long \fBf_bsize\fP"
.br
.ti -1c
.RI "fsblkcnt_t \fBf_blocks\fP"
.br
.ti -1c
.RI "fsblkcnt_t \fBf_bfree\fP"
.br
.ti -1c
.RI "fsblkcnt_t \fBf_bavail\fP"
.br
.ti -1c
.RI "fsfilcnt_t \fBf_files\fP"
.br
.ti -1c
.RI "fsfilcnt_t \fBf_ffree\fP"
.br
.ti -1c
.RI "fsid_t \fBf_fsid\fP"
.br
.ti -1c
.RI "unsigned long \fBf_namelen\fP"
.br
.ti -1c
.RI "unsigned long \fBf_frsize\fP"
.br
.ti -1c
.RI "unsigned long \fBf_flags\fP"
.br
.ti -1c
.RI "unsigned long \fBf_spare\fP [4]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
