.TH "std::__exception_ptr::exception_ptr" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::__exception_ptr::exception_ptr
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexception_ptr\fP (const \fBexception_ptr\fP &) _NOEXCEPT"
.br
.ti -1c
.RI "\fBexception_ptr\fP & \fBoperator=\fP (const \fBexception_ptr\fP &) _NOEXCEPT"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fB__ptr_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
