.TH "std::equal_to< cashew::IString >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::equal_to< cashew::IString >
.SH SYNOPSIS
.br
.PP
.PP
Inherits binary_function< cashew::IString, cashew::IString, bool >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBcashew::IString\fP &x, const \fBcashew::IString\fP &y) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
