.TH "std::less< checksum256 >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::less< checksum256 > \- provide less for \fBchecksum256\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.hpp>\fP
.PP
Inherits binary_function< checksum256, checksum256, bool >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBchecksum256\fP &lhs, const \fBchecksum256\fP &rhs) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct std::less< checksum256 >"
provide less for \fBchecksum256\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
