.TH "std::is_error_code_enum< testing >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_error_code_enum< testing >
.SH SYNOPSIS
.br
.PP
.PP
Inherits true_type, and true_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
