.TH "stltest::contract::message" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stltest::contract::message
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static uint64_t \fBget_account\fP ()"
.br
.ti -1c
.RI "static uint64_t \fBget_name\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "account_name \fBfrom\fP"
.br
.ti -1c
.RI "account_name \fBto\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename DataStream > DataStream & \fBoperator<<\fP (DataStream &ds, const \fBmessage\fP &m)"
.br
.ti -1c
.RI "template<typename DataStream > DataStream & \fBoperator>>\fP (DataStream &ds, \fBmessage\fP &m)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
