.TH "StoresIncomplete< IncompleteT, Del >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StoresIncomplete< IncompleteT, Del >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIncompleteType\fP * \fBget\fP () const"
.br
.ti -1c
.RI "Del & \fBget_deleter\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::unique_ptr< IncompleteT, Del > \fBm_ptr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
