.TH "libraries/utilities/include/aacio/utilities/string_escape.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/utilities/include/aacio/utilities/string_escape.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBaacio::utilities::escape_string_for_c_source_code\fP (const std::string &input)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
