.TH "stub_config_ext" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stub_config_ext
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpermessage_deflate_config\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBwebsocketpp::http::parser::request\fP \fBrequest_type\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::http::parser::response\fP \fBresponse_type\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::message_buffer::message\fP< \fBwebsocketpp::message_buffer::alloc::con_msg_manager\fP > \fBmessage_type\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::message_buffer::alloc::con_msg_manager\fP< \fBmessage_type\fP > \fBcon_msg_manager_type\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::random::none::int_generator\fP< uint32_t > \fBrng_type\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::extensions::permessage_deflate::enabled\fP< \fBpermessage_deflate_config\fP > \fBpermessage_deflate_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const size_t \fBmax_message_size\fP = 16000000"
.br
.ti -1c
.RI "static const bool \fBenable_extensions\fP = true"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
