.TH "stub_config::permessage_deflate_config" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stub_config::permessage_deflate_config \- Extension specific config\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef stub_config::request_type \fBrequest_type\fP"
.br
.ti -1c
.RI "typedef stub_config::request_type \fBrequest_type\fP"
.br
.ti -1c
.RI "typedef stub_config::request_type \fBrequest_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Extension specific config\&. 

permessage_compress_config
.PP
\fBpermessage_deflate_config\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
