.TH "stub< con_msg_manager >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stub< con_msg_manager >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef websocketpp::lib::shared_ptr< \fBstub\fP > \fBptr\fP"
.br
.ti -1c
.RI "typedef con_msg_manager< \fBstub\fP > \fBcon_msg_man_type\fP"
.br
.ti -1c
.RI "typedef con_msg_man_type::ptr \fBcon_msg_man_ptr\fP"
.br
.ti -1c
.RI "typedef con_msg_man_type::weak_ptr \fBcon_msg_man_weak_ptr\fP"
.br
.ti -1c
.RI "typedef websocketpp::lib::weak_ptr< \fBstub\fP > \fBweak_ptr\fP"
.br
.ti -1c
.RI "typedef websocketpp::lib::shared_ptr< \fBstub\fP > \fBptr\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstub\fP (con_msg_man_ptr manager, websocketpp::frame::opcode::value op, size_t size=128)"
.br
.ti -1c
.RI "bool \fBrecycle\fP ()"
.br
.ti -1c
.RI "bool \fBrecycle\fP (message *)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "websocketpp::frame::opcode::value \fBm_opcode\fP"
.br
.ti -1c
.RI "con_msg_man_weak_ptr \fBm_manager\fP"
.br
.ti -1c
.RI "size_t \fBm_size\fP"
.br
.ti -1c
.RI "bool \fBrecycled\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
