.TH "systemcapi" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
systemcapi \- Define API for interacting with system level intrinsics\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBaacio_assert\fP (uint32_t \fBtest\fP, const char *cstr)"
.br
.RI "Aborts processing of this action and unwinds all pending changes\&. "
.ti -1c
.RI "void \fBaacio_exit\fP (int32_t code)"
.br
.ti -1c
.RI "time \fBnow\fP ()"
.br
.RI "Get time of the last accepted block\&. "
.in -1c
.SH "Detailed Description"
.PP 
Define API for interacting with system level intrinsics\&. 


.SH "Function Documentation"
.PP 
.SS "void aacio_assert (uint32_t test, const char * cstr)"

.PP
Aborts processing of this action and unwinds all pending changes\&. Aborts processing of this action and unwinds all pending changes if the test condition is true 
.PP
\fBParameters:\fP
.RS 4
\fItest\fP - 0 to abort, 1 to ignore 
.br
\fIcstr\fP - a null terminated action to explain the reason for failure 
.RE
.PP

.SS "void aacio_exit (int32_t code)"
This method will abort execution of wasm without failing the contract\&. This is used to bypass all cleanup / destructors that would normally be called\&. 
.SS "time now ()"

.PP
Get time of the last accepted block\&. Returns the time in seconds from 1970 of the last accepted block (not the block including this action) 
.PP
\fBReturns:\fP
.RS 4
time in seconds from 1970 of the last accepted block 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
