.TH "systemapi" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
systemapi \- Define API for interacting with system level intrinsics\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPrivileged API\fP"
.br
.RI "Defines an API for accessing configuration of the chain that can only be done by privileged accounts\&. "
.ti -1c
.RI "\fBSystem C API\fP"
.br
.RI "Define API for interacting with system level intrinsics\&. "
.in -1c
.SH "Detailed Description"
.PP 
Define API for interacting with system level intrinsics\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
