.TH "contracts/aaciolib/system.h" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/aaciolib/system.h
.SH SYNOPSIS
.br
.PP
\fC#include <aaciolib/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBaacio_assert\fP (uint32_t \fBtest\fP, const char *cstr)"
.br
.RI "Aborts processing of this action and unwinds all pending changes\&. "
.ti -1c
.RI "void \fBaacio_exit\fP (int32_t code)"
.br
.ti -1c
.RI "time \fBnow\fP ()"
.br
.RI "Get time of the last accepted block\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
