.TH "Tag< int >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tag< int >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDerFromTag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTag\fP (int a, const char *b)"
.br
.ti -1c
.RI "\fBTag\fP (int a, const char *b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBval\fP"
.br
.ti -1c
.RI "const char * \fBtag\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
