.TH "tcp_echo_session" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcp_echo_session
.SH SYNOPSIS
.br
.PP
.PP
Inherits enable_shared_from_this< tcp_echo_session >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef websocketpp::lib::shared_ptr< \fBtcp_echo_session\fP > \fBptr\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtcp_echo_session\fP (asio::io_service &service)"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBhandle_read\fP (const asio::error_code &ec, size_t transferred)"
.br
.ti -1c
.RI "void \fBhandle_write\fP (const asio::error_code &ec)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "asio::ip::tcp::socket \fBm_socket\fP"
.br
.ti -1c
.RI "char \fBm_buffer\fP [1024]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
