.TH "tdefl_compressor" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tdefl_compressor
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "tdefl_put_buf_func_ptr \fBm_pPut_buf_func\fP"
.br
.ti -1c
.RI "void * \fBm_pPut_buf_user\fP"
.br
.ti -1c
.RI "mz_uint \fBm_flags\fP"
.br
.ti -1c
.RI "mz_uint \fBm_max_probes\fP [2]"
.br
.ti -1c
.RI "int \fBm_greedy_parsing\fP"
.br
.ti -1c
.RI "mz_uint \fBm_adler32\fP"
.br
.ti -1c
.RI "mz_uint \fBm_lookahead_pos\fP"
.br
.ti -1c
.RI "mz_uint \fBm_lookahead_size\fP"
.br
.ti -1c
.RI "mz_uint \fBm_dict_size\fP"
.br
.ti -1c
.RI "mz_uint8 * \fBm_pLZ_code_buf\fP"
.br
.ti -1c
.RI "mz_uint8 * \fBm_pLZ_flags\fP"
.br
.ti -1c
.RI "mz_uint8 * \fBm_pOutput_buf\fP"
.br
.ti -1c
.RI "mz_uint8 * \fBm_pOutput_buf_end\fP"
.br
.ti -1c
.RI "mz_uint \fBm_num_flags_left\fP"
.br
.ti -1c
.RI "mz_uint \fBm_total_lz_bytes\fP"
.br
.ti -1c
.RI "mz_uint \fBm_lz_code_buf_dict_pos\fP"
.br
.ti -1c
.RI "mz_uint \fBm_bits_in\fP"
.br
.ti -1c
.RI "mz_uint \fBm_bit_buffer\fP"
.br
.ti -1c
.RI "mz_uint \fBm_saved_match_dist\fP"
.br
.ti -1c
.RI "mz_uint \fBm_saved_match_len\fP"
.br
.ti -1c
.RI "mz_uint \fBm_saved_lit\fP"
.br
.ti -1c
.RI "mz_uint \fBm_output_flush_ofs\fP"
.br
.ti -1c
.RI "mz_uint \fBm_output_flush_remaining\fP"
.br
.ti -1c
.RI "mz_uint \fBm_finished\fP"
.br
.ti -1c
.RI "mz_uint \fBm_block_index\fP"
.br
.ti -1c
.RI "mz_uint \fBm_wants_to_finish\fP"
.br
.ti -1c
.RI "tdefl_status \fBm_prev_return_status\fP"
.br
.ti -1c
.RI "const void * \fBm_pIn_buf\fP"
.br
.ti -1c
.RI "void * \fBm_pOut_buf\fP"
.br
.ti -1c
.RI "size_t * \fBm_pIn_buf_size\fP"
.br
.ti -1c
.RI "size_t * \fBm_pOut_buf_size\fP"
.br
.ti -1c
.RI "tdefl_flush \fBm_flush\fP"
.br
.ti -1c
.RI "const mz_uint8 * \fBm_pSrc\fP"
.br
.ti -1c
.RI "size_t \fBm_src_buf_left\fP"
.br
.ti -1c
.RI "size_t \fBm_out_buf_ofs\fP"
.br
.ti -1c
.RI "mz_uint8 \fBm_dict\fP [TDEFL_LZ_DICT_SIZE+TDEFL_MAX_MATCH_LEN \- 1]"
.br
.ti -1c
.RI "mz_uint16 \fBm_huff_count\fP [TDEFL_MAX_HUFF_TABLES][TDEFL_MAX_HUFF_SYMBOLS]"
.br
.ti -1c
.RI "mz_uint16 \fBm_huff_codes\fP [TDEFL_MAX_HUFF_TABLES][TDEFL_MAX_HUFF_SYMBOLS]"
.br
.ti -1c
.RI "mz_uint8 \fBm_huff_code_sizes\fP [TDEFL_MAX_HUFF_TABLES][TDEFL_MAX_HUFF_SYMBOLS]"
.br
.ti -1c
.RI "mz_uint8 \fBm_lz_code_buf\fP [TDEFL_LZ_CODE_BUF_SIZE]"
.br
.ti -1c
.RI "mz_uint16 \fBm_next\fP [TDEFL_LZ_DICT_SIZE]"
.br
.ti -1c
.RI "mz_uint16 \fBm_hash\fP [TDEFL_LZ_HASH_SIZE]"
.br
.ti -1c
.RI "mz_uint8 \fBm_output_buf\fP [TDEFL_OUT_BUF_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
