.TH "tdefl_output_buffer" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tdefl_output_buffer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBm_size\fP"
.br
.ti -1c
.RI "size_t \fBm_capacity\fP"
.br
.ti -1c
.RI "mz_uint8 * \fBm_pBuf\fP"
.br
.ti -1c
.RI "mz_bool \fBm_expandable\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
