.TH "plugins/template_plugin/template_plugin.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/template_plugin/template_plugin.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/template_plugin/template_plugin\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::template_plugin_impl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
