.TH "libraries/utilities/tempdir.cpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/utilities/tempdir.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/utilities/tempdir\&.hpp>\fP
.br
\fC#include <cstdlib>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfc::path\fP \fBaacio::utilities::temp_directory_path\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
