.TH "termios" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
termios
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "tcflag_t \fBc_iflag\fP"
.br
.ti -1c
.RI "tcflag_t \fBc_oflag\fP"
.br
.ti -1c
.RI "tcflag_t \fBc_cflag\fP"
.br
.ti -1c
.RI "tcflag_t \fBc_lflag\fP"
.br
.ti -1c
.RI "cc_t \fBc_line\fP"
.br
.ti -1c
.RI "cc_t \fBc_cc\fP [NCCS]"
.br
.ti -1c
.RI "speed_t \fB__c_ispeed\fP"
.br
.ti -1c
.RI "speed_t \fB__c_ospeed\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
