.TH "test_deleter_base" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_deleter_base
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtest_deleter< T >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBcount\fP = 0"
.br
.ti -1c
.RI "static int \fBdealloc_count\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
