.TH "testUtils.WalletMgr" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testUtils.WalletMgr
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, walletd, nodaacPort=8888, nodaacHost='localhost', port=8899, host='localhost')"
.br
.ti -1c
.RI "def \fBlaunch\fP (self)"
.br
.ti -1c
.RI "def \fBcreate\fP (self, name)"
.br
.ti -1c
.RI "def \fBimportKey\fP (self, \fBaccount\fP, wallet)"
.br
.ti -1c
.RI "def \fBlockWallet\fP (self, wallet)"
.br
.ti -1c
.RI "def \fBunlockWallet\fP (self, wallet)"
.br
.ti -1c
.RI "def \fBlockAllWallets\fP (self)"
.br
.ti -1c
.RI "def \fBgetOpenWallets\fP (self)"
.br
.ti -1c
.RI "def \fBgetKeys\fP (self)"
.br
.ti -1c
.RI "def \fBdumpErrorDetails\fP (self)"
.br
.ti -1c
.RI "def \fBkillall\fP (self)"
.br
.ti -1c
.RI "def \fBcleanup\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBwalletd\fP"
.br
.ti -1c
.RI "\fBnodaacPort\fP"
.br
.ti -1c
.RI "\fBnodaacHost\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBwallets\fP"
.br
.ti -1c
.RI "\fBendpointArgs\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
