.TH "test_model_v2" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_model_v2
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtest_model\fP\&.
.PP
Inherited by \fBtest_model_v3\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBnew_field\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
