.TH "test_action_action< ACCOUNT, NAME >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_action_action< ACCOUNT, NAME >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static account_name \fBget_account\fP ()"
.br
.ti -1c
.RI "static action_name \fBget_name\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaacio::vector\fP< char > \fBdata\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename DataStream > DataStream & \fBoperator<<\fP (DataStream &ds, const \fBtest_action_action\fP &a)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
