.TH "contracts/test_api/test_chain.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/test_api/test_chain.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aaciolib/action\&.h>\fP
.br
\fC#include <aaciolib/chain\&.h>\fP
.br
\fC#include <aaciolib/aacio\&.hpp>\fP
.br
\fC#include 'test_api\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBproducers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
