.TH "test_codecvt" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_codecvt
.SH SYNOPSIS
.br
.PP
.PP
Inherits codecvt< wchar_t, char, std::mbstate_t >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_codecvt\fP (std::size_t refs=0)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
