.TH "test_alloc_base" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_alloc_base
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBnon_default_test_allocator< T >\fP, \fBtest_allocator< T >\fP, and \fBtest_allocator< void >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBthrow_after\fP = INT_MAX"
.br
.ti -1c
.RI "static int \fBcount\fP = 0"
.br
.ti -1c
.RI "static int \fBalloc_count\fP = 0"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static int \fBtime_to_throw\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
