.TH "testUtils.Utils" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testUtils.Utils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBPrint\fP (args, kwargs)"
.br
.ti -1c
.RI "def \fBiAmNotNoon\fP ()"
.br
.ti -1c
.RI "def \fBsetMongoSyncTime\fP (syncTime)"
.br
.ti -1c
.RI "def \fBsetSystemWaitTimeout\fP (timeout)"
.br
.ti -1c
.RI "def \fBgetChainStrategies\fP ()"
.br
.ti -1c
.RI "def \fBcheckOutput\fP (cmd)"
.br
.ti -1c
.RI "def \fBerrorExit\fP (msg='', raw=\fBFalse\fP, errorCode=1)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBDebug\fP = \fBFalse\fP"
.br
.ti -1c
.RI "\fBFNull\fP = open(os\&.devnull, 'w')"
.br
.ti -1c
.RI "string \fBAacClientPath\fP = 'programs/clAcute-Angle-Chain/claac'"
.br
.ti -1c
.RI "string \fBAacWalletName\fP = 'kaacd'"
.br
.ti -1c
.RI "string \fBAacWalletPath\fP = 'programs/kaacd/'+ AacWalletName"
.br
.ti -1c
.RI "string \fBAacServerName\fP = 'nodaac'"
.br
.ti -1c
.RI "string \fBAacServerPath\fP = 'programs/nodAcute-Angle-Chain/'+ AacServerName"
.br
.ti -1c
.RI "string \fBAacLauncherPath\fP = 'programs/aacio\-launcher/aacio\-launcher'"
.br
.ti -1c
.RI "string \fBMongoPath\fP = 'mongo'"
.br
.ti -1c
.RI "\fBSyncStrategy\fP"
.br
.ti -1c
.RI "string \fBSyncNoneTag\fP = 'none'"
.br
.ti -1c
.RI "string \fBSyncReplayTag\fP = 'replay'"
.br
.ti -1c
.RI "string \fBSyncResyncTag\fP = 'resync'"
.br
.ti -1c
.RI "string \fBSigKillTag\fP = 'kill'"
.br
.ti -1c
.RI "string \fBSigTermTag\fP = 'term'"
.br
.ti -1c
.RI "int \fBsystemWaitTimeout\fP = 90"
.br
.ti -1c
.RI "int \fBmongoSyncTime\fP = 25"
.br
.ti -1c
.RI "bool \fBamINoon\fP = \fBTrue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
