.TH "TestModel128x2" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestModel128x2
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTestModel128x2_V2\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint128_t \fBnumber\fP"
.br
.ti -1c
.RI "uint128_t \fBprice\fP"
.br
.ti -1c
.RI "uint64_t \fBextra\fP"
.br
.ti -1c
.RI "uint64_t \fBtable_name\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
