.TH "test_ostream< CharT >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_ostream< CharT >
.SH SYNOPSIS
.br
.PP
.PP
Inherits basic_ostream< CharT >, basic_ostream< CharT >, and basic_ostream< CharT >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::basic_ostream< CharT > \fBbase\fP"
.br
.ti -1c
.RI "typedef std::basic_ostream< CharT > \fBbase\fP"
.br
.ti -1c
.RI "typedef std::basic_ostream< CharT > \fBbase\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_ostream\fP (\fBtestbuf\fP< CharT > *sb)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBtest_ostream\fP &s)"
.br
.ti -1c
.RI "\fBtest_ostream\fP (\fBtestbuf\fP< CharT > *sb)"
.br
.ti -1c
.RI "\fBtest_ostream\fP & \fBoperator=\fP (\fBtest_ostream\fP &&s)"
.br
.ti -1c
.RI "\fBtest_ostream\fP (\fBtestbuf\fP< CharT > *sb)"
.br
.ti -1c
.RI "\fBtest_ostream\fP (\fBtest_ostream\fP &&s)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
