.TH "testee_config" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testee_config
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwebsocketpp::config::asio\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpermessage_deflate_config\fP"
.br
.RI "permessage_compress extension "
.ti -1c
.RI "struct \fBtransport_config\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBwebsocketpp::config::asio\fP \fBcore\fP"
.br
.ti -1c
.RI "typedef \fBcore::concurrency_type\fP \fBconcurrency_type\fP"
.br
.ti -1c
.RI "typedef \fBcore::request_type\fP \fBrequest_type\fP"
.br
.ti -1c
.RI "typedef \fBcore::response_type\fP \fBresponse_type\fP"
.br
.ti -1c
.RI "typedef \fBcore::message_type\fP \fBmessage_type\fP"
.br
.ti -1c
.RI "typedef \fBcore::con_msg_manager_type\fP \fBcon_msg_manager_type\fP"
.br
.ti -1c
.RI "typedef \fBcore::endpoint_msg_manager_type\fP \fBendpoint_msg_manager_type\fP"
.br
.ti -1c
.RI "typedef \fBcore::alog_type\fP \fBalog_type\fP"
.br
.ti -1c
.RI "typedef \fBcore::elog_type\fP \fBelog_type\fP"
.br
.ti -1c
.RI "typedef \fBcore::rng_type\fP \fBrng_type\fP"
.br
.ti -1c
.RI "typedef \fBcore::endpoint_base\fP \fBendpoint_base\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::transport::asio::endpoint\fP< \fBtransport_config\fP > \fBtransport_type\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::extensions::permessage_deflate::enabled\fP< \fBpermessage_deflate_config\fP > \fBpermessage_deflate_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool const \fBenable_multithreading\fP = true"
.br
.ti -1c
.RI "static const websocketpp::log::level \fBelog_level\fP"
.br
.ti -1c
.RI "static const websocketpp::log::level \fBalog_level\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const websocketpp::log::level testee_config::alog_level\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
        websocketpp::log::alevel::none
.fi
.SS "const websocketpp::log::level testee_config::elog_level\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
        websocketpp::log::elevel::none
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
