.TH "test_print" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_print
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBtest_prints\fP ()"
.br
.ti -1c
.RI "static void \fBtest_prints_l\fP ()"
.br
.ti -1c
.RI "static void \fBtest_printi\fP ()"
.br
.ti -1c
.RI "static void \fBtest_printui\fP ()"
.br
.ti -1c
.RI "static void \fBtest_printi128\fP ()"
.br
.ti -1c
.RI "static void \fBtest_printn\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
