.TH "testUtils.Account" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testUtils.Account
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, name)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBbalance\fP"
.br
.ti -1c
.RI "\fBownerPrivateKey\fP"
.br
.ti -1c
.RI "\fBownerPublicKey\fP"
.br
.ti -1c
.RI "\fBactivePrivateKey\fP"
.br
.ti -1c
.RI "\fBactivePublicKey\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
