.TH "test_deleter< T >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_deleter< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtest_deleter_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_deleter\fP (int s)"
.br
.ti -1c
.RI "\fBtest_deleter\fP (const \fBtest_deleter\fP &d)"
.br
.ti -1c
.RI "int \fBstate\fP () const"
.br
.ti -1c
.RI "void \fBset_state\fP (int i)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBT\fP *p)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
