.TH "test_types" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_types
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBtypes_size\fP ()"
.br
.ti -1c
.RI "static void \fBchar_to_symbol\fP ()"
.br
.ti -1c
.RI "static void \fBstring_to_name\fP ()"
.br
.ti -1c
.RI "static void \fBname_class\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
