.TH "test_allocator< void >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_allocator< void >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtest_alloc_base\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrebind\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef unsigned \fBsize_type\fP"
.br
.ti -1c
.RI "typedef int \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef void \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef value_type * \fBpointer\fP"
.br
.ti -1c
.RI "typedef const value_type * \fBconst_pointer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_allocator\fP (int i, int id=0) TEST_NOEXCEPT"
.br
.ti -1c
.RI "\fBtest_allocator\fP (const \fBtest_allocator\fP &a) TEST_NOEXCEPT"
.br
.ti -1c
.RI "template<class U > \fBtest_allocator\fP (const \fBtest_allocator\fP< \fBU\fP > &a) TEST_NOEXCEPT"
.br
.ti -1c
.RI "int \fBget_id\fP () const"
.br
.ti -1c
.RI "int \fBget_data\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<class U > class \fBtest_allocator\fP"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBtest_allocator\fP &x, const \fBtest_allocator\fP &y)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBtest_allocator\fP &x, const \fBtest_allocator\fP &y)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
