.TH "contracts/test_api/test_api.cpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/test_api/test_api.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aaciolib/aacio\&.hpp>\fP
.br
\fC#include <aaciolib/transaction\&.hpp>\fP
.br
\fC#include 'test_api\&.hpp'\fP
.br
\fC#include 'test_action\&.cpp'\fP
.br
\fC#include 'test_print\&.cpp'\fP
.br
\fC#include 'test_types\&.cpp'\fP
.br
\fC#include 'test_fixedpoint\&.cpp'\fP
.br
\fC#include 'test_math\&.cpp'\fP
.br
\fC#include 'test_compiler_builtins\&.cpp'\fP
.br
\fC#include 'test_real\&.cpp'\fP
.br
\fC#include 'test_crypto\&.cpp'\fP
.br
\fC#include 'test_chain\&.cpp'\fP
.br
\fC#include 'test_transaction\&.cpp'\fP
.br
\fC#include 'test_checktime\&.cpp'\fP
.br
\fC#include 'test_permission\&.cpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBapply\fP (uint64_t receiver, uint64_t code, uint64_t \fBaction\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "account_name \fBglobal_receiver\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
