.TH "TestClass" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestClass
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDerivedFromTestClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestClass\fP (int x)"
.br
.ti -1c
.RI "int & \fBoperator()\fP (\fBNonCopyable\fP &&) &"
.br
.ti -1c
.RI "int const  & \fBoperator()\fP (\fBNonCopyable\fP &&) const &"
.br
.ti -1c
.RI "int volatile & \fBoperator()\fP (\fBNonCopyable\fP &&) volatile &"
.br
.ti -1c
.RI "int const volatile & \fBoperator()\fP (\fBNonCopyable\fP &&) const volatile &"
.br
.ti -1c
.RI "int && \fBoperator()\fP (\fBNonCopyable\fP &&) &&"
.br
.ti -1c
.RI "int const  && \fBoperator()\fP (\fBNonCopyable\fP &&) const &&"
.br
.ti -1c
.RI "int volatile && \fBoperator()\fP (\fBNonCopyable\fP &&) volatile &&"
.br
.ti -1c
.RI "int const volatile && \fBoperator()\fP (\fBNonCopyable\fP &&) const volatile &&"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
