.TH "test_dummy_action< ACCOUNT, NAME >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_dummy_action< ACCOUNT, NAME >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static account_name \fBget_account\fP ()"
.br
.ti -1c
.RI "static action_name \fBget_name\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBa\fP"
.br
.ti -1c
.RI "unsigned long long \fBb\fP"
.br
.ti -1c
.RI "int32_t \fBc\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename DataStream > DataStream & \fBoperator<<\fP (DataStream &ds, const \fBtest_dummy_action\fP &da)"
.br
.ti -1c
.RI "template<typename DataStream > DataStream & \fBoperator>>\fP (DataStream &ds, \fBtest_dummy_action\fP &da)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
