.TH "contracts/test_api/test_transaction.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/test_api/test_transaction.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aaciolib/action\&.hpp>\fP
.br
\fC#include <aaciolib/crypto\&.h>\fP
.br
\fC#include <aaciolib/transaction\&.hpp>\fP
.br
\fC#include 'test_api\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtest_action_action< ACCOUNT, NAME >\fP"
.br
.ti -1c
.RI "struct \fBtest_dummy_action< ACCOUNT, NAME >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcopy_data\fP (char *data, size_t data_len, \fBaacio::vector\fP< char > &data_out)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
