.TH "TestMutex" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestMutex
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBlock\fP ()"
.br
.ti -1c
.RI "bool \fBtry_lock\fP ()"
.br
.ti -1c
.RI "void \fBunlock\fP ()"
.br
.ti -1c
.RI "\fBTestMutex\fP (\fBTestMutex\fP const &)=delete"
.br
.ti -1c
.RI "\fBTestMutex\fP & \fBoperator=\fP (\fBTestMutex\fP const &)=delete"
.br
.ti -1c
.RI "void \fBlock\fP ()"
.br
.ti -1c
.RI "bool \fBtry_lock\fP ()"
.br
.ti -1c
.RI "void \fBunlock\fP ()"
.br
.ti -1c
.RI "\fBTestMutex\fP (\fBTestMutex\fP const &)=delete"
.br
.ti -1c
.RI "\fBTestMutex\fP & \fBoperator=\fP (\fBTestMutex\fP const &)=delete"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBlocked\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
