.TH "test_iostream< CharT >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_iostream< CharT >
.SH SYNOPSIS
.br
.PP
.PP
Inherits basic_iostream< CharT >, basic_iostream< CharT >, and basic_iostream< CharT >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::basic_iostream< CharT > \fBbase\fP"
.br
.ti -1c
.RI "typedef std::basic_iostream< CharT > \fBbase\fP"
.br
.ti -1c
.RI "typedef std::basic_iostream< CharT > \fBbase\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_iostream\fP (\fBtestbuf\fP< CharT > *sb)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBtest_iostream\fP &s)"
.br
.ti -1c
.RI "\fBtest_iostream\fP (\fBtestbuf\fP< CharT > *sb)"
.br
.ti -1c
.RI "\fBtest_iostream\fP & \fBoperator=\fP (\fBtest_iostream\fP &&s)"
.br
.ti -1c
.RI "\fBtest_iostream\fP (\fBtestbuf\fP< CharT > *sb)"
.br
.ti -1c
.RI "\fBtest_iostream\fP (\fBtest_iostream\fP &&s)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
