.TH "test_iterator" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_iterator
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef int \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef \fBA\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBA\fP * \fBpointer\fP"
.br
.ti -1c
.RI "typedef \fBA\fP & \fBreference\fP"
.br
.ti -1c
.RI "typedef std::forward_iterator_tag \fBiterator_category\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
