.TH "test_action" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_action
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBread_action_normal\fP ()"
.br
.ti -1c
.RI "static void \fBread_action_to_0\fP ()"
.br
.ti -1c
.RI "static void \fBread_action_to_64k\fP ()"
.br
.ti -1c
.RI "static void \fBtest_dummy_action\fP ()"
.br
.ti -1c
.RI "static void \fBtest_cf_action\fP ()"
.br
.ti -1c
.RI "static void \fBrequire_notice\fP (uint64_t receiver, uint64_t code, uint64_t \fBaction\fP)"
.br
.ti -1c
.RI "static void \fBrequire_auth\fP ()"
.br
.ti -1c
.RI "static void \fBassert_false\fP ()"
.br
.ti -1c
.RI "static void \fBassert_true\fP ()"
.br
.ti -1c
.RI "static void \fBassert_true_cf\fP ()"
.br
.ti -1c
.RI "static void \fBnow\fP ()"
.br
.ti -1c
.RI "static void \fBtest_abort\fP () __attribute__((noreturn))"
.br
.ti -1c
.RI "static void \fBtest_current_receiver\fP (uint64_t receiver, uint64_t code, uint64_t \fBaction\fP)"
.br
.ti -1c
.RI "static void \fBtest_current_sender\fP ()"
.br
.ti -1c
.RI "static void \fBtest_publication_time\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
