.TH "testios" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testios
.SH SYNOPSIS
.br
.PP
.PP
Inherits ios, ios, and ios\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestios\fP (std::streambuf *p)"
.br
.ti -1c
.RI "void \fBmove\fP (std::ios &x)"
.br
.ti -1c
.RI "\fBtestios\fP (std::streambuf *p)"
.br
.ti -1c
.RI "void \fBset_rdbuf\fP (std::streambuf *x)"
.br
.ti -1c
.RI "\fBtestios\fP (std::streambuf *p)"
.br
.ti -1c
.RI "void \fBswap\fP (std::ios &x)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
