.TH "test_compare< C >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_compare< C >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBC< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_compare\fP (int data=0)"
.br
.ti -1c
.RI "C::result_type \fBoperator()\fP (typename std::add_lvalue_reference< const typename C::first_argument_type >::type x, typename std::add_lvalue_reference< const typename C::second_argument_type >::type y) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBtest_compare\fP &c) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
