.TH "test_model" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_model
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtest_model_v2\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "account_name \fBname\fP"
.br
.ti -1c
.RI "unsigned char \fBage\fP"
.br
.ti -1c
.RI "uint64_t \fBphone\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
