.TH "TestScriptResolver" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestScriptResolver
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRuntime::Resolver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestScriptResolver\fP (const \fBTestScriptState\fP &inState)"
.br
.ti -1c
.RI "bool \fBresolve\fP (const std::string &moduleName, const std::string &exportName, \fBObjectType\fP type, \fBObjectInstance\fP *&outObject) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
