.TH "test_hash< C >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_hash< C >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBC< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_hash\fP (int data=0)"
.br
.ti -1c
.RI "std::size_t \fBoperator()\fP (typename std::add_lvalue_reference< const typename C::argument_type >::type x) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBtest_hash\fP &c) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
