.TH "testUtils.Cluster" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testUtils.Cluster
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, walletd=\fBFalse\fP, localCluster=\fBTrue\fP, host='localhost', port=8888, walletHost='localhost', walletPort=8899, enableMongo=\fBFalse\fP, mongoHost='localhost', mongoPort=27017, mongoDb='AACtest', initaPrvtKey=None, initbPrvtKey=None, staging=\fBFalse\fP)"
.br
.ti -1c
.RI "def \fBsetChainStrategy\fP (self, chainSyncStrategy=Utils\&.SyncReplayTag)"
.br
.ti -1c
.RI "def \fBsetWalletMgr\fP (self, walletMgr)"
.br
.ti -1c
.RI "def \fBlaunch\fP (self, pnodes=1, total_nodes=1, topo='mesh', delay=0)"
.br
.ti -1c
.RI "def \fBinitializeNodes\fP (self)"
.br
.ti -1c
.RI "def \fBinitializeNodesFromJson\fP (self, nodesJsonStr)"
.br
.ti -1c
.RI "def \fBsetNodes\fP (self, nodes)"
.br
.ti -1c
.RI "def \fBwaitOnClusterSync\fP (self, timeout=None)"
.br
.ti -1c
.RI "def \fBwaitOnClusterBlockNumSync\fP (self, targetHeadBlockNum, timeout=None)"
.br
.ti -1c
.RI "def \fBpopulateWallet\fP (self, accountsCount, wallet)"
.br
.ti -1c
.RI "def \fBgetNode\fP (self, id=0)"
.br
.ti -1c
.RI "def \fBgetNodes\fP (self)"
.br
.ti -1c
.RI "def \fBspreadFunds\fP (self, amount=1)"
.br
.ti -1c
.RI "def \fBvalidateSpreadFunds\fP (self, expectedTotal)"
.br
.ti -1c
.RI "def \fBspreadFundsAndValidate\fP (self, amount=1)"
.br
.ti -1c
.RI "def \fBcreateAccountAndVerify\fP (self, \fBaccount\fP, creator, stakedDeposit=1000)"
.br
.ti -1c
.RI "def \fBparseClusterInfo\fP (self, totalNodes)"
.br
.ti -1c
.RI "def \fBdiscoverLocalNodes\fP (self, totalNodes)"
.br
.ti -1c
.RI "def \fBupdateNodesStatus\fP (self)"
.br
.ti -1c
.RI "def \fBkillSomeAacInstances\fP (self, killCount, killSignalStr=Utils\&.SigKillTag)"
.br
.ti -1c
.RI "def \fBrelaunchAacInstances\fP (self)"
.br
.ti -1c
.RI "def \fBdumpErrorDEtailImpl\fP (self, fileName)"
.br
.ti -1c
.RI "def \fBdumpErrorDetails\fP (self)"
.br
.ti -1c
.RI "def \fBkillall\fP (self, silent=\fBTrue\fP)"
.br
.ti -1c
.RI "def \fBwaitForNextBlock\fP (self, timeout=None)"
.br
.ti -1c
.RI "def \fBcleanup\fP (self)"
.br
.ti -1c
.RI "def \fBcreateAccounts\fP (self, creator, waitForTransBlock=\fBTrue\fP, stakedDeposit=1000)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBcreateAccountKeys\fP (count)"
.br
.ti -1c
.RI "def \fBparseProducerKeys\fP (configFile)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccounts\fP"
.br
.ti -1c
.RI "\fBnodes\fP"
.br
.ti -1c
.RI "\fBlocalCluster\fP"
.br
.ti -1c
.RI "\fBwallet\fP"
.br
.ti -1c
.RI "\fBwalletd\fP"
.br
.ti -1c
.RI "\fBenableMongo\fP"
.br
.ti -1c
.RI "\fBmongoHost\fP"
.br
.ti -1c
.RI "\fBmongoPort\fP"
.br
.ti -1c
.RI "\fBmongoDb\fP"
.br
.ti -1c
.RI "\fBwalletMgr\fP"
.br
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.ti -1c
.RI "\fBwalletHost\fP"
.br
.ti -1c
.RI "\fBwalletPort\fP"
.br
.ti -1c
.RI "\fBwalletEndpointArgs\fP"
.br
.ti -1c
.RI "\fBmongoEndpointArgs\fP"
.br
.ti -1c
.RI "\fBmongoUri\fP"
.br
.ti -1c
.RI "\fBstaging\fP"
.br
.ti -1c
.RI "\fBinitaAccount\fP"
.br
.ti -1c
.RI "\fBinitbAccount\fP"
.br
.ti -1c
.RI "\fBaacioAccount\fP"
.br
.ti -1c
.RI "\fBproducerKeys\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def testUtils\&.Cluster\&.parseClusterInfo ( self,  totalNodes)"

.PP
.nf
Parse cluster config file. Updates producer keys data members. Returns True/False
.fi
.PP
 
.SS "def testUtils\&.Cluster\&.parseProducerKeys ( configFile)\fC [static]\fP"

.PP
.nf
Parse config file. Returns dictionary with account name keys. Dictionary values are list containing the public/private keys
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
