.TH "test_extended_memory" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_extended_memory
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBtest_initial_buffer\fP ()"
.br
.ti -1c
.RI "static void \fBtest_page_memory\fP ()"
.br
.ti -1c
.RI "static void \fBtest_page_memory_exceeded\fP ()"
.br
.ti -1c
.RI "static void \fBtest_page_memory_negative_bytes\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
