.TH "test_istream< CharT >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_istream< CharT >
.SH SYNOPSIS
.br
.PP
.PP
Inherits basic_istream< CharT >, basic_istream< char >, basic_istream< CharT >, and basic_istream< CharT >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::basic_istream< CharT > \fBbase\fP"
.br
.ti -1c
.RI "typedef std::basic_istream< CharT > \fBbase\fP"
.br
.ti -1c
.RI "typedef std::basic_istream< char > \fBbase\fP"
.br
.ti -1c
.RI "typedef std::basic_istream< CharT > \fBbase\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_istream\fP (\fBtestbuf\fP< CharT > *sb)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBtest_istream\fP &s)"
.br
.ti -1c
.RI "\fBtest_istream\fP (\fBtestbuf\fP< CharT > *sb)"
.br
.ti -1c
.RI "\fBtest_istream\fP & \fBoperator=\fP (\fBtest_istream\fP &&s)"
.br
.ti -1c
.RI "\fBtest_istream\fP (\fBtest_istream\fP &&s)"
.br
.ti -1c
.RI "\fBtest_istream\fP & \fBoperator=\fP (\fBtest_istream\fP &&s)"
.br
.ti -1c
.RI "\fBtest_istream\fP (\fBtest_istream\fP const &s)"
.br
.ti -1c
.RI "\fBtest_istream\fP & \fBoperator=\fP (\fBtest_istream\fP const &s)"
.br
.ti -1c
.RI "\fBtest_istream\fP (\fBtestbuf\fP< CharT > *sb)"
.br
.ti -1c
.RI "\fBtest_istream\fP (\fBtest_istream\fP &&s)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
