.TH "TestNoexceptCallable< IsNoexcept >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestNoexceptCallable< IsNoexcept >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class \&.\&.\&. Args> \fBNothrowMoveable\fP \fBoperator()\fP (Args\&.\&.\&.) const noexcept(IsNoexcept)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
