.TH "test_math" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_math
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBtest_multeq\fP ()"
.br
.ti -1c
.RI "static void \fBtest_diveq\fP ()"
.br
.ti -1c
.RI "static void \fBtest_diveq_by_0\fP ()"
.br
.ti -1c
.RI "static void \fBtest_double_api\fP ()"
.br
.ti -1c
.RI "static void \fBtest_double_api_div_0\fP ()"
.br
.ti -1c
.RI "static void \fBtest_i64_to_double\fP ()"
.br
.ti -1c
.RI "static void \fBtest_double_to_i64\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
