.TH "test1" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test1
.SH SYNOPSIS
.br
.PP
.PP
Inherits error_category\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest1\fP (char xc)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const int &i) const"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const int &i) const"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const int &i) const"
.br
.ti -1c
.RI "virtual const char * \fBname\fP () const noexcept"
.br
.ti -1c
.RI "virtual std::string \fBmessage\fP (int) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBc\fP"
.br
.ti -1c
.RI "\fBstrsystem\fP = platform\&.system()"
.br
.ti -1c
.RI "tuple \fBARCH\fP = ( uname )"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
