.TH "testbuf1< CharT >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testbuf1< CharT >
.SH SYNOPSIS
.br
.PP
.PP
Inherits basic_streambuf< CharT >, and basic_streambuf< CharT >\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBsync\fP ()"
.br
.ti -1c
.RI "virtual int \fBsync\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
