.TH "contracts/test_api/test_api_common.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/test_api/test_api_common.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdummy_action\fP"
.br
.ti -1c
.RI "struct \fBu128_action\fP"
.br
.ti -1c
.RI "struct \fBcf_action\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDUMMY_ACTION_DEFAULT_A\fP   0x45"
.br
.ti -1c
.RI "#define \fBDUMMY_ACTION_DEFAULT_B\fP   0xab11cd1244556677"
.br
.ti -1c
.RI "#define \fBDUMMY_ACTION_DEFAULT_C\fP   0x7451ae12"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
