.TH "TestModel3xi64" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestModel3xi64
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTestModel3xi64_V2\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBa\fP"
.br
.ti -1c
.RI "uint64_t \fBb\fP"
.br
.ti -1c
.RI "uint64_t \fBc\fP"
.br
.ti -1c
.RI "uint64_t \fBtable\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
