.TH "Throws" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Throws
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThrows\fP (int v)"
.br
.ti -1c
.RI "\fBThrows\fP (const \fBThrows\fP &rhs)"
.br
.ti -1c
.RI "\fBThrows\fP (\fBThrows\fP &&rhs)"
.br
.ti -1c
.RI "\fBThrows\fP & \fBoperator=\fP (const \fBThrows\fP &rhs)"
.br
.ti -1c
.RI "\fBThrows\fP & \fBoperator=\fP (\fBThrows\fP &&rhs)"
.br
.ti -1c
.RI "\fBThrows\fP (int v)"
.br
.ti -1c
.RI "\fBThrows\fP (const \fBThrows\fP &rhs)"
.br
.ti -1c
.RI "\fBThrows\fP (\fBThrows\fP &&rhs)"
.br
.ti -1c
.RI "\fBThrows\fP & \fBoperator=\fP (const \fBThrows\fP &rhs)"
.br
.ti -1c
.RI "\fBThrows\fP & \fBoperator=\fP (\fBThrows\fP &&rhs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBv_\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBsThrows\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
