.TH "ThrowsOnSecondMove" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThrowsOnSecondMove
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThrowsOnSecondMove\fP (int v)"
.br
.ti -1c
.RI "\fBThrowsOnSecondMove\fP (\fBThrowsOnSecondMove\fP &&o) noexcept(false)"
.br
.ti -1c
.RI "\fBThrowsOnSecondMove\fP & \fBoperator=\fP (\fBThrowsOnSecondMove\fP &&)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "int \fBmove_count\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
