.TH "ThrowsCounted" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThrowsCounted
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThrowsCounted\fP (\fBThrowsCounted\fP const &)"
.br
.ti -1c
.RI "\fBThrowsCounted\fP (\fBThrowsCounted\fP const &)"
.br
.ti -1c
.RI "\fBThrowsCounted\fP (\fBThrowsCounted\fP const &)"
.br
.ti -1c
.RI "\fBThrowsCounted\fP (\fBThrowsCounted\fP const &)"
.br
.ti -1c
.RI "\fBThrowsCounted\fP (int &&x)"
.br
.ti -1c
.RI "\fBThrowsCounted\fP (\fBThrowsCounted\fP const &)"
.br
.ti -1c
.RI "\fBThrowsCounted\fP (int &&x)"
.br
.ti -1c
.RI "\fBThrowsCounted\fP (\fBThrowsCounted\fP const &)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.ti -1c
.RI "static void \fBreset\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBcount\fP = 0"
.br
.ti -1c
.RI "static int \fBconstructed\fP = 0"
.br
.ti -1c
.RI "static int \fBthrow_after\fP = 0"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "void \fBoperator &\fP (\fBThrowsCounted\fP)=delete"
.br
.ti -1c
.RI "void \fBoperator &\fP (\fBThrowsCounted\fP)=delete"
.br
.ti -1c
.RI "void \fBoperator &\fP (\fBThrowsCounted\fP)=delete"
.br
.ti -1c
.RI "void \fBoperator &\fP (\fBThrowsCounted\fP)=delete"
.br
.ti -1c
.RI "void \fBoperator &\fP (\fBThrowsCounted\fP)=delete"
.br
.ti -1c
.RI "void \fBoperator &\fP (\fBThrowsCounted\fP)=delete"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
