.TH "tinfl_huff_table" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinfl_huff_table
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "mz_uint8 \fBm_code_size\fP [TINFL_MAX_HUFF_SYMBOLS_0]"
.br
.ti -1c
.RI "mz_int16 \fBm_look_up\fP [TINFL_FAST_LOOKUP_SIZE]"
.br
.ti -1c
.RI "mz_int16 \fBm_tree\fP [TINFL_MAX_HUFF_SYMBOLS_0 *2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
