.TH "tinfl_decompressor_tag" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinfl_decompressor_tag
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "mz_uint32 \fBm_state\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_num_bits\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_zhdr0\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_zhdr1\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_z_adler32\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_final\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_type\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_check_adler32\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_dist\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_counter\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_num_extra\fP"
.br
.ti -1c
.RI "mz_uint32 \fBm_table_sizes\fP [TINFL_MAX_HUFF_TABLES]"
.br
.ti -1c
.RI "tinfl_bit_buf_t \fBm_bit_buf\fP"
.br
.ti -1c
.RI "size_t \fBm_dist_from_out_buf_start\fP"
.br
.ti -1c
.RI "\fBtinfl_huff_table\fP \fBm_tables\fP [TINFL_MAX_HUFF_TABLES]"
.br
.ti -1c
.RI "mz_uint8 \fBm_raw_header\fP [4]"
.br
.ti -1c
.RI "mz_uint8 \fBm_len_codes\fP [TINFL_MAX_HUFF_SYMBOLS_0+TINFL_MAX_HUFF_SYMBOLS_1+137]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
