.TH "tm" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tm
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtm_sec\fP"
.br
.ti -1c
.RI "int \fBtm_min\fP"
.br
.ti -1c
.RI "int \fBtm_hour\fP"
.br
.ti -1c
.RI "int \fBtm_mday\fP"
.br
.ti -1c
.RI "int \fBtm_mon\fP"
.br
.ti -1c
.RI "int \fBtm_year\fP"
.br
.ti -1c
.RI "int \fBtm_wday\fP"
.br
.ti -1c
.RI "int \fBtm_yday\fP"
.br
.ti -1c
.RI "int \fBtm_isdst\fP"
.br
.ti -1c
.RI "long \fB__tm_gmtoff\fP"
.br
.ti -1c
.RI "const char * \fB__tm_zone\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
