.TH "TMoveNTCopy" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMoveNTCopy
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBTMoveNTCopy\fP (int v)"
.br
.ti -1c
.RI "\fBTMoveNTCopy\fP (const \fBTMoveNTCopy\fP &that)"
.br
.ti -1c
.RI "\fBTMoveNTCopy\fP (\fBTMoveNTCopy\fP &&)=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
