.TH "TMoveAssign" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMoveAssign
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBTMoveAssign\fP (int v)"
.br
.ti -1c
.RI "\fBTMoveAssign\fP (const \fBTMoveAssign\fP &)=delete"
.br
.ti -1c
.RI "\fBTMoveAssign\fP (\fBTMoveAssign\fP &&)=default"
.br
.ti -1c
.RI "\fBTMoveAssign\fP & \fBoperator=\fP (const \fBTMoveAssign\fP &)=delete"
.br
.ti -1c
.RI "\fBTMoveAssign\fP & \fBoperator=\fP (\fBTMoveAssign\fP &&)=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
