.TH "TrackingDeleter< ID >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrackingDeleter< ID >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrackingDeleter\fP (\fBTrackingDeleter\fP const &)"
.br
.ti -1c
.RI "\fBTrackingDeleter\fP (\fBTrackingDeleter\fP &&)"
.br
.ti -1c
.RI "template<class T , class  = EnableIfSpecialization<TrackingDeleter, T>> \fBTrackingDeleter\fP (\fBT\fP &&)"
.br
.ti -1c
.RI "\fBTrackingDeleter\fP & \fBoperator=\fP (\fBTrackingDeleter\fP const &)"
.br
.ti -1c
.RI "\fBTrackingDeleter\fP & \fBoperator=\fP (\fBTrackingDeleter\fP &&)"
.br
.ti -1c
.RI "template<class T , class  = EnableIfSpecialization<TrackingDeleter, T>> \fBTrackingDeleter\fP & \fBoperator=\fP (\fBT\fP &&)"
.br
.ti -1c
.RI "void \fBoperator()\fP (void *) const"
.br
.ti -1c
.RI "\fBTypeID\fP const  * \fBreset\fP () const"
.br
.ti -1c
.RI "\fBTrackingDeleter\fP (\fBTrackingDeleter\fP const &)"
.br
.ti -1c
.RI "\fBTrackingDeleter\fP (\fBTrackingDeleter\fP &&)"
.br
.ti -1c
.RI "template<class T , class  = EnableIfSpecialization<TrackingDeleter, T>> \fBTrackingDeleter\fP (\fBT\fP &&)"
.br
.ti -1c
.RI "\fBTrackingDeleter\fP & \fBoperator=\fP (\fBTrackingDeleter\fP const &)"
.br
.ti -1c
.RI "\fBTrackingDeleter\fP & \fBoperator=\fP (\fBTrackingDeleter\fP &&)"
.br
.ti -1c
.RI "template<class T , class  = EnableIfSpecialization<TrackingDeleter, T>> \fBTrackingDeleter\fP & \fBoperator=\fP (\fBT\fP &&)"
.br
.ti -1c
.RI "void \fBoperator()\fP (void *) const"
.br
.ti -1c
.RI "\fBTypeID\fP const  * \fBreset\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTypeID\fP const  * \fBarg_type\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
