.TH "plugins/account_history_plugin/include/aacio/account_history_plugin/transaction_history_object.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/account_history_plugin/include/aacio/account_history_plugin/transaction_history_object.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <chainbase/chainbase\&.hpp>\fP
.br
\fC#include <aacio/chain/transaction\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::transaction_history_object\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBaacio::transaction_history_multi_index\fP = chainbase::shared_multi_index_container< transaction_history_object, indexed_by< ordered_unique< tag< by_id >, BOOST_MULTI_INDEX_MEMBER(transaction_history_object, transaction_history_object::id_type, id)>, ordered_unique< tag< by_trx_id >, BOOST_MULTI_INDEX_MEMBER(transaction_history_object, \fBtransaction_id_type\fP, transaction_id)> > >"
.br
.ti -1c
.RI "typedef \fBchainbase::generic_index\fP< transaction_history_multi_index > \fBaacio::transaction_history_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
