.TH "transactioncppapi" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transactioncppapi \- Type-safe C++ wrappers for transaction \fBC\fP API\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::transaction_header\fP"
.br
.ti -1c
.RI "class \fBaacio::transaction\fP"
.br
.ti -1c
.RI "class \fBaacio::deferred_transaction\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBaction\fP \fBaacio::get_action\fP (uint32_t type, uint32_t index)"
.br
.ti -1c
.RI "void \fBaacio::check_auth\fP (const \fBbytes\fP &trx_packed, const \fBvector\fP< \fBpermission_level\fP > &permissions)"
.br
.ti -1c
.RI "void \fBaacio::check_auth\fP (const char *serialized_transaction, size_t size, const \fBvector\fP< \fBpermission_level\fP > &permissions)"
.br
.ti -1c
.RI "void \fBaacio::check_auth\fP (const \fBtransaction\fP &trx, const \fBvector\fP< \fBpermission_level\fP > &permissions)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type-safe C++ wrappers for transaction \fBC\fP API\&. 


.PP
\fBNote:\fP
.RS 4
There are some methods from the \fBTransaction C API\fP that can be used directly from C++ 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "\fBaction\fP aacio::get_action (uint32_t type, uint32_t index)\fC [inline]\fP"
Retrieve the indicated action from the active transaction\&. 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP - 0 for context free action, 1 for action 
.br
\fIindex\fP - the index of the requested action 
.RE
.PP
\fBReturns:\fP
.RS 4
the indicated action 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
