.TH "contracts/aaciolib/transaction.h" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contracts/aaciolib/transaction.h
.SH SYNOPSIS
.br
.PP
\fC#include <aaciolib/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsend_deferred\fP (const uint128_t &sender_id, account_name payer, const char *serialized_transaction, size_t size)"
.br
.ti -1c
.RI "void \fBcancel_deferred\fP (const uint128_t &sender_id)"
.br
.ti -1c
.RI "size_t \fBread_transaction\fP (char *buffer, size_t size)"
.br
.ti -1c
.RI "size_t \fBtransaction_size\fP ()"
.br
.ti -1c
.RI "int \fBtapos_block_num\fP ()"
.br
.ti -1c
.RI "int \fBtapos_block_prefix\fP ()"
.br
.ti -1c
.RI "time \fBexpiration\fP ()"
.br
.ti -1c
.RI "int \fBget_action\fP (uint32_t type, uint32_t index, char *buff, size_t size)"
.br
.ti -1c
.RI "int \fBget_context_free_data\fP (uint32_t index, char *buff, size_t size)"
.br
.ti -1c
.RI "void \fBcheck_auth\fP (const char *serialized_transaction, size_t size, const char *permissions, size_t psize)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
