.TH "libraries/chain/include/aacio/chain/transaction.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/include/aacio/chain/transaction.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/chain/types\&.hpp>\fP
.br
\fC#include <numeric>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaacio::chain::permission_level\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::action\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::action_notice\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::transaction_receipt\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::transaction_header\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::transaction\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::signed_transaction\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::packed_transaction\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::deferred_transaction\fP"
.br
.ti -1c
.RI "struct \fBaacio::chain::deferred_reference\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBaacio::chain::operator==\fP (const permission_level &lhs, const permission_level &rhs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
