.TH "TypeList< First, Rest... >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeList< First, Rest... >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<template< class > class Trait, bool Expect = true> static constexpr bool \fBassertTrait\fP ()"
.br
.ti -1c
.RI "template<class Trait > static void \fBapplyTrait\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
