.TH "tests/tests/types_tests.cpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/tests/types_tests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <Acute-Angle-Chain/types/type_parser\&.hpp>\fP
.br
\fC#include <boost/test/unit_test\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBaacio::types::BOOST_AUTO_TEST_CASE\fP (basic_simple_symbol_table_test)"
.br
.RI "Put the SimpleSymbolTable through its paces\&. "
.ti -1c
.RI "\fBaacio::types::BOOST_AUTO_TEST_CASE\fP (simple_symbol_table_parse_test)"
.br
.RI "Check that SimpleSymbolTable can handle a basic schema parse\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
