.TH "TypeList<>" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeList<>
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<template< class > class Trait, bool Expect = true> static constexpr bool \fBassertTrait\fP ()"
.br
.ti -1c
.RI "template<class Trait > static void \fBapplyTrait\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
