.TH "Type" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Type
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArray\fP< char, 1 >::type & \fBf1\fP ()"
.br
.ti -1c
.RI "\fBArray\fP< char, 2 >::type & \fBf2\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
