.TH "Unary< inType >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Unary< inType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnary\fP (\fBNode\fP *inChild)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNode\fP * \fBchild\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
