.TH "Union" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Union
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_\fP"
.br
.ti -1c
.RI "double \fB__\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "void * \fBy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
