.TH "UserAtomicType" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserAtomicType
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUserAtomicType\fP (int d=0) TEST_NOEXCEPT"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBUserAtomicType\fP &x, const \fBUserAtomicType\fP &y)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
