.TH "UsesAllocatorTestBase< Self, Alloc >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UsesAllocatorTestBase< Self, Alloc >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBCtorAlloc\fP = typename \fBTransformErasedTypeAlloc\fP< Alloc >::type"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class \&.\&.\&. ArgTypes> bool \fBcheckConstruct\fP (UsesAllocatorType expectType) const"
.br
.ti -1c
.RI "template<class \&.\&.\&. ArgTypes> bool \fBcheckConstruct\fP (UsesAllocatorType expectType, CtorAlloc const &expectAlloc) const"
.br
.ti -1c
.RI "bool \fBcheckConstructEquiv\fP (\fBUsesAllocatorTestBase\fP &O) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBTypeID\fP * \fBargs_id\fP"
.br
.ti -1c
.RI "UsesAllocatorType \fBconstructor_called\fP = UA_None"
.br
.ti -1c
.RI "\fBUsesAllocatorTestBaseStorage\fP< CtorAlloc > \fBalloc_store\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBUsesAllocatorTestBase\fP (const \fBTypeID\fP *aid)"
.br
.ti -1c
.RI "\fBUsesAllocatorTestBase\fP (\fBUsesAllocatorTestBase\fP const &)"
.br
.ti -1c
.RI "\fBUsesAllocatorTestBase\fP (\fBUsesAllocatorTestBase\fP &&)"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args> \fBUsesAllocatorTestBase\fP (std::allocator_arg_t, CtorAlloc const &a, Args &&\&.\&.\&.)"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args, class ArgsIDL  = detail::TakeNArgs<sizeof\&.\&.\&.(Args) \- 1, Args&&\&.\&.\&.>> \fBUsesAllocatorTestBase\fP (\fBAllocLastTag\fP, Args &&\&.\&.\&. args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
