.TH "UsesAllocatorTestBaseStorage< Alloc, false >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UsesAllocatorTestBaseStorage< Alloc, false >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUsesAllocatorTestBaseStorage\fP (Alloc const &a)"
.br
.ti -1c
.RI "Alloc const  * \fBget_allocator\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union \fBUsesAllocatorTestBaseStorage\fP< Alloc, false >:: { \&.\&.\&. }  "
.br
.ti -1c
.RI "bool \fBhas_alloc\fP = false"
.br
.ti -1c
.RI "char \fBdummy\fP"
.br
.ti -1c
.RI "Alloc \fBalloc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
