.TH "UsesAllocatorV3< Alloc, Arity >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UsesAllocatorV3< Alloc, Arity >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUsesAllocatorTestBase< UsesAllocatorV3< Alloc, Arity >, Alloc >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Alloc \fBallocator_type\fP"
.br
.ti -1c
.RI "using \fBBase\fP = \fBUsesAllocatorTestBase\fP< \fBUsesAllocatorV3\fP, Alloc >"
.br
.ti -1c
.RI "using \fBCtorAlloc\fP = typename Base::CtorAlloc"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUsesAllocatorV3\fP (\fBUsesAllocatorV3\fP const &)"
.br
.ti -1c
.RI "\fBUsesAllocatorV3\fP (\fBUsesAllocatorV3\fP &&)"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args, EnableIfB< sizeof\&.\&.\&.(Args)==Arity >  = false> \fBUsesAllocatorV3\fP (Args &&\&.\&.\&.)"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args> \fBUsesAllocatorV3\fP (std::allocator_arg_t tag, CtorAlloc const &alloc, Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "template<class \&.\&.\&. Args, EnableIfB< sizeof\&.\&.\&.(Args)==Arity+1 >  = false> \fBUsesAllocatorV3\fP (Args &&\&.\&.\&. args)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
