.TH "utf8::invalid_utf8" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utf8::invalid_utf8
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fButf8::exception\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinvalid_utf8\fP (uint8_t u)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const  throw ()"
.br
.ti -1c
.RI "uint8_t \fButf8_octet\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
