.TH "utf8::exception" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utf8::exception
.SH SYNOPSIS
.br
.PP
.PP
Inherits exception\&.
.PP
Inherited by \fButf8::invalid_code_point\fP, \fButf8::invalid_utf16\fP, \fButf8::invalid_utf8\fP, and \fButf8::not_enough_room\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
