.TH "utf8::unchecked::iterator< octet_iterator >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utf8::unchecked::iterator< octet_iterator >
.SH SYNOPSIS
.br
.PP
.PP
Inherits iterator< std::bidirectional_iterator_tag, uint32_t >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP (const octet_iterator &octet_it)"
.br
.ti -1c
.RI "octet_iterator \fBbase\fP () const"
.br
.ti -1c
.RI "uint32_t \fBoperator*\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &rhs) const"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP \fBoperator\-\-\fP (int)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
