.TH "utf8::invalid_utf16" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utf8::invalid_utf16
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fButf8::exception\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinvalid_utf16\fP (uint16_t u)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const  throw ()"
.br
.ti -1c
.RI "uint16_t \fButf16_word\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
