.TH "utility_server" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utility_server
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBecho_handler\fP (\fBwebsocketpp::connection_hdl\fP hdl, \fBserver::message_ptr\fP msg)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
