.TH "vote_action" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vote_action
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "account_name \fBvoter\fP"
.br
.ti -1c
.RI "account_name \fBauthor\fP"
.br
.ti -1c
.RI "post_name \fBpostid\fP"
.br
.ti -1c
.RI "int32_t \fBvote_power\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
