.TH "plugins/wallet_plugin/include/aacio/wallet_plugin/wallet_plugin.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/wallet_plugin/include/aacio/wallet_plugin/wallet_plugin.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <appbase/application\&.hpp>\fP
.br
\fC#include <fc/variant\&.hpp>\fP
.br
\fC#include <aacio/chain/contracts/types\&.hpp>\fP
.br
\fC#include <aacio/chain/transaction\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaacio::wallet_plugin\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBfc\fP"
.br
.RI "aacio::chain "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
