.TH "plugins/wallet_plugin/wallet_manager.cpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugins/wallet_plugin/wallet_manager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <aacio/wallet_plugin/wallet_manager\&.hpp>\fP
.br
\fC#include <aacio/chain/exceptions\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBaacio::wallet::gen_password\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr auto \fBaacio::wallet::file_ext\fP = '\&.wallet'"
.br
.ti -1c
.RI "constexpr auto \fBaacio::wallet::password_prefix\fP = 'PW'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
