.TH "wasm::Bits" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Bits
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int32_t \fBlowBitMask\fP (int32_t bits)"
.br
.ti -1c
.RI "static uint32_t \fBgetMaskedBits\fP (uint32_t mask)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
