.TH "wasm::FunctionType" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::FunctionType
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBstructuralComparison\fP (\fBFunctionType\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBFunctionType\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBFunctionType\fP &b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBName\fP \fBname\fP"
.br
.ti -1c
.RI "WasmType \fBresult\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< WasmType > \fBparams\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
