.TH "wasm::LocalCSE::UsableInfo" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::LocalCSE::UsableInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUsableInfo\fP (\fBExpression\fP **item, \fBPassOptions\fP &passOptions)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP ** \fBitem\fP"
.br
.ti -1c
.RI "Index \fBindex\fP"
.br
.ti -1c
.RI "\fBEffectAnalyzer\fP \fBeffects\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
