.TH "wasm::DuplicateFunctionElimination" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::DuplicateFunctionElimination
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::Pass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun\fP (\fBPassRunner\fP *runner, \fBModule\fP *module) override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
