.TH "wasm::I64Utilities" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::I64Utilities
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBExpression\fP * \fBrecreateI64\fP (\fBBuilder\fP &builder, \fBExpression\fP *low, \fBExpression\fP *high)"
.br
.ti -1c
.RI "static \fBExpression\fP * \fBrecreateI64\fP (\fBBuilder\fP &builder, Index low, Index high)"
.br
.ti -1c
.RI "static \fBExpression\fP * \fBgetI64High\fP (\fBBuilder\fP &builder, Index index)"
.br
.ti -1c
.RI "static \fBExpression\fP * \fBgetI64Low\fP (\fBBuilder\fP &builder, Index index)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
