.TH "wasm::SSAify" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::SSAify
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::WalkerPass< PostWalker< SSAify > >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBstd::set\fP< \fBSetLocal\fP * > \fBSets\fP"
.br
.ti -1c
.RI "typedef \fBstd::vector\fP< \fBSets\fP > \fBMapping\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisFunctionParallel\fP () override"
.br
.ti -1c
.RI "\fBPass\fP * \fBcreate\fP () override"
.br
.ti -1c
.RI "void \fBdoWalkFunction\fP (\fBFunction\fP *\fBfunc\fP)"
.br
.ti -1c
.RI "void \fBvisitBlock\fP (\fBBlock\fP *curr)"
.br
.ti -1c
.RI "void \fBfinishIf\fP ()"
.br
.ti -1c
.RI "void \fBvisitLoop\fP (\fBLoop\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitBreak\fP (\fBBreak\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitSwitch\fP (\fBSwitch\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitReturn\fP (\fBReturn\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitUnreachable\fP (\fBUnreachable\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitGetLocal\fP (\fBGetLocal\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitSetLocal\fP (\fBSetLocal\fP *curr)"
.br
.ti -1c
.RI "void \fBsetUnreachable\fP (\fBMapping\fP &mapping)"
.br
.ti -1c
.RI "bool \fBisUnreachable\fP (\fBMapping\fP &mapping)"
.br
.ti -1c
.RI "\fBMapping\fP & \fBmerge\fP (\fBstd::vector\fP< \fBMapping\fP > &mappings)"
.br
.ti -1c
.RI "void \fBcomputeGetsAndPhis\fP ()"
.br
.ti -1c
.RI "Index \fBaddLocal\fP (WasmType type)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBafterIfCondition\fP (\fBSSAify\fP *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBafterIfTrue\fP (\fBSSAify\fP *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBafterIfFalse\fP (\fBSSAify\fP *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBbeforeLoop\fP (\fBSSAify\fP *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBscan\fP (\fBSSAify\fP *self, \fBExpression\fP **currp)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Index \fBnumLocals\fP"
.br
.ti -1c
.RI "\fBMapping\fP \fBcurrMapping\fP"
.br
.ti -1c
.RI "Index \fBnextIndex\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBMapping\fP > \fBmappingStack\fP"
.br
.ti -1c
.RI "\fBstd::map\fP< \fBName\fP, \fBstd::vector\fP< \fBMapping\fP > > \fBbreakMappings\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBstd::vector\fP< \fBGetLocal\fP * > > \fBloopGetStack\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBExpression\fP * > \fBfunctionPrepends\fP"
.br
.ti -1c
.RI "\fBstd::map\fP< \fBGetLocal\fP *, \fBSets\fP > \fBgetSetses\fP"
.br
.ti -1c
.RI "\fBstd::map\fP< \fBGetLocal\fP *, \fBExpression\fP ** > \fBgetLocations\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
