.TH "wasm::Action" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Action
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBWhat\fP { \fBGet\fP, \fBSet\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAction\fP (What what, Index index, \fBExpression\fP **origin)"
.br
.ti -1c
.RI "bool \fBisGet\fP ()"
.br
.ti -1c
.RI "bool \fBisSet\fP ()"
.br
.ti -1c
.RI "\fBAction\fP (\fBCall\fP *call, \fBBlock\fP *block, \fBFunction\fP *contents)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "What \fBwhat\fP"
.br
.ti -1c
.RI "Index \fBindex\fP"
.br
.ti -1c
.RI "\fBExpression\fP ** \fBorigin\fP"
.br
.ti -1c
.RI "bool \fBeffective\fP"
.br
.ti -1c
.RI "\fBCall\fP * \fBcall\fP"
.br
.ti -1c
.RI "\fBBlock\fP * \fBblock\fP"
.br
.ti -1c
.RI "\fBFunction\fP * \fBcontents\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
