.TH "wasm::SourceLocation" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::SourceLocation
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSourceLocation\fP (\fBcashew::IString\fP filename_, uint32_t line_, uint32_t column_=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcashew::IString\fP \fBfilename\fP"
.br
.ti -1c
.RI "uint32_t \fBline\fP"
.br
.ti -1c
.RI "uint32_t \fBcolumn\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
