.TH "wasm::Function::DebugLocation" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Function::DebugLocation
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBDebugLocation\fP &\fBother\fP) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBDebugLocation\fP &\fBother\fP) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBfileIndex\fP"
.br
.ti -1c
.RI "uint32_t \fBlineNumber\fP"
.br
.ti -1c
.RI "uint32_t \fBcolumnNumber\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
