.TH "wasm::GeneticLearner< Genome, Fitness, Generator >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::GeneticLearner< Genome, Fitness, Generator >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeneticLearner\fP (Generator &\fBgenerator\fP, size_t size)"
.br
.ti -1c
.RI "Genome * \fBgetBest\fP ()"
.br
.ti -1c
.RI "unique_ptr \fBacquireBest\fP ()"
.br
.ti -1c
.RI "void \fBrunGeneration\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
