.TH "wasm::Flow" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Flow
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlow\fP (\fBLiteral\fP value)"
.br
.ti -1c
.RI "\fBFlow\fP (\fBName\fP breakTo)"
.br
.ti -1c
.RI "bool \fBbreaking\fP ()"
.br
.ti -1c
.RI "void \fBclearIf\fP (\fBName\fP target)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLiteral\fP \fBvalue\fP"
.br
.ti -1c
.RI "\fBName\fP \fBbreakTo\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, \fBFlow\fP &flow)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
