.TH "wasm::Walker< SubType, VisitorType >::Task" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Walker< SubType, VisitorType >::Task
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTask\fP (TaskFunc \fBfunc\fP, \fBExpression\fP **currp)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TaskFunc \fBfunc\fP"
.br
.ti -1c
.RI "\fBExpression\fP ** \fBcurrp\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
