.TH "wasm::LocalCSE" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::LocalCSE
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::WalkerPass< LinearExecutionWalker< LocalCSE > >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBUsableInfo\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBHashedExpressionMap\fP< \fBUsableInfo\fP > \fBUsables\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisFunctionParallel\fP () override"
.br
.ti -1c
.RI "\fBPass\fP * \fBcreate\fP () override"
.br
.ti -1c
.RI "void \fBcheckInvalidations\fP (\fBEffectAnalyzer\fP &effects)"
.br
.ti -1c
.RI "bool \fBisRelevant\fP (\fBExpression\fP *curr)"
.br
.ti -1c
.RI "void \fBhandle\fP (\fBExpression\fP **currp, \fBExpression\fP *curr)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdoNoteNonLinear\fP (\fBLocalCSE\fP *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBvisitPre\fP (\fBLocalCSE\fP *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBvisitPost\fP (\fBLocalCSE\fP *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBscan\fP (\fBLocalCSE\fP *self, \fBExpression\fP **currp)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUsables\fP \fBusables\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBExpression\fP * > \fBexpressionStack\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
