.TH "wasm::ModuleInstanceBase< GlobalManager, SubType >::ExternalInterface" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::ModuleInstanceBase< GlobalManager, SubType >::ExternalInterface
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBModule\fP &wasm, SubType &instance)"
.br
.ti -1c
.RI "virtual void \fBimportGlobals\fP (GlobalManager &globals, \fBModule\fP &wasm)=0"
.br
.ti -1c
.RI "virtual \fBLiteral\fP \fBcallImport\fP (\fBImport\fP *import, \fBLiteralList\fP &arguments)=0"
.br
.ti -1c
.RI "virtual \fBLiteral\fP \fBcallTable\fP (Index index, \fBLiteralList\fP &arguments, WasmType result, SubType &instance)=0"
.br
.ti -1c
.RI "virtual void \fBgrowMemory\fP (\fBAddress\fP oldSize, \fBAddress\fP newSize)=0"
.br
.ti -1c
.RI "virtual void \fBtrap\fP (const char *why)=0"
.br
.ti -1c
.RI "virtual \fBLiteral\fP \fBload\fP (\fBLoad\fP *load, \fBAddress\fP addr)"
.br
.ti -1c
.RI "virtual void \fBstore\fP (\fBStore\fP *store, \fBAddress\fP addr, \fBLiteral\fP value)"
.br
.ti -1c
.RI "virtual int8_t \fBload8s\fP (\fBAddress\fP addr)"
.br
.ti -1c
.RI "virtual uint8_t \fBload8u\fP (\fBAddress\fP addr)"
.br
.ti -1c
.RI "virtual int16_t \fBload16s\fP (\fBAddress\fP addr)"
.br
.ti -1c
.RI "virtual uint16_t \fBload16u\fP (\fBAddress\fP addr)"
.br
.ti -1c
.RI "virtual int32_t \fBload32s\fP (\fBAddress\fP addr)"
.br
.ti -1c
.RI "virtual uint32_t \fBload32u\fP (\fBAddress\fP addr)"
.br
.ti -1c
.RI "virtual int64_t \fBload64s\fP (\fBAddress\fP addr)"
.br
.ti -1c
.RI "virtual uint64_t \fBload64u\fP (\fBAddress\fP addr)"
.br
.ti -1c
.RI "virtual void \fBstore8\fP (\fBAddress\fP addr, int8_t value)"
.br
.ti -1c
.RI "virtual void \fBstore16\fP (\fBAddress\fP addr, int16_t value)"
.br
.ti -1c
.RI "virtual void \fBstore32\fP (\fBAddress\fP addr, int32_t value)"
.br
.ti -1c
.RI "virtual void \fBstore64\fP (\fBAddress\fP addr, int64_t value)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
