.TH "wasm::LinkerObject::SymbolAlias" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::LinkerObject::SymbolAlias
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSymbolAlias\fP (\fBName\fP symbol, Relocation::Kind kind, Offset offset)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBName\fP \fBsymbol\fP"
.br
.ti -1c
.RI "Relocation::Kind \fBkind\fP"
.br
.ti -1c
.RI "Offset \fBoffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
