.TH "wasm::Properties" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Properties
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBemitsBoolean\fP (\fBExpression\fP *curr)"
.br
.ti -1c
.RI "static bool \fBisSymmetric\fP (\fBBinary\fP *binary)"
.br
.ti -1c
.RI "static \fBExpression\fP * \fBgetSignExtValue\fP (\fBExpression\fP *curr)"
.br
.ti -1c
.RI "static Index \fBgetSignExtBits\fP (\fBExpression\fP *curr)"
.br
.ti -1c
.RI "static \fBExpression\fP * \fBgetAlmostSignExt\fP (\fBExpression\fP *curr)"
.br
.ti -1c
.RI "static Index \fBgetAlmostSignExtBits\fP (\fBExpression\fP *curr, Index &extraShifts)"
.br
.ti -1c
.RI "static \fBExpression\fP * \fBgetZeroExtValue\fP (\fBExpression\fP *curr)"
.br
.ti -1c
.RI "static Index \fBgetZeroExtBits\fP (\fBExpression\fP *curr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
