.TH "wasm::Import" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Import
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBName\fP \fBname\fP"
.br
.ti -1c
.RI "\fBName\fP \fBmodule\fP"
.br
.ti -1c
.RI "\fBName\fP \fBbase\fP"
.br
.ti -1c
.RI "ExternalKind \fBkind\fP"
.br
.ti -1c
.RI "\fBName\fP \fBfunctionType\fP"
.br
.ti -1c
.RI "WasmType \fBglobalType\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
