.TH "wasm::CFGWalker< SubType, VisitorType, Contents >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::CFGWalker< SubType, VisitorType, Contents >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::ControlFlowWalker< SubType, VisitorType >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBasicBlock\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBasicBlock\fP * \fBmakeBasicBlock\fP ()"
.br
.ti -1c
.RI "void \fBstartBasicBlock\fP ()"
.br
.ti -1c
.RI "void \fBstartUnreachableBlock\fP ()"
.br
.ti -1c
.RI "void \fBlink\fP (\fBBasicBlock\fP *from, \fBBasicBlock\fP *to)"
.br
.ti -1c
.RI "void \fBdoWalkFunction\fP (\fBFunction\fP *\fBfunc\fP)"
.br
.ti -1c
.RI "\fBstd::unordered_set\fP< \fBBasicBlock\fP * > \fBfindLiveBlocks\fP ()"
.br
.ti -1c
.RI "void \fBunlinkDeadBlocks\fP (\fBstd::unordered_set\fP< \fBBasicBlock\fP *> alive)"
.br
.ti -1c
.RI "void \fBgenerateDebugIds\fP ()"
.br
.ti -1c
.RI "void \fBdumpCFG\fP (std::string message)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdoStartUnreachableBlock\fP (SubType *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBdoEndBlock\fP (SubType *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBdoStartIfTrue\fP (SubType *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBdoStartIfFalse\fP (SubType *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBdoEndIf\fP (SubType *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBdoStartLoop\fP (SubType *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBdoEndLoop\fP (SubType *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBdoEndBreak\fP (SubType *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBdoEndSwitch\fP (SubType *self, \fBExpression\fP **currp)"
.br
.ti -1c
.RI "static void \fBscan\fP (SubType *self, \fBExpression\fP **currp)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBasicBlock\fP * \fBentry\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< std::unique_ptr< \fBBasicBlock\fP > > \fBbasicBlocks\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBBasicBlock\fP * > \fBloopTops\fP"
.br
.ti -1c
.RI "\fBBasicBlock\fP * \fBcurrBasicBlock\fP"
.br
.ti -1c
.RI "\fBstd::map\fP< \fBExpression\fP *, \fBstd::vector\fP< \fBBasicBlock\fP * > > \fBbranches\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBBasicBlock\fP * > \fBifStack\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBBasicBlock\fP * > \fBloopStack\fP"
.br
.ti -1c
.RI "\fBstd::map\fP< \fBBasicBlock\fP *, size_t > \fBdebugIds\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
