.TH "wasm::Unary" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Unary
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::SpecificExpression< Expression::UnaryId >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnary\fP (\fBMixedArena\fP &allocator)"
.br
.ti -1c
.RI "bool \fBisRelational\fP ()"
.br
.ti -1c
.RI "void \fBfinalize\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UnaryOp \fBop\fP"
.br
.ti -1c
.RI "\fBExpression\fP * \fBvalue\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
