.TH "wasm::Metrics" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Metrics
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::WalkerPass< PostWalker< Metrics, UnifiedExpressionVisitor< Metrics > > >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBvisitExpression\fP (\fBExpression\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitModule\fP (\fBModule\fP *module)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmap\fP< const char *, int > \fBcounts\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBMetrics\fP * \fBlastMetricsPass\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
