.TH "wasm::LocalScanner" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::LocalScanner
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::PostWalker< LocalScanner >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocalScanner\fP (\fBstd::vector\fP< \fBLocalInfo\fP > &localInfo)"
.br
.ti -1c
.RI "void \fBdoWalkFunction\fP (\fBFunction\fP *\fBfunc\fP)"
.br
.ti -1c
.RI "void \fBvisitSetLocal\fP (\fBSetLocal\fP *curr)"
.br
.ti -1c
.RI "Index \fBgetMaxBitsForLocal\fP (\fBGetLocal\fP *get)"
.br
.ti -1c
.RI "Index \fBgetBitsForType\fP (WasmType type)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::vector\fP< \fBLocalInfo\fP > & \fBlocalInfo\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
