.TH "wasm::Element" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Element
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElement\fP (\fBMixedArena\fP &allocator)"
.br
.ti -1c
.RI "bool \fBisList\fP () const"
.br
.ti -1c
.RI "bool \fBisStr\fP () const"
.br
.ti -1c
.RI "bool \fBdollared\fP () const"
.br
.ti -1c
.RI "bool \fBquoted\fP () const"
.br
.ti -1c
.RI "\fBList\fP & \fBlist\fP ()"
.br
.ti -1c
.RI "\fBElement\fP * \fBoperator[]\fP (unsigned i)"
.br
.ti -1c
.RI "size_t \fBsize\fP ()"
.br
.ti -1c
.RI "\fBcashew::IString\fP \fBstr\fP () const"
.br
.ti -1c
.RI "const char * \fBc_str\fP () const"
.br
.ti -1c
.RI "\fBElement\fP * \fBsetString\fP (\fBcashew::IString\fP str__, bool dollared__, bool quoted__)"
.br
.ti -1c
.RI "\fBElement\fP * \fBsetMetadata\fP (size_t line_, size_t col_, \fBSourceLocation\fP *loc_)"
.br
.ti -1c
.RI "void \fBdump\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBline\fP"
.br
.ti -1c
.RI "size_t \fBcol\fP"
.br
.ti -1c
.RI "\fBSourceLocation\fP * \fBloc\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, \fBElement\fP &e)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
