.TH "wasm::Asm2WasmBuilder" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Asm2WasmBuilder
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMappedGlobal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTrapMode\fP { \fBAllow\fP, \fBClamp\fP, \fBJS\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAsm2WasmBuilder\fP (\fBModule\fP &wasm, \fBAsm2WasmPreProcessor\fP &preprocessor, bool debug, TrapMode trapMode, \fBPassOptions\fP passOptions, bool legalizeJavaScriptFFI, bool runOptimizationPasses, bool wasmOnly)"
.br
.ti -1c
.RI "void \fBprocessAsm\fP (\fBRef\fP ast)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBModule\fP & \fBwasm\fP"
.br
.ti -1c
.RI "\fBMixedArena\fP & \fBallocator\fP"
.br
.ti -1c
.RI "\fBBuilder\fP \fBbuilder\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBOptimizingIncrementalModuleBuilder\fP > \fBoptimizingBuilder\fP"
.br
.ti -1c
.RI "\fBstd::map\fP< \fBIString\fP, int > \fBfunctionTableStarts\fP"
.br
.ti -1c
.RI "\fBAsm2WasmPreProcessor\fP & \fBpreprocessor\fP"
.br
.ti -1c
.RI "bool \fBdebug\fP"
.br
.ti -1c
.RI "TrapMode \fBtrapMode\fP"
.br
.ti -1c
.RI "\fBPassOptions\fP \fBpassOptions\fP"
.br
.ti -1c
.RI "bool \fBlegalizeJavaScriptFFI\fP"
.br
.ti -1c
.RI "bool \fBrunOptimizationPasses\fP"
.br
.ti -1c
.RI "bool \fBwasmOnly\fP"
.br
.ti -1c
.RI "\fBstd::map\fP< \fBIString\fP, \fBMappedGlobal\fP > \fBmappedGlobals\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
