.TH "wasm::LinkerObject::SymbolInfo" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::LinkerObject::SymbolInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBmerge\fP (\fBSymbolInfo\fP &\fBother\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::unordered_set\fP< \fBcashew::IString\fP > \fBimplementedFunctions\fP"
.br
.ti -1c
.RI "\fBstd::unordered_set\fP< \fBcashew::IString\fP > \fBundefinedFunctions\fP"
.br
.ti -1c
.RI "\fBstd::unordered_set\fP< \fBcashew::IString\fP > \fBimportedObjects\fP"
.br
.ti -1c
.RI "\fBstd::unordered_map\fP< \fBcashew::IString\fP, \fBSymbolAlias\fP > \fBaliasedSymbols\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
