.TH "wasm::OptimizingIncrementalModuleBuilder" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::OptimizingIncrementalModuleBuilder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptimizingIncrementalModuleBuilder\fP (\fBModule\fP *wasm, Index numFunctions, \fBPassOptions\fP passOptions, std::function< void(\fBPassRunner\fP &)> addPrePasses, bool debug, bool validateGlobally)"
.br
.ti -1c
.RI "bool \fBuseWorkers\fP ()"
.br
.ti -1c
.RI "void \fBaddFunction\fP (\fBFunction\fP *\fBfunc\fP)"
.br
.ti -1c
.RI "void \fBfinish\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
