.TH "tests/tests/wasm_tests/wasm_tests.cpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/tests/wasm_tests/wasm_tests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <boost/test/unit_test\&.hpp>\fP
.br
\fC#include '\&.\&./\&.\&./common/database_fixture\&.hpp'\fP
.br
\fC#include <rate_limit_auth/rate_limit_auth\&.wast\&.hpp>\fP
.br
\fC#include <currency/currency\&.wast\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (rate_limit_single_authority_test, testing_fixture)"
.br
.ti -1c
.RI "\fBBOOST_FIXTURE_TEST_CASE\fP (rate_limit_multi_authority_test, testing_fixture)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
