.TH "wasm::Store" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Store
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::SpecificExpression< Expression::StoreId >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStore\fP (\fBMixedArena\fP &allocator)"
.br
.ti -1c
.RI "void \fBfinalize\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbytes\fP"
.br
.ti -1c
.RI "\fBAddress\fP \fBoffset\fP"
.br
.ti -1c
.RI "\fBAddress\fP \fBalign\fP"
.br
.ti -1c
.RI "\fBExpression\fP * \fBptr\fP"
.br
.ti -1c
.RI "\fBExpression\fP * \fBvalue\fP"
.br
.ti -1c
.RI "WasmType \fBvalueType\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
