.TH "wasm::InliningState" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::InliningState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::set\fP< \fBName\fP > \fBcanInline\fP"
.br
.ti -1c
.RI "\fBstd::map\fP< \fBName\fP, \fBstd::vector\fP< \fBAction\fP > > \fBactionsForFunction\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
