.TH "wasm::Linker" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Linker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinker\fP (\fBAddress\fP globalBase, \fBAddress\fP stackAllocation, \fBAddress\fP userInitialMemory, \fBAddress\fP userMaxMemory, bool importMemory, bool ignoreUnknownSymbols, \fBName\fP startFunction, bool debug)"
.br
.ti -1c
.RI "\fBLinkerObject\fP & \fBgetOutput\fP ()"
.br
.ti -1c
.RI "void \fBlayout\fP ()"
.br
.ti -1c
.RI "void \fBemscriptenGlue\fP (std::ostream &o)"
.br
.ti -1c
.RI "bool \fBlinkObject\fP (S2WasmBuilder &builder)"
.br
.ti -1c
.RI "bool \fBlinkArchive\fP (\fBArchive\fP &archive)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
