.TH "wasm::Drop" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Drop
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::SpecificExpression< Expression::DropId >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDrop\fP (\fBMixedArena\fP &allocator)"
.br
.ti -1c
.RI "void \fBfinalize\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP * \fBvalue\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
