.TH "wasm::Name" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Name
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcashew::IString\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBName\fP (const char *str)"
.br
.ti -1c
.RI "\fBName\fP (\fBcashew::IString\fP str)"
.br
.ti -1c
.RI "\fBName\fP (const std::string &str)"
.br
.ti -1c
.RI "bool \fBhasSubstring\fP (\fBcashew::IString\fP substring)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBName\fP \fBfromInt\fP (size_t i)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, \fBName\fP name)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
