.TH "WASM::OperatorSerializerStream" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WASM::OperatorSerializerStream
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void \fBResult\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOperatorSerializerStream\fP (\fBSerialization::OutputStream\fP &inByteStream, \fBFunctionDef\fP &inFunctionDef)"
.br
.ti -1c
.RI "void \fBunknown\fP (Opcode opcode)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
