.TH "wasm::ModuleIO" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::ModuleIO
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBwasm::ModuleReader\fP, and \fBwasm::ModuleWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetDebug\fP (bool debug_)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBdebug\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
