.TH "wasm::ReReloop::TriageTask" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::ReReloop::TriageTask
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::ReReloop::Task\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTriageTask\fP (\fBReReloop\fP &parent, \fBExpression\fP *curr)"
.br
.ti -1c
.RI "void \fBrun\fP () override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP * \fBcurr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
