.TH "wasm::Asm2WasmBuilder::MappedGlobal" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Asm2WasmBuilder::MappedGlobal
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMappedGlobal\fP (WasmType type)"
.br
.ti -1c
.RI "\fBMappedGlobal\fP (WasmType type, bool import, \fBIString\fP module, \fBIString\fP \fBbase\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "WasmType \fBtype\fP"
.br
.ti -1c
.RI "bool \fBimport\fP"
.br
.ti -1c
.RI "\fBIString\fP \fBmodule\fP"
.br
.ti -1c
.RI "\fBIString\fP \fBbase\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
