.TH "wasm::PostWalker< SubType, VisitorType >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::PostWalker< SubType, VisitorType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::Walker< SubType, VisitorType >\fP\&.
.PP
Inherited by \fBwasm::ControlFlowWalker< SubType, VisitorType >\fP, \fBwasm::ExpressionStackWalker< SubType, VisitorType >\fP, and \fBwasm::LinearExecutionWalker< SubType, VisitorType >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBscan\fP (SubType *self, \fBExpression\fP **currp)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
