.TH "wasm::Asm2WasmPreProcessor" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Asm2WasmPreProcessor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char * \fBprocess\fP (char *input)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBmemoryGrowth\fP = false"
.br
.ti -1c
.RI "bool \fBdebugInfo\fP = false"
.br
.ti -1c
.RI "\fBstd::vector\fP< std::string > \fBdebugInfoFileNames\fP"
.br
.ti -1c
.RI "\fBstd::unordered_map\fP< std::string, Index > \fBdebugInfoFileIndices\fP"
.br
.ti -1c
.RI "char * \fBallocatedCopy\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
