.TH "wasm::ReReloop::SwitchTask" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::ReReloop::SwitchTask
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::ReReloop::Task\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBhandle\fP (\fBReReloop\fP &parent, \fBSwitch\fP *curr)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
