.TH "wasm::Call" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Call
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::SpecificExpression< Expression::CallId >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCall\fP (\fBMixedArena\fP &allocator)"
.br
.ti -1c
.RI "void \fBfinalize\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpressionList\fP \fBoperands\fP"
.br
.ti -1c
.RI "\fBName\fP \fBtarget\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
