.TH "wasm::Vacuum" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Vacuum
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::WalkerPass< PostWalker< Vacuum > >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisFunctionParallel\fP () override"
.br
.ti -1c
.RI "\fBPass\fP * \fBcreate\fP () override"
.br
.ti -1c
.RI "\fBExpression\fP * \fBreplaceCurrent\fP (\fBExpression\fP *expression)"
.br
.ti -1c
.RI "void \fBdoWalkFunction\fP (\fBFunction\fP *\fBfunc\fP)"
.br
.ti -1c
.RI "\fBExpression\fP * \fBoptimize\fP (\fBExpression\fP *curr, bool resultUsed)"
.br
.ti -1c
.RI "void \fBvisitBlock\fP (\fBBlock\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitIf\fP (\fBIf\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitLoop\fP (\fBLoop\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitDrop\fP (\fBDrop\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitFunction\fP (\fBFunction\fP *curr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTypeUpdater\fP \fBtypeUpdater\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
