.TH "wasm::CoalesceLocalsWithLearning" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::CoalesceLocalsWithLearning
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::CoalesceLocals\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBPass\fP * \fBcreate\fP () override"
.br
.ti -1c
.RI "virtual void \fBpickIndices\fP (\fBstd::vector\fP< Index > &indices) override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
