.TH "wasm::ModuleWriter" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::ModuleWriter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::ModuleIO\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetBinary\fP (bool binary_)"
.br
.ti -1c
.RI "void \fBsetDebugInfo\fP (bool debugInfo_)"
.br
.ti -1c
.RI "void \fBsetSymbolMap\fP (std::string symbolMap_)"
.br
.ti -1c
.RI "void \fBsetSourceMapFilename\fP (std::string sourceMapFilename_)"
.br
.ti -1c
.RI "void \fBsetSourceMapUrl\fP (std::string sourceMapUrl_)"
.br
.ti -1c
.RI "void \fBwriteText\fP (\fBModule\fP &wasm, std::string filename)"
.br
.ti -1c
.RI "void \fBwriteBinary\fP (\fBModule\fP &wasm, std::string filename)"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBModule\fP &wasm, std::string filename)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
