.TH "wasm::Memory::Segment" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Memory::Segment
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSegment\fP (\fBExpression\fP *offset, const char *init, \fBAddress\fP size)"
.br
.ti -1c
.RI "\fBSegment\fP (\fBExpression\fP *offset, \fBstd::vector\fP< char > &init)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP * \fBoffset\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< char > \fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
