.TH "wasm::PassRunner" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::PassRunner
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPassRunner\fP (\fBModule\fP *wasm)"
.br
.ti -1c
.RI "\fBPassRunner\fP (\fBModule\fP *wasm, \fBPassOptions\fP options)"
.br
.ti -1c
.RI "void \fBsetDebug\fP (bool debug_)"
.br
.ti -1c
.RI "void \fBsetValidateGlobally\fP (bool validate)"
.br
.ti -1c
.RI "void \fBadd\fP (std::string passName)"
.br
.ti -1c
.RI "template<class P > void \fBadd\fP ()"
.br
.ti -1c
.RI "template<class P , class Arg > void \fBadd\fP (Arg \fBarg\fP)"
.br
.ti -1c
.RI "void \fBaddDefaultOptimizationPasses\fP ()"
.br
.ti -1c
.RI "void \fBaddDefaultFunctionOptimizationPasses\fP ()"
.br
.ti -1c
.RI "void \fBaddDefaultGlobalOptimizationPasses\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBrunFunction\fP (\fBFunction\fP *\fBfunc\fP)"
.br
.ti -1c
.RI "template<class P > \fBP\fP * \fBgetLast\fP ()"
.br
.ti -1c
.RI "void \fBsetIsNested\fP (bool nested)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBgetPassDebug\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBModule\fP * \fBwasm\fP"
.br
.ti -1c
.RI "\fBMixedArena\fP * \fBallocator\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBPass\fP * > \fBpasses\fP"
.br
.ti -1c
.RI "\fBPassOptions\fP \fBoptions\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBisNested\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
