.TH "wasm::LocalSet" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::LocalSet
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstd::vector< Index >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocalSet\fP \fBmerge\fP (const \fBLocalSet\fP &\fBother\fP) const"
.br
.ti -1c
.RI "void \fBinsert\fP (Index x)"
.br
.ti -1c
.RI "bool \fBerase\fP (Index x)"
.br
.ti -1c
.RI "bool \fBhas\fP (Index x)"
.br
.ti -1c
.RI "void \fBverify\fP () const"
.br
.ti -1c
.RI "void \fBdump\fP (const char *str=nullptr) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
