.TH "wasm::ParseException" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::ParseException
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseException\fP (std::string text)"
.br
.ti -1c
.RI "\fBParseException\fP (std::string text, size_t line, size_t col)"
.br
.ti -1c
.RI "void \fBdump\fP (std::ostream &o)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBtext\fP"
.br
.ti -1c
.RI "size_t \fBline\fP"
.br
.ti -1c
.RI "size_t \fBcol\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
