.TH "wasm::Memory" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Memory
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSegment\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBName\fP \fBname\fP"
.br
.ti -1c
.RI "\fBAddress\fP \fBinitial\fP"
.br
.ti -1c
.RI "\fBAddress\fP \fBmax\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBSegment\fP > \fBsegments\fP"
.br
.ti -1c
.RI "bool \fBexists\fP"
.br
.ti -1c
.RI "bool \fBimported\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const Address::address_t \fBkPageSize\fP = 64 * 1024"
.br
.ti -1c
.RI "static const Address::address_t \fBkMaxSize\fP = ~Address::address_t(0) / kPageSize"
.br
.ti -1c
.RI "static const Address::address_t \fBkPageMask\fP = ~(kPageSize \- 1)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
