.TH "wasm::LocalAnalyzer" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::LocalAnalyzer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::PostWalker< LocalAnalyzer >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBanalyze\fP (\fBFunction\fP *\fBfunc\fP)"
.br
.ti -1c
.RI "bool \fBisSFA\fP (Index i)"
.br
.ti -1c
.RI "Index \fBgetNumGets\fP (Index i)"
.br
.ti -1c
.RI "void \fBvisitGetLocal\fP (\fBGetLocal\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitSetLocal\fP (\fBSetLocal\fP *curr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::vector\fP< bool > \fBsfa\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< Index > \fBnumSets\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< Index > \fBnumGets\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
