.TH "wasm::Output" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Output
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOutput\fP (const std::string &filename, Flags::BinaryOption binary, Flags::DebugOption debug)"
.br
.ti -1c
.RI "template<typename T > std::ostream & \fBoperator<<\fP (const \fBT\fP &v)"
.br
.ti -1c
.RI "std::ostream & \fBgetStream\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
