.TH "wasm::SimplifyLocals::BlockBreak" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::SimplifyLocals::BlockBreak
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP ** \fBbrp\fP"
.br
.ti -1c
.RI "\fBSinkables\fP \fBsinkables\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
