.TH "wasm::Measurer" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Measurer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::PostWalker< Measurer, UnifiedExpressionVisitor< Measurer > >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBvisitExpression\fP (\fBExpression\fP *curr)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Index \fBmeasure\fP (\fBExpression\fP *tree)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Index \fBsize\fP = 0"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
