.TH "wasm::Block" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::Block
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::SpecificExpression< Expression::BlockId >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlock\fP (\fBMixedArena\fP &allocator)"
.br
.ti -1c
.RI "void \fBfinalize\fP (WasmType type_)"
.br
.ti -1c
.RI "void \fBfinalize\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBName\fP \fBname\fP"
.br
.ti -1c
.RI "\fBExpressionList\fP \fBlist\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
