.TH "wasm::TypeSeeker" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::TypeSeeker
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::PostWalker< TypeSeeker >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTypeSeeker\fP (\fBExpression\fP *target, \fBName\fP targetName)"
.br
.ti -1c
.RI "void \fBvisitBreak\fP (\fBBreak\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitSwitch\fP (\fBSwitch\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitBlock\fP (\fBBlock\fP *curr)"
.br
.ti -1c
.RI "void \fBvisitLoop\fP (\fBLoop\fP *curr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpression\fP * \fBtarget\fP"
.br
.ti -1c
.RI "\fBName\fP \fBtargetName\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< WasmType > \fBtypes\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
