.TH "wasm::ConstantExpressionRunner< GlobalManager >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::ConstantExpressionRunner< GlobalManager >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwasm::ExpressionRunner< ConstantExpressionRunner< GlobalManager > >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstantExpressionRunner\fP (GlobalManager &globals)"
.br
.ti -1c
.RI "\fBFlow\fP \fBvisitLoop\fP (\fBLoop\fP *curr)"
.br
.ti -1c
.RI "\fBFlow\fP \fBvisitCall\fP (\fBCall\fP *curr)"
.br
.ti -1c
.RI "\fBFlow\fP \fBvisitCallImport\fP (\fBCallImport\fP *curr)"
.br
.ti -1c
.RI "\fBFlow\fP \fBvisitCallIndirect\fP (\fBCallIndirect\fP *curr)"
.br
.ti -1c
.RI "\fBFlow\fP \fBvisitGetLocal\fP (\fBGetLocal\fP *curr)"
.br
.ti -1c
.RI "\fBFlow\fP \fBvisitSetLocal\fP (\fBSetLocal\fP *curr)"
.br
.ti -1c
.RI "\fBFlow\fP \fBvisitGetGlobal\fP (\fBGetGlobal\fP *curr)"
.br
.ti -1c
.RI "\fBFlow\fP \fBvisitSetGlobal\fP (\fBSetGlobal\fP *curr)"
.br
.ti -1c
.RI "\fBFlow\fP \fBvisitLoad\fP (\fBLoad\fP *curr)"
.br
.ti -1c
.RI "\fBFlow\fP \fBvisitStore\fP (\fBStore\fP *curr)"
.br
.ti -1c
.RI "\fBFlow\fP \fBvisitHost\fP (\fBHost\fP *curr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
