.TH "wasm::LinkerObject" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wasm::LinkerObject
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRelocation\fP"
.br
.ti -1c
.RI "struct \fBSymbolAlias\fP"
.br
.ti -1c
.RI "struct \fBSymbolInfo\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddStatic\fP (\fBAddress\fP allocSize, \fBAddress\fP alignment, \fBName\fP name)"
.br
.ti -1c
.RI "void \fBaddGlobal\fP (\fBName\fP name)"
.br
.ti -1c
.RI "void \fBaddRelocation\fP (\fBRelocation\fP *relocation)"
.br
.ti -1c
.RI "bool \fBisFunctionImplemented\fP (\fBName\fP name)"
.br
.ti -1c
.RI "bool \fBisObjectImplemented\fP (\fBName\fP name)"
.br
.ti -1c
.RI "\fBName\fP \fBresolveAlias\fP (\fBName\fP name, Relocation::Kind kind)"
.br
.ti -1c
.RI "\fBSymbolAlias\fP * \fBgetAlias\fP (\fBName\fP name, Relocation::Kind kind)"
.br
.ti -1c
.RI "void \fBaddSegment\fP (\fBName\fP name, const char *data, \fBAddress\fP size)"
.br
.ti -1c
.RI "void \fBaddSegment\fP (\fBName\fP name, \fBstd::vector\fP< char > &data)"
.br
.ti -1c
.RI "void \fBaddInitializerFunction\fP (\fBName\fP name)"
.br
.ti -1c
.RI "void \fBaddUndefinedFunctionCall\fP (\fBCall\fP *call)"
.br
.ti -1c
.RI "void \fBaddExternType\fP (\fBName\fP name, \fBFunctionType\fP *ty)"
.br
.ti -1c
.RI "\fBFunctionType\fP * \fBgetExternType\fP (\fBName\fP name)"
.br
.ti -1c
.RI "void \fBaddIndirectIndex\fP (\fBName\fP name, \fBAddress\fP index)"
.br
.ti -1c
.RI "bool \fBisEmpty\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBModule\fP \fBwasm\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBLinker\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
