.TH "WAST::Action" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAST::Action
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBWAST::GetAction\fP, \fBWAST::InvokeAction\fP, and \fBWAST::ModuleAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAction\fP (ActionType inType, \fBTextFileLocus\fP &&inLocus)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const ActionType \fBtype\fP"
.br
.ti -1c
.RI "const \fBTextFileLocus\fP \fBlocus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
