.TH "WAST::AssertReturnCommand" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAST::AssertReturnCommand
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBWAST::Command\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssertReturnCommand\fP (\fBTextFileLocus\fP &&inLocus, \fBAction\fP *inAction, \fBRuntime::Result\fP inExpectedReturn)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBAction\fP > \fBaction\fP"
.br
.ti -1c
.RI "\fBRuntime::Result\fP \fBexpectedReturn\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
