.TH "WAST::UnresolvedFunctionType" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAST::UnresolvedFunctionType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBReference\fP \fBreference\fP"
.br
.ti -1c
.RI "const \fBIR::FunctionType\fP * \fBexplicitType\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
