.TH "WAST::ParseState" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAST::ParseState
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBWAST::ModuleParseState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseState\fP (const char *inString, const \fBLineInfo\fP *inLineInfo, \fBstd::vector\fP< \fBUnresolvedError\fP > &inErrors, const Token *inNextToken)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBstring\fP"
.br
.ti -1c
.RI "const \fBLineInfo\fP * \fBlineInfo\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBUnresolvedError\fP > & \fBerrors\fP"
.br
.ti -1c
.RI "const Token * \fBnextToken\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
