.TH "WAST::ModuleAction" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAST::ModuleAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBWAST::Action\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModuleAction\fP (\fBTextFileLocus\fP &&inLocus, std::string &&inInternalModuleName, \fBIR::Module\fP *inModule)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBinternalModuleName\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBIR::Module\fP > \fBmodule\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
