.TH "libraries/chain/include/aacio/chain/wast_to_wasm.hpp" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/chain/include/aacio/chain/wast_to_wasm.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstd::vector\fP< uint8_t > \fBaacio::chain::wast_to_wasm\fP (const std::string &wast)"
.br
.ti -1c
.RI "std::string \fBaacio::chain::wasm_to_wast\fP (const \fBstd::vector\fP< uint8_t > &wasm)"
.br
.RI "wast_to_wasm "
.ti -1c
.RI "std::string \fBaacio::chain::wasm_to_wast\fP (const uint8_t *data, uint64_t size)"
.br
.RI "wasm_to_wast "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in Acute-Angle-Chain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
