.TH "WAST::FunctionPrintContext" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAST::FunctionPrintContext
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void \fBResult\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionPrintContext\fP (\fBModulePrintContext\fP &inModuleContext, Uptr functionDefIndex)"
.br
.ti -1c
.RI "void \fBprintFunctionBody\fP ()"
.br
.ti -1c
.RI "void \fBunknown\fP (Opcode)"
.br
.ti -1c
.RI "void \fBblock\fP (\fBControlStructureImm\fP imm)"
.br
.ti -1c
.RI "void \fBloop\fP (\fBControlStructureImm\fP imm)"
.br
.ti -1c
.RI "void \fBif_\fP (\fBControlStructureImm\fP imm)"
.br
.ti -1c
.RI "void \fBelse_\fP (\fBNoImm\fP imm)"
.br
.ti -1c
.RI "void \fBend\fP (\fBNoImm\fP)"
.br
.ti -1c
.RI "void \fBreturn_\fP (\fBNoImm\fP)"
.br
.ti -1c
.RI "void \fBbr\fP (\fBBranchImm\fP imm)"
.br
.ti -1c
.RI "void \fBbr_table\fP (\fBBranchTableImm\fP imm)"
.br
.ti -1c
.RI "void \fBbr_if\fP (\fBBranchImm\fP imm)"
.br
.ti -1c
.RI "void \fBunreachable\fP (\fBNoImm\fP)"
.br
.ti -1c
.RI "void \fBdrop\fP (\fBNoImm\fP)"
.br
.ti -1c
.RI "void \fBselect\fP (\fBNoImm\fP)"
.br
.ti -1c
.RI "void \fBget_local\fP (\fBGetOrSetVariableImm\fP< false > imm)"
.br
.ti -1c
.RI "void \fBset_local\fP (\fBGetOrSetVariableImm\fP< false > imm)"
.br
.ti -1c
.RI "void \fBtee_local\fP (\fBGetOrSetVariableImm\fP< false > imm)"
.br
.ti -1c
.RI "void \fBget_global\fP (\fBGetOrSetVariableImm\fP< true > imm)"
.br
.ti -1c
.RI "void \fBset_global\fP (\fBGetOrSetVariableImm\fP< true > imm)"
.br
.ti -1c
.RI "void \fBcall\fP (\fBCallImm\fP imm)"
.br
.ti -1c
.RI "void \fBcall_indirect\fP (\fBCallIndirectImm\fP imm)"
.br
.ti -1c
.RI "void \fBprintImm\fP (\fBNoImm\fP)"
.br
.ti -1c
.RI "void \fBprintImm\fP (\fBMemoryImm\fP)"
.br
.ti -1c
.RI "void \fBprintImm\fP (\fBLiteralImm\fP< I32 > imm)"
.br
.ti -1c
.RI "void \fBprintImm\fP (\fBLiteralImm\fP< I64 > imm)"
.br
.ti -1c
.RI "void \fBprintImm\fP (\fBLiteralImm\fP< F32 > imm)"
.br
.ti -1c
.RI "void \fBprintImm\fP (\fBLiteralImm\fP< F64 > imm)"
.br
.ti -1c
.RI "template<Uptr naturalAlignmentLog2> void \fBprintImm\fP (\fBLoadOrStoreImm\fP< naturalAlignmentLog2 > imm)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBModulePrintContext\fP & \fBmoduleContext\fP"
.br
.ti -1c
.RI "const \fBModule\fP & \fBmodule\fP"
.br
.ti -1c
.RI "const \fBFunctionDef\fP & \fBfunctionDef\fP"
.br
.ti -1c
.RI "const \fBFunctionType\fP * \fBfunctionType\fP"
.br
.ti -1c
.RI "std::string & \fBstring\fP"
.br
.ti -1c
.RI "const \fBstd::vector\fP< std::string > & \fBlocalNames\fP"
.br
.ti -1c
.RI "\fBNameScope\fP \fBlabelNameScope\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
