.TH "WAST::TextFileLocus" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAST::TextFileLocus
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "U32 \fBlineNumber\fP () const"
.br
.ti -1c
.RI "U32 \fBcolumn\fP (U32 spacesPerTab=4) const"
.br
.ti -1c
.RI "std::string \fBdescribe\fP (U32 spacesPerTab=4) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBsourceLine\fP"
.br
.ti -1c
.RI "U32 \fBnewlines\fP"
.br
.ti -1c
.RI "U32 \fBtabs\fP"
.br
.ti -1c
.RI "U32 \fBcharacters\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
