.TH "WAST::GetAction" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAST::GetAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBWAST::Action\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetAction\fP (\fBTextFileLocus\fP &&inLocus, std::string &&inInternalModuleName, std::string &&inExportName)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBinternalModuleName\fP"
.br
.ti -1c
.RI "std::string \fBexportName\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
