.TH "WAST::RegisterCommand" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAST::RegisterCommand
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBWAST::Command\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegisterCommand\fP (\fBTextFileLocus\fP &&inLocus, std::string &&inModuleName, std::string &&inInternalModuleName)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmoduleName\fP"
.br
.ti -1c
.RI "std::string \fBinternalModuleName\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
