.TH "websocketpp::processor::error" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::processor::error \- Error code category and codes used by all processor types\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBprocessor_category\fP"
.br
.RI "Category for processor errors\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBprocessor_errors\fP { \fBgeneral\fP = 1, \fBbad_request\fP, \fBprotocol_violation\fP, \fBmessage_too_big\fP, \fBinvalid_payload\fP, \fBinvalid_arguments\fP, \fBinvalid_opcode\fP, \fBcontrol_too_big\fP, \fBinvalid_rsv_bit\fP, \fBfragmented_control\fP, \fBinvalid_continuation\fP, \fBmasking_required\fP, \fBmasking_forbidden\fP, \fBnon_minimal_encoding\fP, \fBrequires_64bit\fP, \fBinvalid_utf8\fP, \fBnot_implemented\fP, \fBinvalid_http_method\fP, \fBinvalid_http_version\fP, \fBinvalid_http_status\fP, \fBmissing_required_header\fP, \fBsha1_library\fP, \fBno_protocol_support\fP, \fBreserved_close_code\fP, \fBinvalid_close_code\fP, \fBreason_requires_code\fP, \fBsubprotocol_parse_error\fP, \fBextension_parse_error\fP, \fBextensions_disabled\fP, \fBshort_key3\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "lib::error_category const  & \fBget_processor_category\fP ()"
.br
.RI "Get a reference to a static copy of the processor error category\&. "
.ti -1c
.RI "lib::error_code \fBmake_error_code\fP (\fBerror::processor_errors\fP e)"
.br
.RI "Create an error code with the given value and the processor category\&. "
.ti -1c
.RI "\fBclose::status::value\fP \fBto_ws\fP (lib::error_code ec)"
.br
.RI "Converts a processor error_code into a websocket close code\&. "
.in -1c
.SH "Detailed Description"
.PP 
Error code category and codes used by all processor types\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBwebsocketpp::processor::error::processor_errors\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIgeneral \fP\fP
Catch-all error for processor policy errors that don't fit in other categories 
.TP
\fB\fIbad_request \fP\fP
Error was the result of improperly formatted user input\&. 
.TP
\fB\fIprotocol_violation \fP\fP
Processor encountered a protocol violation in an incoming message\&. 
.TP
\fB\fImessage_too_big \fP\fP
Processor encountered a message that was too large\&. 
.TP
\fB\fIinvalid_payload \fP\fP
Processor encountered invalid payload data\&. 
.TP
\fB\fIinvalid_arguments \fP\fP
The processor method was called with invalid arguments\&. 
.TP
\fB\fIinvalid_opcode \fP\fP
Opcode was invalid for requested operation\&. 
.TP
\fB\fIcontrol_too_big \fP\fP
Control frame too large\&. 
.TP
\fB\fIinvalid_rsv_bit \fP\fP
Illegal use of reserved bit\&. 
.TP
\fB\fIfragmented_control \fP\fP
Fragmented control message\&. 
.TP
\fB\fIinvalid_continuation \fP\fP
Continuation without message\&. 
.TP
\fB\fImasking_required \fP\fP
Clients may not send unmasked frames\&. 
.TP
\fB\fImasking_forbidden \fP\fP
Servers may not send masked frames\&. 
.TP
\fB\fInon_minimal_encoding \fP\fP
Payload length not minimally encoded\&. 
.TP
\fB\fIrequires_64bit \fP\fP
Not supported on 32 bit systems\&. 
.TP
\fB\fIinvalid_utf8 \fP\fP
Invalid UTF-8 encoding\&. 
.TP
\fB\fInot_implemented \fP\fP
\fBOperation\fP required not implemented functionality\&. 
.TP
\fB\fIinvalid_http_method \fP\fP
Invalid HTTP method\&. 
.TP
\fB\fIinvalid_http_version \fP\fP
Invalid HTTP version\&. 
.TP
\fB\fIinvalid_http_status \fP\fP
Invalid HTTP status\&. 
.TP
\fB\fImissing_required_header \fP\fP
Missing Required Header\&. 
.TP
\fB\fIsha1_library \fP\fP
Embedded SHA-1 library error\&. 
.TP
\fB\fIno_protocol_support \fP\fP
No support for this feature in this protocol version\&. 
.TP
\fB\fIreserved_close_code \fP\fP
Reserved close code used\&. 
.TP
\fB\fIinvalid_close_code \fP\fP
Invalid close code used\&. 
.TP
\fB\fIreason_requires_code \fP\fP
Using a reason requires a close code\&. 
.TP
\fB\fIsubprotocol_parse_error \fP\fP
Error parsing subprotocols\&. 
.TP
\fB\fIextension_parse_error \fP\fP
Error parsing extensions\&. 
.TP
\fB\fIextensions_disabled \fP\fP
Extension related operation was ignored because extensions are disabled\&. 
.TP
\fB\fIshort_key3 \fP\fP
Short Ke3 read\&. Hybi00 requires a third key to be read from the 8 bytes after the handshake\&. Less than 8 bytes were read\&. 
.SH "Function Documentation"
.PP 
.SS "\fBclose::status::value\fP websocketpp::processor::error::to_ws (lib::error_code ec)\fC [inline]\fP"

.PP
Converts a processor error_code into a websocket close code\&. Looks up the appropriate WebSocket close code that should be sent after an error of this sort occurred\&.
.PP
If the error is not in the processor category close::status::blank is returned\&.
.PP
If the error isn't normally associated with reasons to close a connection (such as errors intended to be used internally or delivered to client applications, ex: invalid arguments) then close::status::internal_endpoint_error is returned\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
