.TH "websocketpp::processor::error_cat" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::processor::error_cat \- Processor class related error codes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBvalue\fP { \fBBAD_REQUEST\fP = 0, \fBINTERNAL_ERROR\fP = 1, \fBPROTOCOL_VIOLATION\fP = 2, \fBMESSAGE_TOO_BIG\fP = 3, \fBPAYLOAD_VIOLATION\fP = 4 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Processor class related error codes\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
