.TH "websocketpp::transport::buffer" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::transport::buffer \- \fBA\fP simple utility buffer class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <connection\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbuffer\fP (char const *b, size_t l)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char const  * \fBbuf\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP simple utility buffer class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
