.TH "websocketpp::utility::ci_less" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::utility::ci_less \- Helper less than functor for case insensitive find\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utilities\&.hpp>\fP
.PP
Inherits binary_function< std::string, std::string, bool >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBnocase_compare\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (std::string const &s1, std::string const &s2) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper less than functor for case insensitive find\&. 

Based on code from http://stackoverflow.com/questions/3152241/case-insensitive-stdstring-find 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
