.TH "websocketpp::message_buffer::pool::endpoint_msg_manager" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::message_buffer::pool::endpoint_msg_manager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pool\&.hpp>\fP
.SH "Detailed Description"
.PP 
An endpoint manager that maintains a shared pool of connection managers and returns an appropriate one for the requesting connection\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
