.TH "websocketpp::transport::asio::basic_socket" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::transport::asio::basic_socket
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBconnection\fP"
.br
.RI "Basic Asio connection socket component\&. "
.ti -1c
.RI "class \fBendpoint\fP"
.br
.RI "Basic ASIO endpoint socket component\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef lib::function< void(\fBconnection_hdl\fP, lib::asio::ip::tcp::socket &)> \fBsocket_init_handler\fP"
.br
.RI "The signature of the socket init handler for this socket policy\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP socket policy for the asio transport that implements a plain, unencrypted socket 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
