.TH "websocketpp::transport::asio::tls_socket" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::transport::asio::tls_socket
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBconnection\fP"
.br
.RI "TLS enabled Asio connection socket component\&. "
.ti -1c
.RI "class \fBendpoint\fP"
.br
.RI "TLS enabled Asio endpoint socket component\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef lib::function< void(\fBconnection_hdl\fP, lib::asio::ssl::stream< lib::asio::ip::tcp::socket > &)> \fBsocket_init_handler\fP"
.br
.RI "The signature of the socket_init_handler for this socket policy\&. "
.ti -1c
.RI "typedef lib::function< lib::shared_ptr< lib::asio::ssl::context >\fBconnection_hdl\fP)> \fBtls_init_handler\fP"
.br
.RI "The signature of the tls_init_handler for this socket policy\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP socket policy for the asio transport that implements a TLS encrypted socket by wrapping with an asio::ssl::stream 
.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
