.TH "websocketpp::concurrency::none_impl" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::concurrency::none_impl \- Implementation for no-op locking primitives\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBfake_lock_guard\fP"
.br
.RI "\fBA\fP fake lock guard implementation that does nothing\&. "
.ti -1c
.RI "class \fBfake_mutex\fP"
.br
.RI "\fBA\fP fake mutex implementation that does nothing\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation for no-op locking primitives\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
