.TH "websocketpp::transport::debug" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::transport::debug
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBerror\fP"
.br
.RI "debug transport errors "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBconnection\fP"
.br
.ti -1c
.RI "class \fBendpoint\fP"
.br
.ti -1c
.RI "struct \fBtimer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Debug transport policy that is used for various mocking and stubbing duties in unit tests\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
