.TH "websocketpp::transport::asio" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::transport::asio \- Transport policy that uses asio\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbasic_socket\fP"
.br
.ti -1c
.RI " \fBerror\fP"
.br
.RI "Asio transport errors\&. "
.ti -1c
.RI " \fBtls_socket\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBconnection\fP"
.br
.RI "Asio based connection transport component\&. "
.ti -1c
.RI "class \fBcustom_alloc_handler\fP"
.br
.ti -1c
.RI "class \fBendpoint\fP"
.br
.RI "Asio based endpoint transport component\&. "
.ti -1c
.RI "class \fBhandler_allocator\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef lib::function< void(lib::asio::error_code const &ec, size_t bytes_transferred)> \fBasync_read_handler\fP"
.br
.ti -1c
.RI "typedef lib::function< void(lib::asio::error_code const &ec, size_t bytes_transferred)> \fBasync_write_handler\fP"
.br
.ti -1c
.RI "typedef lib::function< void(lib::error_code const &ec)> \fBpre_init_handler\fP"
.br
.ti -1c
.RI "typedef lib::function< void(\fBconnection_hdl\fP)> \fBtcp_init_handler\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Handler > \fBcustom_alloc_handler\fP< Handler > \fBmake_custom_alloc_handler\fP (\fBhandler_allocator\fP &a, Handler h)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Transport policy that uses asio\&. 

This policy uses a single asio io_service to provide transport services to a WebSocket++ endpoint\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
