.TH "websocketpp::utility::ci_less::nocase_compare" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::utility::ci_less::nocase_compare
.SH SYNOPSIS
.br
.PP
.PP
Inherits binary_function< unsigned char, unsigned char, bool >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (unsigned char const &c1, unsigned char const &c2) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
