.TH "websocketpp::uri" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::uri
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuri\fP (std::string const &uri_string)"
.br
.ti -1c
.RI "\fBuri\fP (bool secure, std::string const &host, uint16_t port, std::string const &resource)"
.br
.ti -1c
.RI "\fBuri\fP (bool secure, std::string const &host, std::string const &resource)"
.br
.ti -1c
.RI "\fBuri\fP (bool secure, std::string const &host, std::string const &port, std::string const &resource)"
.br
.ti -1c
.RI "\fBuri\fP (std::string const &scheme, std::string const &host, uint16_t port, std::string const &resource)"
.br
.ti -1c
.RI "\fBuri\fP (std::string scheme, std::string const &host, std::string const &resource)"
.br
.ti -1c
.RI "\fBuri\fP (std::string const &scheme, std::string const &host, std::string const &port, std::string const &resource)"
.br
.ti -1c
.RI "bool \fBget_valid\fP () const"
.br
.ti -1c
.RI "bool \fBget_secure\fP () const"
.br
.ti -1c
.RI "std::string const  & \fBget_scheme\fP () const"
.br
.ti -1c
.RI "std::string const  & \fBget_host\fP () const"
.br
.ti -1c
.RI "std::string \fBget_host_port\fP () const"
.br
.ti -1c
.RI "std::string \fBget_authority\fP () const"
.br
.ti -1c
.RI "uint16_t \fBget_port\fP () const"
.br
.ti -1c
.RI "std::string \fBget_port_str\fP () const"
.br
.ti -1c
.RI "std::string const  & \fBget_resource\fP () const"
.br
.ti -1c
.RI "std::string \fBstr\fP () const"
.br
.ti -1c
.RI "std::string \fBget_query\fP () const"
.br
.RI "Return the query portion\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::string websocketpp::uri::get_query () const\fC [inline]\fP"

.PP
Return the query portion\&. Returns the query portion (after the ?) of the URI or an empty string if there is none\&.
.PP
\fBReturns:\fP
.RS 4
query portion of the URI\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
