.TH "websocketpp::random::random_device" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::random::random_device \- RNG policy based on std::random_device or boost::random_device\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBint_generator\fP"
.br
.RI "Thread safe non-deterministic random integer generator\&. "
.in -1c
.SH "Detailed Description"
.PP 
RNG policy based on std::random_device or boost::random_device\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
