.TH "websocketpp::processor::error::processor_category" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::processor::error::processor_category \- Category for processor errors\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <base\&.hpp>\fP
.PP
Inherits error_category\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char const  * \fBname\fP () const _WEBSOCKETPP_NOEXCEPT_TOKEN_"
.br
.ti -1c
.RI "std::string \fBmessage\fP (int value) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Category for processor errors\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
