.TH "websocketpp::concurrency::basic" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::concurrency::basic \- Concurrency policy that uses std::mutex / boost::mutex\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef lib::mutex \fBmutex_type\fP"
.br
.ti -1c
.RI "typedef lib::lock_guard< mutex_type > \fBscoped_lock_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Concurrency policy that uses std::mutex / boost::mutex\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
