.TH "websocketpp::log::basic< concurrency, names >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::log::basic< concurrency, names > \- Basic logger that outputs to an ostream\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic\&.hpp>\fP
.PP
Inherited by \fBwebsocketpp::log::syslog< concurrency, names >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbasic\fP (\fBchannel_type_hint::value\fP h=\fBchannel_type_hint::access\fP)"
.br
.ti -1c
.RI "\fBbasic\fP (std::ostream *out)"
.br
.ti -1c
.RI "\fBbasic\fP (level c, \fBchannel_type_hint::value\fP h=\fBchannel_type_hint::access\fP)"
.br
.ti -1c
.RI "\fBbasic\fP (level c, std::ostream *out)"
.br
.ti -1c
.RI "\fB~basic\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "\fBbasic\fP (\fBbasic\fP< concurrency, names > const &\fBother\fP)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "void \fBset_ostream\fP (std::ostream *out=&std::cout)"
.br
.ti -1c
.RI "void \fBset_channels\fP (level channels)"
.br
.ti -1c
.RI "void \fBclear_channels\fP (level channels)"
.br
.ti -1c
.RI "void \fBwrite\fP (level \fBchannel\fP, std::string const &msg)"
.br
.RI "Write a string message to the given channel\&. "
.ti -1c
.RI "void \fBwrite\fP (level \fBchannel\fP, char const *msg)"
.br
.RI "Write a cstring message to the given channel\&. "
.ti -1c
.RI "_WEBSOCKETPP_CONSTEXPR_TOKEN_ bool \fBstatic_test\fP (level \fBchannel\fP) const"
.br
.ti -1c
.RI "bool \fBdynamic_test\fP (level \fBchannel\fP)"
.br
.in -1c
.SS "Protected Types"

.in +1c
.ti -1c
.RI "typedef concurrency::scoped_lock_type \fBscoped_lock_type\fP"
.br
.ti -1c
.RI "typedef concurrency::mutex_type \fBmutex_type\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "mutex_type \fBm_lock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename concurrency, typename names>
.br
class websocketpp::log::basic< concurrency, names >"
Basic logger that outputs to an ostream\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename concurrency, typename names> void \fBwebsocketpp::log::basic\fP< concurrency, names >::write (level channel, std::string const & msg)\fC [inline]\fP"

.PP
Write a string message to the given channel\&. 
.PP
\fBParameters:\fP
.RS 4
\fIchannel\fP The channel to write to 
.br
\fImsg\fP The message to write 
.RE
.PP

.SS "template<typename concurrency, typename names> void \fBwebsocketpp::log::basic\fP< concurrency, names >::write (level channel, char const * msg)\fC [inline]\fP"

.PP
Write a cstring message to the given channel\&. 
.PP
\fBParameters:\fP
.RS 4
\fIchannel\fP The channel to write to 
.br
\fImsg\fP The message to write 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
