.TH "websocketpp::close::code_converter" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::close::code_converter \- \fBType\fP used to convert close statuses between integer and wire representations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <close\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBi\fP"
.br
.ti -1c
.RI "char \fBc\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType\fP used to convert close statuses between integer and wire representations\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
