.TH "websocketpp::config::minimal_server::permessage_deflate_config" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::config::minimal_server::permessage_deflate_config \- Extension specific settings:  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <minimal_server\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBcore::request_type\fP \fBrequest_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBallow_disabling_context_takeover\fP = true"
.br
.ti -1c
.RI "static const uint8_t \fBminimum_outgoing_window_bits\fP = 8"
.br
.in -1c
.SH "Detailed Description"
.PP 
Extension specific settings: 

permessage_compress extension 
.SH "Member Data Documentation"
.PP 
.SS "const bool websocketpp::config::minimal_server::permessage_deflate_config::allow_disabling_context_takeover = true\fC [static]\fP"
If the remote endpoint requests that we reset the compression context after each message should we honor the request? 
.SS "const uint8_t websocketpp::config::minimal_server::permessage_deflate_config::minimum_outgoing_window_bits = 8\fC [static]\fP"
If the remote endpoint requests that we reduce the size of the LZ77 sliding window size this is the lowest value that will be allowed\&. Values range from 8 to 15\&. \fBA\fP value of 8 means we will allow any possible window size\&. \fBA\fP value of 15 means do not allow negotiation of the window size (ie require the default)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
