.TH "websocketpp::message_buffer::pool::con_msg_manager" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::message_buffer::pool::con_msg_manager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pool\&.hpp>\fP
.SH "Detailed Description"
.PP 
\fBA\fP connection messages manager that maintains a pool of messages that is used to fulfill get_message requests\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
