.TH "websocketpp::client< config >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::client< config > \- Client endpoint role based on the given config\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client_endpoint\&.hpp>\fP
.PP
Inherits \fBwebsocketpp::endpoint< connection< config >, config >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBclient\fP< \fBconfig\fP > \fBtype\fP"
.br
.RI "\fBType\fP of this endpoint\&. "
.ti -1c
.RI "typedef \fBconfig::concurrency_type\fP \fBconcurrency_type\fP"
.br
.RI "\fBType\fP of the endpoint concurrency component\&. "
.ti -1c
.RI "typedef \fBconfig::transport_type\fP \fBtransport_type\fP"
.br
.RI "\fBType\fP of the endpoint transport component\&. "
.ti -1c
.RI "typedef \fBconnection\fP< \fBconfig\fP > \fBconnection_type\fP"
.br
.RI "\fBType\fP of the connections this server will create\&. "
.ti -1c
.RI "typedef \fBconnection_type::ptr\fP \fBconnection_ptr\fP"
.br
.RI "\fBType\fP of a shared pointer to the connections this server will create\&. "
.ti -1c
.RI "typedef \fBtransport_type::transport_con_type\fP \fBtransport_con_type\fP"
.br
.RI "\fBType\fP of the connection transport component\&. "
.ti -1c
.RI "typedef transport_con_type::ptr \fBtransport_con_ptr\fP"
.br
.RI "\fBType\fP of a shared pointer to the connection transport component\&. "
.ti -1c
.RI "typedef \fBendpoint\fP< \fBconnection_type\fP, \fBconfig\fP > \fBendpoint_type\fP"
.br
.RI "\fBType\fP of the endpoint component of this server\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnection_ptr\fP \fBget_connection\fP (\fBuri_ptr\fP location, lib::error_code &ec)"
.br
.RI "Get a new connection\&. "
.ti -1c
.RI "\fBconnection_ptr\fP \fBget_connection\fP (std::string const &u, lib::error_code &ec)"
.br
.RI "Get a new connection (string version) "
.ti -1c
.RI "\fBconnection_ptr\fP \fBconnect\fP (\fBconnection_ptr\fP con)"
.br
.RI "Begin the connection process for the given connection\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBconnection< config >\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename config>
.br
class websocketpp::client< config >"
Client endpoint role based on the given config\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename config> \fBconnection_ptr\fP \fBwebsocketpp::client\fP< \fBconfig\fP >::connect (\fBconnection_ptr\fP con)\fC [inline]\fP"

.PP
Begin the connection process for the given connection\&. Initiates the opening connection handshake for connection con\&. Exact behavior depends on the underlying transport policy\&.
.PP
\fBParameters:\fP
.RS 4
\fIcon\fP The connection to connect
.RE
.PP
\fBReturns:\fP
.RS 4
The pointer to the connection originally passed in\&. 
.RE
.PP

.SS "template<typename config> \fBconnection_ptr\fP \fBwebsocketpp::client\fP< \fBconfig\fP >::get_connection (\fBuri_ptr\fP location, lib::error_code & ec)\fC [inline]\fP"

.PP
Get a new connection\&. Creates and returns a pointer to a new connection to the given URI suitable for passing to \fBconnect(connection_ptr)\fP\&. This method allows applying connection specific settings before performing the opening handshake\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocation\fP URI to open the connection to as a uri_ptr 
.br
\fIec\fP An status code indicating failure reasons, if any
.RE
.PP
\fBReturns:\fP
.RS 4
\fBA\fP connection_ptr to the new connection 
.RE
.PP

.SS "template<typename config> \fBconnection_ptr\fP \fBwebsocketpp::client\fP< \fBconfig\fP >::get_connection (std::string const & u, lib::error_code & ec)\fC [inline]\fP"

.PP
Get a new connection (string version) Creates and returns a pointer to a new connection to the given URI suitable for passing to \fBconnect(connection_ptr)\fP\&. This overload allows default construction of the uri_ptr from a standard string\&.
.PP
\fBParameters:\fP
.RS 4
\fIu\fP URI to open the connection to as a string 
.br
\fIec\fP An status code indicating failure reasons, if any
.RE
.PP
\fBReturns:\fP
.RS 4
\fBA\fP connection_ptr to the new connection 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
