.TH "websocketpp::frame::uint16_converter" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::frame::uint16_converter \- \fBTwo\fP byte conversion union\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <frame\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBi\fP"
.br
.ti -1c
.RI "uint8_t \fBc\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTwo\fP byte conversion union\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
