.TH "websocketpp::random::none::int_generator< int_type >" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::random::none::int_generator< int_type > \- Thread safe stub 'random' integer generator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <none\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int_type \fBoperator()\fP ()"
.br
.RI "advances the engine's state and returns the generated value "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename int_type>
.br
class websocketpp::random::none::int_generator< int_type >"
Thread safe stub 'random' integer generator\&. 

This template class provides a random integer stub\&. The interface mimics the WebSocket++ RNG generator classes but the generater function always returns zero\&. This can be used to stub out the RNG for unit and performance testing\&.
.PP
Call operator() to generate the next number 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
