.TH "websocketpp::config::asio_tls_client" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::config::asio_tls_client \- Client config with asio transport and TLS enabled\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <asio_client\&.hpp>\fP
.PP
Inherits \fBwebsocketpp::config::core_client\fP\&.
.PP
Inherited by \fBconfig_tls\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtransport_config\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBasio_tls_client\fP \fBtype\fP"
.br
.ti -1c
.RI "typedef \fBcore_client\fP \fBbase\fP"
.br
.ti -1c
.RI "typedef \fBbase::concurrency_type\fP \fBconcurrency_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::request_type\fP \fBrequest_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::response_type\fP \fBresponse_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::message_type\fP \fBmessage_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::con_msg_manager_type\fP \fBcon_msg_manager_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::endpoint_msg_manager_type\fP \fBendpoint_msg_manager_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::alog_type\fP \fBalog_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::elog_type\fP \fBelog_type\fP"
.br
.ti -1c
.RI "typedef \fBbase::rng_type\fP \fBrng_type\fP"
.br
.ti -1c
.RI "typedef \fBwebsocketpp::transport::asio::endpoint\fP< \fBtransport_config\fP > \fBtransport_type\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Client config with asio transport and TLS enabled\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
