.TH "websocketpp::transport::error" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::transport::error \- Generic transport related errors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcategory\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBvalue\fP { \fBgeneral\fP = 1, \fBpass_through\fP, \fBinvalid_num_bytes\fP, \fBdouble_read\fP, \fBoperation_aborted\fP, \fBoperation_not_supported\fP, \fBeof\fP, \fBtls_short_read\fP, \fBtimeout\fP, \fBaction_after_shutdown\fP, \fBtls_error\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "lib::error_category const  & \fBget_category\fP ()"
.br
.ti -1c
.RI "lib::error_code \fBmake_error_code\fP (\fBerror::value\fP e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generic transport related errors\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBwebsocketpp::transport::error::value\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIgeneral \fP\fP
Catch-all error for transport policy errors that don't fit in other categories 
.TP
\fB\fIpass_through \fP\fP
underlying transport pass through 
.TP
\fB\fIinvalid_num_bytes \fP\fP
async_read_at_least call requested more bytes than buffer can store 
.TP
\fB\fIdouble_read \fP\fP
async_read called while another async_read was in progress 
.TP
\fB\fIoperation_aborted \fP\fP
\fBOperation\fP aborted\&. 
.TP
\fB\fIoperation_not_supported \fP\fP
\fBOperation\fP not supported\&. 
.TP
\fB\fIeof \fP\fP
End of file\&. 
.TP
\fB\fItls_short_read \fP\fP
TLS short read\&. 
.TP
\fB\fItimeout \fP\fP
Timer expired\&. 
.TP
\fB\fIaction_after_shutdown \fP\fP
read or write after shutdown 
.TP
\fB\fItls_error \fP\fP
Other TLS error\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
