.TH "websocketpp::utf8_validator::validator" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::utf8_validator::validator \- Provides streaming UTF8 validation functionality\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utf8_validator\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvalidator\fP ()"
.br
.RI "Construct and initialize the validator\&. "
.ti -1c
.RI "bool \fBconsume\fP (uint8_t byte)"
.br
.RI "Advance the state of the validator with the next input byte\&. "
.ti -1c
.RI "template<typename iterator_type > bool \fBdecode\fP (iterator_type begin, iterator_type end)"
.br
.RI "Advance validator state with input from an iterator pair\&. "
.ti -1c
.RI "bool \fBcomplete\fP ()"
.br
.RI "Return whether the input sequence ended on a valid utf8 codepoint\&. "
.ti -1c
.RI "void \fBreset\fP ()"
.br
.RI "Reset the validator to decode another message\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides streaming UTF8 validation functionality\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool websocketpp::utf8_validator::validator::complete ()\fC [inline]\fP"

.PP
Return whether the input sequence ended on a valid utf8 codepoint\&. 
.PP
\fBReturns:\fP
.RS 4
Whether or not the input sequence ended on a valid codepoint\&. 
.RE
.PP

.SS "bool websocketpp::utf8_validator::validator::consume (uint8_t byte)\fC [inline]\fP"

.PP
Advance the state of the validator with the next input byte\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbyte\fP The byte to advance the validation state with 
.RE
.PP
\fBReturns:\fP
.RS 4
Whether or not the byte resulted in a validation error\&. 
.RE
.PP

.SS "template<typename iterator_type > bool websocketpp::utf8_validator::validator::decode (iterator_type begin, iterator_type end)\fC [inline]\fP"

.PP
Advance validator state with input from an iterator pair\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbegin\fP Input iterator to the start of the input range 
.br
\fIend\fP Input iterator to the end of the input range 
.RE
.PP
\fBReturns:\fP
.RS 4
Whether or not decoding the bytes resulted in a validation error\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
