.TH "websocketpp::transport::iostream" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::transport::iostream \- Transport policy that uses STL iostream for I/O and does not support timers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBerror\fP"
.br
.RI "iostream transport errors "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBconnection\fP"
.br
.ti -1c
.RI "class \fBendpoint\fP"
.br
.ti -1c
.RI "struct \fBtimer\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef lib::function< lib::error_code(\fBconnection_hdl\fP, char const *, size_t)> \fBwrite_handler\fP"
.br
.RI "The type and signature of the callback used by iostream transport to write\&. "
.ti -1c
.RI "typedef lib::function< lib::error_code(\fBconnection_hdl\fP, \fBstd::vector\fP< \fBtransport::buffer\fP > const &bufs)> \fBvector_write_handler\fP"
.br
.ti -1c
.RI "typedef lib::function< lib::error_code(\fBconnection_hdl\fP)> \fBshutdown_handler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Transport policy that uses STL iostream for I/O and does not support timers\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef lib::function<lib::error_code(\fBconnection_hdl\fP)> \fBwebsocketpp::transport::iostream::shutdown_handler\fP"
The type and signature of the callback used by iostream transport to signal a transport shutdown\&. 
.SS "typedef lib::function<lib::error_code(\fBconnection_hdl\fP, \fBstd::vector\fP<\fBtransport::buffer\fP> const & bufs)> \fBwebsocketpp::transport::iostream::vector_write_handler\fP"
The type and signature of the callback used by iostream transport to perform vectored writes\&. 
.br
If a vectored write handler is not set the standard write handler will be called multiple times\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
