.TH "websocketpp::extensions" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::extensions
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpermessage_deflate\fP"
.br
.RI "Implementation of the draft permessage-deflate WebSocket extension\&. "
.in -1c
.SH "Detailed Description"
.PP 
Some generic information about extensions
.PP
Each extension object has an implemented flag\&. It can be retrieved by calling is_implemented()\&. This compile time flag indicates whether or not the object in question actually implements the extension or if it is a placeholder stub
.PP
Each extension object also has an enabled flag\&. It can be retrieved by calling is_enabled()\&. This runtime flag indicates whether or not the extension has been negotiated for this connection\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
