.TH "websocketpp::processor" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::processor \- Processors encapsulate the protocol rules specific to each WebSocket version\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBconstants\fP"
.br
.RI "Constants related to processing WebSocket connections\&. "
.ti -1c
.RI " \fBerror\fP"
.br
.RI "Error code category and codes used by all processor types\&. "
.ti -1c
.RI " \fBerror_cat\fP"
.br
.RI "Processor class related error codes\&. "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBhybi00\fP"
.br
.RI "Processor for Hybi Draft version 00\&. "
.ti -1c
.RI "class \fBhybi07\fP"
.br
.RI "Processor for Hybi Draft version 07\&. "
.ti -1c
.RI "class \fBhybi08\fP"
.br
.RI "Processor for Hybi Draft version 08\&. "
.ti -1c
.RI "class \fBhybi13\fP"
.br
.RI "Processor for Hybi version 13 (RFC6455) "
.ti -1c
.RI "class \fBprocessor\fP"
.br
.RI "WebSocket protocol processor abstract base class\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename request_type > bool \fBis_websocket_handshake\fP (request_type &r)"
.br
.RI "Determine whether or not a generic HTTP request is a WebSocket handshake\&. "
.ti -1c
.RI "template<typename request_type > int \fBget_websocket_version\fP (request_type &r)"
.br
.RI "Extract the version from a WebSocket handshake request\&. "
.ti -1c
.RI "template<typename request_type > \fBuri_ptr\fP \fBget_uri_from_host\fP (request_type &request, std::string scheme)"
.br
.RI "Extract a URI ptr from the host header of the request\&. "
.in -1c
.SH "Detailed Description"
.PP 
Processors encapsulate the protocol rules specific to each WebSocket version\&. 

The processors namespace includes a number of free functions that operate on various WebSocket related data structures and perform processing that is not related to specific versions of the protocol\&.
.PP
It also includes the abstract interface for the protocol specific processing engines\&. These engines wrap all of the logic necessary for parsing and validating WebSocket handshakes and messages of specific protocol version and set of allowed extensions\&.
.PP
An instance of a processor represents the state of a single WebSocket connection of the associated version\&. \fBOne\fP processor instance is needed per logical WebSocket connection\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename request_type > \fBuri_ptr\fP websocketpp::processor::get_uri_from_host (request_type & request, std::string scheme)"

.PP
Extract a URI ptr from the host header of the request\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrequest\fP The request to extract the Host header from\&.
.br
\fIscheme\fP The scheme under which this request was received (ws, wss, http, https, etc)
.RE
.PP
\fBReturns:\fP
.RS 4
\fBA\fP uri_pointer that encodes the value of the host header\&. 
.RE
.PP

.SS "template<typename request_type > int websocketpp::processor::get_websocket_version (request_type & r)"

.PP
Extract the version from a WebSocket handshake request\&. \fBA\fP blank version header indicates a spec before versions were introduced\&. The only such versions in shipping products are Hixie Draft 75 and Hixie Draft 76\&. Draft 75 is present in Chrome 4-5 and Safari 5\&.0\&.0, Draft 76 (also known as hybi 00 is present in Chrome 6-13 and Safari 5\&.0\&.1+\&. As differentiating between these two sets of browsers is very difficult and Safari 5\&.0\&.1+ accounts for the vast majority of cases in the wild this function assumes that all handshakes without a valid version header are Hybi 00\&.
.PP
\fBParameters:\fP
.RS 4
\fIr\fP The WebSocket handshake request to read\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The WebSocket handshake version or -1 if there was an extraction error\&. 
.RE
.PP

.SS "template<typename request_type > bool websocketpp::processor::is_websocket_handshake (request_type & r)"

.PP
Determine whether or not a generic HTTP request is a WebSocket handshake\&. 
.PP
\fBParameters:\fP
.RS 4
\fIr\fP The HTTP request to read\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBTrue\fP if the request is a WebSocket handshake, false otherwise 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
