.TH "websocketpp::transport::asio::error::category" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::transport::asio::error::category \- Asio transport error category\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <base\&.hpp>\fP
.PP
Inherits error_category\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char const  * \fBname\fP () const _WEBSOCKETPP_NOEXCEPT_TOKEN_"
.br
.ti -1c
.RI "std::string \fBmessage\fP (int \fBvalue\fP) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Asio transport error category\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
