.TH "websocketpp::server< config >" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::server< config > \- Server endpoint role based on the given config\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server_endpoint\&.hpp>\fP
.PP
Inherits \fBwebsocketpp::endpoint< connection< config >, config >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBserver\fP< \fBconfig\fP > \fBtype\fP"
.br
.RI "\fBType\fP of this endpoint\&. "
.ti -1c
.RI "typedef \fBconfig::concurrency_type\fP \fBconcurrency_type\fP"
.br
.RI "\fBType\fP of the endpoint concurrency component\&. "
.ti -1c
.RI "typedef \fBconfig::transport_type\fP \fBtransport_type\fP"
.br
.RI "\fBType\fP of the endpoint transport component\&. "
.ti -1c
.RI "typedef \fBconnection\fP< \fBconfig\fP > \fBconnection_type\fP"
.br
.RI "\fBType\fP of the connections this server will create\&. "
.ti -1c
.RI "typedef \fBconnection_type::ptr\fP \fBconnection_ptr\fP"
.br
.RI "\fBType\fP of a shared pointer to the connections this server will create\&. "
.ti -1c
.RI "typedef \fBtransport_type::transport_con_type\fP \fBtransport_con_type\fP"
.br
.RI "\fBType\fP of the connection transport component\&. "
.ti -1c
.RI "typedef transport_con_type::ptr \fBtransport_con_ptr\fP"
.br
.RI "\fBType\fP of a shared pointer to the connection transport component\&. "
.ti -1c
.RI "typedef \fBendpoint\fP< \fBconnection_type\fP, \fBconfig\fP > \fBendpoint_type\fP"
.br
.RI "\fBType\fP of the endpoint component of this server\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~server\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "\fBconnection_ptr\fP \fBget_connection\fP ()"
.br
.RI "Create and initialize a new connection\&. "
.ti -1c
.RI "void \fBstart_accept\fP (lib::error_code &ec)"
.br
.RI "Starts the server's async connection acceptance loop (exception free) "
.ti -1c
.RI "void \fBstart_accept\fP ()"
.br
.RI "Starts the server's async connection acceptance loop\&. "
.ti -1c
.RI "void \fBhandle_accept\fP (\fBconnection_ptr\fP con, lib::error_code const &ec)"
.br
.RI "Handler callback for start_accept\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBconnection< config >\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename config>
.br
class websocketpp::server< config >"
Server endpoint role based on the given config\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename config> \fBconnection_ptr\fP \fBwebsocketpp::server\fP< \fBconfig\fP >::get_connection ()\fC [inline]\fP"

.PP
Create and initialize a new connection\&. The connection will be initialized and ready to begin\&. Call its start() method to begin the processing loop\&.
.PP
Note: The connection must either be started or terminated using connection::terminate in order to avoid memory leaks\&.
.PP
\fBReturns:\fP
.RS 4
\fBA\fP pointer to the new connection\&. 
.RE
.PP

.SS "template<typename config> void \fBwebsocketpp::server\fP< \fBconfig\fP >::start_accept (lib::error_code & ec)\fC [inline]\fP"

.PP
Starts the server's async connection acceptance loop (exception free) Initiates the server connection acceptance loop\&. Must be called after listen\&. This method will have no effect until the underlying io_service starts running\&. It may be called after the io_service is already running\&.
.PP
Refer to documentation for the transport policy you are using for instructions on how to stop this acceptance loop\&.
.PP
\fBParameters:\fP
.RS 4
\fIec\fP \fBA\fP status code indicating an error, if any\&. 
.RE
.PP

.SS "template<typename config> void \fBwebsocketpp::server\fP< \fBconfig\fP >::start_accept ()\fC [inline]\fP"

.PP
Starts the server's async connection acceptance loop\&. Initiates the server connection acceptance loop\&. Must be called after listen\&. This method will have no effect until the underlying io_service starts running\&. It may be called after the io_service is already running\&.
.PP
Refer to documentation for the transport policy you are using for instructions on how to stop this acceptance loop\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
