.TH "websocketpp::random" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::random \- Random number generation policies\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBnone\fP"
.br
.RI "Stub RNG policy that always returns 0\&. "
.ti -1c
.RI " \fBrandom_device\fP"
.br
.RI "RNG policy based on std::random_device or boost::random_device\&. "
.in -1c
.SH "Detailed Description"
.PP 
Random number generation policies\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
