.TH "websocketpp::transport::stub" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::transport::stub \- Stub transport policy that has no input or output\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBerror\fP"
.br
.RI "stub transport errors "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBconnection\fP"
.br
.ti -1c
.RI "class \fBendpoint\fP"
.br
.ti -1c
.RI "struct \fBtimer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stub transport policy that has no input or output\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
