.TH "websocketpp::frame::uint64_converter" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::frame::uint64_converter \- Eight byte conversion union\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <frame\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBi\fP"
.br
.ti -1c
.RI "uint8_t \fBc\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Eight byte conversion union\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
