.TH "websocketpp::random::none" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::random::none \- Stub RNG policy that always returns 0\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBint_generator\fP"
.br
.RI "Thread safe stub 'random' integer generator\&. "
.in -1c
.SH "Detailed Description"
.PP 
Stub RNG policy that always returns 0\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
