.TH "websocketpp::utility" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::utility \- Generic non-websocket specific utility functions and data structures\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBci_less\fP"
.br
.RI "Helper less than functor for case insensitive find\&. "
.ti -1c
.RI "struct \fBmy_equal\fP"
.br
.RI "Helper functor for case insensitive find\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBto_lower\fP (std::string const &in)"
.br
.RI "Convert a string to lowercase\&. "
.ti -1c
.RI "std::string \fBto_hex\fP (std::string const &input)"
.br
.RI "Convert std::string to ascii printed string of hex digits\&. "
.ti -1c
.RI "std::string \fBto_hex\fP (uint8_t const *input, size_t length)"
.br
.RI "Convert byte array (uint8_t) to ascii printed string of hex digits\&. "
.ti -1c
.RI "std::string \fBto_hex\fP (char const *input, size_t length)"
.br
.RI "Convert char array to ascii printed string of hex digits\&. "
.ti -1c
.RI "std::string \fBstring_replace_all\fP (std::string subject, std::string const &search, std::string const &replace)"
.br
.RI "Replace all occurrances of a substring with another\&. "
.ti -1c
.RI "template<typename T > T::const_iterator \fBci_find_substr\fP (\fBT\fP const &haystack, \fBT\fP const &needle, std::locale const &loc=std::locale())"
.br
.RI "Find substring (case insensitive) "
.ti -1c
.RI "template<typename T > T::const_iterator \fBci_find_substr\fP (\fBT\fP const &haystack, typename T::value_type const *needle, typename T::size_type size, std::locale const &loc=std::locale())"
.br
.RI "Find substring (case insensitive) "
.in -1c
.SH "Detailed Description"
.PP 
Generic non-websocket specific utility functions and data structures\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T > T::const_iterator websocketpp::utility::ci_find_substr (\fBT\fP const & haystack, \fBT\fP const & needle, std::locale const & loc = \fCstd::locale()\fP)"

.PP
Find substring (case insensitive) 
.PP
\fBParameters:\fP
.RS 4
\fIhaystack\fP The string to search in 
.br
\fIneedle\fP The string to search for 
.br
\fIloc\fP The locale to use for determining the case of values\&. Defaults to the current locale\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
An iterator to the first element of the first occurrance of needle in haystack\&. If the sequence is not found, the function returns haystack\&.end() 
.RE
.PP

.SS "template<typename T > T::const_iterator websocketpp::utility::ci_find_substr (\fBT\fP const & haystack, typename T::value_type const * needle, typename T::size_type size, std::locale const & loc = \fCstd::locale()\fP)"

.PP
Find substring (case insensitive) 
.PP
\fBTodo\fP
.RS 4
Is this still used? This method may not make sense\&.\&. should use iterators or be less generic\&. As is it is too tightly coupled to std::string
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIhaystack\fP The string to search in 
.br
\fIneedle\fP The string to search for as a char array of values 
.br
\fIsize\fP Length of needle 
.br
\fIloc\fP The locale to use for determining the case of values\&. Defaults to the current locale\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
An iterator to the first element of the first occurrance of needle in haystack\&. If the sequence is not found, the function returns haystack\&.end() 
.RE
.PP

.SS "std::string websocketpp::utility::string_replace_all (std::string subject, std::string const & search, std::string const & replace)\fC [inline]\fP"

.PP
Replace all occurrances of a substring with another\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsubject\fP The string to search in 
.br
\fIsearch\fP The string to search for 
.br
\fIreplace\fP The string to replace with 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBA\fP copy of \fCsubject\fP with all occurances of \fCsearch\fP replaced with \fCreplace\fP 
.RE
.PP

.SS "std::string websocketpp::utility::to_hex (std::string const & input)\fC [inline]\fP"

.PP
Convert std::string to ascii printed string of hex digits\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinput\fP The string to print 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBA\fP copy of \fCinput\fP converted to the printable representation of the hex values of its data\&. 
.RE
.PP

.SS "std::string websocketpp::utility::to_hex (uint8_t const * input, size_t length)\fC [inline]\fP"

.PP
Convert byte array (uint8_t) to ascii printed string of hex digits\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinput\fP The byte array to print 
.br
\fIlength\fP The length of input 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBA\fP copy of \fCinput\fP converted to the printable representation of the hex values of its data\&. 
.RE
.PP

.SS "std::string websocketpp::utility::to_hex (char const * input, size_t length)\fC [inline]\fP"

.PP
Convert char array to ascii printed string of hex digits\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinput\fP The char array to print 
.br
\fIlength\fP The length of input 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBA\fP copy of \fCinput\fP converted to the printable representation of the hex values of its data\&. 
.RE
.PP

.SS "std::string websocketpp::utility::to_lower (std::string const & in)\fC [inline]\fP"

.PP
Convert a string to lowercase\&. 
.PP
\fBParameters:\fP
.RS 4
\fIin\fP The string to convert 
.RE
.PP
\fBReturns:\fP
.RS 4
The converted string 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
