.TH "websocketpp::md5" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websocketpp::md5 \- Provides MD5 hashing functionality\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBmd5_state_s\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBmd5_byte_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBmd5_word_t\fP"
.br
.ti -1c
.RI "typedef struct \fBwebsocketpp::md5::md5_state_s\fP \fBmd5_state_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmd5_init\fP (\fBmd5_state_t\fP *pms)"
.br
.ti -1c
.RI "void \fBmd5_append\fP (\fBmd5_state_t\fP *pms, md5_byte_t const *data, size_t nbytes)"
.br
.ti -1c
.RI "void \fBmd5_finish\fP (\fBmd5_state_t\fP *pms, md5_byte_t digest[16])"
.br
.ti -1c
.RI "std::string \fBmd5_hash_string\fP (std::string const &s)"
.br
.ti -1c
.RI "std::string \fBmd5_hash_hex\fP (std::string const &input)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBhexval\fP [16] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides MD5 hashing functionality\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
