.TH "libraries/utilities/include/aacio/utilities/words.hpp" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libraries/utilities/include/aacio/utilities/words.hpp
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef const char * \fBaacio::words::const_char_ptr\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const const_char_ptr \fBaacio::words::word_list\fP []"
.br
.ti -1c
.RI "const uint32_t \fBaacio::words::word_list_size\fP = sizeof(word_list)/sizeof(word_list[0])"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
defined in AcuteAngleChain/LICENSE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
