.TH "Y" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Y
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBT\fP\&.
.PP
Inherited by \fBZ\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBY\fP & \fBoperator=\fP (const \fBY\fP &)"
.br
.ti -1c
.RI "\fBY\fP & \fBoperator=\fP (\fBY\fP &&)"
.br
.ti -1c
.RI "\fBY\fP (const \fBY\fP &)"
.br
.ti -1c
.RI "\fBY\fP (\fBY\fP &&)"
.br
.ti -1c
.RI "constexpr \fBY\fP (int i)"
.br
.ti -1c
.RI "constexpr \fBY\fP (std::initializer_list< int > il)"
.br
.ti -1c
.RI "constexpr \fBY\fP (int i)"
.br
.ti -1c
.RI "\fBY\fP (int i)"
.br
.ti -1c
.RI "\fBY\fP (const \fBY\fP &x)"
.br
.ti -1c
.RI "constexpr \fBY\fP (int i)"
.br
.ti -1c
.RI "constexpr \fBY\fP (int i, int j)"
.br
.ti -1c
.RI "constexpr \fBY\fP (int i)"
.br
.ti -1c
.RI "constexpr \fBY\fP (std::initializer_list< int > il)"
.br
.ti -1c
.RI "\fBY\fP (int i)"
.br
.ti -1c
.RI "\fBY\fP (\fBY\fP &&x) noexcept"
.br
.ti -1c
.RI "constexpr \fBY\fP (int i)"
.br
.ti -1c
.RI "constexpr \fBY\fP (\fBY\fP &&x)"
.br
.ti -1c
.RI "int \fBtest\fP () const"
.br
.ti -1c
.RI "int \fBtest\fP () const"
.br
.ti -1c
.RI "\fBY\fP (int i)"
.br
.ti -1c
.RI "constexpr \fBY\fP (int i)"
.br
.ti -1c
.RI "\fBY\fP (int i)"
.br
.ti -1c
.RI "\fBY\fP (\fBY\fP &&)=default"
.br
.ti -1c
.RI "\fBY\fP (int i)"
.br
.ti -1c
.RI "\fBY\fP (\fBY\fP &&)=default"
.br
.ti -1c
.RI "\fBY\fP (int)"
.br
.ti -1c
.RI "constexpr \fBY\fP (int i)"
.br
.ti -1c
.RI "constexpr \fBY\fP (std::initializer_list< int > il)"
.br
.ti -1c
.RI "\fBY\fP (int i)"
.br
.ti -1c
.RI "\fBY\fP (int i)"
.br
.ti -1c
.RI "constexpr \fBY\fP (int i)"
.br
.ti -1c
.RI "constexpr \fBY\fP (int i, int j)"
.br
.ti -1c
.RI "constexpr \fBY\fP (int i)"
.br
.ti -1c
.RI "constexpr \fBY\fP (std::initializer_list< int > il)"
.br
.ti -1c
.RI "constexpr int \fBtest\fP ()"
.br
.ti -1c
.RI "int \fBtest\fP () const"
.br
.ti -1c
.RI "int \fBtest\fP () const &&"
.br
.ti -1c
.RI "constexpr int \fBtest\fP () &&"
.br
.ti -1c
.RI "constexpr int \fBtest\fP ()"
.br
.ti -1c
.RI "int \fBtest\fP () const noexcept"
.br
.ti -1c
.RI "constexpr int \fBtest\fP () &"
.br
.ti -1c
.RI "constexpr \fBY\fP (int i)"
.br
.ti -1c
.RI "constexpr \fBY\fP (int i)"
.br
.ti -1c
.RI "constexpr int \fBtest\fP () &&"
.br
.ti -1c
.RI "\fBY\fP (int i)"
.br
.ti -1c
.RI "\fBY\fP (\fBY\fP &&)=default"
.br
.ti -1c
.RI "\fBY\fP (int i)"
.br
.ti -1c
.RI "\fBY\fP (\fBY\fP &&)=default"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBdtor_called\fP = false"
.br
.ti -1c
.RI "static unsigned \fBdtor_called\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBY\fP &x, \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBY\fP &x, \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBY\fP &x, \fBY\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBY\fP &x, const \fBY\fP &y)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBY\fP &x, \fBY\fP &y)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
