.TH "Y2" 3 "Sun Jun 3 2018" "Acute-Angle-Chain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Y2
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBY2\fP (const int &)=delete"
.br
.ti -1c
.RI "\fBY2\fP & \fBoperator=\fP (const int &)"
.br
.ti -1c
.RI "\fBY2\fP (const int &)=delete"
.br
.ti -1c
.RI "\fBY2\fP & \fBoperator=\fP (const int &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Acute-Angle-Chain from the source code\&.
