.TH "Z" 3 "Sun Jun 3 2018" "AcuteAngleChain" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Z
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBY\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZ\fP (\fBZ\fP &&)=delete"
.br
.ti -1c
.RI "\fBZ\fP (const \fBZ\fP &)=delete"
.br
.ti -1c
.RI "\fBZ\fP & \fBoperator=\fP (\fBZ\fP &&)=delete"
.br
.ti -1c
.RI "\fBZ\fP & \fBoperator=\fP (const \fBZ\fP &)=delete"
.br
.ti -1c
.RI "\fBZ\fP (\fBZ\fP &&)=delete"
.br
.ti -1c
.RI "\fBZ\fP (const \fBZ\fP &)=delete"
.br
.ti -1c
.RI "\fBZ\fP & \fBoperator=\fP (\fBZ\fP &&)=delete"
.br
.ti -1c
.RI "\fBZ\fP & \fBoperator=\fP (const \fBZ\fP &)=delete"
.br
.ti -1c
.RI "\fBZ\fP (int)"
.br
.ti -1c
.RI "constexpr \fBZ\fP (int i)"
.br
.ti -1c
.RI "\fBZ\fP (std::initializer_list< int > il)"
.br
.ti -1c
.RI "\fBZ\fP (int)"
.br
.ti -1c
.RI "\fBZ\fP (const \fBZ\fP &)"
.br
.ti -1c
.RI "\fBZ\fP (int i)"
.br
.ti -1c
.RI "\fBZ\fP (const \fBZ\fP &)"
.br
.ti -1c
.RI "\fBZ\fP (int)"
.br
.ti -1c
.RI "constexpr \fBZ\fP (int i)"
.br
.ti -1c
.RI "\fBZ\fP (std::initializer_list< int > il)"
.br
.ti -1c
.RI "\fBZ\fP (int i)"
.br
.ti -1c
.RI "\fBZ\fP (\fBZ\fP &&)"
.br
.ti -1c
.RI "\fBZ\fP (int)"
.br
.ti -1c
.RI "\fBZ\fP (\fBZ\fP &&)"
.br
.ti -1c
.RI "const \fBZ\fP * \fBoperator &\fP () const"
.br
.ti -1c
.RI "constexpr int \fBtest\fP () const"
.br
.ti -1c
.RI "\fBZ\fP (int i)"
.br
.ti -1c
.RI "\fBZ\fP (\fBZ\fP &&)"
.br
.ti -1c
.RI "\fBZ\fP (int i)"
.br
.ti -1c
.RI "\fBZ\fP (\fBZ\fP &&)"
.br
.ti -1c
.RI "\fBZ\fP (int i)"
.br
.ti -1c
.RI "\fBZ\fP (std::initializer_list< int > il)"
.br
.ti -1c
.RI "\fBZ\fP (int i)"
.br
.ti -1c
.RI "\fBZ\fP (int i)"
.br
.ti -1c
.RI "\fBZ\fP (int)"
.br
.ti -1c
.RI "\fBZ\fP (int)"
.br
.ti -1c
.RI "\fBZ\fP (int i)"
.br
.ti -1c
.RI "\fBZ\fP (std::initializer_list< int > il)"
.br
.ti -1c
.RI "\fBZ\fP (int)"
.br
.ti -1c
.RI "\fBZ\fP (int)"
.br
.ti -1c
.RI "\fBZ\fP (\fBZ\fP &&)"
.br
.ti -1c
.RI "const \fBZ\fP * \fBoperator &\fP () const"
.br
.ti -1c
.RI "constexpr int \fBtest\fP () const"
.br
.ti -1c
.RI "\fBZ\fP (int i)"
.br
.ti -1c
.RI "\fBZ\fP (\fBZ\fP &&)"
.br
.ti -1c
.RI "\fBZ\fP (int i)"
.br
.ti -1c
.RI "\fBZ\fP (\fBZ\fP &&)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBdtor_called\fP = false"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBZ\fP &x, const \fBZ\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBZ\fP &x, const \fBZ\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBZ\fP &x, const \fBZ\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBZ\fP &x, const \fBZ\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBZ\fP &x, const \fBZ\fP &y)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBZ\fP &, \fBZ\fP &)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBZ\fP &x, const \fBZ\fP &y)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBZ\fP &, \fBZ\fP &)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBZ\fP &x, const \fBZ\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBZ\fP &x, const \fBZ\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBZ\fP &x, const \fBZ\fP &y)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBZ\fP &x, const \fBZ\fP &y)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBZ\fP &x, const \fBZ\fP &y)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBZ\fP &, \fBZ\fP &)"
.br
.ti -1c
.RI "constexpr bool \fBoperator==\fP (const \fBZ\fP &x, const \fBZ\fP &y)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBZ\fP &, \fBZ\fP &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AcuteAngleChain from the source code\&.
